Planning-Inspectorate/appeals-back-office

appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/__tests__/__snapshots__/manage-linked-appeals.test.js.snap
appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/__tests__/manage-linked-appeals.test.js
appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/manage-linked-appeals.mapper.js

fix warning text when attempting to link child appeal to lead of different appeal
BOAT-1068

fix(web): fix warning text when attempting to link child appeal to lead of different appeal

---

appeals/web/environment/schema.js

There is still some lack of clarity on Horizon URLs, until then made the horizonAppealBaseUrl ENV setting optional, to avoid the site breaking on deploy.

fix(web): makes horizonAppealBaseUrl optional

---

appeals/web/environment/config.d.ts
appeals/web/environment/schema.js
appeals/web/src/server/lib/display-page-formatter.js

As it says in the title... Avoid making links to Horizon if the setting is not available...

fix(web): make external appeal linkable only if settings are found

---

appeals/web/src/server/appeals/appeal-details/appeal-timetables/__tests__/__snapshots__/appeal-timetables.test.js.snap
appeals/web/src/server/appeals/appeal-details/appeal-timetables/appeal-timetables.mapper.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js

pre-populate update due date values on change timetable flow, add missing inset text to lpaq incomplete flow update due date page
BOAT-1078

fix(web): pre-populate update due date values on change timetable flow

---

appeals/api/src/server/endpoints/appeals.d.ts
appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
appeals/api/src/server/endpoints/appeals/appeals.controller.js
appeals/api/src/server/endpoints/appeals/appeals.formatter.js
appeals/api/src/server/endpoints/constants.js
appeals/web/testing/app/fixtures/referencedata.js

Adds folders for costs:
- `appeal_costs/lpa`
- `appeal_costs/appellant`
Returns the contents of those folders in a `costs` property.

feat(api): appeal folders for costs

---

appeals/api/src/server/endpoints/constants.js
appeals/api/src/server/endpoints/documents/__tests__/documents.test.js
appeals/api/src/server/endpoints/documents/documents.controller.js

[BOAT-1058](https://pins-ds.atlassian.net/browse/BOAT-1058)

BOAT-1058 API - Create audit event for when doc redaction status or date receieved is changed

---

appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
appeals/web/src/server/lib/mappers/appeal.mapper.js
appeals/web/testing/app/fixtures/referencedata.js

fix for BOAT-1083, specifically addresses the service displaying a 500 error page when attempting to load the manage linked appeals page for an appeal which is a child of an external (Horizon) lead appeal. 
BOAT-1083

fix(web): remove action links from linked appeals row when appeal is child of external lead

---

appeals/api/src/server/endpoints/appeals.d.ts
appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
appeals/api/src/server/endpoints/appeals/appeals.formatter.js
appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.formatter.js
appeals/api/src/server/tests/appeals/expectation.js
appeals/api/src/server/tests/appeals/mocks.js
appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
appeals/web/src/server/appeals/appeal-details/appeal-details.types.d.ts
appeals/web/src/server/lib/mappers/appeal.mapper.js
appeals/web/testing/app/fixtures/referencedata.js

BOAT-1105
Adds `recevedAt` data column

feat(appeals): feature/BOAT-1105-add-received-date-column

---

appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.controller.js
appeals/web/src/server/appeals/appeal-details/costs/__tests__/costs.test.js
appeals/web/src/server/appeals/appeal-details/costs/costs.controller.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.controller.js
appeals/web/src/server/appeals/appeal-documents/appeal-documents.controller.js

Few improvement on the delete document journey:
- `cancelUrl` param added to `postDocumentDelete` to handle the 'No' post redirect correctly
- 'Yes, and upload another document' post consistently redirects to add document, not update document
- Back links from delete document page goes to manage document instead of manage folder
[BOAT-1222](https://pins-ds.atlassian.net/browse/BOAT-1222)

fix(web): document delete journey improved

---

appeals/web/src/server/appeals/appeal-details/appeal-timetables/__tests__/__snapshots__/appeal-timetables.test.js.snap
appeals/web/src/server/appeals/appeal-details/appeal-timetables/appeal-timetables.controller.js
appeals/web/src/server/appeals/appeal-details/appeal-timetables/appeal-timetables.mapper.js
appeals/web/src/server/appeals/appeal-details/appeal-timetables/appeal-timetables.router.js
appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap
appeals/web/src/server/lib/mappers/notification-banners.mapper.js
appeals/web/src/server/lib/validators/date-input.validator.js

"Change LPA questionnaire due date" page changes:
- When confirming the change, user is redirected to Appeal Details with a success notification stating 'LPA questionnaire due date changed'
- Old Confirmation page removed and all related code cleaned up
- Submit button text changed from 'Continue' to 'Confirm'
- Error message updated from 'Date must be a date in the future’ to ‘Date must be in the future’
Some other tests were affected by the error message change. Those were replaced.
[BOAT-1378](https://pins-ds.atlassian.net/browse/BOAT-1378)

fix(web): lpaq due date confirmation page removed and replaced with notification banner

---

appeals/web/src/client/components/file-uploader/_client-actions.js

Moved finalize upload cleanup code inside the errors condition where it's relevant. The exit condition only redirects, so there's no need for any cleanup.
The cleanup code was the cause of re-enabling the dropzone visibility.
[BOAT-1239](https://pins-ds.atlassian.net/browse/BOAT-1239)

fix(web): finalize upload cleanup only if there are errors

---

infrastructure/data.tf

implement vnet peering
removing `provider = azurerm.tooling` as this may have been causing the error  on the pipeline being tied to the wrong sub 
https://dev.azure.com/planninginspectorate/appeals-back-office/_build/results?buildId=83508&view=logs&j=d8c8df2e-1b9e-55db-c620-fddadb65a07b&t=ad3e177c-dc5f-5737-3548-7b4aa1a78cc5&l=348
DEV 235

fix(tooling): removing tooling sub provider on group of variables

---

.github/workflows/deploy-c4-diagrams.yml
appeals/api/src/server/config/config.js
appeals/api/src/server/config/schema.js
appeals/api/src/server/endpoints/appellant-cases/__tests__/appellant-cases.test.js
appeals/api/src/server/endpoints/appellant-cases/appellant-cases.service.js

- `appealIncomplete` template ID added to schema
- notifyClient sends email when appellant case is incomplete
- incomplete reasons and appeal due date formatted for template
[BOAT-875 API - Comms - Appellant case marked as ‘incomplete’](https://pins-ds.atlassian.net/browse/BOAT-875)

feat(api): notify comms for appellant case incomplete

---

appeals/api/src/server/config/config.js
appeals/api/src/server/config/schema.js
appeals/api/src/server/endpoints/appellant-cases/__tests__/appellant-cases.test.js
appeals/api/src/server/endpoints/appellant-cases/appellant-cases.service.js
appeals/api/src/server/tests/appeals/mocks.js
appeals/api/src/server/tests/shared/mocks.js
appeals/api/src/server/utils/appeal-formatter.js

- `appealInvalid` template ID added to config & schema
- notifyClient sends email when appellant case is invalid
- invalid reasons formatted for template
- `getFormattedReasons` util created to support invalid and incomplete
- incomplete/invalid shared mocks updated to include reason texts
[BOAT-870 API - Comms - Case found to be 'invalid’](https://pins-ds.atlassian.net/browse/BOAT-870)

feat(api): notify comms on case invalid

---

appeals/api/src/server/config/config.js
appeals/api/src/server/config/schema.js
appeals/api/src/server/endpoints/appeals.d.ts
appeals/api/src/server/endpoints/site-visits/__tests__/site-visits.test.js
appeals/api/src/server/endpoints/site-visits/site-visits.controller.js
appeals/api/src/server/endpoints/site-visits/site-visits.routes.js
appeals/api/src/server/endpoints/site-visits/site-visits.service.js

- `siteVisitSchedule.unaccompanied.appellant` template ID added to config
- notifyClient sends email when an unaccompanied site visit is created
- `createSiteVisit` controller renamed `postSiteVisit`
- migrated controller logic into a `createSiteVisit` service
- added new test to test for the email being sent
[BOAT-206 API - Comms - Visit type marked as ‘unaccompanied’](https://pins-ds.atlassian.net/browse/BOAT-206)

feat(api): notify comms on unaccompanied site visit

---

appeals/api/src/server/config/config.js
appeals/api/src/server/config/schema.js
appeals/api/src/server/endpoints/site-visits/__tests__/site-visits.test.js

- access required template ID added to config
- added new test to test for the access required email being sent
no changes to the service were needed for sending the email, config updates were sufficient.
[BOAT-895 API - Comms - Visit type marked as 'access required'](https://pins-ds.atlassian.net/browse/BOAT-895)

feat(api): notify comms on access required site visit

---

appeals/api/src/server/config/config.js
appeals/api/src/server/config/schema.js
appeals/api/src/server/endpoints/appeals.d.ts
appeals/api/src/server/endpoints/lpa-questionnaires/__tests__/lpa-questionnaires.test.js
appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.controller.js
appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.service.js
appeals/api/src/server/utils/check-validation-outcome.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js

- lpaqComplete template ID added to config
- notifyClient sends email to lpa when LPA questionnaire is set as complete
- added new test to test for the LPA questionnaire complete emails being sent
Minor web update
- Changed the submit button content from 'Continue' to 'Confirm'
[BOAT-1214 API - Comms - LPA questionnaire is complete](https://pins-ds.atlassian.net/browse/BOAT-1214)

feat(api): notify comms on lpaq complete

---

infrastructure/function-casedata-import.tf
infrastructure/function-doc-processing.tf
infrastructure/function-scheduled-jobs.tf
infrastructure/function-user-import.tf

I noticed when looking at Portal that the Function App Service Plan was unused... this corrects that!

fix(infrastructure): move functions onto the function app service plan

---

appeals/api/src/server/config/config.js
appeals/api/src/server/config/schema.js
appeals/api/src/server/endpoints/appeals.d.ts
appeals/api/src/server/endpoints/lpa-questionnaires/__tests__/lpa-questionnaires.test.js
appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.controller.js
appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.service.js
appeals/api/src/server/tests/shared/mocks.js

- lpaqIncomplete template ID added to config
- notifyClient sends email to lpa when LPA questionnaire is set as incomplete
- added new test to test for the LPA questionnaire incomplete emails being sent
- fixed typo `questionaire` to `questionnaire` (two n's)
[BOAT-874 API - Comms - LPAQ REVIEW - Case marked as ‘incomplete’](https://pins-ds.atlassian.net/browse/BOAT-874)

feat(api): notify comms on lpaq incomplete

---

appeals/api/src/server/repositories/document.repository.js

Fixes the AV scan, which was using the old `checked` value rather than `scanned`.

fix(api): correct value for AV scan report

---

appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/__tests__/__snapshots__/manage-linked-appeals.test.js.snap
appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/manage-linked-appeals.mapper.js
appeals/web/src/server/appeals/appeal-details/other-appeals/__tests__/__snapshots__/other-appeals.test.js.snap
appeals/web/src/server/appeals/appeal-details/other-appeals/other-appeals.mapper.js
appeals/web/src/server/appeals/appeal-details/safety-risks/__tests__/__snapshots__/safety-risks.test.js.snap
appeals/web/src/server/appeals/national-list/__tests__/__snapshots__/national-list.test.js.snap
appeals/web/src/server/appeals/national-list/national-list.mapper.js
appeals/web/src/server/lib/display-page-formatter.js
appeals/web/src/server/lib/mappers/appeal.mapper.js
appeals/web/src/server/lib/mappers/appellantCase.mapper.js
appeals/web/src/server/lib/mappers/lpaQuestionnaire.mapper.js
appeals/web/src/server/lib/mappers/notification-banners.mapper.js
appeals/web/src/server/views/appeals/components/appeals-table.njk

This adds `data-cy` attributes to key page elements so that the E2E Cypress tests will be less brittle. This is following the recommended best practise, as per https://docs.cypress.io/guides/references/best-practices#Selecting-Elements
Next steps are to update and extend the existing E2E tests, before using again in the pipeline and allow individual devs to run locally to perform a quick regression test locally.
Relates to [BOAT-1198](https://pins-ds.atlassian.net/browse/BOAT-1198) and [BOAT-1148](https://pins-ds.atlassian.net/browse/BOAT-1148]

feat(appeals): add element attributes for cypress

---

appeals/api/setup-tests.js
appeals/api/src/database/migrations/20240618151224_avscan_fix/migration.sql
appeals/api/src/database/schema.d.ts
appeals/api/src/database/schema.prisma
appeals/api/src/server/endpoints/appeals.d.ts
appeals/api/src/server/endpoints/documents/__tests__/documents.test.js
appeals/api/src/server/endpoints/documents/documents.controller.js
appeals/api/src/server/endpoints/documents/documents.service.js
appeals/api/src/server/endpoints/documents/documents.validators.js
appeals/api/src/server/endpoints/integrations/integrations.broadcasters/documents.js
appeals/api/src/server/repositories/document-metadata.repository.js
appeals/api/src/server/repositories/document.repository.js
appeals/api/src/server/repositories/folder.repository.js

As a result of AVI-80, and the changes in the document upload process, the AV scan was failing to report results on documents that were added to blob storage, but not yet committed to the database.
To fix, the DocumentVersionAvScan table (were AV scans are written), no longer has a constraint to the DocumentVersion table, allowing scan reports to be stored independently.
Fix to [AVI-80](https://pins-ds.atlassian.net/browse/ASI-80)

fix(appeals): correct avscan for documents not yet committed

---

appeals/web/src/server/appeals/appeal-details/assign-user/__tests__/assign-user.test.js
appeals/web/src/server/appeals/appeal-users/users-service.js

Currently trying to assign a user when they are not a direct member of the relevant Entra group doesn't work - they aren't found. This was noticed in Training where most members are from an inherited group.
To fix this, we use the transitive members API.

fix(web): get all entra group members, not just direct members

---

appeals/api/src/server/common/validators/string-parameter.js
appeals/api/src/server/endpoints/addresses/__tests__/addresses.test.js
appeals/api/src/server/endpoints/addresses/addresses.validators.js
appeals/web/src/server/appeals/appeal-details/address/address.service.js

Was unable to clear data when it was no longer required, so changing addressLine2 from a string to an empty is now possible.

fix(api): fix address update to allow removal of data from optional fields

---

appeals/api/src/server/endpoints/integrations/integrations.mappers/questionnaire.mapper.js

Removes the `listedBuildingDetails` field, as it was a duplicate of `affectedListedBuildingNumbers`

fix(api): removes duplicate data

---

appeals/api/src/server/repositories/integrations.repository.js

The DB field `externalType` on `appealRelationship` was misspelled in the integration routine importing cases.

fix(api): fixed mispelled field

---

appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
appeals/web/src/server/appeals/appeal-details/audit/audit.service.js
appeals/web/src/server/appeals/national-list/__tests__/__snapshots__/national-list.test.js.snap
appeals/web/src/server/appeals/national-list/__tests__/national-list.test.js
appeals/web/src/server/appeals/personal-list/__tests__/__snapshots__/personal-list.test.js.snap
appeals/web/src/server/appeals/personal-list/__tests__/personal-list.test.js
appeals/web/src/server/appeals/personal-list/personal-list.mapper.js
appeals/web/src/server/lib/nunjucks-filters/status-tag.js
appeals/web/src/server/views/appeals/components/status-tag.njk
appeals/web/testing/app/fixtures/referencedata.js

Fix status-dependent action link copy and URLs on personal list, plus some additional changes:
- changed default action for personal list from ‘View appellant case’ to ‘View case’ (URL not changed as it was already linking to case details page, not appellant case)
- amended all personal list actions copy casing to `Sentence case` instead of `Title Case` as requested by content designer
- updated status tag template to account for `lpa_questionnaire_due` status having changed to `lpa_questionnaire`
- update personal list `mapAppealStatusToActionRequiredHtml` function to use STATUSES values from shared constants file, to avoid future regressions if state names change
- update unit tests in WEB to update `lpa_questionnaire_due` status value to `lpa_questionnaire`
BOAT-1390

fix(web): fix status-dependent action link copy and URLs on personal list

---

appeals/functions/casedata-import/appellant-case/back-office-api-client.js
appeals/functions/casedata-import/appellant-case/index.js
appeals/functions/casedata-import/questionnaire/back-office-api-client.js
appeals/functions/casedata-import/questionnaire/index.js
appeals/functions/document-processing/malware-detection/back-office-api-client.js
appeals/functions/document-processing/malware-detection/index.js
appeals/functions/user-import/employee/back-office-api-client.js
appeals/functions/user-import/employee/index.js
appeals/functions/user-import/service-user/back-office-api-client.js
appeals/functions/user-import/service-user/index.js

Tested from the branch, the try/catch was not returning the `HTTPError` so the response body was not logged.

fix(functions): don't wrap HTTPErrors to enable logging response body

---

appeals/api/src/server/endpoints/appellant-cases/appellant-cases.controller.js
appeals/api/src/server/endpoints/appellant-cases/appellant-cases.service.js
appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.controller.js
appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.service.js

Moves the execution of the appeal broadcaster, so every PATCH to appeal, appellant case or lpa questionnaire will result in an updated appeal message.

fix(api): broadcast appeal data when change pages are used

---

infrastructure/app-api.tf
infrastructure/environments/dev.tfvars
infrastructure/environments/prod.tfvars
infrastructure/environments/test.tfvars
infrastructure/environments/training.tfvars

Infrastructure changes to go with https://github.com/Planning-Inspectorate/appeals-back-office/pull/300
Adds a TIMEOUT_LIMIT_HORIZON setting to all environments

feat(appeals): infra settings for horizon timeouts

---

appeals/api/src/server/endpoints/appeals.d.ts
appeals/web/src/server/appeals/appeal-details/appeal-details.types.d.ts
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.controller.js
appeals/web/src/server/lib/mappers/lpaQuestionnaire.mapper.js

Document types fix:
- siteNotice -> whoNotifiedSiteNotice
- lettersToNeighbours -> whoNotifiedLetterToNeighbours
- pressAdvert -> whoNotifiedPressAdvert
[A2-315 Creation of three new rows/folders for HAS LPAQ](https://pins-ds.atlassian.net.mcas.ms/browse/A2-315)

fix(appeals): updated folder names for new notify rows

---

appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/__tests__/__snapshots__/manage-linked-appeals.test.js.snap
appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/__tests__/manage-linked-appeals.test.js
appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/manage-linked-appeals.validators.js
appeals/web/src/server/appeals/appeal-details/other-appeals/__tests__/__snapshots__/other-appeals.test.js.snap
appeals/web/src/server/appeals/appeal-details/other-appeals/__tests__/other-appeals.test.js
appeals/web/src/server/appeals/appeal-details/other-appeals/other-appeals.validators.js

add validation for linkable appeal reference length on linked and related appeals flows. Fixes bugs relating to user entering appeal references fewer or greater than 7 digits in length.
A2-402

fix(web): add validation for linkable appeal reference length on linked and related appeals flows

---

appeals/web/src/server/appeals/appeal-documents/appeal-documents.controller.js

Redirects are failing on appeal documents on DEV and TEST only.
It seems to coincide with a recent PR addressing security logs and looks consistent with where it's failing.
https://github.com/Planning-Inspectorate/appeals-back-office/pull/307
This reverts a small part of that code update.
[A2-616 WEB/API - cannot remove documents from manage file page ](https://pins-ds.atlassian.net.mcas.ms/browse/A2-616)

fix(web): security logs update reverted (partially)

---

appeals/api/src/server/endpoints/addresses/__tests__/addresses.test.js
appeals/api/src/server/endpoints/addresses/addresses.controller.js
appeals/api/src/server/endpoints/appellant-cases/__tests__/appellant-cases.test.js
appeals/api/src/server/endpoints/appellant-cases/appellant-cases.controller.js
appeals/api/src/server/endpoints/constants.js
appeals/api/src/server/endpoints/lpa-questionnaires/__tests__/lpa-questionnaires.test.js
appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.controller.js
appeals/api/src/server/endpoints/neighbouring-sites/neighbouring-sites.controller.js
appeals/api/src/server/tests/appeals/mocks.js
appeals/api/src/server/utils/__tests__/string-utils.test.js
appeals/api/src/server/utils/string-utils.js

Applies `createAuditTrail` where missing for appellant case and LPAQ change rows.
Adds a `camelToScreamingSnake` string util
[A2-647](https://pins-ds.atlassian.net.mcas.ms/browse/A2-647)
[A2-647]: https://pins-ds.atlassian.net/browse/A2-647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(api): audit trails for appellant case and lpaq

---

appeals/api/.env.test
appeals/api/src/database/seed/data-test.js
appeals/api/src/server/config/config.js
appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
appeals/api/src/server/endpoints/integrations/integrations.middleware.js
appeals/api/src/server/middleware/check-appeal-exists-and-add-to-request.js
appeals/api/src/server/repositories/appeal-lists.repository.js
appeals/api/src/server/utils/feature-flags-appeal-types.js
appeals/web/.env.test
appeals/web/environment/config.js

Adds logic depending on the value of FEATURE_FLAG_S78_WRITTEN env variable, in order to:
- Import S78 appeals
- Add S78 seed data
- Display S78 appeals in lists
- Access S78 appeal details
General unblocking, but here's the epic: https://pins-ds.atlassian.net/browse/A2-730

Enable s78 data, based on flag

---

appeals/api/src/database/seed/seed-training.js

Modifies the DB seed to case data is not deleted from the TRAINING env

feat(api): keep training data when running db seed

---

appeals/api/src/database/seed/data-samples.js
appeals/api/src/database/seed/data-test.js
appeals/api/src/server/endpoints/appeals.d.ts
appeals/api/src/server/endpoints/appellant-cases/appellant-cases.controller.js
appeals/api/src/server/endpoints/appellant-cases/appellant-cases.formatter.js
appeals/api/src/server/openapi-types.ts
appeals/api/src/server/openapi.json
appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.router.js
appeals/web/src/server/appeals/appeal-details/appellant-case/planning-obligation/__tests__/__snapshots__/planning-obligation.test.js.snap
appeals/web/src/server/appeals/appeal-details/appellant-case/planning-obligation/__tests__/planning-obligation.test.js
appeals/web/src/server/appeals/appeal-details/appellant-case/planning-obligation/planning-obligation.controller.js
appeals/web/src/server/appeals/appeal-details/appellant-case/planning-obligation/planning-obligation.mapper.js
appeals/web/src/server/appeals/appeal-details/appellant-case/planning-obligation/planning-obligation.router.js
appeals/web/src/server/appeals/appeal-details/appellant-case/planning-obligation/planning-obligation.service.js
appeals/web/src/server/lib/display-page-formatter.js
appeals/web/src/server/lib/mappers/appellant-case/appeal-type-fpa.mapper.js
appeals/web/src/server/lib/mappers/appellantCase.mapper.js
appeals/web/testing/app/fixtures/referencedata.js

add planning obligation boolean and status rows to s78 appellant case
A2-173

feat(appeals): add planning obligation boolean and status rows to s78 appellant case

---

infrastructure/environments/test.tfvars

Enables the S78 flag on the TEST environment.
Terraform CI

feat(appeals): enable S78 flag on TEST env

---

appeals/web/src/server/appeals/appeal-details/appellant-case/agricultural-holding/agricultural-holding.controller.js
appeals/web/src/server/appeals/appeal-details/appellant-case/appeal-costs-application/appeal-costs-application.controller.js
appeals/web/src/server/appeals/appeal-details/appellant-case/application-decision-date/application-decision-date.controller.js
appeals/web/src/server/appeals/appeal-details/appellant-case/application-outcome/application-outcome.controller.js
appeals/web/src/server/appeals/appeal-details/appellant-case/application-submission-date/application-submission-date.controller.js
appeals/web/src/server/appeals/appeal-details/appellant-case/development-description/development-description.controller.js
appeals/web/src/server/appeals/appeal-details/appellant-case/owners-known/owners-known.controller.js
appeals/web/src/server/appeals/appeal-details/appellant-case/planning-obligation/planning-obligation.controller.js
appeals/web/src/server/appeals/appeal-details/appellant-case/site-area/site-area.controller.js
appeals/web/src/server/appeals/appeal-details/appellant-case/site-ownership/site-ownership.controller.js
appeals/web/src/server/appeals/appeal-details/green-belt/green-belt.controller.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/affected-listed-buildings/affected-listed-buildings.controller.js

Calls to addNotificationBannerToSession were previously passing `undefined` as the `html` parameter in situations where the parameter was not required. This PR changes these instances to pass empty strings instead.
A2-846

refactor(web): pass empty string to addNotificationBannerToSession instead of undefined (html param)

---

appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js

fix late entry tags appearing on manage pages for folders other than additional documents
A2-886

fix(web): fix late entry tags appearing on manage pages for folders other than additional documents

---

appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
appeals/web/src/server/appeals/appeal-details/costs/__tests__/__snapshots__/costs.test.js.snap
appeals/web/src/server/appeals/appeal-details/costs/__tests__/costs.test.js
appeals/web/src/server/appeals/appeal-details/internal-correspondence/__tests__/__snapshots__/internal-correspondence.test.js.snap
appeals/web/src/server/appeals/appeal-details/internal-correspondence/__tests__/internal-correspondence.test.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
appeals/web/src/server/appeals/appeal-documents/appeal-documents.controller.js
appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js

Remove "Yes, and upload another document" option from delete document version journey
A2-901

feat(web): Remove "Yes, and upload another document" option from delete document version journey

---

appeals/api/src/server/endpoints/integrations/integrations.broadcasters/documents.js
appeals/api/src/server/endpoints/integrations/integrations.controller.js
appeals/api/src/server/repositories/integrations.repository.js

A2-946
Correct the types for document broadcast, and use the `documentGuid` property of the document version for broadcast.

fix(api): ensure broadcast document selects the correct document by guid

---

appeals/api/setup-tests.js
appeals/api/src/server/endpoints/integrations/__tests__/integrations.test.js
appeals/api/src/server/endpoints/integrations/integrations.mappers/document.mapper.js

When broadcasting document data, use an exception for `caseDecisionLetter` document types, forcing them to be broadcasted with `redactedStatus: no_redaction_required`.

fix(api): broadcast no redaction required for decision letter

---

appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
appeals/web/src/server/appeals/appeal-details/appeal-details.controller.js
appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
appeals/web/src/server/appeals/appeal-details/interested-party-comments/interested-party-comments.service.js
appeals/web/src/server/lib/mappers/notification-banners.mapper.js
appeals/web/testing/app/fixtures/referencedata.js

add notification banner to case details page for full planning / s78 appeals in 'statements' status which have unreviewed IP comments
A2-587

feat(web): add notification banner for unreviewed ip comments

---

appeals/api/jest.config.js
appeals/api/setup-tests.js
appeals/api/src/server/endpoints/documents/documents.service.js
appeals/api/src/server/endpoints/integrations/__tests__/integrations.test.js
appeals/api/src/server/endpoints/integrations/integrations.controller.js
appeals/api/src/server/endpoints/integrations/integrations.mappers.js
appeals/api/src/server/endpoints/integrations/integrations.mappers/appellant-case.mapper.js
appeals/api/src/server/endpoints/integrations/integrations.mappers/document.mapper.js
appeals/api/src/server/endpoints/integrations/integrations.service.js
appeals/api/src/server/repositories/integrations.repository.js
appeals/api/src/server/tests/integrations/mocks.js

Increase test coverage on integration code.
Removes custom coverage thresholds for integration.
Uses `originalFilename` when displaying imported documents.
[A2-976](https://pins-ds.atlassian.net/browse/A2-976)
[A2-778](https://pins-ds.atlassian.net/browse/A2-778)
[A2-976]: https://pins-ds.atlassian.net/browse/A2-976?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[A2-778]: https://pins-ds.atlassian.net/browse/A2-778?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(api): integration test coverage

---

appeals/web/src/server/app/components/file-downloader.component.js

Fixes downloading document encoded in storage: uses `decodeURIComponent` to decode the storage path and allow finding the blob.

fix(web): decode document key in doc download

---

appeals/api/src/server/endpoints/integrations/__tests__/documents-import.test.js
appeals/functions/document-processing/document-move/blob.js
appeals/web/src/server/app/components/file-downloader.component.js

When importing blobs from front office, documents with spaces where encoded when trying to validate the document URI.

fix(appeals): decoding of blob path when copying blobs

---

appeals/api/setup-tests.js
appeals/api/src/server/config/config.js
appeals/api/src/server/config/schema.js
appeals/api/src/server/endpoints/appeal-timetables/appeal-timetables.service.js
appeals/api/src/server/endpoints/documents/documents.service.js
appeals/api/src/server/utils/blobValidation.js
infrastructure/document-storage.tf
packages/appeals/constants/common.js
packages/appeals/constants/documents.js

This is a remedy to the PEN test report, client-side upload vulnerabilities.
Before writing document records to the database, an extra validation check will:
- Download the first bytes from blob storage
- Calculate the `magic number` signature of the file, to ensure the content type is allowed
- Validates the documentURI
[A2-848](https://pins-ds.atlassian.net/browse/A2-848)
[A2-848]: https://pins-ds.atlassian.net/browse/A2-848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(api): server-side checks on uploaded blobs

---

appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js

Add visually hidden content to review IP comments link in notification banner. Also includes a small refactoring improvement to `mapStatusDependentNotifications` (replace hardcoded appeal status strings with constants)
A2-587

fix(web): add visually hidden content to review IP comments link in notification banner

---

.vscode/settings.json
appeals/api/src/server/endpoints/appeal-timetables/appeal-timetables.service.js

Quick fix from dates refactoring, ensures that start date is set back to start of the day after business days calc

fix(api): ensures start date is set to beginning of day UTC

---

appeals/api/package.json
package-lock.json
package.json

Uses an upgraded data model schema (v1.9.1) to support new document types for HAS.

feat(api): updates schemas to include new doc types

---

appeals/web/src/server/lib/mappers/appeal/appeal.mapper.js

Small bug, was trying to load inspector details from the wrong group.
[A2-1240](https://pins-ds.atlassian.net/browse/A2-1240)
[A2-1240]: https://pins-ds.atlassian.net/browse/A2-1240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(web): binding of inspector data A2-1240

---

appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
appeals/web/src/server/lib/mappers/notification-banners.mapper.js

Two important notification banners added to Appeal details
- 'Ready for validation' when the case status is 'validation'
- 'LPA questionnaire ready for review' when the status is 'lpa_questionnaire' and it has an LPAQ id
[A2-397 WEB - Missing banners -  Appeal ready for validation & LPA is ready to review](https://pins-ds.atlassian.net.mcas.ms/browse/A2-397)

fix(web): ready for validation and ready for LPAQ review banners added

---

appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-ip-comment/__tests__/__snapshots__/add-ip-comment.test.js.snap
appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-ip-comment/__tests__/add-ip-comment.test.js
appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-ip-comment/add-ip-comment.mapper.js

Previously missed that there is a lib function for creating the full set of address inputs. This PR just replaces the duplicated instance in interested-party-comments with the `addressInputs` function.
[A2-600](https://pins-ds.atlassian.net/browse/A2-600)
[A2-600]: https://pins-ds.atlassian.net/browse/A2-600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(web): use addressInputs lib function in Add IP Comment form

---

appeals/web/package.json
appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.controller.js
appeals/web/src/server/appeals/appeal-details/costs/__tests__/__snapshots__/costs.test.js.snap
appeals/web/src/server/appeals/appeal-details/costs/__tests__/costs.test.js
appeals/web/src/server/appeals/appeal-details/costs/costs.controller.js
appeals/web/src/server/appeals/appeal-details/costs/costs.mapper.js
appeals/web/src/server/appeals/appeal-details/costs/costs.router.js
appeals/web/src/server/appeals/appeal-details/internal-correspondence/internal-correspondence.controller.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.controller.js
appeals/web/src/server/appeals/appeal-documents/appeal-documents.controller.js
appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js

Add custom date field label copy for costs decision document flows. Includes supporting refactoring of some shared document functions to accept a params object, which has several advantages. Also fixes the costs decision upload new version flow to use the correct check and confirm screen (was previously using the same screen as other costs flows, which doesn't include the confirmation checkbox).
A2-844

feat(web): add custom date field label copy for costs decision document flows

---

appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.controller.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.controller.js

fix add document notification banners not displaying on appellant case and lpaq pages
A2-1232

fix(web): fix add document notification banners not displaying on appellant case and lpaq pages

---

appeals/web/environment/permissions.js
appeals/web/src/server/app/auth/auth.router.js
appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.mapper.js
appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.router.js
appeals/web/src/server/appeals/appeal-details/assign-user/assign-user.router.js
appeals/web/src/server/appeals/appeal-details/costs/costs.router.js
appeals/web/src/server/appeals/appeal-details/internal-correspondence/internal-correspondence.router.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.router.js
appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.router.js
appeals/web/src/server/appeals/personal-list/personal-list.mapper.js

Aligns permissions between inspectors and case officers
A2-1279

fix(appeals): inspector perms reset A2-1279

---

appeals/api/src/database/seed/seed-clear.js
appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
appeals/web/src/server/appeals/appeal-details/appeal-details.controller.js
appeals/web/src/server/appeals/appeal-details/appeal-details.router.js
appeals/web/src/server/appeals/appeal-details/case-notes/case-notes.controller.js

Empty case note submission now gives error message instead of 500 error page

fix(appeals): handle case notes empty string without 500 error

---

appeals/api/src/database/seed/data-samples.js
appeals/api/src/database/seed/data-test.js
appeals/api/src/server/endpoints/appeals.d.ts
appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.controller.js
appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.formatter.js
appeals/api/src/server/repositories/lpa-questionnaire.repository.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/environmental-impact-assessment/__tests__/__snapshots__/environmental-impact-assessment.test.js.snap
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/environmental-impact-assessment/__tests__/environmental-impact-assessment.test.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/environmental-impact-assessment/environmental-impact-assessment.controller.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/environmental-impact-assessment/environmental-impact-assessment.mapper.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/environmental-impact-assessment/environmental-impact-assessment.router.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/environmental-impact-assessment/environmental-impact-assessment.service.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.router.js
appeals/web/src/server/lib/mappers/components/radio.js
appeals/web/src/server/lib/mappers/lpa-questionnaire/s78.js
appeals/web/src/server/lib/mappers/lpa-questionnaire/submappers/map-eia-column-two-threshold.js
appeals/web/src/server/lib/mappers/lpa-questionnaire/submappers/map-eia-requires-environmental-statement.js

add s78 lpaq rows for environmental impact assessment boolean fields
A2-1149

feat(appeals): add s78 lpaq rows for environmental impact assessment boolean fields

---

appeals/api/src/server/endpoints/change-appeal-type/__tests__/change-appeal-type.test.js
appeals/api/src/server/endpoints/change-appeal-type/change-appeal-type.service.js

Aligns the GovNotify notification variables to changes to templates: appeal type change and resubmit.

fix(appeals): align changed notification vars

---

appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
appeals/web/src/server/appeals/appeal-details/appellant-case/procedure-preference/__tests__/__snapshots__/procedure-preference.test.js.snap
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js
appeals/web/src/server/lib/mappers/appeal/submappers/appellant-health-and-safety.mapper.js
appeals/web/src/server/lib/mappers/appeal/submappers/appellant-inspector-access.mapper.js
appeals/web/src/server/lib/mappers/appeal/submappers/lpa-health-and-safety.mapper.js
appeals/web/src/server/lib/mappers/appeal/submappers/lpa-inspector-access.mapper.js
appeals/web/src/server/lib/mappers/appellantCase.mapper.js
appeals/web/src/server/lib/mappers/components/boolean.js
appeals/web/src/server/lib/mappers/components/text.js
appeals/web/src/server/lib/mappers/lpa-questionnaire/has.js
appeals/web/src/server/lib/mappers/lpa-questionnaire/submappers/map-extra-conditions.js
appeals/web/src/server/lib/mappers/lpa-questionnaire/submappers/map-lpa-health-and-safety.js
appeals/web/src/server/lib/mappers/lpa-questionnaire/submappers/map-site-access.js
appeals/web/testing/app/fixtures/referencedata.js

Global rollout of show more component. Also includes a fix to map appellant case inspector access from the appellant case data rather than the equivalent field on the appeal data (for consistency with the LPAQ mapper).
A2-826

feat(web): global rollout of show more component

---

appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
appeals/web/src/server/appeals/appeal-details/appellant-case/procedure-preference/__tests__/__snapshots__/procedure-preference.test.js.snap
appeals/web/src/server/lib/mappers/appellant-case/appeal-type-fpa.mapper.js

Updating the FPA mapper to reorganise appeal details items in order to group the planning oblication information
A2-903

fix(web): update to the FPA mapper to reorder the appeal details items

---

appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-ip-comment/add-ip-comment.controller.js

The post upload handler is incorrectly referencing `currentAppeal.id`. This changes it to `currentAppeal.appealId`.
[A2-604](https://pins-ds.atlassian.net/browse/A2-604)
[A2-604]: https://pins-ds.atlassian.net/browse/A2-604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(web): fix reference to appealId in add-ip-comment upload handler

---

appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-ip-comment/add-ip-comment.mapper.js

Updating the add ip comment mapper to ensure that when no address is provided the correct content is displayed on the screen

fix(web): ensuring correct content displays when no Address is provided

---

appeals/api/src/server/endpoints/appeal-timetables/__tests__/appeal-timetables.test.js
appeals/api/src/server/endpoints/appellant-cases/__tests__/appellant-cases.test.js
appeals/api/src/server/endpoints/appellant-cases/appellant-cases.service.js
appeals/api/src/server/endpoints/integrations/__tests__/integrations.test.js
appeals/api/src/server/endpoints/lpa-questionnaires/__tests__/lpa-questionnaires.test.js
appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.service.js
appeals/api/src/server/repositories/document-metadata.repository.js
appeals/api/src/server/repositories/document.repository.js
appeals/api/src/server/repositories/integrations.repository.js
appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.mapper.js
appeals/web/src/server/appeals/appeal-details/costs/__tests__/__snapshots__/costs.test.js.snap
appeals/web/src/server/appeals/appeal-details/costs/__tests__/costs.test.js
appeals/web/src/server/appeals/appeal-details/internal-correspondence/__tests__/__snapshots__/internal-correspondence.test.js.snap
appeals/web/src/server/appeals/appeal-details/internal-correspondence/__tests__/internal-correspondence.test.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js
appeals/web/src/server/appeals/appeal-documents/appeal-documents.controller.js
appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js
appeals/web/src/server/views/patterns/display-page.pattern.njk
appeals/web/testing/app/fixtures/referencedata.js

Sets default redaction statuses
It will set redaction status to NULL (for documents received through appellant case and LPAQ), which is then updated to 'No redaction required' when validating those submissions.
It will pre-check 'No redaction required' on documents uploaded directly in the back office.
[A2-1161](https://pins-ds.atlassian.net/browse/A2-1161)
[A2-1161]: https://pins-ds.atlassian.net/browse/A2-1161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(appeals): redaction status defaults A2-1161

---

appeals/api/src/server/endpoints/constants.js
appeals/api/src/server/endpoints/documents/__tests__/documents.test.js
appeals/api/src/server/endpoints/documents/documents.controller.js

This adds the case audit requirement not implemented in the previous PR for this ticket
API:
- Add case audit trail for filename rename 
TESTING:
- Ran all unit tests in API.
- Manually tested within browser and checked case audit
[A2-1138 Rename files](https://pins-ds.atlassian.net/browse/A2-1138)

feat(appeals): rename files case audit A2-1138

---

appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
appeals/web/src/server/lib/mappers/appeal/submappers/appeal-withdrawal.mapper.js
appeals/web/src/server/lib/mappers/appeal/submappers/case-history.mapper.js
appeals/web/src/server/lib/mappers/appeal/submappers/cross-team-correspondence.mapper.js
appeals/web/src/server/lib/mappers/appeal/submappers/inspector-correspondence.mapper.js
appeals/web/src/server/lib/mappers/components/instructions/document.js
appeals/web/src/server/lib/mappers/lpa-questionnaire/utils.js

Refactor mappers in appeal details / case management to use available instructions.
Updated `documentSummaryListItem` to optionally hide documents (like in internal correspondence)

feat(web): refactor instructions for case management

---

appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
appeals/web/src/server/lib/mappers/appeal/submappers/cross-team-correspondence.mapper.js
appeals/web/src/server/lib/mappers/appeal/submappers/started-at.mapper.js

Fixes 2 regressions from recent component refactoring:
- A2-1563 (Cross-team correspondence not saving)
- A2-1559 (Change start date button not appearing)
[A2-1563 ](https://pins-ds.atlassian.net/browse/A2-1563)
[A2-1559](https://pins-ds.atlassian.net/browse/A2-1559) 
[A2-1559]: https://pins-ds.atlassian.net/browse/A2-1559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(web): regressions A2-1563 A2-1559

---

appeals/api/src/database/seed/data-samples.js
appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
appeals/web/src/server/lib/dates.js

- uses the correct appeal type enum for calculating the deadline
- adds the required dates in seed data
[A2-161](https://pins-ds.atlassian.net/browse/A2-161)
[A2-161]: https://pins-ds.atlassian.net/browse/A2-161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(web): picking the correct appealtype config

---

appeals/e2e/cypress/e2e/back-office-appeals/changeAppealType.spec.js

This is a small chaneg to remove the smoke tage for the p2 test - Change appeal type and resubmit
https://pins-ds.atlassian.net/browse/A2-1552
- [ x ] Other (please explain in the description section above)
- [x ] I have performed a self-review of my own code
- [x ] I have double checked this work does not include any hardcoded secrets or passwords
- [] I have made corresponding changes to the documentation
- [x ] I have referenced the ticket number above
- [x ] I have provided a description of the ticket

test: remove smoke tag for p2 change appeal type and resubmit

---

appeals/api/src/server/endpoints/integrations/integrations.mappers/address.mapper.js
appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js

Always broadcast site safety and site access arrays as full, null values are no longer removed but replaced with empty strings.
[A2-1561](https://pins-ds.atlassian.net/browse/A2-1561)
[A2-1561]: https://pins-ds.atlassian.net/browse/A2-1561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(appeals): broadcast of safety and access details (A2-1561)

---

appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-incomplete/outcome-incomplete.router.js
appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-incomplete/outcome-incomplete.validators.js

Removes weekend and business day validation when setting an appellant case as incomplete and providing a future extension date.
Removes related tests
[A2-161](https://pins-ds.atlassian.net/browse/A2-161)
[A2-161]: https://pins-ds.atlassian.net/browse/A2-161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(appeals): removes business day validation from appeal due date

---

appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
appeals/web/src/server/lib/mappers/data/appellant-case/submappers/costs-document.js

Amend copy on some existing rows on HAS appellant case
WEB:
- Changed "Cost document" copy to "Cost application" as instructed
Please note the other copy changes have already been done in this PR: [A2-1186](https://github.com/Planning-Inspectorate/appeals-back-office/pull/682)
[A2-540 Amend copy on some existing rows on HAS appellant case](https://pins-ds.atlassian.net/browse/A2-540)
[A2-1186]: https://pins-ds.atlassian.net/browse/A2-1186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(appeals): amend copy costs application (a2-540)

---

infrastructure/app-api.tf
infrastructure/app-web.tf

In v1.31, DOCKER_ENABLE_CI tag is set false which is essential to ensure that continuous deployment is not enabled for app services 
Comparison between 130 (current) and 1.31(new)
https://github.com/Planning-Inspectorate/infrastructure-modules/compare/1.30...1.31
https://pins-ds.atlassian.net/browse/DEV-273

fix(tooling): updating node app service module version to 1.31

---

appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
appeals/web/src/server/appeals/appeals.types.d.ts
appeals/web/src/server/lib/display-page-formatter.js
appeals/web/src/server/lib/mappers/components/instructions/document.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/cross-team-correspondence.mapper.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/inspector-correspondence.mapper.js
appeals/web/src/server/lib/mappers/data/appellant-case/submappers/additional-documents.js
appeals/web/src/server/lib/mappers/data/lpa-questionnaire/common.js
appeals/web/src/server/lib/mappers/data/lpa-questionnaire/submappers/map-additional-documents-contents.js

Add option to display document row values as text indicating the number of contained documents, rather than a file list. Applied to case details > case management > cross-team correspondence and inspector correspondence rows. Supporting refactoring.
A2-1659

feat(web): update case details correspondence rows to display number of documents

---

appeals/api/src/database/migrations/20241213155447_representations_text_nvarchar_max/migration.sql
appeals/api/src/database/schema.prisma

Increase the `originalRepresentation` and `redactedRepresentation` columns in the `Representation` database table to `nvarchar(max)`.
[A2-1893](https://pins-ds.atlassian.net/browse/A2-1893)
[A2-1893]: https://pins-ds.atlassian.net/browse/A2-1893?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(api): increase rep fields storage A2-1893

---

appeals/web/src/server/lib/nunjucks-filters/__tests__/format-line-breaks.test.js
appeals/web/src/server/lib/nunjucks-filters/format-line-breaks.js
appeals/web/src/server/lib/nunjucks-filters/index.js
appeals/web/src/server/views/appeals/components/case-notes.njk

WEB:
- Added a filter to format the line breaks
- Applied the filter to the case notes component
TESTING:
- Added a unit tests for new filter
- WEB unit tests pass
[A2-1399 As a back office user I want my paragraph breaks to be reflected in the case note](https://pins-ds.atlassian.net/browse/A2-1399)

fix(appeals): case notes paragraph breaks are formatted correctly (a2-1399)

---

appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
appeals/web/src/server/lib/display-page-formatter.js
appeals/web/src/styles/5-elements/_elements.pins-file-list.scss
appeals/web/src/styles/7-components/_summary-list.scss
appeals/web/src/styles/main.scss

Update summary list rows which display documents as lists of filename links to ordered lists displaying numbered markers (number is not displayed if there is only one item in the list)
A2-859

feat(web): update summary list row document lists to numbered lists

---

appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/environmental-impact-assessment/__tests__/environmental-impact-assessment.test.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/environmental-impact-assessment/environmental-impact-assessment.controller.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/environmental-impact-assessment/environmental-impact-assessment.mapper.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/neighbouring-site-access/__tests__/neighbouring-site-access.test.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/neighbouring-site-access/neighbouring-site-access.controller.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/neighbouring-site-access/neighbouring-site-access.mapper.js

The following conditional free text rows were recently added to the s78 LPA questionnaire:
- Environmental impact assessment: In, partly in or likely to affect sensitive area
- Consultation responses and representations: Consulted relevant statutory consultees
- Site access: Inspector needs neighbouring site access
This PR fixes an issue where the user-submitted text is cleared from the field if a validation error occurs.
A2-1287

fix(web): fix to re-populate submitted text into textareas on s78 lpaq conditional text rows

---

appeals/api/src/server/endpoints/integrations/__tests__/documents-import.test.js
appeals/api/src/server/endpoints/integrations/integrations.mappers.js
appeals/api/src/server/endpoints/integrations/integrations.utils.js

Fixes import of duplicate documents, by appending a `_n` suffix in the file name.
Example input:
`
[
{ documentType: 'A', originalFilename: 'name.pdf' },
{ documentType: 'A', originalFilename: 'name.pdf' },
{ documentType: 'A', originalFilename: 'name.pdf' }
]
`
Expected output:
`
[
{ documentType: 'A', originalFilename: 'name.pdf' },
{ documentType: 'A', originalFilename: 'name_1.pdf' },
{ documentType: 'A', originalFilename: 'name_2.pdf' }
]
`

fix(api): importing duplicate documents

---

appeals/web/src/client/components/file-uploader/_errors.js
appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
appeals/web/src/server/appeals/appeal-details/costs/__tests__/__snapshots__/costs.test.js.snap
appeals/web/src/server/appeals/appeal-details/internal-correspondence/__tests__/__snapshots__/internal-correspondence.test.js.snap
appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/__snapshots__/issue-decision.test.js.snap
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
appeals/web/src/server/appeals/appeal-details/withdrawal/__tests__/__snapshots__/withdrawal.test.js.snap
appeals/web/src/server/appeals/appeal-documents/__tests__/__snapshots__/appeal-documents.test.js.snap
appeals/web/src/server/views/app/components/file-uploader.component.njk
appeals/web/src/server/views/appeals/documents/decision-letter-upload.njk
appeals/web/src/server/views/appeals/documents/document-upload.njk

WEB:
- Moved the error summary hook outside the file-uploader-component and above the page heading
- Changed the client-side JavaScript to cope with above and added the logic to create the standard error messages around the upload component as requested by design
TESTING:
- WEB unit tests pass
[A2-1222 WEB - File upload component - error summary should be above the H1](https://pins-ds.atlassian.net/browse/A2-1222)
**Note there is a screenshot of the new design seen in a comment in the ticket above**

fix(appeals): error summary should be above heading (a2-1222)

---

appeals/web/src/client/components/show-more/show-more.js

Still not totally sure why this bug happens but like a lot of those sorts of bugs it can be fixed by waiting for a bit 🤷🏻‍♀️
Adds a recursive timeout to the show more script that waits for inner text to appear in the target before proceeding.

fix(web): make show more wait for inner text

---

appeals/web/src/server/appeals/appeal-details/interested-party-comments/view-and-review/view-and-review.controller.js

Fixes a bug where the user would be redirected to the view IP comment page if an error occurred on the review IP comment page

fix(web): redirect to review on review error

---

appeals/web/src/server/appeals/appeal-details/appeal-details.controller.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.controller.js
appeals/web/src/server/lib/mappers/data/lpa-questionnaire/mapper.js
appeals/web/src/server/lib/mappers/data/lpa-questionnaire/submappers/map-review-outcome.js

**Please note that these changes now mean all Acceptance Criteria on the ticket A2-1882 are satisfied whether the ticket itself is correct or not.**
Please also note that in this PR, a fix has been made to make sure the LPA Questionnaire will now **only complete** after the new  environmental impact assessment screening required page is confirmed.
WEB:
- Moved the logic to "complete" the LPA Questionnaire to the post of the new  environmental impact assessment screening required page.
- Added a session variable to allow the complete or incomplete radio buttons to show as checked when the back link is clicked from the environmental impact assessment screening required page.
TESTING:
- WEB fixed unit tests and checked all other tests pass.
- API checked all tests pass
- Manually tested …

feat(appeals): address eia screening scenario 3 back link (a2-1882)

---

appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.controller.js

This PR is to fix the issue caused by the previous PR which meant that HAS LPA Questionnaires  did not "complete" correctly.
WEB:
- Put the logic back to "complete" the LPA Questionnaire when HAS.  This is because the new environmental impact assessment screening required page is not in the flow when HAS.
TESTING:
- WEB fixed unit tests and checked all other tests pass.
- API checked all tests pass
- Manually tested both HAS and S78 within browser
[A2-1882 Boolean - Does the environmental services team need to review the case?](https://pins-ds.atlassian.net/browse/A2-1882)

feat(appeals): fix complete when householder (a2-1882)

---

appeals/api/setup-tests.js
appeals/api/src/server/endpoints/representations/__tests__/representations.test.js
appeals/api/src/server/endpoints/representations/representations.controller.js
appeals/api/src/server/endpoints/representations/representations.routes.js
appeals/api/src/server/endpoints/representations/representations.service.js
appeals/api/src/server/openapi-types.ts
appeals/api/src/server/openapi.json

Developed a new API endpoint to enable the association of uploaded documents with an existing statement.
[A2-2004](https://pins-ds.atlassian.net/browse/A2-2004)
[A2-2004]: https://pins-ds.atlassian.net/browse/A2-2004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(api): associate uploaded documents with an existing statement

---

appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-document/add-document.router.js
appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-document/controller/date-submitted.js
appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-document/controller/redaction-status.js
appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-ip-comment/add-ip-comment.controller.js
appeals/web/src/server/appeals/appeal-details/interested-party-comments/common/date-submitted.js
appeals/web/src/server/appeals/appeal-details/interested-party-comments/common/redaction-status.js
appeals/web/src/server/appeals/appeal-details/interested-party-comments/interested-party-comments.router.js

Fixes a bug in IP doc flows that use the date submitted and redaction status components where session values were not displayed in the inputs.
[Ticket](https://pins-ds.atlassian.net/browse/A2-1748)

fix(web): Read redaction status and date submitted from session

---

appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js
appeals/web/src/server/lib/display-page-formatter.js
appeals/web/src/server/lib/mappers/data/lpa-questionnaire/submappers/map-notification-methods.js
appeals/web/src/server/lib/mappers/data/lpa-questionnaire/submappers/map-notify-parties.js
appeals/web/src/styles/7-components/_summary-list.scss

Please note that this affects section 2 for HAS and section 3 for S78.  (They are the same section)
WEB:
- Amended copy in mappers as described within the ticket
- Cleaned up padding around the unordered list in the "Notification methods" row
TESTING:
[A2-2047 WEB/API -Amend copy on section 2. Notifying relevant parties of the application of the LPA questionnaire](https://pins-ds.atlassian.net/browse/A2-2047)

feat(appeals): amend copy on notifying relevant parties (a2-2047)

---

azure-pipelines-build.yml
azure-pipelines-deploy-appeals.yml

Switch to newer versions of the Build & Deploy pipelines, to use git commit hash for docker image tags
More [docs here](https://pins-ds.atlassian.net/wiki/spaces/CS/pages/1719861253/App+Service+Deployments)
[Ticket](https://pins-ds.atlassian.net/browse/DEV-337)

ci: use git commit hash for deployments

---

appeals/api/src/database/seed/data-test.js
appeals/api/src/server/endpoints/appeal-details/__tests__/appeals-details.test.js
appeals/api/src/server/endpoints/appeal-details/appeal-details.controller.js
appeals/api/src/server/endpoints/appeal-details/appeal-details.service.js
appeals/api/src/server/endpoints/integrations/integrations.broadcasters/documents.js

- Moves appeal status only when case officer is added, not when replaced
- Additional LPAQ cases in seed
[Ticket](https://pins-ds.atlassian.net/browse/A2-2196)

fix(api): case assignment and more lpa seeds

---

appeals/api/src/server/endpoints/appeals.d.ts
appeals/api/src/server/openapi-types.ts
appeals/api/src/server/openapi.json
appeals/api/src/server/utils/mapping/map-enums.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js
appeals/web/src/server/lib/mappers/data/lpa-questionnaire/has.js
appeals/web/src/server/lib/mappers/data/lpa-questionnaire/submappers/map-appeal-notification.js

WEB:
- Added the submapper for the Appeal notification letter row
- Included the submapper in the Notifying relevant parties section for both HAS and S78
- hooked up the functionality to add and manage documents for this row
API:
- Updated SingleLPAQuestionnaireResponse interface to include appealNotification
- Regenerated APIspec
TESTING:
[A2-1985 Remove an agent](https://pins-ds.atlassian.net/browse/A2-1985)

feat(appeals): add appeal notification letter row (a2-1985)

---

appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/incomplete/incomplete.controller.js
appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/incomplete/incomplete.mapper.js
appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/incomplete/incomplete.router.js
appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/incomplete/incomplete.validator.js

Implementation of the set new date page within the incomplete lpa statements journey. 
Also a few tweaks to routing of other pages on confirm / back links. 
fyi that while the success banner design (for when the CYA page is submitted) is included in this ticket the cya confirm will be part of ticket part 4. 
https://pins-ds.atlassian.net/browse/A2-1743

feat(web): lpa statements set new date page addition

---

appeals/api/src/server/endpoints/appeal-timetables/appeal-timetables.service.js

Tiny PR, fixes the broadcast of appeal data when updating timetable deadlines.
[Ticket]()

fix(api): fixes the appeal broadcast when updating deadlines

---

appeals/api/src/server/endpoints/documents/documents.controller.js
appeals/api/src/server/endpoints/documents/documents.routes.js
appeals/api/src/server/endpoints/documents/documents.service.js
appeals/api/src/server/mappers/integration/map-document-entity.js
appeals/api/src/server/openapi.json
appeals/api/src/server/repositories/appeal.repository.js
appeals/api/src/server/repositories/folder.repository.js

Adds an optional `repId` querystring param when loading a single folder. If the folder is for representation attachments, it will only return the documents that are attachment of the representation ID provided.
Also, removed any GUID prefixes in the document name (used to avoid folder constraints) when showing the data back to the user.

fix(api): returns only attachments to a rep in that folder

---

appeals/api/src/server/repositories/appeal.repository.js

A2-1832
In the endpoint used by the new cron job, check `visitDate` column is in the past if `visitEndTime` is not present.
[A2-1832](https://pins-ds.atlassian.net/browse/A2-1832)
[A2-1832]: https://pins-ds.atlassian.net/browse/A2-1832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(api): check visitDate is in the past if visitEndTime is not present

---

appeals/web/src/server/appeals/appeal-details/accordions/utils/map-status-dependent-notifications.js
appeals/web/src/server/appeals/appeal-details/representations/representations.mapper.js
appeals/web/src/server/appeals/appeal-details/representations/representations.validators.js
appeals/web/src/server/appeals/personal-list/__tests__/personal-list.test.js
appeals/web/src/server/appeals/personal-list/personal-list.mapper.js
appeals/web/src/server/lib/mappers/components/page-components/notification-banners.mapper.js

- Added "Progress to final comments" banner in case details page
- Added "Progress to final comments" action link in personal list
- Simplified parameters passed into "mapAppealStatusToActionRequiredHtml" function to pass in the appeal object to reduce the number of parameters required.
- Simplified WEB tests for personal list now the number of parameters are far less when calling "mapAppealStatusToActionRequiredHtml"
[A2-1954 Progress the case on even if no Statements/IP comments have been received](https://pins-ds.atlassian.net/browse/A2-1954)

feat(appeals): progress the case even if no statements, or ipcomments, have been received (a2-1954)

---

infrastructure/app-api.tf
infrastructure/app-web.tf

With infrastructure module v1.38, 
- Uses new public_network_access setting to ensure staging slots have the same networking rules set as the prod slot
- Deny all public network access for Api's
- Allow only front door access for Web Apps
- All site_config changes were ignored due to a incorrect ignore_changes entry. This has been updated to only ignore  the docker image name/tag.
This ensures IP restrictions allowing only front_door and default action settings will apply.
[Ticket-slot-access](https://pins-ds.atlassian.net/browse/DEV-308)
[Ticket-ignore-changes](https://pins-ds.atlassian.net/browse/DEV-351)

fix(infrastructure): updating module version to 1.38

---

appeals/api/src/server/endpoints/documents/documents.controller.js

(Attempts) to fix an issue where updating the name of a doc on back office appears (at first) not to update the name of the doc on front office
[Ticket](https://pins-ds.atlassian.net/browse/A2-2281)

fix(api): update doc before broadcast

---

appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
appeals/api/src/server/endpoints/appeals/appeals.formatter.js

- Update the appeals formatter in personal list to calculate due date as 30 business days after the site visit 
- API unit tests updated
[A2-2248 Notify: Share comments and statements for Written Representations](https://pins-ds.atlassian.net/browse/A2-2248)

fix(appeals): review personal list deadlines (a2-2248)

---

appeals/api/src/server/repositories/appeal-lists.repository.js

- Fix bug in the where clause within the appeal-lists.repository getUserAppeals function
[A2-2384 Unable to filter on personal list](https://pins-ds.atlassian.net/browse/A2-2384)

fix(appeals): unable to filter on personal list (a2-2384)

---

appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
appeals/web/src/server/lib/representation-utilities.js

adds handling for rejected comments to `mapRepresentationDocumentSummaryStatus`
https://pins-ds.atlassian.net/browse/A2-2162

fix(web): fix incorrect status in documentation summary rows for rejected final comments

---

appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
appeals/api/src/server/endpoints/appeals/appeals.formatter.js

API:
- Added constant
- Updated due date calculation for issue determination after a site visit
TESTS:
- Updated API unit test
- All other API tests pass
[Ticket: Review personal list deadlines (a2-2248)](https://pins-ds.atlassian.net.mcas.ms/browse/A2-2248)

fix(appeals): issue determination due date should be 10 days after the site visit (a2-2248)

---

appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/affected-listed-buildings/__tests__/__snapshots__/affected-listed-buildings.test.js.snap
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/affected-listed-buildings/__tests__/affected-listed-buildings.test.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/affected-listed-buildings/affected-listed-buildings.mapper.js

Added govuk-link class where missing in affected-listed-buildings mapper
[Ticket: A2-1768](https://pins-ds.atlassian.net/browse/A2-1768)

fix(appeals): add listed building check answers page has unstyled link (a2-1768)

---

appeals/web/src/server/appeals/appeal-details/representations/__tests__/__snapshots__/representations.test.js.snap
appeals/web/src/server/appeals/appeal-details/representations/__tests__/representations.test.js
appeals/web/src/server/appeals/appeal-details/representations/representations.mapper.js

WEB:
- Added hash to link to open accepted tab as requested
TESTS:
- Added WEB unit test
- Added snapshot
- All WEB tests pass
[Ticket: Review personal list deadlines (a2-2356)](https://pins-ds.atlassian.net.mcas.ms/browse/A2-2356)

fix(appeals): clicking IP comments should take user to IP Comments Accepted Tab (a2-2356)

---

appeals/web/src/server/appeals/appeal-details/final-comments/view-and-review/__tests__/__snapshots__/view-and-review.test.js.snap
appeals/web/src/server/appeals/appeal-details/final-comments/view-and-review/__tests__/view-and-review.test.js
appeals/web/src/server/appeals/appeal-details/final-comments/view-and-review/page-components/common.js

Adds a wrapping "show more" component to the redacted comment text summary list row on the view/review final comments screen. Also includes a small fix to the existing view-and-review unit tests (POST test was inside describe for GET tests, moved this out into its own describe)
https://pins-ds.atlassian.net/browse/A2-2393

fix(web): wrap redacted final comment in show-more component on view and review screen

---

appeals/web/src/server/lib/mappers/data/appeal/submappers/ip-comments-due-date.mapper.js

Hide IP comments timetable change link after sharing comments
[A2-2408](https://pins-ds.atlassian.net/browse/A2-2408)
[A2-2408]: https://pins-ds.atlassian.net/browse/A2-2408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(web): hide IP comments timetable change link after sharing comments

---

appeals/web/src/server/appeals/appeal-details/accordions/utils/__tests__/__snapshots__/map-status-dependent-notifications.test.js.snap
appeals/web/src/server/appeals/appeal-details/accordions/utils/__tests__/map-status-dependent-notifications.test.js
appeals/web/src/server/appeals/appeal-details/accordions/utils/map-status-dependent-notifications.js
appeals/web/src/server/appeals/personal-list/__tests__/personal-list.test.js
appeals/web/src/server/appeals/personal-list/personal-list.mapper.js

Although this ticket concentrates on appeal status of STATEMENTS, it is hopefully a template especially for the unit tests that we should use to bring all the other banners being displayed within the other appeal statuses.
WEB:
- Refactored banners for STATEMENTS status to match acceptance criteria 
- Add unit tests for banners with STATEMENTS status to test above criteria
- Refactored CTAs for STATEMENTS status in personal list to match acceptance criteria 
- Add unit tests for CTAs with STATEMENTS status in personal list to test above criteria
TESTING:
[A2-2389 Share IP comments and LPA Statement - Share banner not displaying on case details](https://pins-ds.atlassian.net/browse/A2-2389)

fix(appeals): correct banner display conditions when appeal status is STATEMENTS (a2-2389)

---

appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/add-ip-comment/__tests__/add-ip-comment.test.js
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/add-ip-comment/add-ip-comment.controller.js
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/add-ip-comment/add-ip-comment.mapper.js

Include persisted data in rendered page views on add IP comment journey.
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-2109)

fix(web): a2-2109 render persisted data on add IP comment views

---

appeals/web/src/server/appeals/appeal-details/accordions/utils/__tests__/__snapshots__/map-status-dependent-notifications.test.js.snap
appeals/web/src/server/appeals/appeal-details/accordions/utils/__tests__/map-status-dependent-notifications.test.js
appeals/web/src/server/appeals/appeal-details/accordions/utils/map-status-dependent-notifications.js
appeals/web/src/server/appeals/personal-list/__tests__/personal-list.test.js
appeals/web/src/server/appeals/personal-list/personal-list.mapper.js

WEB:
- Refactored banners for FINAL COMMENTS status to match acceptance criteria 
- Add unit tests for banners with FINAL COMMENTS status to test above criteria
- Refactored CTAs for FINAL COMMENTS status in personal list to match acceptance criteria 
- Add unit tests for CTAs with FINAL COMMENTS status in personal list to test above criteria
TESTING:
[A2-2410 "Progress case" entry points vs "review final comments" when deadline has passed](https://pins-ds.atlassian.net/browse/A2-2410)

fix(appeals): align final comments personal-list and info-banners (a2-2410)

---

appeals/web/src/server/appeals/appeal-details/final-comments/accept/__tests__/__snapshots__/accept-final-comments.test.js.snap
appeals/web/src/server/appeals/appeal-details/final-comments/accept/__tests__/accept-final-comments.test.js
appeals/web/src/server/appeals/appeal-details/final-comments/accept/accept.controller.js
appeals/web/src/server/appeals/appeal-details/final-comments/accept/accept.mapper.js
appeals/web/src/server/appeals/appeal-details/final-comments/accept/components/summary-list.js
appeals/web/src/server/lib/mappers/components/page-components/notification-banners.mapper.js

- created route for supporting docs "change" button in accept final comments view
- corrected call to success banner
- added condition to determine success banner type
- updated snapshot & test
https://pins-ds.atlassian.net/browse/A2-2232?atlOrigin=eyJpIjoiY2I0N2EzOWYzNDRkNDJiNDg5NjY1NWRhZDk3ZTdjYzMiLCJwIjoiaiJ9

fix(web): fixes for the accept final comments flow

---

appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/view-and-review/page-components/common.js

Filter deleted items so they are not displayed in the IP supporting documents row.
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-2139)

fix(web): a2-2139 filter deleted docs from IP supporting docs row

---

appeals/api/src/server/endpoints/integrations/integrations.broadcasters/appeal.js
appeals/api/src/server/endpoints/representations/representations.controller.js
appeals/api/src/server/mappers/integration/s78/map-case-dates.js

Broadcasts the dates of the following representation fields with the appeal data:
- appellantCommentsSubmittedDate
- lpaCommentsSubmittedDate
- appellantStatementSubmittedDate
- lpaStatementSubmittedDate

fix(api): broadcast of received reps dates

---

appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/interested-party-comments.router.js
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/view-and-review/__tests__/__snapshots__/view-and-review.test.js.snap

WEB:
- Reverted a change made in [A2-1921](https://github.com/Planning-Inspectorate/appeals-back-office/pull/1022)
- Fixed unit test snapshots.
- Ran all unit tests successfully
[Ticket: WEB -Reviewing an IP comment then reviewing the second shows you the content of the first comment (A2-2517)](https://pins-ds.atlassian.net/browse/A2-2517)
[A2-1921]: https://pins-ds.atlassian.net/browse/A2-1921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(appeals): make sure the correct ip comment is reviewed (a2-2517)

---

appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
appeals/api/src/server/endpoints/appeals/appeals.formatter.js

- Add case for appeal status EVENT within the appeals formatter
- Set the correct due date as required in the ACs
- Added unit tests for above
- Tested manually within the browser
[Ticket: A2-2525](https://pins-ds.atlassian.net/browse/A2-2525)

feat(appeals): add a set up site visit due date in the personal list (a2-2525)

---

appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/view-and-review/page-components/__tests__/__snapshots__/common.test.js.snap
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/view-and-review/page-components/__tests__/common.test.js
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/view-and-review/page-components/common.js

- Updated generateCommentSummaryList function so that it is less likely to crash
- Added unit tests for above
- Snapshots added/updated
[Ticket: Broken IP-comments review when address is missing (A2-2534)](https://pins-ds.atlassian.net.mcas.ms/browse/A2-2534)

fix(appeals): broken ip comments review when address is missing (a2-2534)

---

appeals/web/src/server/lib/mappers/__tests__/mappers.test.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/lpa-statement.mapper.js
appeals/web/src/server/lib/representation-utilities.js

Refactored mapLpaStatement to use the generic method for consistency. Updated mapRepresentationDocumentSummaryActionLink to correctly handle lpa-statement links.
[A2-2451](https://pins-ds.atlassian.net/browse/A2-2451)
[A2-2451]: https://pins-ds.atlassian.net/browse/A2-2451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(web): A2-2451 Documentation Row - LPA Statement View CTA

---

appeals/web/src/server/appeals/appeal-details/environmental-assessment/__tests__/__snapshots__/environmental-assessment.test.js.snap
appeals/web/src/server/appeals/appeal-details/environmental-assessment/__tests__/environmental-assessment.test.js
appeals/web/src/server/lib/mappers/components/page-components/__tests__/notification-banners.mapper.test.js
appeals/web/src/server/lib/mappers/components/page-components/notification-banners.mapper.js

- Add the 'appealDetails' page to the list of pages the 'documentAdded' banner can display on
- Amended unit tests for above
- Added a unit test to test the success banner appears when it should
- Snapshots added/updated
[Ticket: Doc upload success banner showing in the wrong page of the service (A2-2537)](https://pins-ds.atlassian.net.mcas.ms/browse/A2-2537)

fix(appeals): upload success banner showing in the wrong page of the service (a2-2537)

---

appeals/web/src/server/appeals/appeal-details/representations/__tests__/__snapshots__/representations.test.js.snap
appeals/web/src/server/appeals/appeal-details/representations/__tests__/representations.test.js
appeals/web/src/server/appeals/appeal-details/representations/final-comments/view-and-review/view-and-review.controller.js
appeals/web/src/server/appeals/appeal-details/representations/final-comments/view-and-review/view-and-review.mapper.js
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/interested-party-comments.controller.js
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/interested-party-comments.mapper.js
appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/lpa-statement.controller.js
appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/lpa-statement.mapper.js
appeals/web/src/server/appeals/appeal-details/representations/representations.mapper.js
appeals/web/src/server/lib/mappers/__tests__/mappers.test.js
appeals/web/src/server/lib/mappers/utils/url.mapper.js

https://pins-ds.atlassian.net/browse/A2-2401
This update introduces dynamic back button behavior and flexible redirect URL handling:
- Reads the `backUrl` query parameter and processes it using the `constructURL` utility
- Since most of the routes are sub-routes of appeal details page - instead of passing the full URL every time, only the path **after** `/<appealId>/` needs to be provided.  
- **Example:** `?backUrl=/share` generates `/appeals-service/appeal-details/${appealId}/share`.  
- Routes that don’t follow this pattern, such as **Personal List**, are handled via a predefined mapping
- **Example:** `?backUrl=/personal-list` resolves to `/appeals-service/personal-list`.  
- The same logic can be applied to **redirect URLs** after an action.  
- **Example:** Passing …

Dynamic Back Button and Redirect URL Functionality

---

appeals/web/src/client/components/show-more/show-more.js

- Returning early from initialising instance statement so that read more link text doesn't show when less than 300 chars.  
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-2454)

fix(web): fixing read more text link to not show when there are less than 300 chars

---

appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/add-ip-comment/__tests__/add-ip-comment.test.js
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/add-ip-comment/add-ip-comment.controller.js

redactionStatusId correctly set when adding IP comment, approach is  consistent with the additional documents flow.  
[A2-2582](https://pins-ds.atlassian.net/browse/A2-2582)
[A2-2582]: https://pins-ds.atlassian.net/browse/A2-2582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(web): A2-2582 Add IP Comment - incorrect redaction status shows on document upload

---

appeals/api/src/server/endpoints/appeals.d.ts
appeals/api/src/server/endpoints/site-visits/__tests__/site-visits.test.js
appeals/api/src/server/endpoints/site-visits/site-visits.controller.js
appeals/api/src/server/endpoints/site-visits/site-visits.service.js
appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/site-visit.test.js
appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.controller.js
appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.mapper.js
appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.service.js
appeals/web/src/server/appeals/appeal-users/users-service.js

Please note that any variables added to notify are ignored if they are not used.  It is safe to add this prior to the template/s being updated  to include it.
- Add inspectorName to the UpdateSiteVisitData interface
- Add inspectorName to the CreateSiteVisitData interface
- Added unit tests for above
- Add inspector_name to the notify variables for arranging a site visit
- Amended unit tests for above
[Ticket: WEB/API - 500 seen when first scheduling site visit (A2-2578)](https://pins-ds.atlassian.net.mcas.ms/browse/A2-2578)

fix(appeals): add inspector name to site visit notify (a2-2578)

---

appeals/web/src/client/components/show-more/show-more.js

- Using inner html text rather than attribute since attribute is only set in initialiseTextMode method that runs after.
[Ticket]()

fix(A2-2454/web): Fixing Read more for redacted representations

---

appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/interested-party-comments.router.js
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/view-and-review/__tests__/__snapshots__/view-and-review.test.js.snap
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/view-and-review/__tests__/view-and-review.test.js
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/view-and-review/view-and-review.controller.js
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/view-and-review/view-and-review.router.js

- Use manage-document routes 
- Remove replaced redundant routes and controller functions
[Ticket: API/WEB - 'Page not found' error when clicking upload updated version for ip comments (A2-2595)](https://pins-ds.atlassian.net.mcas.ms/browse/A2-2595)

fix(appeals): use document attachments to manage document versions (a2-2595)

---

appeals/web/src/server/appeals/appeal-details/appeal-details.controller.js

When running the application, there is an issue where the links in the rows within the document section of the Case details page are corrupted with a double slash when the page itself has been loaded with a url containing and ending slash.  This certainly affects Linux when running the back office locally.  The links are broken.
This PR prevents the double slashes.

fix(appeals): fix double slash in url issue

---

docs/blob-emulator.md

Blob emulator doc update.
A clone of https://github.com/Planning-Inspectorate/appeals-back-office/pull/1057 (will be closed)

docs(appeals): updated storage container docs

---

appeals/api/package.json
appeals/api/src/database/migrations/20250314101043_remove_inquiry_how_many_witnesses_from_command/migration.sql
appeals/api/src/database/schema.prisma
appeals/api/src/server/mappers/integration/commands/appellant-case.mapper.js
appeals/api/src/server/mappers/integration/s78/map-appellant-case.js
package-lock.json
package.json

There was a bit of confusion on the fields `appellantProcedurePreferenceWitnessCount` and `inquiryHowManyWitnesses`.
Now the latter is removed and we are using `appellantProcedurePreferenceWitnessCount` to capture the data.

fix(api): using data model 1.9.19

---

appeals/api/src/server/repositories/appeal.repository.js

Adds the correct filter when loading appeals that have an AWAITING_EVENT elapsed.

fix(api): update complete events correct query

---

appeals/api/src/server/endpoints/representations/representations.controller.js
appeals/web/src/server/appeals/appeal-details/representations/final-comments/accept/__tests__/__snapshots__/accept-final-comments.test.js.snap
appeals/web/src/server/appeals/appeal-details/representations/final-comments/accept/accept.mapper.js
appeals/web/src/server/appeals/appeal-details/representations/final-comments/accept/components/summary-list.js

Fixed:
- Added missing return to stringTokenReplacement, allowing "details" data to equate correctly, fixing CreateAuditTrail call
- Added attachmentList into view mapper. providing necessary data to display supporting doc/s in final comments view
- Added supporting docs route for "change" button 
Ticket:
https://pins-ds.atlassian.net/browse/A2-86

fix(appeals): accept final comments change button and case history log fix

---

appeals/web/src/server/appeals/appeal-details/representations/document-attachments/manage-documents.controller.js
appeals/web/src/server/appeals/appeal-details/representations/final-comments/view-and-review/page-components/common.js
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/view-and-review/page-components/common.js
appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/lpa-statement.mapper.js

Please note, that there does seem to be some repetition when creating the attachments list for each of the different types of representation, but as other tickets are currently being worked on in this area, I thought it best not to create a common function in this PR.
- Call postUploadDocumentVersionCheckAndConfirm instead of postUploadDocumentsCheckAndConfirm to upload versions
- Patch the representation attachment to include the new document version
- Remove duplicate filenames in each attachment list by filtering on latest document version
[Ticket: API/WEB - Cannot upload updated version of supporting document (A2-2594)](https://pins-ds.atlassian.net.mcas.ms/browse/A2-2594)

fix(appeals): cannot upload updated version of supporting document (a2-2594)

---

appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.mapper.js
appeals/web/src/server/appeals/appeal-details/environmental-assessment/__tests__/__snapshots__/environmental-assessment.test.js.snap
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js
appeals/web/src/server/appeals/appeal-details/withdrawal/withdrawal.mapper.js
appeals/web/src/server/lib/mappers/components/page-components/__tests__/notification-banners.mapper.test.js
appeals/web/src/server/lib/mappers/components/page-components/notification-banners.mapper.js
appeals/web/src/server/lib/nunjucks-template-builders/gds-components-properties-jsdoc.js

Adds a new function `sortNotificationBanners` to ensure success and important notification banners are always sorted in the correct order relative to one-another.
https://pins-ds.atlassian.net/browse/A2-2419

fix(web): fix ordering of success and important notification banners

---

azure-pipelines-e2e-appeals.yml

`e2e` pipeline failing after node 22 update
`Unable to locate executable file: 'npm'`
Added NodeTool task with v22 hint
[Ticket](https://dev.azure.com/planninginspectorate/appeals-back-office/_build/results?buildId=108229&view=logs&j=f52bf699-3ddc-5068-598c-8f87b671093d&t=c33f332c-202a-58bd-65a0-17bfc6e3b077&l=9)

chore(appeals): add node to  e2e pipeline

---

appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/allocation/allocation.mapper.js
appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/lpa-statement.controller.js
appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/redact/redact.controller.js
appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/redact/redact.mapper.js
appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/valid/valid.controller.js
appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/valid/valid.mapper.js

Forces the user into the allocation flow when accepting or redacting an LPA statement if no allocation level or specialisms have been set
[Ticket](https://pins-ds.atlassian.net/browse/A2-2467)

fix(web): force allocation selection

---

appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/__tests__/__snapshots__/interested-party-comments.test.js.snap
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/view-and-review/__tests__/__snapshots__/view-and-review.test.js.snap
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/view-and-review/page-components/common.js
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/view-and-review/page-components/review.mapper.js
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/view-and-review/page-components/view.mapper.js
appeals/web/src/server/views/appeals/appeal/interested-party-comments.njk

- Removed withdraw link from view page
- Removed withdraw link from review page
- Removed withdraw link from .njk file rendering IP comments overview page
https://pins-ds.atlassian.net/browse/A2-2597

fix(web): remove withdraw link from ip comment flows (a2-2597)

---

appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.controller.js
appeals/web/src/server/appeals/appeal-details/costs/costs.controller.js
appeals/web/src/server/appeals/appeal-details/internal-correspondence/internal-correspondence.controller.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.controller.js
appeals/web/src/server/lib/constants.js
appeals/web/src/server/lib/mappers/utils/__tests__/documents-and-folders.test.js
appeals/web/src/server/lib/mappers/utils/documents-and-folders.js

Global update to display appropriate folder name in "document added" success banners content. Includes addition of a new web-only constant `DOCUMENT_FOLDER_DISPLAY_LABELS` which may come in handy for future refactoring of document/folder related content (eg. in document upload flows, manage folder and document pages).
https://pins-ds.atlassian.net/browse/A2-1754

fix(web): global content updates to document upload success banners

---

appeals/api/src/server/endpoints/appeals/appeals.formatter.js

Upating the date logic for the personal page to display the earliest due date out of lpaStatementDueDate and IPCommentDueDate when both are available. 
https://pins-ds.atlassian.net/browse/A2-2608

fix(web): updating date logic to display earliest date on personal list

---

appeals/api/src/server/endpoints/representations/representations.routes.js
appeals/api/src/server/openapi.json

Edited the Swagger definition for the endpoint, correcting the parameter to type, also updated the openapi.json file.
[A2-2689](https://pins-ds.atlassian.net/browse/A2-2689)
[A2-2689]: https://pins-ds.atlassian.net/browse/A2-2689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(api): A2-2689 Incorrect Swagger parameter name for type in GET /appeals/{appealId}/reps endpoint

---

appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/__tests__/__snapshots__/lpa-statement.test.js.snap
appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/__tests__/lpa-statement.test.js
appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/lpa-statement.controller.js
appeals/web/testing/app/fixtures/referencedata.js

Small code fix to address a crash when submitting the lpa statement review page with "Accept" outcome. Also adds some unit tests to cover this scenario (but more are needed for the lpa statement flow as a whole, tech debt ticket to be created)
https://pins-ds.atlassian.net/browse/A2-2681

fix(web): fix crash on submitting lpa statement review page

---

appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/redact/redact.controller.js
appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/redact/redact.mapper.js

- Clear the session.redactLPAStatement if redacting a different LPA Statement comment
[Ticket: WEB/API E2E- Redacted comment pre-populated with another appeal comment for all reps  (A2-2555)](https://pins-ds.atlassian.net.mcas.ms/browse/A2-2594)

fix(appeals): redacted comment pre-populated with another appeal comment for all reps (a2-2555)

---

appeals/api/src/server/mappers/integration/__tests__/mappers.test.js
appeals/api/src/server/mappers/integration/shared/map-case-dates.js
appeals/api/src/server/utils/case-invalid.js

When an appeal is INVALID, it returns the correct `caseValidationDate` and applies the correct logic based on the state transition history.

fix(api): caseValidationDate set on invalid appeals

---

appeals/api/src/server/endpoints/representations/notify/services/index.js

Minor tweak to send reject email to appellant email address .
[A2-2615](https://pins-ds.atlassian.net/browse/A2-2615)
[A2-2615]: https://pins-ds.atlassian.net/browse/A2-2615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(api): A2-2615 Wrong Email sent when ip comment is rejected#1097

---

appeals/api/src/database/seed/seed-clear-test-data.js

Fixes an issue deleting test data using the `npm run db:seed:clear-test-data` command, due to missing reference tables.
Changed the folder clear up to a SQL command as Prisma cannot parse the number of parameters, in some cases.

fix(appeals): clear test data pipeline fixes

---

appeals/api/src/server/endpoints/site-visits/__tests__/site-visits.test.js
appeals/api/src/server/endpoints/site-visits/site-visits.service.js
appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.controller.js
appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.mapper.js

Reinstated previousVisitType handling, also fixed missing emails when both time/date and visit type were changed.
[A2-2710](https://pins-ds.atlassian.net/browse/A2-2710)
[A2-2709](https://pins-ds.atlassian.net/browse/A2-2709)
[A2-2710]: https://pins-ds.atlassian.net/browse/A2-2710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[A2-2709]: https://pins-ds.atlassian.net/browse/A2-2709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(api): A2-2710 appellant & LPA not receiving email on site visit type change

---

appeals/web/src/server/appeals/appeal-details/representations/document-attachments/add-document.mapper.js
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/add-ip-comment/__tests__/__snapshots__/add-ip-comment.test.js.snap
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/add-ip-comment/__tests__/add-ip-comment.test.js
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/add-ip-comment/add-ip-comment.mapper.js

When adding a supporting document to a statement, ip comment or final comment. The submitted date input boxes are blank. This release sets them to todays date.
[Ticket](https://pins-ds.atlassian.net/browse/A2-2635)

fix(web): set supporting document date to today

---

appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
appeals/web/src/server/appeals/appeal-details/accordions/has.js
appeals/web/src/server/appeals/appeal-details/accordions/s78.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/__tests__/final-comments-due-date.mapper.test.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/__tests__/ip-comments-due-date.mapper.test.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/__tests__/lpa-questionnaire-due-date.mapper.test.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/__tests__/lpa-statement-due-date.mapper.test.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/__tests__/s106-obligation-due-date.mapper.test.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/__tests__/site-visit-date.mapper.test.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/__tests__/started-at.mapper.test.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/__tests__/valid-at.mapper.test.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/final-comment-due-date.mapper.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/ip-comments-due-date.mapper.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/lpa-questionnaire-due-date.mapper.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/lpa-statement-due-date.mapper.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/s106-obligation-due-date.mapper.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/site-visit-date.mapper.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/started-at.mapper.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/valid-at.mapper.js

- Timetable rows are filtered out via the sub-mappers returning the display parameter as an empty object when they should not be shown.  Also satisfies typescript.
- Added a class to the timetable summary list to allow for snapshots of the whole timetable in unit tests
- Unit tests to test for each AC
- Unit tests and snapshots updated to match
[Ticket:  Case timetable showing rows and action links pre case start (A2-2673)](https://pins-ds.atlassian.net.mcas.ms/browse/A2-2673)

feat(appeals): case timetable showing rows and action links pre case start (a2-2673)

---

appeals/web/src/server/appeals/appeal-details/representations/common/document-attachment-list.js
appeals/web/testing/app/fixtures/referencedata.js

Stop showing deleted documents on the check your answers page after accepting/rejecting final comments.
They were being filtered on the review final comments page but not the check details page.
[A2-2685](https://pins-ds.atlassian.net.mcas.ms/browse/A2-2685?McasTsid=20596&McasCtx=4)
[A2-2685]: https://pins-ds.atlassian.net/browse/A2-2685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(web): hide deleted docs on final comments check your answers page

---

appeals/web/src/common/feature-flags.js
appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.mapper.js
appeals/web/src/server/appeals/appeal-details/start-case/__tests__/start-case.test.js
appeals/web/src/server/appeals/appeal-details/start-case/start-case.controller.js
appeals/web/src/server/appeals/appeal-details/start-case/start-case.mapper.js
appeals/web/src/server/appeals/appeal-details/start-case/start-case.router.js
appeals/web/src/server/appeals/personal-list/__tests__/__snapshots__/personal-list.test.js.snap
appeals/web/src/server/appeals/personal-list/__tests__/personal-list.test.js
appeals/web/src/server/appeals/personal-list/personal-list.controller.js
appeals/web/src/server/appeals/personal-list/personal-list.mapper.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/__tests__/started-at.mapper.test.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/started-at.mapper.js
appeals/web/src/server/lib/mappers/utils/__tests__/map-status-dependent-notifications.test.js
appeals/web/src/server/lib/mappers/utils/map-status-dependent-notifications.js

Adds a new page to start case flow (s78 select procedure type) and entry points, including new functionality to pass the back link URL using a query string (based on existing approach used elsewhere in the codebase), plus some unit tests.
https://pins-ds.atlassian.net/browse/A2-2636

feat(web): add s78 start case select procedure type page and entry points

---

infrastructure/pipelines/terraform-ci-commit.yaml

We did upgrade recently from node 20 to node 22. This pipeline was missed.

chore(appeals): missed node 22 upgrade on terraform-ci-commit pipeline

---

infrastructure/app-api.tf
infrastructure/environments/dev.tfvars
infrastructure/environments/prod.tfvars
infrastructure/environments/test.tfvars
infrastructure/environments/training.tfvars

Emergency fix to add missing generic template id to all environments
- Added generic template id
[Ticket:  Create generic functionality to read in a specific mark down required and send to generic template id (A2-2732)](https://pins-ds.atlassian.net.mcas.ms/browse/A2-2732)

fix(appeals): missing generic notify template id (a2-2732)

---

appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js

Remove the "Plans, drawings and list of plans" row when reviewing the LPAQ for S78 appeals. It should still be displayed for Householder appeals.
[A2-2679](https://pins-ds.atlassian.net.mcas.ms/browse/A2-2679?McasTsid=20596&McasCtx=4)
[A2-2679]: https://pins-ds.atlassian.net/browse/A2-2679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(web): remove plans & drawings row from S78 LPAQ

---

appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-valid/outcome-valid.mapper.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/affected-listed-buildings/affected-listed-buildings.mapper.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/changed-listed-buildings/changed-listed-buildings.mapper.js
appeals/web/src/server/appeals/appeal-details/neighbouring-sites/__tests__/__snapshots__/neighbouring-sites.test.js.snap
appeals/web/src/server/appeals/appeal-details/neighbouring-sites/neighbouring-sites.mapper.js
appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/__tests__/__snapshots__/lpa-statement.test.js.snap
appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/allocation/allocation.mapper.js
appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/lpa-statement.mapper.js
appeals/web/src/server/appeals/appeal-details/service-user/__tests__/__snapshots__/service-user.test.js.snap
appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap
appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.mapper.js
appeals/web/src/server/appeals/appeal-details/withdrawal/__tests__/__snapshots__/withdrawal.test.js.snap
appeals/web/src/server/appeals/appeal-details/withdrawal/withdrawal.mapper.js
appeals/web/src/server/lib/mappers/types.js
appeals/web/src/server/views/app/includes/change-page-content.pattern.njk
appeals/web/src/server/views/patterns/display-page.pattern.njk

Updated change page pattern template to add support for rendering page components outside the form tag where desired. Associated updates to existing clients of the change page pattern to render components that are not valid children of the form element outside the form tag where possible. The ideal fix would be to create a separate `PageContent` type for change pages, and refactor all existing code to use that, but given the increasing likelihood the page component system will be removed entirely in the foreseeable future, I didn't want to spend more time than seemed reasonably necessary on this.
https://pins-ds.atlassian.net/browse/A2-2682

fix(web): updates to change page pattern to only render valid elements inside form tag

---

appeals/api/src/server/notify/__tests__/emulate-notify.test.js
appeals/api/src/server/notify/__tests__/notify-send.test.js
appeals/api/src/server/notify/emulate-notify.js
appeals/api/src/server/notify/notify-send.js

- Replace ':' in notify emulator temp filename with '_' to allow for windows when testing locally
- Add an additional line break to make sure there is a gap between the inset appeal details and the rest of the email when emulating notify while developing.
- Make sure templates contain valid formatted variable names where the variable names must:
- Be within double brackets (( ... ))
- Start with a lowercase letter
- Only contain lowercase letters, digits, underscores
- Underscore is allowed, but not at the start or end and no double underscores
- Add unit tests for above
- Checked that the notify emulator generated the email
[Ticket:  Make sure notify templates contain valid formatted variable names …

fix(appeals): allow notify emulator to write to linux, mac, and windows

---

appeals/api/src/server/endpoints/appeal-details/appeal-details.service.js
appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
appeals/web/src/server/appeals/appeal-details/appellant-case/page-components/has.mapper.js
appeals/web/src/server/appeals/appeal-details/appellant-case/page-components/s78.mapper.js
appeals/web/src/server/appeals/appeal-details/lpa-reference/__tests__/__snapshots__/change-lpa-reference.test.js.snap
appeals/web/src/server/appeals/appeal-details/lpa-reference/__tests__/change-lpa-reference.test.js
appeals/web/src/server/appeals/appeal-details/lpa-reference/lpa-reference.controller.js
appeals/web/src/server/appeals/appeal-details/lpa-reference/lpa-reference.mapper.js
appeals/web/src/server/appeals/appeal-details/lpa-reference/lpa-reference.middleware.js
appeals/web/src/server/appeals/appeal-details/lpa-reference/lpa-reference.router.js
appeals/web/src/server/appeals/appeal-details/lpa-reference/lpa-reference.validators.js
appeals/web/src/server/lib/error-handlers/change-screen-error-handlers.js
appeals/web/src/server/lib/mappers/data/appellant-case/submappers/application-reference.js
packages/appeals/constants/support.js

The page already existed so I reinstated the link and added some validation.
It now looks in support.js to see if there is a more specific message for the audit trail - this may also affect the audit trail message for other property updates.
The page to change LPA reference number already existed, so I reinstated the change link, added some validation, and changed the wording as per the ticket.
The reference can only be changed up to the point where the LPAQ has been sent to the LPA, so it checks that an LPAQ does not yet exist and that the appeal status is not `LPA_QUESTIONNAIRE`.
It now looks in support.js to see if there is a more specific message for the audit trail - this may also affect the audit trail message for other property updates if they already have a custom audit message …

feat(appeals): change LPA reference number

---

appeals/web/src/client/components/show-more/show-more.js
appeals/web/src/styles/7-components/show-more.scss

Fixing issue where show-more component was not initialised when it was needed. 
- Updated logic so that if rowSelector is null (i.e. contentRowSelector has not been specified) which means we have not said what should be used to define individual rows, we now check the number of characters as we do for text mode
- Updated the css for the show-more component so that highlight applies even when the component is not fully initialised
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-2979)

A2-2979(fix): updating show more logic to highlight text

---

appeals/api/src/server/repositories/common.repository.js

Upgrading to a newer version of Prisma brought this bug. Fixed by avoiding executing a DB call when there is no need.

fix(api): code failing after prisma update

---

appeals/web/src/server/appeals/appeal-details/appeal-details.router.js
appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.router.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.router.js
appeals/web/src/server/appeals/appeal-details/representations/final-comments/final-comments.router.js
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/interested-party-comments.router.js
appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/lpa-statement.router.js
appeals/web/src/server/appeals/appeal-documents/appeal-documents.middleware.js

- Added common middleware to remove uncommitted files from session
- Applying middleware function to top-level pages GETs to ensure session is clear of uncommitted files
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-2078)

A2-2078(fix): Uncommitted files persisting when moving out of flow

---

appeals/web/src/client/components/file-uploader/_client-actions.js
appeals/web/src/client/components/file-uploader/_errors.js
appeals/web/src/client/components/file-uploader/_html.js
appeals/web/src/server/appeals/appeal-details/costs/__tests__/__snapshots__/costs.test.js.snap
appeals/web/src/server/appeals/appeal-details/costs/__tests__/costs.test.js
appeals/web/src/server/appeals/appeal-details/internal-correspondence/__tests__/__snapshots__/internal-correspondence.test.js.snap
appeals/web/src/server/appeals/appeal-details/internal-correspondence/__tests__/internal-correspondence.test.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
appeals/web/src/server/appeals/appeal-details/representations/final-comments/view-and-review/__tests__/__snapshots__/view-and-review.test.js.snap
appeals/web/src/server/appeals/appeal-details/representations/final-comments/view-and-review/__tests__/view-and-review.test.js
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/view-and-review/__tests__/__snapshots__/view-and-review.test.js.snap
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/view-and-review/__tests__/view-and-review.test.js
appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/__tests__/__snapshots__/lpa-statement.test.js.snap
appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/__tests__/lpa-statement.test.js
appeals/web/src/server/appeals/appeal-documents/__tests__/appeal-documents.test.js
appeals/web/src/server/appeals/appeal-documents/appeal-documents.controller.js
appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js
appeals/web/src/server/appeals/appeal-documents/appeal-documents.types.d.ts
appeals/web/src/server/appeals/appeal-documents/appeal-documents.validators.js

- The file extension is now hidden when changing the filename of a document
- New versions of a document must have the same file extension as the original document
[A2-2926](https://pins-ds.atlassian.net.mcas.ms/browse/A2-2926?McasTsid=20596&McasCtx=4)
[A2-2926]: https://pins-ds.atlassian.net/browse/A2-2926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(web): hide extension when changing filenames

---

appeals/api/src/server/endpoints/lpa-questionnaires/__tests__/lpa-questionnaires.test.js
appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.service.js
appeals/api/src/server/tests/appeals/mocks.js

Adds a check for appeal status when validating a LPAQ. If incorrect status, throw an error and log it.
[Ticket](https://pins-ds.atlassian.net/browse/A2-3091)

fix(api): throws an error if trying to validate a LPAQ in the incorrect state

---

appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.controller.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.controller.js
appeals/web/src/server/appeals/national-list/national-list.controller.js
appeals/web/src/server/appeals/personal-list/personal-list.controller.js
appeals/web/src/server/lib/__tests__/libraries.test.js
appeals/web/src/server/lib/url-utilities.js

Adds a new url utility `stripQueryString` (including tests), and uses it to remove any query from `request.originalUrl` before it's passed to the `appellantCasePage` and `lpaQuestionnairePage` mappers, to fix the change links on those pages.
https://pins-ds.atlassian.net/browse/A2-3090

fix(web): strip query string from request.originalUrl to resolve broken change links

---

appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/interested-party-comments.router.js
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/view-and-review/view-and-review.controller.js
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/view-and-review/view-and-review.router.js

- Removed unnecessary routes and controller functions as deletion is done with the shared manage document routes
- Added a redirect route so that the return from a successful deletion in the shared code returns to the correct page 
[Ticket:  S78w - Web - Page not found when removing document from Accepted IP comment (A2-2302)](https://pins-ds.atlassian.net.mcas.ms/browse/A2-2302)

fix(appeals): page not found when removing a document from accepted ip comment (a2-2302)

---

appeals/web/src/server/lib/mappers/components/page-components/notification-banners.mapper.js

Further to the previous [PR](<https://github.com.mcas.ms/Planning-Inspectorate/appeals-back-office/pull/1238>), this PR makes sure the Document removed banner displays on the correct page
[Ticket](<[!--Paste your ticket link here--](https://pins-ds.atlassian.net/browse/A2-3057)>)

fix(appeals): document removed banner should be on view ip comment page (a2-3057)

---

appeals/api/src/server/endpoints/lpa-questionnaires/__tests__/lpa-questionnaires.test.js

Fix the broken easter test by setting the lpaQuestionnaireDueDate to '2025-08-23T00:00:00.000Z' within the test as this is also Good Friday, but 100 years in the future.  Shouldn't be an issue for the next 100 years.

fix(appeals): broken easter test for LPA Questionnaire due date

---

appeals/api/src/server/endpoints/representations/__tests__/representations.test.js
appeals/api/src/server/endpoints/representations/notify/services/index.js
appeals/api/src/server/endpoints/representations/notify/services/utils.js

The new logic for the date given to the IP for submission of another comment is either todays date +7 days or the existing date from the timetable, whichever is later.
- Updated calculation of extended deadline as described above and within the comments of the ticket.
- Added a test to test the email containing the extended deadline date
- Tested emails with emulator
[Comment rejected (interested parties) (A2-2767)](https://pins-ds.atlassian.net/browse/A2-2767)

fix(appeals): ip comment rejected extended deadline in notify (a2-2767)

---

appeals/api/src/server/endpoints/appeal-decision/appeal-decision.service.js
appeals/api/src/server/notify/templates/__tests__/notify-decision-is-allowed-split-dismissed-appellant.test.js
appeals/api/src/server/notify/templates/__tests__/notify-decision-is-allowed-split-dismissed-lpa.test.js
appeals/api/src/server/notify/templates/decision-is-allowed-split-dismissed-appellant.content.md
appeals/api/src/server/notify/templates/decision-is-allowed-split-dismissed-lpa.content.md

Fixed incorrect appellant email in notify payload, updated tests to use named mock emails for clarity and corrected markdown URL syntax in templates. 
[A2-2559](https://pins-ds.atlassian.net/browse/A2-2559)
[A2-2559]: https://pins-ds.atlassian.net/browse/A2-2559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(api):A2-2559 link LPA decision notify email directly to appeal pages

---

appeals/web/src/server/appeals/appeal-details/representations/__tests__/__snapshots__/representations.test.js.snap
appeals/web/src/server/appeals/appeal-details/representations/__tests__/representations.test.js
appeals/web/src/server/appeals/appeal-details/representations/representations.controller.js
appeals/web/src/server/appeals/appeal-details/representations/representations.mapper.js
appeals/web/src/server/lib/__tests__/libraries.test.js
appeals/web/src/server/lib/url-utilities.js

- replace old hardcoded back link query in links to ip comments and statements page from share page with new standardised equivalent using `addBackLinkQueryToUrl` helper function
- update `addBackLinkQueryToUrl` helper to work correctly in situations where the supplied URL has a hash, by moving it after the query that is added to the URL (everything after the hash is ignored by the server)
https://pins-ds.atlassian.net/browse/A2-2369

fix(web): fix back link from ip comments and statements to share page

---

appeals/web/src/server/appeals/appeal-details/representations/representations.controller.js
appeals/web/src/server/appeals/appeal-details/representations/representations.mapper.js

replaces old hardcoded back link query in links to final comments pages from share page with new standardised equivalent using addBackLinkQueryToUrl helper function
https://pins-ds.atlassian.net/browse/A2-3054

fix(web): fix back link from final comments to share page

---

infrastructure/front-door-web.tf

Removing diagnostic setting terraform configurations 
Configuration is added in Frontdoor as logs were duplicated in all the instance
Non-prod front door diagnostic setting: pins-fd-mds-common-tooling
Prod: [PR](https://github.com/Planning-Inspectorate/infrastructure-environments/pull/959)  to create the instance 
[Ticket](https://pins-ds.atlassian.net/browse/DEV-320)
[Terraform Plan- Dev, Test, training and prod](https://dev.azure.com/planninginspectorate/appeals-back-office/_build/results?buildId=112791&view=logs&j=912cd5a8-ca36-5904-6537-633e2db44bcf&t=3b9b33d7-43b5-59b1-29a3-5cf0cadb8bc7)

fix(infrastructure): removing diagnostic settings

---

appeals/api/src/server.js
appeals/api/src/server/notify/emulate-notify.js
appeals/api/src/server/notify/index.js

It makes more sense to delete the previous local notify emails stored in the temp folder when starting the api than when the first notify email is created.

chore(appeals): clear local emails on start

---

appeals/api/src/server/endpoints/lpa-questionnaires/__tests__/lpa-questionnaires.test.js
appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.validators.js
packages/appeals/constants/support.js

- Small fix to increase the char limit on the API side for extra condition details 
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-1909)

fix(api): updating api validator to accept max 8000 chars for extra conditions details

---

appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/allocation/allocation.mapper.js
appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/redact/__tests__/lpa-statement-redact.test.js
appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/redact/redact.controller.js
appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/valid/__tests__/__snapshots__/lpa-statement-valid.test.js.snap
appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/valid/__tests__/lpa-statement-valid.test.js
appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/valid/valid.controller.js

Updated allocation specialisms mapper to render the correct back link depending on whether the user is in the accept (valid) or redact and accept version of the review LPA statement flow
https://pins-ds.atlassian.net/browse/A2-3052

fix(web): fix back link from allocation specialisms page in review lpa statement flow

---

appeals/api/src/server/endpoints/appeal-timetables/__tests__/appeal-timetables.test.js
appeals/api/src/server/endpoints/appeal-timetables/appeal-timetables.service.js
appeals/api/src/server/endpoints/site-visits/__tests__/site-visits.test.js

LPAQ start email now sent to LPA not appellant; updated tests with clearer mock addresses for clarity. 
[A2-3114](https://pins-ds.atlassian.net/browse/A2-3114)
[A2-3114]: https://pins-ds.atlassian.net/browse/A2-3114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(api): A2-3114 lpaq start email incorrectly sent to appellant instead of lpa

---

appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
appeals/web/src/server/lib/mappers/data/appeal/submappers/hearing-add-hearing-estimates.js

The hearing estimates heading was duplicated on the appeal details page when there were no hearing estimates.
[A2-2825](https://pins-ds.atlassian.net/browse/A2-2825)
[A2-2825]: https://pins-ds.atlassian.net/browse/A2-2825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(web): remove duplicate hearing estimates heading

---

appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
appeals/web/src/server/appeals/appeal-details/hearing/estimates/__tests__/__snapshots__/estimates.test.js.snap
appeals/web/src/server/appeals/appeal-details/hearing/estimates/estimates.mapper.js
appeals/web/src/server/lib/dates.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/hearing-hearing-estimates.js

On both they check your answers page and the appeal details page, the hearing estimates summary list should format the days with either one decimal place or none (i.e. 2 or 2.5), and the suffix should be 'day' instead of 'days' if it is exactly one day.
[A2-2825](https://pins-ds.atlassian.net.mcas.ms/browse/A2-2825?McasTsid=20596&McasCtx=4)
[A2-2825]: https://pins-ds.atlassian.net/browse/A2-2825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(web): format days correctly for hearing estimates

---

appeals/api/src/database/seed/seed-clear.js

Fixes the seed routine by clearing data in the new tables Hearing and HearingEstimate.

fix(api): deletes hearing and hearing estimate data when seeding

---

appeals/web/src/server/appeals/appeal-details/hearing/setup/__tests__/__snapshots__/set-up-hearing.test.js.snap
appeals/web/src/server/appeals/appeal-details/hearing/setup/__tests__/set-up-hearing.test.js
appeals/web/src/server/appeals/appeal-details/hearing/setup/set-up-hearing.mapper.js
appeals/web/src/server/appeals/appeal-details/hearing/setup/set-up-hearing.router.js

- Update hearing date error messages
- Add default hearing time of 10:00
[A2-2711](https://pins-ds.atlassian.net.mcas.ms/browse/A2-2711?McasTsid=20596&McasCtx=4)
[A2-2711]: https://pins-ds.atlassian.net/browse/A2-2711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(web): improve hearing date/time error messages and add default time

---

appeals/api/src/server/notify/templates/__tests__/notify-decision-is-allowed-split-dismissed-appellant.test.js
appeals/api/src/server/notify/templates/__tests__/notify-decision-is-allowed-split-dismissed-lpa.test.js
appeals/api/src/server/notify/templates/decision-is-allowed-split-dismissed-appellant.content.md
appeals/api/src/server/notify/templates/decision-is-allowed-split-dismissed-lpa.content.md

Fixes a live issue (404) with the link to the LPA dashboard in a notification template. This branch is created out of our deployed production release

fix(api): hotfix on dashboard url

---

appeals/web/src/server/appeals/appeal-details/hearing/estimates/__tests__/estimates.test.js
appeals/web/src/server/appeals/appeal-details/hearing/estimates/estimates.controller.js
appeals/web/src/server/views/app/404.njk

Display a custom 404 page if the user clicks the browser back button and lands on the CYA page for hearing estimates but the session data has already been cleared
[A2-3039](https://pins-ds.atlassian.net.mcas.ms/browse/A2-3039?McasTsid=20596&McasCtx=4)
[A2-3039]: https://pins-ds.atlassian.net/browse/A2-3039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(web): show custom 404 page if the session data is not present

---

appeals/api/.env.example
appeals/api/src/server/endpoints/appeal-decision/__tests__/appeal-decision.test.js
appeals/api/src/server/endpoints/appeal-decision/appeal-decision.service.js
appeals/api/src/server/endpoints/appeal-timetables/__tests__/appeal-timetables.test.js
appeals/api/src/server/endpoints/appeal-timetables/appeal-timetables.service.js
appeals/api/src/server/endpoints/change-appeal-type/__tests__/change-appeal-type.test.js
appeals/api/src/server/endpoints/change-appeal-type/change-appeal-type.service.js
appeals/api/src/server/endpoints/representations/__tests__/representations.test.js
appeals/api/src/server/endpoints/representations/notify/services/index.js
appeals/api/src/server/notify/templates/__tests__/notify-decision-is-allowed-split-dismissed-appellant.test.js
appeals/api/src/server/notify/templates/__tests__/notify-decision-is-allowed-split-dismissed-lpa.test.js
appeals/api/src/server/notify/templates/decision-is-allowed-split-dismissed-appellant.content.md
appeals/api/src/server/notify/templates/decision-is-allowed-split-dismissed-lpa.content.md
infrastructure/app-api.tf
infrastructure/environments/dev.tfvars
infrastructure/environments/prod.tfvars
infrastructure/environments/test.tfvars
infrastructure/environments/training.tfvars
infrastructure/variables.tf
packages/appeals/constants/support.js

Added a new env variable to the Terraform config, updated the application settings to dynamically include the URL, and updated the email templates to use the dynamic link.
[A2-3216](https://pins-ds.atlassian.net/browse/A2-3216)
[A2-3216]: https://pins-ds.atlassian.net/browse/A2-3216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(api): A2-3216 make LPA dashboard link in email templates environment-specific

---

appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
appeals/web/src/server/appeals/appeal-details/appeal-details.router.js
appeals/web/src/server/appeals/appeal-details/appeal-timetables/__tests__/__snapshots__/appeal-timetables.test.js.snap
appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
appeals/web/src/server/appeals/appeal-details/timetable/__tests__/__snapshots__/timetable.test.js.snap
appeals/web/src/server/appeals/appeal-details/timetable/__tests__/timetable.test.js
appeals/web/src/server/appeals/appeal-details/timetable/timetable.controller.js
appeals/web/src/server/appeals/appeal-details/timetable/timetable.mapper.js
appeals/web/src/server/appeals/appeal-details/timetable/timetable.router.js
appeals/web/src/server/appeals/appeal-details/timetable/timetable.service.js
appeals/web/src/server/appeals/appeal-details/timetable/timetable.validators.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/__tests__/lpa-questionnaire-due-date.mapper.test.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/lpa-questionnaire-due-date.mapper.js
appeals/web/src/server/views/appeals/appeal/update-date.njk

- Updated lpa questionnaire due date navigation to go to new time table due dates page rather than existing page.
- Added mapper, controller and router for new timetable route
- Created the base for further work to be done to make timetable due dates page work for other appeal types and multiple timetable types (hence some commented code) 
[A2-3118](https://pins-ds.atlassian.net.mcas.ms/browse/A2-3118) & [A2-3117](https://pins-ds.atlassian.net.mcas.ms/browse/A2-3117) 
[A2-3118]: https://pins-ds.atlassian.net/browse/A2-3118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[A2-3117]: https://pins-ds.atlassian.net/browse/A2-3117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

A2-3117/3118(feat): adding new timetable updates page with navigation for HAS

---

appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/__snapshots__/issue-decision.test.js.snap
appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/issue-decision.test.js
appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.controller.js
appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.mapper.js
appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.router.js

- Amended the LPA costs decision page so that it redirects to the new LPA costs decision letter upload page when "Yes" has been selected
- Added /issue-decision/lpa-costs-decision-letter-upload page
- Updated pre headers to include a suffix of - issue decision
- Added a new row to the check your decision page for above
- Handle the back url correctly from change link
- Change button text from "Send decision" to "Issue decision"
[Issuing decision flow - Part 6 - 'LPA costs decision letter' upload screen (A2-3153)](https://pins-ds.atlassian.net/browse/A2-3153)

fix(appeals): issue lpa costs decision letter upload (a2-3153)

---

infrastructure/app-api.tf
infrastructure/environments/dev.tfvars
infrastructure/variables.tf

Moving the "front_office_url" variable to the correct place.

fix(api): adjusting FO env URLs for email templates dashboard links

---

appeals/web/src/client/components/redact-button/__tests__/index.test.js
appeals/web/src/client/components/redact-button/index.js
appeals/web/src/server/appeals/appeal-details/representations/common/components/redact-input.js
appeals/web/src/server/appeals/appeal-details/representations/final-comments/redact/__tests__/__snapshots__/redact-final-comments.test.js.snap
appeals/web/src/server/appeals/appeal-details/representations/final-comments/view-and-review/__tests__/__snapshots__/view-and-review.test.js.snap
appeals/web/src/server/appeals/appeal-details/representations/final-comments/view-and-review/page-components/common.js
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/redact/__tests__/__snapshots__/redact-ip-comment.test.js.snap
appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/redact/__tests__/__snapshots__/lpa-statement-redact.test.js.snap
appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/redact/redact.mapper.js

WEB:
Added functionality so that when the. undo button is clicked it will revert the redacted text to the previously saved version rather then the session redaction
Updated LPA statement so that when there is no redactions the redact link is shown next to the original statement
Updated final comments page so that the redact link  for the original comment is not shown if the original and redacted text is the same
TEST:
Updated snapshots
Updated redact tests to account for new functionality
[A2-2694](https://pins-ds.atlassian.net.mcas.ms/browse/A2-2694)
[A2-2694]: https://pins-ds.atlassian.net/browse/A2-2694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(web): fixing redaction logic

---

appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/__tests__/__snapshots__/lpa-statement.test.js.snap
appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/__tests__/lpa-statement.test.js
appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/lpa-statement.mapper.js

- updated `no-actions` summary list row modifier class to render conditionally on view LPA statement page to fix layout issue
- updated unit tests to guard against regression
https://pins-ds.atlassian.net/browse/A2-2676

fix(web): fix view redacted lpa statement page summary list layout

---

appeals/api/src/server/endpoints/withdrawal/__tests__/withdrawal.test.js
appeals/api/src/server/endpoints/withdrawal/withdrawal.service.js
appeals/api/src/server/notify/notify-send.js
appeals/api/src/server/notify/templates/__tests__/notify-appeal-withdrawn-appellant.test.js
appeals/api/src/server/notify/templates/__tests__/notify-appeal-withdrawn-lpa.test.js
appeals/api/src/server/notify/templates/appeal-withdrawn-lpa.content.md

- Amended the appeal withdrawn email template to include the event type of site visit if set 
- Created specific template tests
- Updated withdrawn unit test
- Tested with notify emulator
[Appeal withdrawn email for LPA is incorrect (A2-2739)](https://pins-ds.atlassian.net/browse/A2-2739)

fix(appeals): appeal withdrawn email for lpa incorrect (a2-2739)

---

appeals/web/src/server/appeals/appeal-details/start-case/__tests__/start-case.test.js
appeals/web/src/server/appeals/appeal-details/start-case/start-case.controller.js

- removed session check for pre-existing procedure selection from start case controller to fix a bug where the user would not be redirected to the select procedure type if they selected a procedure type before restarting the start case flow without submitting the confirmation page (this was introduced by a previous fix)
- added unit tests to guard against regression
https://pins-ds.atlassian.net/browse/A2-3113

fix(web): fix start case redirect when flow is restarted after written procedure is selected

---

appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
appeals/api/src/server/endpoints/appeals/appeals.controller.js
appeals/api/src/server/endpoints/appeals/appeals.service.js
appeals/api/src/server/repositories/appeal-lists.repository.js
appeals/web/src/server/appeals/national-list/__tests__/__snapshots__/national-list.test.js.snap
appeals/web/src/server/appeals/national-list/__tests__/national-list.test.js
appeals/web/src/server/appeals/national-list/national-list.mapper.js
appeals/web/src/server/appeals/personal-list/personal-list.mapper.js
appeals/web/src/server/lib/nunjucks-filters/index.js
appeals/web/src/server/lib/nunjucks-filters/status-tag.js
appeals/web/testing/app/fixtures/referencedata.js
packages/appeals/types/appeal.d.ts

- update appeals endpoint to return a list of all appeal statuses in national list
- update national list filter status dropdown to always contain an option for each appeal status present in national list
- rename `appealStatusToStatusTag` function to better reflect its purpose
https://pins-ds.atlassian.net/browse/A2-3289

fix(web): all cases filter status dropdown to always contain all statuses of appeals in national list

---

appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.mapper.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js
appeals/web/src/server/appeals/appeal-details/representations/common/components/reject-reasons.js
appeals/web/src/server/appeals/appeal-details/representations/final-comments/reject/reject.mapper.js
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/view-and-review/__tests__/__snapshots__/view-and-review.test.js.snap
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/view-and-review/page-components/reject.mapper.js
appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/incomplete/incomplete.controller.js
appeals/web/src/server/appeals/appeal.constants.js
appeals/web/src/server/lib/__tests__/libraries.test.js
appeals/web/src/server/lib/validators/checkbox-text-items.validator.js

- increase checkbox conditional text inputs character limit to 1000 (affects invalid/incomplete/rejected reasons text inputs on appellant case, LPA questionnaire, and representations)
- add 'show more' component to reasons display on relevant check your answers pages
- update unit tests
https://pins-ds.atlassian.net/browse/A2-3307

fix(web): increase checkbox conditional text inputs character limit to 1000

---

commitlint.config.cjs

Allowing dependabot commits for infra provider updates and npm deps, which can have long body lines
N/A

chore(tooling): allow all dependabot commits

---

appeals/api/src/server/notify/templates/__tests__/notify-decision-is-allowed-split-dismissed-lpa.test.js
appeals/api/src/server/notify/templates/__tests__/notify-decision-is-invalid-appellant.test.js
appeals/api/src/server/notify/templates/__tests__/notify-decision-is-invalid-lpa.test.js
appeals/api/src/server/notify/templates/decision-is-allowed-split-dismissed-lpa.content.md
appeals/api/src/server/notify/templates/decision-is-invalid-appellant.content.md
appeals/api/src/server/notify/templates/decision-is-invalid-lpa.content.md
appeals/web/src/server/app/components/file-uploader.component.js
appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/__snapshots__/issue-decision.test.js.snap
appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.controller.js
appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.mapper.js
appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.router.js
appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.validators.js
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/add-ip-comment/add-ip-comment.controller.js
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/add-ip-comment/add-ip-comment.mapper.js
appeals/web/src/server/lib/mappers/utils/file-upload-info-to-documents.js
appeals/web/src/server/views/appeals/appeal/issue-decision.njk

- Improve caching of decision upload file info by sharing with each existing decision property on the session 
- Add the ability to save each decision file to the DB via the API
- Add the new hint text at the bottom of the screen
- Make sure the decision is sent to the API and successfully sends the LPA and Appellant valid emails
- Updated the email address in the notify templates
- Moved mapFileUploadInfoToMappedDocuments from add-ip-comments.mapper to a reusable function so decisions can use it.
- Made sure emails are generated using the notify emulator
[Issuing decision flow - Part 7 - Check details …

fix(appeals): issue decision check details (a2-3162)

---

appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.controller.js
appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.middleware.js
appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.router.js

- Remove redundant "validateAppeal" middleware as it is already in the parent route.  see appeal-details.router.js
- Move clearing the session cache for the decision types when the appeal-id is different into middleware for every route
- Add some comments describing why the reuse of the appeal-documents upload page functions requires storing and restoring the uploadFileInfo object in the session for each decision type.
[Issuing decision flow - Part 7 - Check details (A2-3162)](https://pins-ds.atlassian.net/browse/A2-3162)

chore(appeals): issue decision clean-up routes (a2-3162)

---

appeals/web/src/client/components/file-uploader/_client-actions.js

Fixes a representation upload issue by removing duplicate file name validation for these type of documents.
[A2-3338](https://pins-ds.atlassian.net/browse/A2-3338)
[A2-3338]: https://pins-ds.atlassian.net/browse/A2-3338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(web): bypassing file name duplicate check on rep attachments upload

---

appeals/api/src/server/endpoints/appeals.routes.js
appeals/api/src/server/endpoints/decision/__tests__/decision.test.js
appeals/api/src/server/endpoints/decision/decision.controller.js
appeals/api/src/server/endpoints/decision/decision.routes.js
appeals/api/src/server/endpoints/decision/decision.service.js
appeals/api/src/server/endpoints/decision/decision.validator.js
appeals/api/src/server/openapi-types.ts
appeals/api/src/server/openapi.json
appeals/api/src/server/swagger.js
appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/__snapshots__/issue-decision.test.js.snap
appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/issue-decision.test.js
appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.controller.js
appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.service.js
appeals/web/src/server/appeals/appeal-details/status-tags/status-tags.mapper.js
appeals/web/src/server/lib/mappers/components/page-components/notification-banners.mapper.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/costs-appellant-decision.mapper.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/costs-lpa-decision.mapper.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/decision.mapper.js
packages/appeals/constants/support.js

- Create new decisions route to allow decisions to be sent as an array
- Validate the decisions data via array members
- Add audit trail for decision, appellant cost decision, and lpa cost decision
- Create constants for above
- Update the case details inset content for decisions to match the ticket
- Update the decision issued links to link to the uploaded files
- Checked the audit trail is updated correctly
- Made sure emails are generated using the notify emulator
[Issuing Decision - Part 8 - Issue decision (A2-3175)](https://pins-ds.atlassian.net/browse/A2-3175)

feat(appeals): issue decision display rows (a2-3175)

---

appeals/web/src/client/components/file-uploader/_client-actions.js
appeals/web/src/client/components/file-uploader/_html.js
appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.controller.js

File Upload - Error messages and success banners
verified that error messages and success banners function correctly when uploading documents
Added value for document names for error messages
[A2-3001](https://pins-ds.atlassian.net.mcas.ms/browse/A2-3001)
[A2-3001]: https://pins-ds.atlassian.net/browse/A2-3001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(web): File Upload - Error messages and success banners

---

appeals/api/src/server/endpoints/representations/__tests__/representations.test.js
appeals/api/src/server/endpoints/representations/representations.service.js

Sets the redaction status of attachments where a redaction status has not been previously set to 'No redaction required'.
Triggered when publishing statements/comments and final comments.
[A2-3358](https://pins-ds.atlassian.net/browse/A2-3358)
[A2-3358]: https://pins-ds.atlassian.net/browse/A2-3358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(api): sets redaction status for docs where unset A2-3358

---

appeals/web/src/server/appeals/appeal-details/hearing/setup/__tests__/__snapshots__/set-up-hearing.test.js.snap
appeals/web/src/server/appeals/appeal-details/hearing/setup/__tests__/set-up-hearing.test.js
appeals/web/src/server/appeals/appeal-details/hearing/setup/set-up-hearing.controller.js

Make sure that the yes/no radio is checked when going back to the yes/no page when setting up a hearing
[A2-3023](https://pins-ds.atlassian.net/browse/A2-3023)
[A2-3023]: https://pins-ds.atlassian.net/browse/A2-3023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(web): make sure that radio still checked when going back

---

appeals/api/setup-tests.js
appeals/api/src/database/migrations/20250527141249_remove_unique_from_hearing_address/migration.sql
appeals/api/src/database/schema.prisma
appeals/api/src/server/endpoints/appeals.d.ts
appeals/api/src/server/endpoints/hearings/__tests__/hearing.test.js
appeals/api/src/server/endpoints/hearings/hearing.controller.js
appeals/api/src/server/endpoints/hearings/hearing.routes.js
appeals/api/src/server/endpoints/hearings/hearing.service.js
appeals/api/src/server/endpoints/hearings/hearing.validator.js
appeals/api/src/server/openapi-types.ts
appeals/api/src/server/openapi.json
appeals/api/src/server/repositories/hearing.repository.js
appeals/api/src/server/swagger.js

- Had to make the address non-unique because it was not allowing more than one hearing to have null address
- Added endpoint for cancelling hearing
[A2-2927](https://pins-ds.atlassian.net/browse/A2-2927)
- This includes a DB migration, but it is backwards-compatible
[A2-2927]: https://pins-ds.atlassian.net/browse/A2-2927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(api): add endpoint for cancelling a hearing

---

packages/appeals/constants/documents.js

Adds a document folder display label constant for rep attachments. This fixes an issue where the associated case history logs for rep attachments were corrupted due to the missing constant causing changes in the log string format which aren't expected by the mapping code.
https://pins-ds.atlassian.net/browse/A2-3410

fix(api): add missing document folder display label for rep attachments

---

appeals/api/src/database/seed/data-static.js

Updates appealType where clause to use appealType.key to avoid Unique constraint failed on the constraint: dbo.AppealType when changing the appealType naming
[Ticket](https://pins-ds.atlassian.net/jira/software/c/projects/A2/boards/246?selectedIssue=A2-3013&sprints=2257)

fix(api): update appealType seed where clause to use key

---

appeals/api/src/server/repositories/integrations.repository.js

Fixes an incorrect null check when importing LPAQ with nearby references.
[Ticket](https://pins-ds.atlassian.net/browse/A2-3255)

fix(api): filters falsy nearby refs when importing lpaqs - A2-3255

---

appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/issue-decision.test.js
appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.controller.js
appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.mapper.js
appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.utils.js
appeals/web/src/server/appeals/appeal-details/status-tags/status-tags.mapper.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/appeal-decision.mapper.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/decision.mapper.js
appeals/web/src/server/lib/mappers/utils/map-status-dependent-notifications.js

Please note that this PR is only relevant to the Issue decision flow!
- Clear cache where data is no longer needed based on changes such as removing application and adding withdrawal files
- Retain the cache where data is still required so the user does not need to re-enter the data including selecting files
- Fix routing particularly the back button within the flow
- Only show and submit the data required by the decisions taken within the flow in the check your decisions page
- Moved reusable code to issue-decision.utils.js such as buildLogicData and mapDecisionOutcome
- Walk through with tester to make sure it's working as it should
- [(A2-3367) Issue Appellant Costs Decision](https://pins-ds.atlassian.net/browse/A2-3367)

feat(appeals): issue decision clear caching and improve routing logic (a2-3367)

---

appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/__tests__/__snapshots__/interested-party-comments.test.js.snap
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/__tests__/interested-party-comments.test.js
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/add-ip-comment/add-ip-comment.controller.js
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/add-ip-comment/add-ip-comment.mapper.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/ip-comments.mapper.js

- update 'Add' action link in case details page documentation summary IP comments row to link to first page of add IP comment journey
- update mapper for first page of add IP comment journey to render back link URL from query string if present
https://pins-ds.atlassian.net/browse/A2-3311

fix(web): update add action link in ip comments doc summary to link to correct page

---

appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/__snapshots__/issue-decision.test.js.snap
appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/issue-decision.test.js

Remove an unnecessary snapshot that keeps changing due to it containing the current date.

fix(appeals): remove unnecessary flakey snapshot due to changing current date

---

appeals/api/src/database/migrations/20250603091131_add_po_due_date_to_timetable/migration.sql
appeals/api/src/database/schema.prisma
appeals/api/src/server/endpoints/appeal-details/__tests__/appeals-details.test.js
appeals/api/src/server/endpoints/appeal-timetables/__tests__/appeal-timetables.test.js
appeals/api/src/server/endpoints/appeal-timetables/appeal-timetables.controller.js
appeals/api/src/server/endpoints/appeal-timetables/appeal-timetables.validators.js
appeals/api/src/server/endpoints/appeals.d.ts
appeals/api/src/server/mappers/api/definitions/timetable.js
appeals/api/src/server/mappers/api/shared/map-appeal-timetable.js
appeals/api/src/server/openapi-types.ts
appeals/api/src/server/openapi.json
appeals/api/src/server/swagger.js
appeals/api/src/server/tests/appeals/s78.js

- Add planningObligationDueDate to appeal timetable
- Add statementOfCommonGroundDueDate and planningObligationDueDate to OpenAPI docs
[A2-2670](https://pins-ds.atlassian.net/browse/A2-2670)
[A2-2670]: https://pins-ds.atlassian.net/browse/A2-2670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(api): add planningObligationDueDate to appeal timetable

---

appeals/api/src/server/endpoints/appellant-cases/__tests__/appellant-cases.test.js
appeals/api/src/server/endpoints/appellant-cases/appellant-cases.service.js
appeals/api/src/server/notify/templates/__tests__/notify-appeal-confirmed.test.js
appeals/api/src/server/notify/templates/appeal-confirmed.content.md

- Make link a parameter in the notify template
- Fixed unit tests
- [(A2-3430) Clicking on "Give feedback on the appeals service" for V2 S78 -Validation notify email to Appellant navigating to the Householder | Help us improve this service](https://pins-ds.atlassian.net/browse/A2-3430)

fix(appeals): wrong feedback link (a2-3430)

---

azure-pipelines-e2e-appeals.yml

This PR contains code to
- scheduling e2e test to run against DEV environment at 2am UTC Mon-Fri
- targeting main branch  
- ensuring the pipeline runs even if there are no code changes
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-3414)

test(appeals): schedule e2e tests to run daily

---

appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.controller.js

- Adding success banner before redirect to appeal-details page for lpaq complete
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-3466)

fix(web): adding notification banner for lpaq complete before redirect

---

appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.mapper.js

Quick fix to the show more functionality for invalid decision reason so the "maximumBeforeHiding" parameter is used.
Ignoring the prefix "Reason :", the show more only appears when the invalid reason itself is 301 characters or more. 
[Ticket: A2-3229](https://pins-ds.atlassian.net/browse/A2-3229)

fix(appeals): correct show more parameter (a2-3229)

---

appeals/api/src/server/endpoints/appeal-decision/appeal-decision.controller.js
appeals/api/src/server/endpoints/appeal-details/__tests__/appeals-details.test.js
appeals/api/src/server/endpoints/appeals.d.ts
appeals/api/src/server/endpoints/appeals/appeals.formatter.js
appeals/api/src/server/endpoints/change-appeal-type/change-appeal-type.middleware.js
appeals/api/src/server/endpoints/decision/decision.controller.js
appeals/api/src/server/endpoints/invalid-appeal-decision/invalid-appeal-decision.controller.js
appeals/api/src/server/endpoints/linkable-appeals/linkable-appeal.formatter.js
appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.service.js
appeals/api/src/server/endpoints/representations/representations.controller.js
appeals/api/src/server/endpoints/representations/representations.middleware.js
appeals/api/src/server/endpoints/representations/representations.service.js
appeals/api/src/server/mappers/api/shared/index.js
appeals/api/src/server/mappers/api/shared/map-appeal-status.js
appeals/api/src/server/mappers/api/shared/map-completed-state-list.js
appeals/api/src/server/mappers/api/shared/map-state-list.js
appeals/api/src/server/openapi-types.ts
appeals/api/src/server/openapi.json
appeals/api/src/server/repositories/appeal.repository.js
appeals/api/src/server/state/transition-state.js
appeals/api/src/server/swagger.js
appeals/api/src/server/tests/appeals/has.js
appeals/api/src/server/utils/current-status.js
appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
appeals/web/src/server/lib/appeal-status.js
appeals/web/testing/app/fixtures/referencedata.js

- Return all completed statuses when retrieving appeal data within the API.
- Create a simple single function to retrieve the current status from the list of completed appeal statuses.
- Change all references to obtaining the appeal status to use the currentStatus function
- Updated the API definition for Appeal to include completedStatusList array
- Change the isStatusPassed function so that it just checks the existence of the status in the completed status list
- Fixed unit tests in both the API and WEB
- Tested with the e2e tests  progressS78ToDecision.spec.js and issueDecision.spec.js to check the status progression is working correctly.
- [(A2-3496) Fix completed statuses list so it is possible to know when a status has …

fix(appeals): fix completed statuses list (a2-3496)

---

appeals/api/src/server/endpoints/notifications/notification.controller.js
appeals/api/src/server/endpoints/notifications/notifications.routes.js
appeals/api/src/server/endpoints/test-utils/test-utils.controller.js
appeals/api/src/server/endpoints/test-utils/test-utils.routes.js
appeals/api/src/server/openapi.json

- Add test utils get route: '/appeals/{appealReference}/notify-emails-sent' so the notifications can be retrieved via the appeal reference.
- Amend the return code in the notifications route so that it returns a 200 and not a 201 as nothing is created, just retrieved.

chore(appeals): add notify emails sent route to test utils

---

appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.mapper.js
appeals/web/src/server/lib/nunjucks-template-builders/page-component-rendering.js

Use existing function renderPageComponentsToHtml instead of calling nunjucksEnvironment.render directly when pre-rendering embedded components.

chore(appeals): reuse render page components to html

---

appeals/api/src/server/endpoints/link-appeals/link-appeals.controller.js
appeals/api/src/server/endpoints/link-appeals/link-appeals.service.js
appeals/api/src/server/endpoints/linkable-appeals/__tests__/linkable-appeal.test.js
appeals/api/src/server/endpoints/linkable-appeals/linkable-appeal.controller.js
appeals/api/src/server/endpoints/linkable-appeals/linkable-appeal.routes.js
appeals/api/src/server/openapi.json
appeals/e2e/cypress/e2e/back-office-appeals/linkAppeals.spec.js
appeals/web/package.json
appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
appeals/web/src/server/appeals/appeal-details/linked-appeals/__tests__/linked-appeals.test.js
appeals/web/src/server/appeals/appeal-details/linked-appeals/add/add.controller.js
appeals/web/src/server/appeals/appeal-details/linked-appeals/add/add.service.js
appeals/web/src/server/appeals/appeal-details/other-appeals/__tests__/other-appeals.test.js
appeals/web/src/server/appeals/appeal-details/other-appeals/other-appeals.service.js
appeals/web/src/server/appeals/appeal-details/status-tags/status-tags.mapper.js
appeals/web/src/server/lib/mappers/components/page-components/notification-banners.mapper.js
appeals/web/src/styles/7-components/_status-tag.scss
appeals/web/src/styles/main.scss
packages/appeals/constants/support.js

- Make sure the success banner is as described in the ticket
- Made sure the status and linked relationship (lead or child) if there is one are next to each other in the case details page as shown in the ticket
- Checked that the linked relationship is displayed correctly in the personal list
- Appended "/linked" on to API endpoint /appeals/linkable-appeal/${appealReference} to differentiate linked and related appeals
- Check for linked appeals only when determining existing parent and child relationships within the API
- Add the audit trail for both the current and linked appeals when linking an appeal to the current appeal
- Fixed unit tests the API
- Updated the e2e tests for add linked appeal to handle the new success banner
- [(A2-3339) Link appeals - …

fix(appeals): link appeals part 4 case overview add linked appeal (a2-3339)

---

appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/view-and-review/__tests__/__snapshots__/view-and-review.test.js.snap
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/view-and-review/page-components/reject.mapper.js

- Added condition to remove manage button  when no supporting docs are present
- Updated snapshot
https://pins-ds.atlassian.net/browse/A2-3415

a2-3415/removed-manage-button-from-cya-when-no-supporting-docs-are-present

---

appeals/api/src/server/endpoints/integrations/__tests__/integrations.test.js
appeals/api/src/server/mappers/integration/commands/appellant-case.mapper.js
appeals/api/src/server/tests/integrations/mocks.js

A recent refactor led to the wrong mapper being used when importing cases from FO. This was causing some fields to be missing, e.g. procedure type preference was showing as not answered.
[A2-3669](https://pins-ds.atlassian.net/browse/A2-3669)
[A2-3669]: https://pins-ds.atlassian.net/browse/A2-3669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(api): use correct mapper when importing the appeal from FO

---

appeals/api/src/server/endpoints/representations/__tests__/representations.test.js
appeals/api/src/server/endpoints/representations/representations.service.js
appeals/api/src/server/notify/templates/__tests__/notify-received-statement-and-ip-comments-appellant.test.js
appeals/api/src/server/notify/templates/received-statement-and-ip-comments-appellant.content.md

- Add parameters to the notify template for LPA to tailor whether there are statements and/or ip comments
- Added notify tests to handle no statement or interested parties comments within the template
- [(A2-3643) Create Notify to inform LPAs there are no Statement/Interested Parties](https://pins-ds.atlassian.net/browse/A2-3643)

feat(appeals): create notify to inform lpas there is no statement or interested parties comments (a2-3643)

---

appeals/api/src/server/endpoints/historic-england/historic-england.controller.js
appeals/api/src/server/endpoints/historic-england/historic-england.routes.js
appeals/api/src/server/openapi-types.ts
appeals/api/src/server/openapi.json
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/affected-listed-buildings/__tests__/__snapshots__/affected-listed-buildings.test.js.snap
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/affected-listed-buildings/__tests__/affected-listed-buildings.test.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/affected-listed-buildings/affected-listed-buildings.service.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/affected-listed-buildings/affected-listed-buildings.validator.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/changed-listed-buildings/__tests__/__snapshots__/changed-listed-buildings.test.js.snap
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/changed-listed-buildings/__tests__/changed-listed-buildings.test.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/changed-listed-buildings/changed-listed-buildings.service.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/changed-listed-buildings/changed-listed-buildings.validator.js
appeals/web/testing/app/fixtures/referencedata.js

Adding validation for listed building numbers being 7 digits and being a valid historic england number.
[Ticket](https://pins-ds.atlassian.net/browse/A2-3525)

feat(appeals): error check affected or changed listed building numbers (A2-3525)

---

appeals/api/src/server/endpoints/decision/__tests__/decision.test.js
appeals/api/src/server/endpoints/invalid-appeal-decision/__tests__/invalid-appeal-decision.test.js
appeals/api/src/server/endpoints/invalid-appeal-decision/invalid-appeal-decision.service.js
appeals/api/src/server/endpoints/site-visits/__tests__/site-visits.test.js

- Add S20 notify tests (and full planning) for site visit and appeal decisions, both for lpas and appellants
- Bug fix where lpa email for invalid decision was being sent to the appellant/agent email
[LPA Ticket](https://pins-ds.atlassian.net/browse/A2-3661)
[Appellant Ticket](https://pins-ds.atlassian.net/browse/A2-3663)

feat(A2-3663,A2-3661): appellant and lpa notifies

---

appeals/api/src/server/endpoints/appeals.routes.js
appeals/api/src/server/endpoints/decision/__tests__/decision.test.js
appeals/api/src/server/endpoints/decision/decision.service.js
appeals/api/src/server/endpoints/notify-preview/__tests__/__snapshots__/notify-preview.test.js.snap
appeals/api/src/server/endpoints/notify-preview/__tests__/notify-preview.test.js
appeals/api/src/server/endpoints/notify-preview/notify-preview.controller.js
appeals/api/src/server/endpoints/notify-preview/notify-preview.routes.js
appeals/api/src/server/notify/emulate-notify.js
appeals/api/src/server/notify/notify-send.js
appeals/api/src/server/notify/templates/__tests__/correction-notice-decision.test.js
appeals/api/src/server/notify/templates/correction-notice-decision.content.md
appeals/web/src/server/appeals/appeal-details/update-decision-letter/__tests__/__snapshots__/update-decision-letter.test.js.snap
appeals/web/src/server/appeals/appeal-details/update-decision-letter/__tests__/update-decision-letter.test.js
appeals/web/src/server/appeals/appeal-details/update-decision-letter/update-decision-letter.controller.js
appeals/web/src/server/lib/api/notify-preview.api.js
appeals/web/src/styles/8-utilities/_border.scss
appeals/web/testing/app/fixtures/referencedata.js

- Created a new endpoint that will return the HTML for a Notify Email when called with personalisation object and the template name as a parameter
- Added tests for this
- Updated content of notify template to have the correct front office URL in different environments
- new service to call the api endpoint for notify HTML
- added api call for notify preview to the decision letter CYA controller function
- additional CSS classes to accommodate preview box
- updated snapshots and tests for the updates to CYA page
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-3447)

feat(appeals): notify preview functionality (A2-3447)

---

appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
appeals/web/src/server/appeals/personal-list/__tests__/personal-list.test.js
appeals/web/src/server/appeals/personal-list/personal-list.mapper.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/started-at.mapper.js
appeals/web/src/server/lib/mappers/utils/map-status-dependent-notifications.js

- Hide the start appeal link in personal cases page on child cases
- Hide the important information banner for starting an appeal on the case details page for a child case
- Update tests and snapshots for above
- [(A2-3475) CTA updates on lead and child appeals after linking written rep S78 planning appeals (where none have been started) - part 1](https://pins-ds.atlassian.net/browse/A2-3475)

feat(appeals): cta updates on lead and child appeals after linking where none have started (a2-3475)

---

appeals/api/src/server/endpoints/appeal-decision/__tests__/appeal-decision.test.js
appeals/api/src/server/endpoints/appeal-timetables/__tests__/appeal-timetables.test.js
appeals/api/src/server/endpoints/appellant-cases/__tests__/appellant-cases.test.js
appeals/api/src/server/endpoints/change-appeal-type/__tests__/change-appeal-type.test.js
appeals/api/src/server/endpoints/decision/__tests__/decision.test.js
appeals/api/src/server/endpoints/hearings/__tests__/hearing.test.js
appeals/api/src/server/endpoints/invalid-appeal-decision/__tests__/invalid-appeal-decision.test.js
appeals/api/src/server/endpoints/lpa-questionnaires/__tests__/lpa-questionnaires.test.js
appeals/api/src/server/endpoints/representations/__tests__/representations.test.js
appeals/api/src/server/endpoints/site-visits/__tests__/site-visits.test.js
appeals/api/src/server/endpoints/withdrawal/__tests__/withdrawal.test.js

Due to the function "mockNotifySend" now being included as a global in .eslintrc.cjs for our jest tests, the eslint-disable-next-line comment can be removed everywhere the function is used.
Unit tests have been successfully run and tscheck also passes.

chore(appeals): remove unnecessary eslint-disable-next-line comment

---

appeals/web/src/server/appeals/appeal-details/appeal-timetables/__tests__/__snapshots__/appeal-timetables.test.js.snap
appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
appeals/web/src/server/appeals/appeal-details/appellant-case/application-submission-date/__tests__/__snapshots__/application-submission-date.test.js.snap
appeals/web/src/server/appeals/appeal-details/change-appeal-type/__tests__/__snapshots__/change-appeal-type.test.js.snap
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap
appeals/web/src/server/appeals/appeal-details/timetable/__tests__/__snapshots__/timetable.test.js.snap
appeals/web/src/server/appeals/appeal-documents/appeal-documents.controller.js
appeals/web/src/server/appeals/appeal-documents/appeal-documents.validators.js
appeals/web/src/server/lib/mappers/utils/create-class-for-date-errors.js
appeals/web/src/server/lib/validators/date-input.validator.js

1. Updated date fields to highlight only the correct empty fields for standard dates and document dates
2. Refactored both validators so that the checks follow the same format
3. Updated css class mappers to accommodate new setup and be more easily adapted if more changes come in the future
1. Updated Unit tests to accomodate for new setup
2. Updated snapshots
3. Manually checked date fields
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-1741)

feat(web): field highlighting and messages for date errors

---

appeals/api/src/server/endpoints/linkable-appeals/linkable-appeal.service.js

- Change logic to test against a specific list of valid linkable statuses
- [(A2-3424) Validation on 'Appeal reference' field when adding a linked appeal](https://pins-ds.atlassian.net/browse/A2-3424)

fix(appeals): validate linkable appeal status (a2-3424)

---

appeals/web/src/server/appeals/appeal-details/inquiry/setup/__tests__/__snapshots__/set-up-inquiry.test.js.snap
appeals/web/src/server/appeals/appeal-details/inquiry/setup/__tests__/set-up-inquiry.test.js
appeals/web/src/server/appeals/appeal-details/inquiry/setup/set-up-inquiry-validators.js
appeals/web/src/server/appeals/appeal-details/inquiry/setup/set-up-inquiry.controller.js
appeals/web/src/server/appeals/appeal-details/inquiry/setup/set-up-inquiry.mapper.js
appeals/web/src/server/appeals/appeal-details/inquiry/setup/set-up-inquiry.router.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
appeals/web/src/server/lib/validators/date-input.validator.js
appeals/web/src/server/lib/validators/generic.validator.js

- Added route, controller, mapper and validators for inquiry setup due dates
- Added generic validator for empty input
- Amended date validator to read when all inputs are blank 
- Added tests
- Added snapshot
https://pins-ds.atlassian.net/browse/A2-3498?atlOrigin=eyJpIjoiZTE4MTExNTUzYmZiNGMwNjgwYjkxYzYyODlkNGM2MjEiLCJwIjoiaiJ9

feat(web): inquiry setup due dates (a2-3498)

---

appeals/e2e/cypress/e2e/back-office-appeals/issueDecisionInvalid.spec.js

Adds the journey for issuing an invalid decision, including appellant and LPA costs, file uploads, CYA page, banner message validation, case status and outcome checks, decision letter, and notify checks.
[A2-3795](https://pins-ds.atlassian.net/browse/A2-3795)
[A2-3795]: https://pins-ds.atlassian.net/browse/A2-3795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add invalid issue decision journey automation

---

appeals/api/src/server/endpoints/appeal-decision/__tests__/appeal-decision.test.js
appeals/api/src/server/endpoints/lpa-questionnaires/__tests__/lpa-questionnaires.test.js
appeals/api/src/server/endpoints/representations/__tests__/representations.test.js
appeals/api/src/server/tests/appeals/mocks.js
docs/notifications-and-triggers.md

Updating/adding tests for:
- decision-is-allowed-split-dismissed(-lpa/-appellant)
- lpaq-incomplete
- ip-comment-rejected
- ip-comment-rejected-deadline-extended
- lpa-statement-incomplete
Updating the documentation to include the S20 notifies
[Ticket](https://pins-ds.atlassian.net/browse/A2-3581)

feat(appeals): updating notify tests and docs for listed building

---

appeals/api/src/server/endpoints/appeal-timetables/appeal-timetables.service.js
appeals/web/src/server/appeals/appeal-details/timetable/__tests__/__snapshots__/timetable.test.js.snap
appeals/web/src/server/appeals/appeal-details/timetable/__tests__/timetable.test.js
appeals/web/src/server/appeals/appeal-details/timetable/timetable.controller.js
appeals/web/src/server/appeals/appeal-details/timetable/timetable.mapper.js
appeals/web/src/server/appeals/appeal-details/timetable/timetable.validators.js
appeals/web/src/server/lib/validators/date-input.validator.js

- Updating the validation logic so that only due dates that have been updated are validated against
- Moving sessionTimetable logic from the POST to the validator
- saving timetable dates in session as UTC  
- Fixed issues for showing errors for hearing timetable due dates
- Added a fix for [A2-3823](https://pins-ds.atlassian.net/browse/A2-3823) 
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-3782)
[A2-3823]: https://pins-ds.atlassian.net/browse/A2-3823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(A2-3782): Only validating due dates that have been changed

---

appeals/web/src/server/lib/mappers/data/appeal/submappers/__tests__/lpa-questionnaire.mapper.test.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/lpa-questionnaire.mapper.js

- Add logic to lpa questionnaire mapper to display the view link when complete or incomplete.
- Added all missing unit tests for the documentation row for LPAQ
- [(A2-3753) WEB/API - "View" button in documentation row next to LPAQ disappears once LPAQ has been reviewed as incomplete](https://pins-ds.atlassian.net/browse/A2-3753)

fix(appeals): missing view link in lpa-questionnaire row mapper (a2-2603)

---

appeals/api/src/server/utils/__tests__/sort-appeals.test.js
appeals/api/src/server/utils/appeal-sorter.js

- Return linked child appeals grouped with each lead appeal based on the lead appeal's due date when retrieving /appeals/my-appeals
- Added more complex unit tests
- [(A2-3794) How are linked appeals currently grouped together in test/prod on 'Cases assigned to you' screen?](https://pins-ds.atlassian.net/browse/A2-3794)

fix(appeals): sort lead and child correctly (a2-3794)

---

appeals/api/src/database/seed/data-samples.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js
appeals/web/src/server/lib/mappers/data/lpa-questionnaire/submappers/map-is-correct-appeal-type.js
appeals/web/src/server/lib/mappers/data/lpa-questionnaire/submappers/map-officers-report.js
appeals/web/src/server/lib/mappers/utils/__tests__/documents-and-folders.test.js
packages/appeals/constants/documents.js

- Adding the LPAQ for CAS (and relevant tests)
- Adding the LPAQ to the seeded data for CAS
- Changing ' to ’ in 'Planning officer’s report' for consistency
- Adding a function to convert the appealType to the text we want displayed (CAS planning)
[Ticket](https://pins-ds.atlassian.net/browse/A2-3266)

feat(web): adding lpaq for CAS (A2-3266)

---

appeals/api/src/server/endpoints/representations/representations.controller.js
appeals/api/src/server/endpoints/representations/representations.service.js
packages/appeals/constants/support.js

- Refactored code segment handling rep audit logs into a service function
- Removed "updated to" wording in rep audit log string values
- Rewrote string values to ensure accept/reject/redact status logs match design requirements 
- Rewrote const titles in common.js into a uniform pattern for reps (fixing calls to AUDIT_TRAIL_REP_LPA_STATEMENT_STATUS_VALID & AUDIT_TRAIL_REP_LPA_STATEMENT_STATUS_INCOMPLETE)
Link to requirements for rep logs for reference:
https://pins-ds.atlassian.net/wiki/spaces/BO/pages/1988558868/Case+history
https://pins-ds.atlassian.net/browse/A2-3864

feat(web): refactored audit rep log function (a2-3864)

---

appeals/api/src/server/utils/__tests__/sort-appeals.test.js
appeals/api/src/server/utils/appeal-sorter.js

- Return linked child appeals grouped with each lead appeal based on the lead appeal's due date when retrieving /appeals/my-appeals even when dates are the same.  Achieved by sorting by lead duedate, lead (if linked), child (if linked).
- Fixed unit tests
- [(A2-3794) How are linked appeals currently grouped together in test/prod on 'Cases assigned to you' screen?](https://pins-ds.atlassian.net/browse/A2-3794)

feat(appeals): fix personal list sort (a2-3794)

---

appeals/api/src/server/utils/build-list-of-linked-appeals.js

- Adding filter to ensure only 'linked' child appeals are added to list of LinkedAppeals. 
- (raising separate tech debt ticket to add tests for utility file)
[Ticket](https://pins-ds.atlassian.net/browse/A2-3945)

fix(A2-3945): filtering out "related" appeals from buildListOfLinkedAppeals

---

appeals/api/src/server/endpoints/appeal-decision/__tests__/appeal-decision.test.js
appeals/api/src/server/endpoints/decision/__tests__/decision.test.js
appeals/api/src/server/endpoints/invalid-appeal-decision/__tests__/invalid-appeal-decision.test.js
appeals/api/src/server/tests/appeals/mocks.js

- Adding tests for notify for CAS planning decisions
- Adding a mock CAS planning appeal
[Ticket](https://pins-ds.atlassian.net/browse/A2-3793)

test(api): updating notify tests to cover cas planning decisions

---

appeals/api/src/server/endpoints/lpa-questionnaires/__tests__/lpa-questionnaires.test.js
appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.service.js
appeals/api/src/server/tests/appeals/mocks.js
docs/notifications-and-triggers.md

- Updating the code to send notifies for CAS planning LPAQ complete
- Updating tests to cover CAS planning questionnaire notifies
- Updating mocks to contain LPAQ incomplete data for CAS planning
- Updating the documentation to reflect the cases where CAS planning notifies are sent
- Changing the adding a name in the input structure on one of the test each so that the test title displays nicely
[Ticket](https://pins-ds.atlassian.net/browse/A2-3668)

feat(api): updating questionnaire notifies to include cas planning

---

appeals/e2e/cypress/e2e/back-office-appeals/scheduleSiteVisit.spec.js

Recently the option to add a site visit date that is in the past has been implemented so the tests have been updated to reflect this change
https://pins-ds.atlassian.net/browse/A2-3801

test(appeals): site visit date in past update

---

appeals/web/src/server/lib/mappers/utils/__tests__/required-actions.test.js
appeals/web/src/server/lib/mappers/utils/required-actions.js

- Default the action link in the personal list to arrange site visit.
- Fixed unit tests
- [(A2-3890) No action link on 'Cases assigned to you' screen when appeal is at 'Site visit ready to set up' stage](https://pins-ds.atlassian.net/browse/A2-3890)

fix(appeals): no action links for arrange site visit in the personal list (a2-3890)

---

appeals/api/src/server/endpoints/site-visits/__tests__/site-visits.test.js
docs/notifications-and-triggers.md

- Refactoring to have large describe each blocks rather than so many test each loops.
- Adding CAS planning notify tests
[Ticket](https://pins-ds.atlassian.net/browse/A2-3680)

test(api): updating site visit notify tests to add cas planning

---

packages/appeals/constants/documents.js

Extending the list of valid hex signatures used when validating mime types
Added a few more from https://en.wikipedia.org/wiki/List_of_file_signatures
[Ticket](https://pins-ds.atlassian.net/browse/A2-4039)

fix(api): extend file upload hex signature list to allow common uploads

---

appeals/api/src/server/endpoints/withdrawal/__tests__/withdrawal.test.js
appeals/api/src/server/endpoints/withdrawal/withdrawal.service.js
appeals/api/src/server/notify/templates/__tests__/notify-appeal-withdrawn-lpa.test.js

- Updated the logic for the LPA withdrawal notify to determine eventType and include hearing in this to ensure "hearing cancelled" is included on the notify email (when it's been set up).
- Added new unit test for updated content
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-3984)

fix(A2-3984): adding hearing event type for lpa withdrawal notify

---

appeals/api/src/server/endpoints/appeal-details/appeal-details.service.js
appeals/api/src/server/mappers/api/shared/map-appeal-relationships.js
appeals/api/src/server/mappers/mapper-factory.js
appeals/api/src/server/utils/is-awaiting-linked-appeal.js
appeals/web/src/server/appeals/personal-list/personal-list.mapper.js
appeals/web/src/server/lib/mappers/utils/required-actions.js

- awaitingLinkedAppeals flag should be true when at least one sibling or parent  appeal (when linked) is on a previous status.
- reuse mapping linked appeal for child and parent appeals
- Tested with feature flag on and off 
- [(A2-3630) Reviewing questionnaires for linked written rep S78 planning appeals (where the appeals have all been started together) - part 4](https://pins-ds.atlassian.net/browse/A2-3630)

fix(appeals): small refactor for awaiting appeals when statuses are different

---

appeals/api/src/server/build-app.js

Appellant submission with large number of files failed
Bumping up the request limit as a quick solution
[Ticket](https://pins-ds.atlassian.net/browse/A2-4073)

fix(api): increase requet body size limit for bodyParser (a2-4073)

---

appeals/api/src/server/endpoints/appeal-details/appeal-details.service.js
appeals/api/src/server/endpoints/appeals.d.ts
appeals/api/src/server/endpoints/appellant-cases/appellant-cases.controller.js
appeals/api/src/server/endpoints/appellant-cases/appellant-cases.service.js
appeals/api/src/server/repositories/appeal-lists.repository.js
appeals/api/src/server/repositories/appeal.repository.js
appeals/api/src/server/utils/is-awaiting-linked-appeal.js
appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.mapper.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js
appeals/web/src/server/appeals/personal-list/personal-list.mapper.js
appeals/web/src/server/lib/mappers/utils/required-actions.js

- The awaitingLinkedAppeal flag should be true for a validated appeal within a group of linked appeals (lead and one or more children) all with status 'validation' when at least one member of the group has not yet been validated.
- When the last member of a group of linked appeals with status 'validation' is validated, they will all transition to the status 'lpq-questionnaire'.
- Fix a small bug to make sure the load-linked-appeals function works with linked and not related appeals.
- Display "Awaiting linked appeal" when a validated appeal is waiting for linked appeals to be validated.
- An additional check for reviewing the Appellant case is necessary to prevent the radio buttons being displayed when viewing after it has been validated as the status will not transition until all linked …

feat(appeals): awaiting linked appeal banner pre starting (a2-4065)

---

appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
appeals/web/src/server/appeals/appeal-details/accordions/common/case-management.js
appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
appeals/web/src/server/appeals/appeal-details/cancel/__tests__/__snapshots__/cancel.test.js.snap
appeals/web/src/server/appeals/appeal-details/cancel/cancel-appeal-section.js
appeals/web/src/server/appeals/appeal-details/cancel/cancel.mapper.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/appeal-withdrawal.mapper.js

- Added a new cancel appeal section to the appeal-details page (not part of the accordion)
- Cancel appeal section displays conditionally depending on FF and whether appeal is invalid/withdrawn
- Added FF conditional to existing withdraw row
- Added unit tests for new cancel appeal section & updated snapshots
- Added new describe container for appeal-details unit tests for linked appeals for better organisation
- Manual testing in browser with Feature flag ON and OFF
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-3840)

feat(A2-3840): adding cancel appeal section to appeal details

---

appeals/web/src/server/lib/__tests__/libraries.test.js
appeals/web/src/server/lib/appeal-status.js

- updated status tag mapper so that 'Site visit is ready to set up ' and 'Awaiting site visit' is displayed when status is 'Event' and 'Awaiting event' respectively
- manually tested within browser
- added new unit tests 
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-4102

fix(web): updating mapStatusTag to display awaiting site visit for s20 appeals (A2-4102)

---

appeals/api/src/database/seed/data-static.js
appeals/web/src/server/appeals/appeal-details/appeal-details.router.js
appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.router.js
appeals/web/src/server/appeals/appeal-details/invalid-appeal/__tests__/__snapshots__/invalid-appeal.test.js.snap
appeals/web/src/server/appeals/appeal-details/invalid-appeal/__tests__/invalid-appeal.test.js
appeals/web/src/server/appeals/appeal-details/invalid-appeal/invalid-appeal.controller.js
appeals/web/src/server/appeals/appeal-details/invalid-appeal/invalid-appeal.mapper.js
appeals/web/src/server/appeals/appeal-details/invalid-appeal/invalid-appeal.router.js
appeals/web/src/server/appeals/appeal-details/invalid-appeal/invalid-appeal.validators.js
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
appeals/web/src/server/lib/__tests__/libraries.test.js
appeals/web/src/server/lib/validators/checkbox-text-items.validator.js
appeals/web/testing/app/fixtures/referencedata.js

- Moved & renamed the existing outcome-invalid directory to make it common and used for both appeal-details in cancel flow and within appellant case (with different routes).
- Made copy updates by updating seed data for invalid reasons table
- Updated the error message for entering a reason characters exceeded
- Added new regex validator to add another components
- Tested feature inside the browser 
- Tested feature with feature flag OFF
- Tested that all features for appellant-case entry point and journey still
[Ticket](https://pins-ds.atlassian.net/browse/A2-3841)

Feat(A2-3841): Adding the invalid appeal reasons why page for cancel flow

---

appeals/e2e/cypress/e2e/back-office-appeals/linkAppeals.spec.js
appeals/web/src/server/appeals/appeal-details/linked-appeals/__tests__/linked-appeals.test.js
appeals/web/src/server/appeals/appeal-details/linked-appeals/add/add.controller.js

- Redirect to the link appeal conflict page if both appeals are a linked lead appeal
- Fixed e2e tests for linked appeals
- Added unit tests to test the functionality
- [(A2-3917) Remove 'Which is the lead appeal?' screen when linking additional child appeals and slightly amend CYA screen](https://pins-ds.atlassian.net/browse/A2-3917)

fix(appeals): prevent linking a lead appeal to another lead appeal (a2-3917)

---

appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/__tests__/interested-party-comments.test.js
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/add-ip-comment/add-ip-comment.mapper.js
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/add-ip-comment/add-ip-comment.router.js
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/interested-party-comments.controller.js
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/interested-party-comments.mapper.js
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/interested-party-comments.router.js
appeals/web/src/server/lib/middleware/__tests__/save-back-url.test.js
appeals/web/src/server/lib/middleware/save-back-url.js

Use the session to save the backUrl when entering the IP comments flow. This means that we don't need to carry forward the backUrl query string on every single link that the user follows within this flow, which would be very error-prone because if we forgot to add it to any of the links or added new links without preserving the query string then it would forget where to go back to at the end. Also this session-based approach requires far less work and touches fewer files, so it will be easier to roll out to other flows. I have scoped the session key by flow and appeal ID to avoid any interference if the user is doing different things in multiple tabs.
[A2-3053](https://pins-ds.atlassian.net/browse/A2-3053)
[A2-3053]: https://pins-ds.atlassian.net/browse/A2-3053?atlOrigin=eyJpIjoiNWRkNTljNz …

feat(web): use session to save backUrl for IP comments flow

---

appeals/api/src/database/seed/seed-clear-test-data.js

Clearing the test data failed for inquiries due to a foreign key constraint.
I changed the ordering, so the inquiry rows are deleted before the appeal.

fix(api): resolve clearing the test data failing

---

appeals/web/src/server/appeals/appeal-details/update-decision-letter/__tests__/__snapshots__/update-decision-letter.test.js.snap
appeals/web/src/server/appeals/appeal-details/update-decision-letter/__tests__/update-decision-letter.test.js
appeals/web/src/server/appeals/appeal-details/update-decision-letter/update-decision-letter.controller.js

- Removed 'update decision letter' from page caption
- Updates unit tests and snapshots
- manual testing within browser 
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-4114)

feat(web): removing update decision letter from caption (A2-4114)

---

appeals/e2e/cypress/e2e/back-office-appeals/linkAppeals.spec.js
appeals/e2e/cypress/page_objects/basePage.js

* Added a simple check to ensure that a specific row was no longer showing
* Added a method to `basePage` object that allows for validating if a row exists or not
[A2-3917](https://pins-ds.atlassian.net/browse/A2-3917)
[A2-3917]: https://pins-ds.atlassian.net/browse/A2-3917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test(appeals): added check for removed row and journey

---

appeals/api/src/server/endpoints/appeals.d.ts
appeals/api/src/server/endpoints/decision/__tests__/decision.test.js
appeals/api/src/server/endpoints/decision/decision.controller.js
appeals/api/src/server/endpoints/decision/decision.service.js
appeals/api/src/server/mappers/api/shared/map-appeal-relationships.js
appeals/api/src/server/repositories/appeal.repository.js
appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/__snapshots__/issue-decision.test.js.snap
appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/issue-decision.test.js
appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.controller.js
appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.mapper.js
appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.middleware.js
appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.router.js
appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.utils.js
appeals/web/src/server/appeals/appeal-details/status-tags/status-tags.mapper.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/decision.mapper.js
appeals/web/src/server/lib/string-utilities.js

This PR "appears" far bigger than it is.  Please don't let the detail below scare you when reviewing.
Please note that the upload page tickets (A2-4135, A2-4164, and A2-4169) and costs page tickets (A2-3046 and A2-4165) only amount to the preHeadingText including (lead) if the appeal is linked appeal.
Most of the specified changes below are for the tickets (A2-3075 and A2-4170)
- Add inspectorDecision to LinkedAppeal interface
- Create publishChildDecision in decision.service.js and call from decision.controller.js when child appeal.
- Include inspectorDecision when mapping relationships for linked appeals in map-appeal-relationships.js
- include inspectorDecision when retrieving linked appeals in appeal.repository.js
- Do not update the document version when creating a child issue …

feat(appeals): issuing a decision for linked appeals (a2-3075)

---

appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.controller.js
appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.service.js
appeals/api/src/server/mappers/api/shared/map-appeal-relationships.js
appeals/api/src/server/utils/__tests__/is-awaiting-linked-appeal.test.js

This is a bug fix for a previous ticket
- Fix the calculation for setting the awaitingLinkedAppeal property on the appeal get requests
- Make sure the broadcast of an appeal happens when all the LPA Questionnaire appeals transition
- Add extra unit tests
- Make sure tests still pass
- Test within browser
[A2-3630](https://pins-ds.atlassian.net/browse/A2-3630)
[A2-3630]: https://pins-ds.atlassian.net/browse/A2-3630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(appeals): prevent awaiting linked appeal loop (a2-3630)

---

appeals/api/src/server/endpoints/link-appeals/link-appeals.controller.js

When two appeals are linked, this change ensures that the updated details in respect of both linked appeals are broadcast.
[Ticket]https://pins-ds.atlassian.net/browse/A2-3911

fix(api): broadcast updated details for both child and lead linked appeals

---

appeals/api/setup-tests.js
appeals/api/src/server/endpoints/documents/__tests__/documents.test.js
appeals/api/src/server/endpoints/documents/documents.service.js
appeals/api/src/server/endpoints/link-appeals/__tests__/link-appeal.test.js
appeals/api/src/server/endpoints/link-appeals/link-appeals.controller.js
appeals/api/src/server/endpoints/link-appeals/link-appeals.service.js
appeals/api/src/server/repositories/document-metadata.repository.js
appeals/api/src/server/tests/documents/mocks.js
appeals/api/src/server/utils/blob-copy.js
appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
appeals/web/src/server/appeals/appeal-details/accordions/has.js
appeals/web/src/server/appeals/appeal-details/accordions/s78.js

- Hide costs accordion on linked child appeal
- Create a function to copy blobs from one location to another
- Create a new generic duplicateFiles function to copy documents from a source appeal to a target appeal for a given stage (such as costs)
- Update unit tests where required
- Make sure they pass
- Tested within browser examining the blob emulator to make sure the blobs are copied correctly
[A2-4173 - What happens to cost files/'Costs' accordion on child appeals when linking (relates to all appeal types)](https://pins-ds.atlassian.net/browse/A2-4173)

feat(appeals): hide costs accordion when linked appeal (a2-4173)

---

appeals/api/setup-tests.js
appeals/api/src/database/schema.d.ts
appeals/api/src/server/endpoints/integrations/__tests__/integrations.test.js
appeals/api/src/server/endpoints/integrations/integrations.middleware.js

This is a bug fix for a previous ticket
- When validating and loading the appeal in the integrations middleware for representations, make sure the representations are loaded on to the lead appeal if the appeal reference supplied is for a linked child appeal.
- Remove unused imports in database schema 
- Add extra unit tests
- Make sure tests still pass
- Tested with swagger
- Test within browser
[A2-3690 - Reviewing interested party (IP) comments for linked written rep S78 planning appeals](https://pins-ds.atlassian.net/browse/A2-3690)

fix(appeals): use lead appeal when importing representations (a2-3690)

---

appeals/web/src/server/appeals/appeal-details/representations/final-comments/view-and-review/__tests__/__snapshots__/view-and-review.test.js.snap
appeals/web/src/server/appeals/appeal-details/representations/final-comments/view-and-review/__tests__/view-and-review.test.js
appeals/web/src/server/appeals/appeal-details/representations/final-comments/view-and-review/view-and-review.mapper.js
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/view-and-review/__tests__/__snapshots__/view-and-review.test.js.snap
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/view-and-review/__tests__/view-and-review.test.js
appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/view-and-review/page-components/review.mapper.js
appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/__tests__/__snapshots__/lpa-statement.test.js.snap
appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/__tests__/lpa-statement.test.js
appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/lpa-statement.mapper.js
appeals/web/src/server/lib/mappers/utils/required-actions.js
appeals/web/testing/app/fixtures/referencedata.js

- Added logic to hide redact and accept radio option for reps (final/ip comments and lpa statement) when there's no rep text to redact (i.e only a supporting doc is added)
- Updated unit tests reference data - reps field is 'source' not origin
- Added new unit tests to ensure 'Accept and Redact' option is NOT present when no orignalRepresentation is present for each representation
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-4034)

fix(A2-4034): hiding redact and accept radio button when there's no rep to redact

---

appeals/api/src/server/endpoints/appellant-cases/appellant-cases.service.js
appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.service.js
appeals/api/src/server/utils/__tests__/is-awaiting-linked-appeal.test.js
appeals/api/src/server/utils/is-awaiting-linked-appeal.js

- Make sure the review outcome current appeal LPA Questionnaire is included correctly when testing that all linked appeals have had their review completed so that the transition to the next appeal status works as it should.
- Make sure the review outcome current appeal Appellant Case is included correctly when testing that all linked appeals have had their review validated so that the transition to the next appeal status works as it should.
- Added detailed unit tests to test the above functionality
[A2-3630 Reviewing questionnaires for linked written rep S78 planning appeals (where the appeals have all been started together)](https://pins-ds.atlassian.net/browse/A2-3630)

fix(appeals): prevent reviewing lpa questionnaire loop for linked appeals (a2-3630)

---

appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/issue-decision.test.js
appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.controller.js
appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.mapper.js
appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.utils.js
appeals/web/src/server/appeals/appeal-details/status-tags/status-tags.mapper.js
appeals/web/src/server/appeals/appeal-documents/appeal.documents.service.js

- viewing issue decision for lead appeal
- viewing issue decision for child appeal
- added unit tests for above
- all other unit tests pass
- tested in browser
[A2-4236 - BO - Issuing a decision for linked appeals (relates to all appeal types) - 'Decision' screen on lead and child appeals after decision(s) issued - Part 11](https://pins-ds.atlassian.net/browse/A2-4236)

fix(appeals): viewing issue decisions for linked appeals (a2-4236)

---

appeals/web/src/server/lib/mappers/data/appeal/submappers/__tests__/decision-mapper.test.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/decision.mapper.js

- Allow decision row to be visible with view link when decision has been made whether the appeal is unlinked, linked lead, or linked child
- Only display row with issue link when decision has not been made and the appeal is not a linked child
- created missing decision row unit tests including above changes
- all other unit tests pass
- tested in browser
[A2-4215- BO - Issuing a decision for linked appeals (relates to all appeal types) - Updates to 'Case details' screen on child appeal(s) after decision(s) issued - Part 10](https://pins-ds.atlassian.net/browse/A2-4215)

feat(appeals): case details page for child after issue decision (a2-4215)

---

appeals/api/src/server/endpoints/appeal-timetables/__tests__/appeal-timetables.test.js
appeals/api/src/server/endpoints/appeal-timetables/appeal-timetables.service.js

- Make sure only linked appeals are listed in the notify
- added unit tests for above
- all other unit tests pass
- tested in browser and email emulator
[A2-3492- Starting linked written rep S78 planning appeals (where none have previously been started) and automated Notifies are sent - part 2](https://pins-ds.atlassian.net/browse/A2-3492?focusedCommentId=94525)

fix(appeals): do not include related appeals in notifies (a2-3492)

---

appeals/web/src/server/appeals/appeal-details/update-case-team/__tests__/__snapshots__/update-case-team.test.js.snap
appeals/web/src/server/appeals/appeal-details/update-case-team/__tests__/update-case-team.test.js
appeals/web/src/server/appeals/appeal-details/update-case-team/update-case-team.mapper.js

- Updated update case team to display NOt assigned on check your answers page when unassign team is selected
- added unit test and snapshot to cover this scenario
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-4123)

feat(web): display Not assigned on CYA update team page (A2-4123)

---

appeals/api/src/server/endpoints/decision/decision.controller.js

- Make sure if all decisions are undefined, a null is returned as expected 
- Made sure unit tests pass,
- Made sure affected e2e tests pass
- Tested manually in browser
[a2-3175](https://pins-ds.atlassian.net/browse/A2-3175)

fix(appeals): prevent undefined decision result (a2-3175)

---

appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.controller.js

- Dedupe audit trail messages for lpaq questionnaire updates.
- Tested manually within browser
- Made sure unit tests pass

fix(appeals): dedupe audit trail messages for lpaq questionnaire updates

---

appeals/web/src/server/appeals/personal-list/__tests__/__snapshots__/personal-list.test.js.snap
appeals/web/src/server/appeals/personal-list/__tests__/personal-list.test.js
appeals/web/src/server/appeals/personal-list/personal-list.mapper.js

- Replace the text "Awaiting LPA update" with an action link "Update questionnaire" in the personal list for LPA questionnaires marked as invalid
- Updated unit tests 
[A2-4368 Reviewing questionnaires for linked written rep S78 planning appeals (where the appeals have all been started together)](https://pins-ds.atlassian.net/browse/A2-4368)

fix(appeals): add update questionnaire action links to personal list (a2-4368)

---

appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
appeals/web/src/server/appeals/appeal-details/appellant-case/page-components/cas-advert.mapper.js
appeals/web/src/server/lib/mappers/data/appellant-case/cas-advert.js
appeals/web/src/server/lib/mappers/data/appellant-case/submappers/changed-advertisement-description-document.js

Adds the change description of advertisement document row using the changed description of development document type
As it uses an existing document type no api changes are required
- Snapshots updated
- Row added to cas advert appellent case controller test
- Change and add document behaviour tested manually in browser 
[Ticket](https://pins-ds.atlassian.net/browse/A2-3847)

feat(web): a2-3847 change the description of the advertisement

---

appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
appeals/web/src/server/lib/mappers/data/appeal/submappers/__tests__/appeal-type.mapper.test.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/appeal-type.mapper.js

- Hide appeal type change link within overview section in case details page when the appeal has been linked
- Added unit test for above
- Updated snap shots where required
- Make sure all other unit tests pass
- Tested within the browser
[A2-4386- BO linked appeals - Hide 'Change' link on 'Appeal type' row on lead and child appeal(s) upon linking (relates to all appeal types)](https://pins-ds.atlassian.net/browse/A2-4386)

feat(appeals): hide appeal type change link for linked appeals (a2-4386)

---

.eslintrc.cjs
appeals/api/setup-tests.js
appeals/api/src/server/endpoints/integrations/integrations.broadcasters/documents.js
appeals/api/src/server/endpoints/representations/__tests__/representations.test.js
appeals/api/src/server/endpoints/representations/representations.service.js
appeals/api/src/server/mappers/integration/__tests__/mappers.test.js
appeals/api/src/server/mappers/integration/commands/document.mapper.js
appeals/api/src/server/mappers/integration/map-document-entity.js
packages/appeals/constants/documents.js

Was broadcasting rep docs with a default doc type of IP comment, as the attachment used for deciding the doctype was set after the initial broadcast
- adds a check to not broadcast in this scenario
- defaults doc type to UNCATEGORISED rather than IP Comment
- calls broadcastDocument after attachment is made
- create and use doc type const
had to mock integrations.broadcasters globally - was unable to get it to work with mocking at a higher level without impacting other tests
[Ticket](https://pins-ds.atlassian.net/browse/A2-4406)

fix(api): handle broadcast of document type correctly for reps

---

appeals/api/src/server/utils/blob-copy.js

- When not emulating blob storage, use the topic "appeal-document-to-move" to send an event to move the blobs between appeals with the correct blob container
[A2-4173 - BO - What happens to cost files/'Costs' accordion on child appeals when linking (relates to all appeal types)](https://pins-ds.atlassian.net/browse/A2-4173)

fix(appeals): add blob storage container to blob uri (a2-4173)

---

appeals/api/src/server/notify/templates/__tests__/appeal-start-date-change-lpa.test.js
appeals/api/src/server/notify/templates/__tests__/notify-appellant-costs-decision-appellant.test.js
appeals/api/src/server/notify/templates/__tests__/notify-appellant-costs-decision-lpa.test.js
appeals/api/src/server/notify/templates/__tests__/notify-lpa-costs-decision-appellant.test.js
appeals/api/src/server/notify/templates/__tests__/notify-lpa-costs-decision-lpa.test.js
appeals/api/src/server/notify/templates/appellant-costs-decision-appellant.content.md
appeals/api/src/server/notify/templates/appellant-costs-decision-lpa.content.md
appeals/api/src/server/notify/templates/lpa-costs-decision-appellant.content.md
appeals/api/src/server/notify/templates/lpa-costs-decision-lpa.content.md

See the original PR against main for reference here: [fix(appeals): links in some emails are broken (a2-4447)](https://github.com/Planning-Inspectorate/appeals-back-office/pull/2056)
- Fix templates to make sure they are not prefixing the front office links with additional "https://"
- Updated tests for notify changes above
[A2-4447- BO: "Sign in to our service" link in costs decision notify email returns the "can't reach this page" error](https://pins-ds.atlassian.net/browse/A2-4447)

fix(appeals): some front office links in emails are broken (a2-4447) - patch for release

---

appeals/api/src/server/endpoints/link-appeals/__tests__/link-appeal.test.js
appeals/api/src/server/utils/blob-copy.js

- When not emulating blob storage, use the topic "appeal-document-to-move" to send an event to move the blobs between appeals with the correctly formatted blob container
- Always use above even if using the blob emulator locally as the event itself will be mocked and displayed within the local api log for debugging purposes.
- Add unit tests to make sure event message is formatted correctly
- [A2-4173 - BO - What happens to cost files/'Costs' accordion on child appeals when linking (relates to all appeal types)](https://pins-ds.atlassian.net/browse/A2-4173)
- [A2-4408 - BO - Linked Appeal: Child Appeal cost documents duplicated in Lead Appeal is not viewable, ends up in error page)](https://pins-ds.atlassian.net/browse/A2-4408)

fix(appeals): amend badly formed blob storage container (a2-4173)

---

appeals/api/src/server/endpoints/representations/__tests__/representations.test.js
appeals/api/src/server/endpoints/representations/representations.service.js
appeals/api/src/server/notify/templates/__tests__/notify-received-statement-and-ip-comments-appellant.test.js
appeals/api/src/server/notify/templates/__tests__/notify-received-statement-and-ip-comments-lpa.test.js
appeals/api/src/server/notify/templates/received-statement-and-ip-comments-appellant.subject.md
appeals/api/src/server/notify/templates/received-statement-and-ip-comments-lpa.subject.md

- Move conditional and text for subject line into the template itself in an attempt to prevent the invalid characters replacing the apostrophe. 
- Updated tests for notify changes above
[A2-4433- Invalid subject Displaying for S78 -Hearing notify email upon sharing IP comments and Statements for both LPA and Appellant. "&#39;s" padding to the Subject.](https://pins-ds.atlassian.net/browse/A2-4433)

fix(appeals): issue with email subject line (a2-4433)

---

appeals/api/src/server/endpoints/link-appeals/__tests__/link-appeal.test.js
appeals/api/src/server/utils/blob-copy.js

- When not emulating blob storage, use the topic "appeal-document-to-move" to send an event to move the blobs between appeals
- Always use above even if using the blob emulator locally as the event itself will be mocked and displayed within the local api log for debugging purposes.
- Add unit tests to make sure event message is formatted correctly
- [A2-4408 - BO - Linked Appeal: Child Appeal cost documents duplicated in Lead Appeal is not viewable, ends up in error page)](https://pins-ds.atlassian.net/browse/A2-4408)

fix(appeals): use an event to move blobs between appeals (a2-4408) - patch for release

---

appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
appeals/web/src/server/lib/mappers/data/appeal/submappers/__tests__/case-officer.mapper.test.js
appeals/web/src/server/lib/mappers/data/appeal/submappers/case-officer.mapper.js

- Hide case officer change link in case details page when the appeal is a linked
child appeal
- Added unit test for above
- Make sure all other unit tests pass
- Tested within the browser
[A2-4462- BO linked appeals - Hide 'Change' CTA on 'Case officer' row which appears at top of 'Case details' on child appeal(s) (applies to all appeal types)](https://pins-ds.atlassian.net/browse/A2-4462)

fix(appeals): hide change link for case officer when child appeal (a2-4462)

---

appeals/api/src/server/endpoints/appeal-timetables/__tests__/appeal-timetables.test.js
appeals/api/src/server/endpoints/appeal-timetables/appeal-timetables.controller.js
appeals/api/src/server/endpoints/appeal-timetables/appeal-timetables.service.js
appeals/api/src/server/repositories/appeal-timetable.repository.js

- Update the timetable on child appeals when updating the timetable of a lead appeal
- Added unit test for above
[A2-4425- BO linked appeals - Changing due dates on the timetable on the lead appeal and it updates on the child appeal(s) (applies to all appeal types)](https://pins-ds.atlassian.net/browse/A2-4425)

feat(appeals): update timetable on child appeals (a2-4425)

---

appeals/web/src/server/appeals/appeal-details/inquiry/setup/__tests__/__snapshots__/set-up-inquiry.test.js.snap
appeals/web/src/server/appeals/appeal-details/inquiry/setup/__tests__/set-up-inquiry.test.js
appeals/web/src/server/appeals/appeal-details/inquiry/setup/set-up-inquiry.controller.js

When starting the case as inquiry user has to answer Yes or No to "do you know the estimated number of days" - when clicking back through the flow or clicking change on check your answers this value is not pre-populate.
I have fixed the bug . when a user click back through the flow, the data is now prepopulated.
https://pins-ds.atlassian.net/browse/A2-4146

fix(appeals): fixed the expected number of days prepopulate bug

---

appeals/api/src/server/endpoints/change-appeal-type/change-appeal-type.controller.js

Moving broadcast of appeal out of Promise.all block to ensure broadcast occurs after state transitions
[Ticket](https://pins-ds.atlassian.net/browse/A2-3882)

fix(api): amend broadcasting of appeal following transfer

---

appeals/api/src/server/endpoints/appeal-timetables/__tests__/appeal-timetables.test.js
appeals/api/src/server/endpoints/appeal-timetables/appeal-timetables.controller.js
appeals/api/src/server/endpoints/appeal-timetables/appeal-timetables.routes.js
appeals/api/src/server/endpoints/appeal-timetables/appeal-timetables.service.js
appeals/api/src/server/notify/templates/__tests__/appeal-valid-start-case-s78-lpa-hearing.test.js
appeals/api/src/server/notify/templates/appeal-valid-start-case-s78-lpa-hearing.content.md
appeals/api/src/server/openapi-types.ts
appeals/api/src/server/openapi.json
appeals/api/src/server/swagger.js
appeals/web/src/server/appeals/appeal-details/start-case/hearing/__tests__/start-case-hearing.test.js
appeals/web/src/server/appeals/appeal-details/start-case/hearing/hearing.controller.js
appeals/web/src/server/appeals/appeal-details/start-case/start-case.service.js

There were discrepancies in the formatting of the preview emails vs. the actualy emails that got sent out. I have added an API enpoint to generate the emails based on the same data that sent when starting a case, to make sure that we get the same result.
[A2-4273](https://pins-ds.atlassian.net/browse/A2-4273)
[A2-4273]: https://pins-ds.atlassian.net/browse/A2-4273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(appeals): generate start hearing case email previews on API side

---

appeals/api/src/server/notify/templates/__tests__/notify-decision-is-allowed-split-dismissed-appellant.test.js
appeals/api/src/server/notify/templates/__tests__/notify-decision-is-allowed-split-dismissed-lpa.test.js
appeals/api/src/server/notify/templates/decision-is-allowed-split-dismissed-appellant.content.md
appeals/api/src/server/notify/templates/decision-is-allowed-split-dismissed-lpa.content.md

- Update notifiy templates and tests to add (lead) to the lead appeal in the list of appeals
- Fixed unit tests for above
- Make sure all unit tests pass
[A2-4561 - Notify - Appeal ref missing '(lead)'](https://pins-ds.atlassian.net/browse/A2-4561)

fix(appeals): add lead in brackets after lead appeal in notify (a2-4561)

---

appeals/api/src/server/endpoints/appeal-timetables/appeal-timetables.service.js

I had an issue where the notify template names for starting an appeal were malformed and caused the back office to crash while testing locally.  This is because the appeal type did not exist in the mapping object used to build the template name.
This caused a template name of "appeal-valid-start-caseappellant" instead of the required "appeal-valid-start-case-appellant"
This fix will always build an existing template for s78 or otherwise.

fix(appeals): issue with malformed notify template name in timetable

---

infrastructure/database-monitoring.tf

As the Azure advanced threat protection is deprecated by Azure, It cannot be deployed to staging environment. Commenting or removing the terraform lines would delete already existing defenders in other environment. 
Hence adding a condition to not deploy if the environment is staging
[Ticket]()

fix(infrastructure): adding count condition for advanced threat protection

---

appeals/pdf-service-api/src/mappers/appellant-case/__tests__/__snapshots__/appellant-case.mapper.test.js.snap
appeals/pdf-service-api/src/mappers/appellant-case/appellant-case.mapper.js
appeals/pdf-service-api/src/mappers/appellant-case/sections/appeal-details.section.js
appeals/pdf-service-api/src/mappers/appellant-case/sections/application-details.section.js
appeals/pdf-service-api/src/mappers/appellant-case/sections/before-you-start.section.js
appeals/pdf-service-api/src/mappers/appellant-case/sections/site-details.section.js
appeals/pdf-service-api/src/mappers/appellant-case/sections/upload-documents.section.js

- Add before you start section to appellant case pdf and move some entries 
to this section
[A2-4540- BO - s78 appellant case PDF to reflect new content/format](https://pins-ds.atlassian.net/browse/A2-4540)

feat(appeals): pdf add before you start section (a2-4540)
