- azure-pipelines-deploy-appeals.yml
> ci: update deploy pipeline with variable group prefix

- azure-pipelines-build.yml
- azure-pipelines-package-function-merge.yml
> ci: tabs -> spaces to fix pipeline yaml

- azure-pipelines-deploy-appeals.yml
> ci: fix deploy pipeline source

- appeals/web/src/server/appeals/appeal-details/neighbouring-sites/neighbouring-sites.mapper.js
- appeals/web/src/server/appeals/appeal-details/neighbouring-sites/neighbouring-sites.service.js
> fix(appeals/web): some changes requested in PR for 695 that were missed

- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/other-appeals/__tests__/__snapshots__/other-appeals.test.js.snap
- appeals/web/src/server/appeals/appeal-details/other-appeals/__tests__/other-appeals.test.js
- appeals/web/src/server/appeals/appeal-details/other-appeals/other-appeals.controller.js
- appeals/web/src/server/appeals/appeal-details/other-appeals/other-appeals.mapper.js
- appeals/web/src/server/appeals/appeal-details/other-appeals/other-appeals.router.js
- appeals/web/src/server/appeals/appeal-details/other-appeals/other-appeals.validators.js
- appeals/web/src/server/appeals/appeal.constants.js
- appeals/web/src/server/lib/display-page-formatter.js
- appeals/web/src/server/lib/mappers/appeal.mapper.js
- appeals/web/src/server/lib/mappers/notification-banners.mapper.js
https://pins-ds.atlassian.net/browse/BOAT-664
also includes bugfix https://pins-ds.atlassian.net/browse/BOAT-1039
> feat(web): feature/BOAT-664-manage-related-appeals

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.router.js
fix lpaq add document details allowing future date
BOAT-764
> fix(web): fix lpaq add document details allowing future date

- appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.mapper.js
fix confirmation page for unchanged outcome of change site visit flow
BOAT-704
> fix(web): fix confirmation page for unchanged outcome of change site visit flow

- appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/manage-linked-appeals.controller.js
- appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/manage-linked-appeals.validators.js
- appeals/web/src/server/appeals/appeal-details/other-appeals/__tests__/__snapshots__/other-appeals.test.js.snap
- appeals/web/src/server/appeals/appeal-details/other-appeals/__tests__/other-appeals.test.js
- appeals/web/src/server/appeals/appeal-details/other-appeals/other-appeals.controller.js
- appeals/web/src/server/appeals/appeal-details/other-appeals/other-appeals.validators.js
add horizon down error page for linked and related appeals flows
BOAT-1089
> fix(web): add horizon down error page for linked and related appeals flows

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js
- appeals/web/src/server/lib/mappers/notification-banners.mapper.js
fix virus scan in progress notification banner URL on appellant case and lpaq pages
BOAT-1069
> fix(web): fix virus scan in progress notification banner URL on appellant case and lpaq pages

- .eslintignore
- .eslintrc.cjs
- appeals/web/jsconfig.json
- commitlint.config.cjs
Additional cleanup of unused and application-specific paths:
- commitlint
- jsonconfig
- eslintignore
- eslintrc
> chore(appeals): repo cleanup

- commitlint.config.cjs
- package.json
Simplified scopes for appeals-only repo.
Removed the appeals identifier from npm scripts
> chore(appeals): scopes and scripts

- appeals/api/src/database/schema.d.ts
- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
- appeals/api/src/server/endpoints/appeals/appeals.formatter.js
- appeals/api/src/server/openapi-types.ts
- appeals/api/src/server/swagger.js
- appeals/api/src/server/tests/appeals/mocks.js
- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.types.d.ts
- appeals/web/src/server/appeals/appeal-details/appeal-timetables/appeal-timetables.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-incomplete/outcome-incomplete.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-valid/outcome-valid.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-valid/outcome-valid.mapper.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-valid/outcome-valid.router.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-valid/outcome-valid.service.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-valid/outcome-valid.validators.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/outcome-incomplete/outcome-incomplete.controller.js
- appeals/web/src/server/lib/mappers/appeal.mapper.js
- appeals/web/src/server/lib/mappers/notification-banners.mapper.js
- appeals/web/src/server/views/appeals/appeal/update-date.njk
- appeals/web/testing/app/fixtures/referencedata.js
[BOAT-838](https://pins-ds.atlassian.net/browse/BOAT-838)
> feat(appeals/web): BOAT-838 Adding a valid date input page and 'Valid date' field to the validation journey for the appeal

- appeals/web/src/server/appeals/appeal-documents/appeal-documents.controller.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js
update change document details page to display only document being updated
BOAT-772
> fix(web): update change document details page to display only document being updated

- appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js
update manage document history items to show correct filename for each version
BOAT-817
> fix(web): update manage document history items to show correct filename for each version

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.mapper.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-incomplete/outcome-incomplete.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-incomplete/outcome-incomplete.router.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/outcome-incomplete/outcome-incomplete.controller.js
- appeals/web/src/server/views/appeals/appeal/update-date.njk
remove skip button and pre-populate due date in appellant case and lpaq incomplete flows
BOAT-1078
> fix(web): remove skip button and pre-populate due date in appellant case and lpaq incomplete flows

- appeals/web/src/server/app/auth/__tests__/__snapshots__/auth.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/__tests__/__snapshots__/manage-linked-appeals.test.js.snap
- appeals/web/src/server/appeals/national-list/__tests__/__snapshots__/national-list.test.js.snap
- appeals/web/src/server/appeals/personal-list/__tests__/__snapshots__/personal-list.test.js.snap
- appeals/web/src/server/views/app/components/global-header.njk
remove go to dashboard link from header
BOAT-1088
> fix(web): remove go to dashboard link from header

- appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/__snapshots__/issue-decision.test.js.snap
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.mapper.js
- appeals/web/src/server/appeals/personal-list/__tests__/__snapshots__/personal-list.test.js.snap
- appeals/web/src/server/appeals/personal-list/__tests__/personal-list.test.js
- appeals/web/src/server/appeals/personal-list/personal-list.mapper.js
- appeals/web/src/server/views/appeals/documents/decision-letter-upload.njk
issue decision flow content changes
BOAT-922
> fix(web): issue decision flow content changes

- appeals/api/src/server/repositories/appellant-case.repository.js
- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-valid/outcome-valid.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-valid/outcome-valid.service.js
[BOAT-838](https://pins-ds.atlassian.net/browse/BOAT-838)
> feat(appeals/web): BOAT-838 Update valid date input page to use Validation state

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/__tests__/__snapshots__/change-appeal-type.test.js.snap
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/__tests__/__snapshots__/manage-linked-appeals.test.js.snap
- appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/__tests__/manage-linked-appeals.test.js
- appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/manage-linked-appeals.mapper.js
- appeals/web/src/server/appeals/appeal-details/other-appeals/__tests__/__snapshots__/other-appeals.test.js.snap
- appeals/web/src/server/appeals/appeal-details/other-appeals/other-appeals.mapper.js
- appeals/web/src/server/appeals/national-list/__tests__/__snapshots__/national-list.test.js.snap
- appeals/web/src/server/appeals/national-list/national-list.mapper.js
- appeals/web/src/server/lib/mappers/appeal.mapper.js
- appeals/web/src/server/lib/mappers/appellantCase.mapper.js
- appeals/web/src/server/views/appeals/components/appeals-table.njk
content changed to align wording used for local planning authority
BOAT-850
> fix(web): content changed to align wording used for local planning authority

- appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js
- appeals/web/src/server/views/app/layouts/app.layout.njk
- appeals/web/src/server/views/appeals/appeal/appellant-case-invalid-incomplete.njk
- appeals/web/src/server/views/appeals/appeal/assign-new-user.njk
- appeals/web/src/server/views/appeals/appeal/assign-user.njk
- appeals/web/src/server/views/appeals/appeal/audit.njk
- appeals/web/src/server/views/appeals/appeal/confirm-assign-unassign-user.njk
- appeals/web/src/server/views/appeals/appeal/issue-decision.njk
- appeals/web/src/server/views/appeals/appeal/lpa-questionnaire-incomplete.njk
- appeals/web/src/server/views/appeals/appeal/schedule-site-visit.njk
- appeals/web/src/server/views/appeals/appeal/set-site-visit-type.njk
- appeals/web/src/server/views/appeals/appeal/site-visit-booked.njk
- appeals/web/src/server/views/appeals/appeal/update-date.njk
- appeals/web/src/server/views/appeals/confirmation.njk
- appeals/web/src/server/views/appeals/documents/add-document-details.njk
- appeals/web/src/server/views/appeals/documents/delete-document.njk
- appeals/web/src/server/views/appeals/documents/document-upload.njk
- appeals/web/src/server/views/appeals/documents/manage-document.njk
- appeals/web/src/server/views/appeals/documents/manage-folder.njk
- appeals/web/src/server/views/patterns/change-page.pattern.njk
- appeals/web/src/server/views/patterns/check-and-confirm-page.pattern.njk
- appeals/web/src/server/views/patterns/display-page.pattern.njk
global update to page title service name
BOAT-1145
> fix(web): global update to page title service name

- appeals/api/src/server/endpoints/appeal-timetables/appeal-timetables.routes.js
- appeals/api/src/server/endpoints/appeals/appeals.routes.js
- appeals/api/src/server/openapi-types.ts
- appeals/api/src/server/openapi.json
- appeals/api/src/server/swagger.js
Changes to API definitions after introducing the VALIDATION state
> fix(api): tidy up swagger definitions after changing flows

- appeals/api/src/server/endpoints/appeal-timetables/appeal-timetables.validators.js
- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.router.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.mapper.js
- appeals/web/src/server/appeals/appeal-details/start-case/__tests__/__snapshots__/start-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/start-case/__tests__/start-case.test.js
- appeals/web/src/server/appeals/appeal-details/start-case/start-case.controller.js
- appeals/web/src/server/appeals/appeal-details/start-case/start-case.mapper.js
- appeals/web/src/server/appeals/appeal-details/start-case/start-case.router.js
- appeals/web/src/server/appeals/appeal-details/start-case/start-case.service.js
- appeals/web/src/server/lib/mappers/appeal.mapper.js
> feat(web): feature/BOAT-851-start-case-date-flow

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
> fix(web): bugfix/BOAT-831-not-banner-fix

- appeals/api/src/server/endpoints/appeal-timetables/appeal-timetables.controller.js
Quick fix for the API, when setting a start date to create a timetable...
It was creating the timetable but not setting the `startedAt` field.
> fix(api): setting the start date

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-valid/outcome-valid.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-valid/outcome-valid.mapper.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-valid/outcome-valid.validators.js
[BOAT-838](https://pins-ds.atlassian.net/browse/BOAT-838)
> feat(appeals/web): BOAT-838 Update valid date input page to show date incorrect date values in the form fields when validation flags an error 

- appeals/api/src/server/endpoints/site-visits/__tests__/site-visits.test.js
- appeals/api/src/server/endpoints/site-visits/site-visits.controller.js
- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/site-visit.test.js
[BOAT-634](https://pins-ds.atlassian.net/browse/BOAT-634)
> fix(api): BOAT-634 visit times for rescheduled visits

- appeals/web/src/server/appeals/appeal-details/appeal-details.middleware.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.router.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.service.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-incomplete/outcome-incomplete.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-incomplete/outcome-incomplete.router.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-invalid/outcome-invalid.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-invalid/outcome-invalid.router.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-valid/outcome-valid.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-valid/outcome-valid.router.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.controller.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.router.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/outcome-incomplete/outcome-incomplete.controller.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/outcome-incomplete/outcome-incomplete.router.js
- appeals/web/src/server/appeals/appeal-details/start-case/start-case.service.js
- appeals/web/src/server/appeals/appeal-documents/__tests__/appeal-documents.test.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.controller.js
- appeals/web/testing/app/fixtures/referencedata.js
- appeals/web/testing/appeals/mocks/api.js
refactor appellant case code to remove unnecessary session usage
BOAT-1143
> refactor(web): refactor appellant case code to remove unnecessary session usage

- appeals/web/src/server/appeals/appeal-details/assign-user/__tests__/__snapshots__/assign-user.test.js.snap
- appeals/web/src/server/appeals/appeal-details/assign-user/__tests__/assign-user.test.js
- appeals/web/src/server/appeals/appeal-details/assign-user/assign-user.mapper.js
[BOAT-963](https://pins-ds.atlassian.net/browse/BOAT-963)
> fix(web): BOAT-963 Amend text to "no matches for [string]" where no results returned in case officer search

- appeals/web/src/client/components/file-uploader/_client-actions.js
- appeals/web/src/client/components/file-uploader/_errors.js
- appeals/web/src/client/components/file-uploader/_html.js
- appeals/web/src/client/components/files-list/files-list.module.js
[BOAT-999](https://pins-ds.atlassian.net/browse/BOAT-999)
> fix(web): BOAT-999 Document upload DOM text

- appeals/web/src/server/appeals/appeal-details/assign-user/__tests__/__snapshots__/assign-user.test.js.snap
- appeals/web/src/server/appeals/appeal-details/assign-user/assign-user.mapper.js
- appeals/web/src/server/appeals/appeal-details/assign-user/assign-user.validator.js
- appeals/web/src/server/views/appeals/appeal/confirm-assign-unassign-user.njk
[BOAT-967](https://pins-ds.atlassian.net/browse/BOAT-967)
> feat(web): BOAT-967 Content Updates - Search For A Case Officer

- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.router.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.types.d.ts
- appeals/web/src/server/appeals/appeal-details/neighbouring-sites/neighbouring-sites.mapper.js
- appeals/web/src/server/appeals/appeal-details/service-user/__tests__/__snapshots__/service-user.test.js.snap
- appeals/web/src/server/appeals/appeal-details/service-user/__tests__/service-user.test.js
- appeals/web/src/server/appeals/appeal-details/service-user/service-user.controller.js
- appeals/web/src/server/appeals/appeal-details/service-user/service-user.mapper.js
- appeals/web/src/server/appeals/appeal-details/service-user/service-user.router.js
- appeals/web/src/server/appeals/appeal-details/service-user/service-user.service.js
- appeals/web/src/server/appeals/appeal-details/service-user/service-user.validators.js
- appeals/web/src/server/lib/error-handlers/__tests__/error-handlers.test.js
- appeals/web/src/server/lib/error-handlers/change-screen-error-handlers.js
- appeals/web/src/server/lib/mappers/appeal.mapper.js
- appeals/web/src/server/lib/mappers/notification-banners.mapper.js
- appeals/web/testing/app/fixtures/referencedata.js
https://pins-ds.atlassian.net/browse/BOAT-1109
> feat(web): add agent and appellant change screens

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.mapper.js
- appeals/web/src/server/appeals/appeal-details/start-case/__tests__/start-case.test.js
- appeals/web/src/server/appeals/appeal-details/start-case/start-case.controller.js
- appeals/web/src/server/appeals/appeal-details/start-case/start-case.router.js
- appeals/web/src/server/lib/mappers/appeal.mapper.js
BOAT-851
disable change start date journey as this will be addressed in a separate ticket
> feat(web): feature/BOAT-851-disable-change-journey

- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
- appeals/api/src/server/endpoints/appeals/appeals.controller.js
- appeals/api/src/server/endpoints/appeals/appeals.validators.js
- appeals/api/src/server/repositories/appeal.repository.js
- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.router.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.router.js
- appeals/web/src/server/appeals/appeal-details/change-lpa-reference/__tests__/__snapshots__/change-lpa-reference.test.js.snap
- appeals/web/src/server/appeals/appeal-details/change-lpa-reference/__tests__/change-lpa-reference.test.js
- appeals/web/src/server/appeals/appeal-details/change-lpa-reference/change-lpa-reference.controller.js
- appeals/web/src/server/appeals/appeal-details/change-lpa-reference/change-lpa-reference.mapper.js
- appeals/web/src/server/appeals/appeal-details/change-lpa-reference/change-lpa-reference.router.js
- appeals/web/src/server/appeals/appeal-details/change-lpa-reference/change-lpa-reference.service.js
- appeals/web/src/server/appeals/appeal-details/change-lpa-reference/change-lpa-reference.validators.js
- appeals/web/src/server/lib/error-handlers/change-screen-error-handlers.js
- appeals/web/src/server/lib/mappers/appeal.mapper.js
- appeals/web/src/server/lib/mappers/appellantCase.mapper.js
- appeals/web/src/server/lib/mappers/notification-banners.mapper.js
https://pins-ds.atlassian.net/browse/BOAT-1111
> feat(appeals): add lpa reference change page and api

- appeals/web/src/server/appeals/appeal-details/other-appeals/__tests__/__snapshots__/other-appeals.test.js.snap
- appeals/web/src/server/appeals/appeal-details/other-appeals/other-appeals.mapper.js
> feat(web): feature/BOAT-1128-copy-update

- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.router.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/costs/__tests__/__snapshots__/costs.test.js.snap
- appeals/web/src/server/appeals/appeal-details/costs/__tests__/costs.test.js
- appeals/web/src/server/appeals/appeal-details/costs/costs.controller.js
- appeals/web/src/server/appeals/appeal-details/costs/costs.mapper.js
- appeals/web/src/server/appeals/appeal-details/costs/costs.router.js
- appeals/web/src/server/appeals/appeal-details/costs/costs.validators.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/other-appeals/other-appeals.validators.js
- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap
- appeals/web/src/server/appeals/appeal-documents/__tests__/__snapshots__/appeal-documents.test.js.snap
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.controller.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js
- appeals/web/src/server/lib/mappers/appeal.mapper.js
- appeals/web/src/server/lib/mappers/notification-banners.mapper.js
- appeals/web/src/server/lib/session-utilities.js
- appeals/web/src/server/views/appeals/documents/document-upload.njk
- appeals/web/testing/app/fixtures/referencedata.js
> feat(web): BOAT-837 - costs - journey 1

- appeals/api/package.json
- appeals/api/src/server/endpoints/constants.js
- appeals/api/src/server/endpoints/integrations/integrations.controller.js
- appeals/api/src/server/endpoints/integrations/integrations.mappers/service-user.mapper.js
- appeals/api/src/server/endpoints/integrations/integrations.service.js
- package-lock.json
- package.json
Service user entity broadcasting
Dependency on shared data model repo
> feat(api): odw Service User entity refactoring

- .vscode/extensions.json
- .vscode/settings.json
> feat(tooling): add jest-runner extension and settings

- appeals/api/src/database/schema.d.ts
- appeals/api/src/database/seed/data-samples.js
- appeals/api/src/server/repositories/appeal.repository.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.types.d.ts
Removed incorrect references to data that no longer exists in DB (neighbouringSiteContacts)
> fix(appeals): remove historic neighbouring site code

- appeals/api/src/server/endpoints/audit-trails/__tests__/audit-trails.test.js
- appeals/api/src/server/endpoints/constants.js
- appeals/api/src/server/endpoints/documents/__tests__/documents.test.js
- appeals/api/src/server/endpoints/documents/documents.controller.js
- appeals/api/src/server/tests/appeals/mocks.js
[BOAT-1058](https://pins-ds.atlassian.net/browse/BOAT-1058)
> BOAT-1058 API - Create audit event document copy update

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js
label update for LPA on appellant case and lpaq pages
BOAT-850
> fix(web): label update for LPA on appellant case and lpaq pages

- appeals/api/src/database/schema.d.ts
- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/appeals/appeals.formatter.js
- appeals/api/src/server/endpoints/constants.js
- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
- appeals/web/src/server/appeals/appeal-details/costs/__tests__/__snapshots__/costs.test.js.snap
- appeals/web/src/server/appeals/appeal-details/costs/__tests__/costs.test.js
- appeals/web/src/server/appeals/appeal-details/costs/costs.controller.js
- appeals/web/src/server/appeals/appeal-details/costs/costs.mapper.js
- appeals/web/src/server/appeals/appeal-details/costs/costs.router.js
- appeals/web/src/server/appeals/appeal-details/costs/costs.validators.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/__snapshots__/issue-decision.test.js.snap
- appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/issue-decision.test.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.mapper.js
- appeals/web/src/server/lib/mappers/appeal.mapper.js
- appeals/web/testing/app/fixtures/referencedata.js
> feat(appeals): costs journey 3

- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
- appeals/api/src/server/endpoints/appeals/appeals.formatter.js
- appeals/api/src/server/tests/appeals/mocks.js
- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.mapper.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.router.js
- appeals/web/src/server/appeals/appeal-details/service-user/__tests__/__snapshots__/service-user.test.js.snap
- appeals/web/src/server/appeals/appeal-details/service-user/__tests__/service-user.test.js
- appeals/web/src/server/appeals/appeal-details/service-user/service-user.controller.js
- appeals/web/src/server/appeals/appeal-details/service-user/service-user.mapper.js
- appeals/web/src/server/appeals/appeal-details/service-user/service-user.service.js
- appeals/web/src/server/appeals/appeal-details/service-user/service-user.validators.js
- appeals/web/src/server/lib/error-handlers/change-screen-error-handlers.js
- appeals/web/src/server/lib/mappers/appeal.mapper.js
- appeals/web/src/server/lib/mappers/appellantCase.mapper.js
- appeals/web/src/server/lib/service-user-formatter.js
- appeals/web/testing/app/fixtures/referencedata.js
> feat(appeals): add service user to appellant case

- appeals/api/src/server/endpoints/documents/__tests__/documents.test.js
- appeals/api/src/server/endpoints/documents/documents.controller.js
[BOAT-1058](https://pins-ds.atlassian.net/browse/BOAT-1058)
> BOAT-1058 API - Create audit event (received date fix) 

- appeals/web/src/server/app/auth/__tests__/__snapshots__/auth.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/__snapshots__/issue-decision.test.js.snap
- appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/issue-decision.test.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.mapper.js
- appeals/web/src/server/appeals/appeal-details/manage-linked-appeals/__tests__/__snapshots__/manage-linked-appeals.test.js.snap
- appeals/web/src/server/appeals/appeals.router.js
- appeals/web/src/server/appeals/national-list/__tests__/__snapshots__/national-list.test.js.snap
- appeals/web/src/server/appeals/national-list/__tests__/national-list.test.js
- appeals/web/src/server/appeals/personal-list/__tests__/__snapshots__/personal-list.test.js.snap
- appeals/web/src/server/appeals/personal-list/personal-list.mapper.js
- appeals/web/src/server/lib/__tests__/libraries.test.js
- appeals/web/src/server/views/app/components/global-header.njk
- appeals/web/src/server/views/app/dashboard.njk
- appeals/web/src/server/views/appeals/all-appeals/dashboard.njk
amend URL pathway on appeal list to appeals-service/all-cases
BOAT-949
> fix(web): amend URL pathway on appeal list to appeals-service/all-cases

- azure-pipelines-ci.yml
> feat(tooling): put excluded trigger in to not run PR for infra changes

- appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
- appeals/api/src/server/endpoints/appeals/appeals.formatter.js
- appeals/web/src/server/appeals/appeal-details/address/__tests__/__snapshots__/address.test.js.snap
- appeals/web/src/server/appeals/appeal-details/address/__tests__/address.test.js
- appeals/web/src/server/appeals/appeal-details/address/address.controller.js
- appeals/web/src/server/appeals/appeal-details/address/address.mapper.js
- appeals/web/src/server/appeals/appeal-details/address/address.router.js
- appeals/web/src/server/appeals/appeal-details/address/address.service.js
- appeals/web/src/server/appeals/appeal-details/address/address.validator.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.router.js
- appeals/web/src/server/appeals/appeal-details/neighbouring-sites/neighbouring-sites.router.js
- appeals/web/src/server/appeals/appeal-details/neighbouring-sites/neighbouring-sites.validators.js
- appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.mapper.js
- appeals/web/src/server/lib/mappers/appellantCase.mapper.js
- appeals/web/src/server/lib/mappers/notification-banners.mapper.js
- appeals/web/src/server/lib/validators/postcode.validator.js
- appeals/web/testing/app/fixtures/referencedata.js
- packages/appeals/types/appeal.d.ts
Add change page for site address in appellant case
https://pins-ds.atlassian.net/browse/BOAT-1202
> feat(appeals): add change page for site address

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.mapper.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.router.js
- appeals/web/src/server/appeals/appeal-details/site-ownership/__tests__/__snapshots__/site-ownership.test.js.snap
- appeals/web/src/server/appeals/appeal-details/site-ownership/__tests__/site-ownership.test.js
- appeals/web/src/server/appeals/appeal-details/site-ownership/site-ownership.controller.js
- appeals/web/src/server/appeals/appeal-details/site-ownership/site-ownership.mapper.js
- appeals/web/src/server/appeals/appeal-details/site-ownership/site-ownership.router.js
- appeals/web/src/server/appeals/appeal-details/site-ownership/site-ownership.service.js
- appeals/web/src/server/lib/mappers/appellantCase.mapper.js
- appeals/web/src/server/lib/mappers/notification-banners.mapper.js
https://pins-ds.atlassian.net/browse/BOAT-768
> feat(appeals): add site ownership change page

- appeals/web/package.json
- package-lock.json
> chore(appeals): Review and address dependabot Axios Cross-Site Request Forgery Vulnerability

- appeals/web/src/client/components/file-uploader/_html.js
fix file upload component remove button
BOAT-1187
> fix(web): fix file upload component remove button

- appeals/web/src/client/components/file-uploader/_client-actions.js
fix file upload component allowing multiple files when configured as single file only
BOAT-1169
> fix(web): fix file upload component allowing multiple files when configured as single file only

- appeals/api/src/server/endpoints/documents/__tests__/documents.test.js
- appeals/api/src/server/endpoints/documents/documents.formatter.js
- appeals/api/src/server/tests/documents/mocks.js
- appeals/web/src/server/appeals/appeal-details/costs/__tests__/__snapshots__/costs.test.js.snap
- appeals/web/src/server/appeals/appeal-details/costs/costs.controller.js
- appeals/web/src/server/appeals/appeal-details/costs/costs.mapper.js
[BOAT-1184](https://pins-ds.atlassian.net/browse/BOAT-1184)
> feat(web): BOAT-1184 store and return documentType value for documents submitted using file upload component

- appeals/api/src/server/endpoints/constants.js
- appeals/api/src/server/endpoints/site-visits/__tests__/site-visits.test.js
- appeals/api/src/server/endpoints/site-visits/site-visits.validators.js
- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap
- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/site-visit.test.js
- appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.service.js
- appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.validators.js
updates to make end time optional for accompanied site visit type
BOAT-1175
> feat(appeals): updates to make end time optional for accompanied site visit type

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/costs/__tests__/__snapshots__/costs.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/views/appeals/documents/manage-document.njk
- appeals/web/src/server/views/appeals/documents/manage-folder.njk
reduce heading margin on manage folder and manage document pages
BOAT-832
> fix(web): reduce heading margin on manage folder and manage document pages

- .gitignore
- commitlint.config.cjs
- infrastructure/.tflint.hcl
- infrastructure/README.md
- infrastructure/environments/dev.tfvars
- infrastructure/environments/prod.tfvars
- infrastructure/environments/test.tfvars
- infrastructure/local.tf
- infrastructure/main.tf
- infrastructure/pipelines/terraform-cd.yaml
- infrastructure/pipelines/terraform-ci.yaml
- infrastructure/provider.tf
- infrastructure/variables.tf
https://pins-ds.atlassian.net/browse/DEV-232
> feat(infrastructure): initial terraform project and pipelines

- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.controller.js
- appeals/api/src/server/repositories/lpa-questionnaire.repository.js
- appeals/web/src/server/appeals/appeal-details/correct-appeal-type/__tests__/__snapshots__/correct-appeal-type.test.js.snap
- appeals/web/src/server/appeals/appeal-details/correct-appeal-type/__tests__/correct-appeal-type.test.js
- appeals/web/src/server/appeals/appeal-details/correct-appeal-type/correct-appeal-type.controller.js
- appeals/web/src/server/appeals/appeal-details/correct-appeal-type/correct-appeal-type.mapper.js
- appeals/web/src/server/appeals/appeal-details/correct-appeal-type/correct-appeal-type.router.js
- appeals/web/src/server/appeals/appeal-details/correct-appeal-type/correct-appeal-type.service.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.router.js
- appeals/web/src/server/lib/mappers/lpaQuestionnaire.mapper.js
- appeals/web/src/server/lib/mappers/notification-banners.mapper.js
https://pins-ds.atlassian.net/browse/BOAT-1224
> feat(appeals): add change page for is correct appeal type

- infrastructure/data.tf
- infrastructure/local.tf
- infrastructure/main.tf
- infrastructure/monitoring.tf
- infrastructure/variables.tf
https://pins-ds.atlassian.net/browse/DEV-180
To be merged after #60
> feat(infrastructure): core resources

- infrastructure/environments/dev.tfvars
- infrastructure/environments/prod.tfvars
- infrastructure/environments/test.tfvars
- infrastructure/local.tf
- infrastructure/main.tf
- infrastructure/networking-secondary.tf
- infrastructure/networking.tf
- infrastructure/pipelines/terraform-cd.yaml
- infrastructure/variables.tf
https://pins-ds.atlassian.net/browse/DEV-233
> feat(infrastructure): secondary network

- infrastructure/networking-secondary.tf
> fix(infrastructure): private DNS zones are in the primary resource group

- infrastructure/data.tf
- infrastructure/database-monitoring.tf
- infrastructure/database-secondary.tf
- infrastructure/database.tf
- infrastructure/environments/dev.tfvars
- infrastructure/environments/prod.tfvars
- infrastructure/environments/test.tfvars
- infrastructure/local.tf
- infrastructure/variables.tf
https://pins-ds.atlassian.net/browse/DEV-181
> feat(infrastructure): database resources

- infrastructure/data.tf
- infrastructure/database.tf
- infrastructure/document-storage.tf
- infrastructure/environments/dev.tfvars
- infrastructure/environments/prod.tfvars
- infrastructure/environments/test.tfvars
- infrastructure/variables.tf
https://pins-ds.atlassian.net/browse/DEV-183
+ a small fix for the DB
> feat(infastructure): document storage resources

- infrastructure/data.tf
- infrastructure/database-monitoring.tf
- infrastructure/environments/dev.tfvars
- infrastructure/environments/prod.tfvars
- infrastructure/environments/test.tfvars
- infrastructure/local.tf
- infrastructure/service-bus-alerts.tf
- infrastructure/service-bus.tf
- infrastructure/terraform.tfvars
- infrastructure/variables.tf
https://pins-ds.atlassian.net/browse/DEV-184
> feat(infrastructure): add service-bus resources

- infrastructure/data.tf
- infrastructure/database-monitoring.tf
- infrastructure/document-storage.tf
Last merge to main had some issues on apply
https://dev.azure.com/planninginspectorate/appeals-back-office/_build/results?buildId=82119&view=logs&j=7c7b2450-8bce-52ef-39a6-dd12dfcbbdfc&t=9e596af9-2782-5afc-e1e1-f758964ee6a3
> infrastructure fixes

- infrastructure/document-storage.tf
- infrastructure/service-bus.tf
Apply issues on the last merge to main:
https://dev.azure.com/planninginspectorate/appeals-back-office/_build/results?buildId=82161&view=logs&j=7c7b2450-8bce-52ef-39a6-dd12dfcbbdfc&t=9e596af9-2782-5afc-e1e1-f758964ee6a3
> infrastructure fixes (take 2)

- appeals/web/src/server/appeals/appeal-details/costs/__tests__/__snapshots__/costs.test.js.snap
- appeals/web/src/server/appeals/appeal-details/costs/__tests__/costs.test.js
- appeals/web/src/server/appeals/appeal-details/costs/costs.controller.js
- appeals/web/src/server/appeals/appeal-details/costs/costs.router.js
- appeals/web/testing/app/fixtures/referencedata.js
fix back link from costs add document details page in upload updated version flow
BOAT-1194
> fix(web): fix back link from costs add document details page in upload updated version flow

- infrastructure/app-api.tf
- infrastructure/app-service-plan.tf
- infrastructure/app-web-redis.tf
- infrastructure/app-web.tf
- infrastructure/database.tf
- infrastructure/environments/dev.tfvars
- infrastructure/environments/prod.tfvars
- infrastructure/environments/test.tfvars
- infrastructure/local.tf
- infrastructure/terraform.tfvars
- infrastructure/variables.tf
https://pins-ds.atlassian.net/browse/DEV-206
App services (API + web)
> feat(infrastructure): app service resources

- infrastructure/document-storage.tf
Quick fix to avoid phantom terraform changes with template deployment
> fix(infrastructure): template type case fixes

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.mapper.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-invalid/outcome-invalid.mapper.js
content updates to appellant case review invalid flow
BOAT-1126
> fix(web): content updates to appellant case review invalid flow

- infrastructure/app-api.tf
- infrastructure/environments/dev.tfvars
- infrastructure/environments/prod.tfvars
- infrastructure/environments/test.tfvars
- infrastructure/function-casedata-import.tf
- infrastructure/function-doc-processing.tf
- infrastructure/function-scheduled-jobs.tf
- infrastructure/function-user-import.tf
- infrastructure/function.tf
- infrastructure/local.tf
- infrastructure/variables.tf
https://pins-ds.atlassian.net/browse/DEV-206
> feat(infrastructure): function apps

- infrastructure/networking.tf
Fixes for latest apply, missed delegation on the subnet for the app services.
> fix(infrastructure): add delegation to subnet

- infrastructure/app-api.tf
- infrastructure/app-web.tf
- infrastructure/environments/dev.tfvars
- infrastructure/environments/prod.tfvars
- infrastructure/environments/test.tfvars
- infrastructure/networking-secondary.tf
- infrastructure/networking.tf
- infrastructure/variables.tf
Additionally subnet for App Services.
> fix(infrastructure): separate subnets for apps and other resources

- infrastructure/function-casedata-import.tf
- infrastructure/function-doc-processing.tf
- infrastructure/function-scheduled-jobs.tf
- infrastructure/function-user-import.tf
> fix(infrastructure): link functions to apps subnet

- azure-pipelines-build.yml
Excludes changes to `infrastructure` when triggering a build
> fix(tooling): exclude infrastructure changes from build trigger

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
Replaced 'Details' with 'Site'
[BOAT-1236](https://pins-ds.atlassian.net/browse/BOAT-1236)
> fix(web): content fix (Details -> Site)

- appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/__snapshots__/issue-decision.test.js.snap
- appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/issue-decision.test.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.mapper.js
content updates to issue decision flow
BOAT-1137
> fix(web): content updates to issue decision flow

- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js
- appeals/web/src/server/views/patterns/display-page.pattern.njk
content updates to lpaq review complete flow
BOAT-1125
> fix(web): content updates to lpaq review complete flow

- appeals/web/src/server/appeals/appeal-details/change-appeal-type/__tests__/__snapshots__/change-appeal-type.test.js.snap
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.mapper.js
content updates to change appeal type flow
BOAT-1123
> fix(web): content updates to change appeal type flow

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-valid/outcome-valid.mapper.js
content updates to appellant case valid flow
BOAT-1120
> fix(web): content updates to appellant case valid flow

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-incomplete/outcome-incomplete.mapper.js
content updates to appellant case incomplete flow
BOAT-1118
> fix(web): content updates to appellant case incomplete flow

- appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/__snapshots__/issue-decision.test.js.snap
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.mapper.js
content updates to issue decision invalid journey + small refactoring
BOAT-1138
> fix(web): content updates to issue decision invalid journey + small refactoring

- infrastructure/app-api.tf
- infrastructure/app-web-redis.tf
- infrastructure/app-web.tf
- infrastructure/database-secondary.tf
- infrastructure/database.tf
- infrastructure/networking-secondary.tf
- infrastructure/networking.tf
- infrastructure/service-bus.tf
> fix(infrastructure): use common private DNS zones

- azure-pipelines-deploy-appeals.yml
- azure-pipelines-variables.yml
Deploy apps + functions to both existing and new App Services.
> feat(cd): deploy to new app services

- infrastructure/networking-secondary.tf
- infrastructure/networking.tf
> fix(infrastructure): use resource group of the private dns zone

- infrastructure/environments/dev.tfvars
> chore(infrastructure): add dev horizon api config

- appeals/api/src/server/config/config.js
> fix(api): log only error details for configuration failures

- infrastructure/networking-secondary.tf
- infrastructure/networking.tf
> fix(infrastructure): use tooling provider for vnet links

- appeals/api/setup-tests.js
- appeals/api/src/server/config/config.js
- appeals/api/src/server/config/schema.js
- appeals/api/src/server/endpoints/addresses/__tests__/addresses.test.js
- appeals/api/src/server/endpoints/addresses/addresses.formatter.js
- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/appellant-cases/__tests__/appellant-cases.test.js
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.controller.js
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.service.js
- appeals/api/src/server/endpoints/constants.js
[BOAT-926](https://pins-ds.atlassian.net/browse/BOAT-926)
> BOAT-926 API - Comms - Applicant Case Review - All appeal case documentation received - 'valid date' added

- infrastructure/database-secondary.tf
- infrastructure/database.tf
> fix(infrastructure): use random id with prefix

- azure-pipelines-db-seed-appeals-production.yml
- azure-pipelines-db-seed-appeals.yml
- azure-pipelines-deploy-appeals.yml
> chore(tooling): setup migration and seed for new db

- infrastructure/app-web.tf
> fix(infrastrucutre): API_HOST must be a valid URI

- infrastructure/app-api.tf
> fix(infrastructure): give the api service bus send permissions

- infrastructure/environments/test.tfvars
- infrastructure/function-casedata-import.tf
- infrastructure/function-doc-processing.tf
- infrastructure/function-scheduled-jobs.tf
- infrastructure/function-user-import.tf
Fixes to enable infrastructure deployment to TEST.
> fix(infrastructure): test setup

- azure-pipelines-deploy-appeals.yml
New infrastructure default deployments go to UK South Azure region
> feat(tooling): deploys to UK-South region by default

- infrastructure/service-bus.tf
> fix(infrastructure): service bus premium requires one partition

- infrastructure/app-api.tf
> fix(infrastructure): can't create a private endpoint on a delegated subnet

- infrastructure/document-storage.tf
> fix(infrasutructure): give entra groups access to blob storage

- azure-pipelines-db-seed-appeals-production.yml
- azure-pipelines-db-seed-appeals.yml
> fix(tooling): seed template references

- appeals/functions/document-processing/malware-detection/index.js
Infrastructure change - name of the doc container
> fix(functions/docs): changed name of container

- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.service.js
Stops writing the full error to the log (including recipient email), if notification fails
> fix(api): remove PII disclosure from gov notify log

- azure-pipelines-db-seed-appeals-production.yml
- azure-pipelines-db-seed-appeals.yml
- azure-pipelines-deploy-appeals.yml
- azure-pipelines-variables.yml
- infrastructure/environments/prod.tfvars
We only need to deploy to the new app services now, the old ones will be removed in time.
> chore(tooling): only deploy to new resources

- infrastructure/app-web.tf
> feat(infrastructure): add retry config for web

- appeals/web/src/server/appeals/appeal-details/appeal-details.router.js
Missed middleware in audit router
> fix(web): appeal audit routes

- appeals/api/package.json
- appeals/api/src/server/endpoints/constants.js
- appeals/api/src/server/utils/notify-client.js
- package-lock.json
adding additional logging around the notifications-node-client
> chore(appeals): gov notify client error logging

- infrastructure/service-bus.tf
- infrastructure/terraform.tfvars
- infrastructure/variables.tf
> feat(infrastructure): add appeal event topic

- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/outcome-incomplete/outcome-incomplete.mapper.js
Extra space removed
[BOAT-1124](https://pins-ds.atlassian.net/browse/BOAT-1124)
> fix(web): extra space removed

- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/site-visits/site-visits.controller.js
- appeals/api/src/server/endpoints/site-visits/site-visits.routes.js
- appeals/api/src/server/endpoints/site-visits/site-visits.service.js
- appeals/api/src/server/openapi-types.ts
- appeals/api/src/server/openapi.json
- appeals/api/src/server/swagger.js
- appeals/web/src/client/components/file-uploader/_client-actions.js
[BOAT-928](https://pins-ds.atlassian.net/browse/BOAT-928)
> BOAT-928 Comms - site visit type changes add previousVisitType

- infrastructure/environments/dev.tfvars
- infrastructure/environments/prod.tfvars
- infrastructure/environments/test.tfvars
> task(tooling): fixing variable issues on environment

- infrastructure/service-bus.tf
- infrastructure/terraform.tfvars
- infrastructure/variables.tf
Adding `listed-buildings` topic in, which is used by Front Office.
> feat(infrastructure): add listed-building topic for front office

- infrastructure/environments/prod.tfvars
As per https://pins-ds.atlassian.net/wiki/spaces/BO/pages/1555988484/Entra+Groups
No longer using distribution groups, Security groups only.
> chore(infrastructure): update prod entra groups

- appeals/api/src/server/endpoints/documents/documents.service.js
- appeals/api/src/server/endpoints/integrations/integrations.broadcasters/documents.js
- appeals/api/src/server/endpoints/integrations/integrations.mappers/document.mapper.js
- appeals/api/src/server/utils/database-connector.js
Broadcast a DELETE type of event for when a document version (including last version) is deleted.
> feat(appeals): document delete broadcast

- infrastructure/document-storage.tf
- infrastructure/environments/dev.tfvars
- infrastructure/environments/prod.tfvars
- infrastructure/environments/test.tfvars
- infrastructure/local.tf
- infrastructure/variables.tf
https://pins-ds.atlassian.net/browse/DEV-242
> chore(infrastructure): set storage account replication type per env

- infrastructure/front-door-web.tf
add managed rules to frontdoor firewall
> chore(infrastructure): add managed rules to frontdoor firewall

- appeals/api/src/database/seed/data-samples.js
- appeals/api/src/server/config/config.js
- appeals/api/src/server/config/schema.js
- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/site-visits/__tests__/site-visits.test.js
- appeals/api/src/server/endpoints/site-visits/site-visits.controller.js
- appeals/api/src/server/endpoints/site-visits/site-visits.service.js
- appeals/api/src/server/tests/appeals/mocks.js
[BOAT-928](https://pins-ds.atlassian.net/browse/BOAT-928)
> BOAT-928 API - Comms - Site visit type changes

- appeals/api/src/server/config/config.js
- appeals/api/src/server/config/schema.js
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.service.js
- appeals/api/src/server/endpoints/invalid-appeal-decision/__tests__/invalid-appeal-decision.test.js
- appeals/api/src/server/endpoints/invalid-appeal-decision/invalid-appeal-decision.controller.js
- appeals/api/src/server/endpoints/invalid-appeal-decision/invalid-appeal-decision.service.js
> BOAT880-feat(api): add invalid appeal decision notify LPA and appellant

- appeals/api/src/server/endpoints/site-visits/site-visits.service.js
- appeals/api/src/server/utils/__tests__/string-utils.test.js
- appeals/api/src/server/utils/string-utils.js
[BOAT-928](https://pins-ds.atlassian.net/browse/BOAT-928)
> BOAT-928 feat(web): site visit type changes adding previous visit type capitalisation fix

- infrastructure/database-monitoring.tf
- infrastructure/document-storage.tf
- infrastructure/environments/training.tfvars
- infrastructure/function.tf
- infrastructure/local.tf
- infrastructure/main.tf
- infrastructure/pipelines/terraform-cd.yaml
Adding in training env within infra directory
> adding in training env

- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/site-visit.test.js
- appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.controller.js
- appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.mapper.js
- appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.service.js
- appeals/web/testing/app/fixtures/referencedata.js
[BOAT-207](https://pins-ds.atlassian.net/browse/BOAT-207)
> feat(web): comms visit date  time rescheduled

- azure-pipelines-build.yml
- azure-pipelines-ci.yml
- azure-pipelines-db-seed-appeals-production.yml
- azure-pipelines-db-seed-appeals.yml
- azure-pipelines-deploy-appeals.yml
- azure-pipelines-regenerate-api-key.yml
Upgrade pipeline template use to 3.16.1
> fix(appeals): update common pipeline version to 3.16.1

- azure-pipelines-deploy-appeals.yml
> fix(tooling): set correct key vault name for training deploy

- appeals/api/src/server/config/config.js
- appeals/api/src/server/config/schema.js
- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/site-visits/__tests__/site-visits.test.js
- appeals/api/src/server/endpoints/site-visits/site-visits.controller.js
- appeals/api/src/server/endpoints/site-visits/site-visits.service.js
- appeals/api/src/server/swagger.js
[BOAT-207](https://pins-ds.atlassian.net/browse/BOAT-207)
> feat(api): comms visit date time rescheduled

- infrastructure/pipelines/terraform-ci-commit.yaml
> chore(tooling): add pipeline to check infrastructure commits

- appeals/api/setup-tests.js
- appeals/web/setup-tests.js
> fix(appeals): add env fix to tests-setup to make debug work

- appeals/e2e/cypress/e2e/back-office-appeals/nationalListSearch.spec.js
- appeals/e2e/cypress/e2e/back-office-appeals/reviewAppellantCase.spec.js
- appeals/e2e/cypress/e2e/back-office-appeals/reviewLpaq.spec.js
- appeals/e2e/cypress/e2e/back-office-appeals/scheduleSiteVisit.spec.js
- appeals/e2e/cypress/e2e/back-office-appeals/startCase.spec.js
- appeals/e2e/cypress/page_objects/appealsListPage.js
- appeals/e2e/cypress/page_objects/basePage.js
- appeals/e2e/cypress/page_objects/updateDueDatePage.js
> Formatting fixes to e2e tests

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/start-case/__tests__/__snapshots__/start-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/start-case/__tests__/start-case.test.js
- appeals/web/src/server/appeals/appeal-details/start-case/start-case.controller.js
- appeals/web/src/server/appeals/appeal-details/start-case/start-case.mapper.js
- appeals/web/src/server/appeals/appeal-details/start-case/start-case.router.js
- appeals/web/src/server/lib/mappers/appeal.mapper.js
add ability to change start date
> feat(web): bOAT-1166

- appeals/api/src/database/seed/data-test.js
Removed dependency on a service requiring additional ENV parameters for db::seed
> fix(api): remove seed env dependencies

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-valid/outcome-valid.mapper.js
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/__tests__/__snapshots__/change-appeal-type.test.js.snap
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/__tests__/change-appeal-type.test.js
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.mapper.js
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.types.d.ts
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js
- appeals/web/testing/app/fixtures/referencedata.js
Content amends to button text on lpaq, change appeal, and appellant case flows.
Also includes a fix for a changed property in the appeal types data ('code' is now 'key)
BOAT-1417
> feat(web): content amends to button text on lpaq, change appeal, and appellant case flows

- infrastructure/data-front-office.tf
- infrastructure/data.tf
- infrastructure/environments/dev.tfvars
- infrastructure/environments/prod.tfvars
- infrastructure/environments/test.tfvars
- infrastructure/environments/training.tfvars
- infrastructure/function-doc-processing.tf
- infrastructure/networking.tf
- infrastructure/provider.tf
- infrastructure/variables.tf
https://pins-ds.atlassian.net/browse/DEV-249
Read access for the doc-processing function, so it can copy blobs to BO.
> fix(infrastructure): add read RBAC for front office blobs

- appeals/api/src/server/endpoints/appeal-decision/__tests__/appeal-decision.test.js
> fix(api): fix decision date in appeal decision test

- appeals/web/src/client/components/file-uploader/__tests__/file-uploader.test.js
- package-lock.json
- packages/blob-storage-client/package.json
- packages/event-client/package.json
- packages/key-vault-secrets-client/package.json
- packages/scripts/package.json
[BOAT-1416](https://pins-ds.atlassian.net/browse/BOAT-1416)
> chore(deps): bump azure deps azure identity

- appeals/e2e/package.json
- package-lock.json
[BOAT-1416](https://pins-ds.atlassian.net/browse/BOAT-1416)
> chore(deps): bump ws deps

- appeals/api/src/database/seed/data-test.js
- appeals/api/src/server/config/config.js
- appeals/api/src/server/config/schema.js
- appeals/api/src/server/endpoints/appeal-timetables/__tests__/appeal-timetables.test.js
- appeals/api/src/server/endpoints/appeal-timetables/appeal-timetables.controller.js
- appeals/api/src/server/endpoints/appeal-timetables/appeal-timetables.service.js
- packages/appeals/constants/documents.js
[BOAT-1122](https://pins-ds.atlassian.net/browse/BOAT-1122)
> feat(api): comms case found to be valid

- appeals/api/src/server/infrastructure/topics.js
Corrects the topic name in the service bus, where the appeal message should be sent.
> fix(api): correct topic name for appeal HAS

- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.formatter.js
- appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.formatter.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.mapper.js
- appeals/web/src/server/lib/mappers/appellantCase.mapper.js
> feat(appeals): update appellantcase page

- appeals/api/src/database/seed/data-samples.js
- appeals/api/src/database/seed/data-test.js
Small fix for address types in db seed
> chore(api): fix db seed address types

- appeals/api/src/server/config/config.js
- appeals/api/src/server/config/schema.js
- appeals/api/src/server/endpoints/appeal-timetables/__tests__/appeal-timetables.test.js
- appeals/api/src/server/endpoints/appeal-timetables/appeal-timetables.controller.js
- appeals/api/src/server/endpoints/appeal-timetables/appeal-timetables.service.js
[BOAT-1213](https://pins-ds.atlassian.net/browse/BOAT-1213)
> feat(web): comms start date changes

- appeals/api/setup-tests.js
- appeals/api/src/database/schema.d.ts
- appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
- appeals/api/src/server/endpoints/integrations/integrations.broadcasters.js
- appeals/api/src/server/endpoints/integrations/integrations.broadcasters/event.js
- appeals/api/src/server/endpoints/integrations/integrations.broadcasters/service-users.js
- appeals/api/src/server/endpoints/integrations/integrations.mappers.js
- appeals/api/src/server/endpoints/integrations/integrations.mappers/address.mapper.js
- appeals/api/src/server/endpoints/integrations/integrations.mappers/document.mapper.js
- appeals/api/src/server/endpoints/integrations/integrations.mappers/service-user.mapper.js
- appeals/api/src/server/endpoints/integrations/integrations.mappers/site-visit.mapper.js
- appeals/api/src/server/endpoints/integrations/integrations.validators.js
- appeals/api/src/server/endpoints/site-visits/__tests__/site-visits.test.js
- appeals/api/src/server/endpoints/site-visits/site-visits.service.js
- appeals/api/src/server/infrastructure/topics.js
- appeals/api/src/server/repositories/site-visit.repository.js
- appeals/api/src/server/tests/appeals/mocks.js
- packages/appeals/constants/common.js
Integration: broadcast of appeal events (site visits for HAS)
[ASI-23](https://pins-ds.atlassian.net/browse/ASI-23)
> feat(api): broadcast appeal event - ASI-23

- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js
- appeals/web/src/server/appeals/change-page/change-page.controller.js
- appeals/web/src/server/appeals/change-page/change-page.mapper.js
- appeals/web/src/server/lib/display-page-formatter.js
- appeals/web/src/server/lib/mappers/__tests__/mappers.test.js
- appeals/web/src/server/lib/mappers/appeal.mapper.js
- appeals/web/src/server/lib/mappers/appellantCase.mapper.js
- appeals/web/src/server/lib/mappers/lpaQuestionnaire.mapper.js
- appeals/web/src/server/lib/mappers/mapper-types-jsdoc.js
also refactored appeals details mapper, appellant case mapper, lpa questionnaire mapper for clarity
https://pins-ds.atlassian.net/browse/ASI-93
> feat(web): update lpa questionnaire page

- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.controller.js
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.formatter.js
- appeals/api/src/server/openapi-types.ts
- appeals/api/src/server/openapi.json
- appeals/api/src/server/swagger.js
- appeals/web/src/server/appeals/appeal-details/site-ownership/__tests__/__snapshots__/site-ownership.test.js.snap
- appeals/web/src/server/appeals/appeal-details/site-ownership/__tests__/site-ownership.test.js
- appeals/web/src/server/appeals/appeal-details/site-ownership/site-ownership.mapper.js
- appeals/web/src/server/appeals/appeal-details/site-ownership/site-ownership.service.js
- appeals/web/src/server/lib/mappers/appellantCase.mapper.js
- appeals/web/testing/app/fixtures/referencedata.js
Add 3rd option to site ownership (Not owned by appellant)
Cleaned up naming to align request and response data
https://pins-ds.atlassian.net/browse/BOAT-1389
> feat(appeals): add new option to land ownership (owns none of the land)

- appeals/api/src/database/migrations/20240626142611_update_appeal_relationship/migration.sql
- appeals/api/src/database/schema.prisma
- appeals/api/src/database/seed/data-test.js
- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
- appeals/api/src/server/endpoints/link-appeals/__tests__/link-appeal.test.js
- appeals/api/src/server/endpoints/link-appeals/link-appeals.controller.js
- appeals/api/src/server/utils/format-linked-appeals.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.mapper.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.router.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.router.js
- appeals/web/src/server/appeals/appeal-details/other-appeals/__tests__/__snapshots__/other-appeals.test.js.snap
- appeals/web/src/server/appeals/appeal-details/other-appeals/other-appeals.controller.js
- appeals/web/src/server/appeals/appeal-details/other-appeals/other-appeals.mapper.js
- appeals/web/src/server/lib/display-page-formatter.js
- appeals/web/src/server/lib/mappers/appellantCase.mapper.js
- appeals/web/src/server/lib/mappers/notification-banners.mapper.js
https://pins-ds.atlassian.net/browse/ASI-98
> feat(appeals): add other appeals to appellant case and lpa questionnaire

- appeals/api/setup-tests.js
- appeals/api/src/server/config/config.js
- appeals/web/environment/config.js
- appeals/web/setup-tests.js
- packages/platform/utils/dotenv.js
Fix debugging API and WEB tests, by loading config from a fixed directory instead of cwd.
> test(api): fix debugging api tests

- appeals/api/src/database/migrations/20240627161939_add_case_resubmission_due_date_to_timetable/migration.sql
- appeals/api/src/database/schema.prisma
- appeals/api/src/server/config/config.js
- appeals/api/src/server/config/schema.js
- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/change-appeal-type/__tests__/change-appeal-type.test.js
- appeals/api/src/server/endpoints/change-appeal-type/change-appeal-type.controller.js
- appeals/api/src/server/endpoints/change-appeal-type/change-appeal-type.service.js
[BOAT-285](https://pins-ds.atlassian.net/browse/BOAT-285)
> feat(api): comms appeal type changed to non-has

- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.router.js
- appeals/web/src/server/appeals/appeal-details/change-lpa-reference/change-lpa-reference.controller.js
- appeals/web/src/server/appeals/appeal-details/inspector-access/inspector-access.controller.js
- appeals/web/src/server/appeals/appeal-details/safety-risks/safety-risks.controller.js
- appeals/web/src/server/appeals/appeal-details/service-user/service-user.controller.js
- appeals/web/src/server/appeals/appeal-details/site-area/__tests__/__snapshots__/site-area.test.js.snap
- appeals/web/src/server/appeals/appeal-details/site-area/__tests__/site-area.test.js
- appeals/web/src/server/appeals/appeal-details/site-area/site-area.controller.js
- appeals/web/src/server/appeals/appeal-details/site-area/site-area.mapper.js
- appeals/web/src/server/appeals/appeal-details/site-area/site-area.router.js
- appeals/web/src/server/appeals/appeal-details/site-area/site-area.service.js
- appeals/web/src/server/appeals/appeal-details/site-area/site-area.validators.js
- appeals/web/src/server/lib/mappers/appellantCase.mapper.js
- appeals/web/src/server/lib/mappers/notification-banners.mapper.js
- appeals/web/testing/app/fixtures/referencedata.js
https://pins-ds.atlassian.net/browse/ASI-24
https://pins-ds.atlassian.net/browse/ASI-31
> feat(appeals): add change page for site area

- azure-pipelines-db-seed-appeals.yml
> feat(api): seeding for env

- appeals/api/src/database/migrations/20240628130315_decision_outcome_date/migration.sql
- appeals/api/src/database/schema.prisma
- appeals/api/src/server/repositories/appeal.repository.js
Another DB modification, to add the decision date to the appeal, as well as the decision document
> fix(api): adds completion date to appeal

- appeals/api/src/server/endpoints/appeal-decision/appeal-decision.controller.js
- appeals/api/src/server/endpoints/invalid-appeal-decision/invalid-appeal-decision.controller.js
I noticed some functions were sending a status and response but continuing function execution.
> fix(api): return early after sending a response

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
- appeals/web/src/server/lib/mappers/appeal.mapper.js
add row for appeal decision to case details page documentation accordion
BOAT-1173
> feat(web): add row for appeal decision to case details page documentation accordion

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.mapper.js
add due date to appellant case incomplete notification banner
BOAT-1414
> feat(web): add due date to appellant case incomplete notification banner

- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.router.js
- appeals/web/src/server/appeals/appeal-details/application-submission-date/__tests__/__snapshots__/application-submission-date.test.js.snap
- appeals/web/src/server/appeals/appeal-details/application-submission-date/__tests__/application-submission-date.test.js
- appeals/web/src/server/appeals/appeal-details/application-submission-date/application-submission-date.controller.js
- appeals/web/src/server/appeals/appeal-details/application-submission-date/application-submission-date.mapper.js
- appeals/web/src/server/appeals/appeal-details/application-submission-date/application-submission-date.router.js
- appeals/web/src/server/appeals/appeal-details/application-submission-date/application-submission-date.service.js
- appeals/web/src/server/appeals/appeal-details/application-submission-date/application-submission-date.validators.js
- appeals/web/src/server/appeals/appeal-details/site-area/site-area.controller.js
- appeals/web/src/server/appeals/appeal-details/site-ownership/site-ownership.controller.js
- appeals/web/src/server/lib/mappers/appellantCase.mapper.js
https://pins-ds.atlassian.net/browse/BOAT-1403
> feat(appeals): add change page for application submission date

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.mapper.js
incomplete appellant case notification banner updated to display due date in summary list (was previously in a details component)
BOAT-1414
> feat(web): incomplete appellant case notification banner updated to display due date in summary list

- appeals/api/src/database/seed/data-samples.js
- appeals/api/src/database/seed/data-test.js
In the test data, not a huge deal but some clean up:
- don't redefine APPEAL_CASE_STATUS
- fix some ts-ignore
> chore(api): don't redefine APPEAL_CASE_STATUS and fix some ts-ignore

- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.router.js
- appeals/web/src/server/appeals/appeal-details/internal-correspondence/__tests__/__snapshots__/internal-correspondence.test.js.snap
- appeals/web/src/server/appeals/appeal-details/internal-correspondence/__tests__/internal-correspondence.test.js
- appeals/web/src/server/appeals/appeal-details/internal-correspondence/internal-correspondence.controller.js
- appeals/web/src/server/appeals/appeal-details/internal-correspondence/internal-correspondence.router.js
- appeals/web/src/server/lib/mappers/appeal.mapper.js
- appeals/web/src/server/lib/mappers/notification-banners.mapper.js
- appeals/web/testing/app/fixtures/referencedata.js
add internal correspondence document folders (cross team and inspector)
BOAT-1265
> feat(appeals): add internal correspondence document folders

- appeals/functions/casedata-import/questionnaire/index.js
> fix(functions): don't do any (incorrect!) questionnaire validation in the function

- appeals/functions/casedata-import/appellant-case/index.js
- appeals/functions/casedata-import/questionnaire/index.js
- appeals/functions/document-processing/malware-detection/index.js
- appeals/functions/user-import/employee/index.js
- appeals/functions/user-import/service-user/index.js
> feat(functions): log api response on error

- appeals/api/src/server/endpoints/integrations/integrations.mappers/document.mapper.js
For submissions import, related to documents: throw a specific error rather than allowing the subsequent code to fail in uncertain ways.
> fix(api): throw a specific error if the document uri is not in the expected format

- appeals/web/src/server/lib/__tests__/libraries.test.js
- appeals/web/src/server/lib/dates.js
https://pins-ds.atlassian.net/browse/A2-376
> fix(web): ensure audit trail logs are shown in Europe/London timezone

- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js
Add lpaq due date to lpaq incomplete notification banner (fixes missed ACs in BOAT-1414)
A2-537
BOAT-1414
> feat(web): add lpaq due date to lpaq incomplete notification banner

- appeals/web/src/server/appeals/appeal-details/internal-correspondence/__tests__/__snapshots__/internal-correspondence.test.js.snap
- appeals/web/src/server/appeals/appeal-details/internal-correspondence/__tests__/internal-correspondence.test.js
- appeals/web/src/server/appeals/appeal-details/internal-correspondence/internal-correspondence.controller.js
- appeals/web/src/server/appeals/appeal-details/internal-correspondence/internal-correspondence.router.js
fix change doc details for internal correspondence folders
BOAT-1487
> fix(web): fix change doc details for internal correspondence folders

- appeals/web/src/server/appeals/appeal-details/internal-correspondence/__tests__/internal-correspondence.test.js
- appeals/web/src/server/appeals/appeal-details/internal-correspondence/internal-correspondence.controller.js
fix 404 on internal correspondence upload another document flow
BOAT-1490
> fix(web): fix 404 on internal correspondence upload another document flow

- appeals/web/src/server/appeals/personal-list/__tests__/personal-list.test.js
- appeals/web/src/server/appeals/personal-list/personal-list.mapper.js
fix personal list action links checking for case officer user role
A2-385
> fix(web): fix personal list action links checking for case officer user role

- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.controller.js
- appeals/web/src/server/appeals/appeal-details/costs/costs.controller.js
- appeals/web/src/server/appeals/appeal-details/internal-correspondence/internal-correspondence.controller.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.controller.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.controller.js
- appeals/web/src/server/appeals/appeal-details/withdrawal/withdrawal.controller.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.controller.js
refactor(web): ensure all async shared document controller methods are called using await
BOAT-1491
> refactor(web): ensure all async shared document controller methods are called using await

- appeals/api/src/server/endpoints/integrations/integrations.mappers/questionnaire.mapper.js
Fixes import of LPAQ where notification methods is an empty array
[ASI-20](https://pins-ds.atlassian.net/browse/ASI-20)
[ASI-20]: https://pins-ds.atlassian.net/browse/ASI-20?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(appeals): import of LPAQ - fix with notification methods

- infrastructure/app-api.tf
- infrastructure/app-web.tf
- infrastructure/function-casedata-import.tf
- infrastructure/function-doc-processing.tf
- infrastructure/function-scheduled-jobs.tf
- infrastructure/function-user-import.tf
https://pins-ds.atlassian.net/browse/DEV-260
> chore(infrastructure): update app and function modules to ignore tag changes

- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.controller.js
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.validators.js
https://pins-ds.atlassian.net/browse/A2-425
> feat(api): add api for development description

- infrastructure/environments/dev.tfvars
- infrastructure/environments/prod.tfvars
- infrastructure/environments/test.tfvars
- infrastructure/environments/training.tfvars
- infrastructure/networking-secondary.tf
- infrastructure/networking.tf
- infrastructure/provider.tf
- infrastructure/variables.tf
Link up the virtual network to the Horizon virtual network for linked cases functionality.
https://pins-ds.atlassian.net/browse/DEV-267
> feat(infrastructure): add a peering to horizon vnet

- infrastructure/pipelines/terraform-ci-commit.yaml
- infrastructure/pipelines/terraform-ci.yaml
> ci: trigger infra pr pipelines for merge queue

- infrastructure/environments/test.tfvars
- infrastructure/provider.tf
Small fixes to #308 
TEST plan works now: https://dev.azure.com/planninginspectorate/appeals-back-office/_build/results?buildId=87853&view=logs&j=2f8dae9a-a8bf-5c36-9b20-9fc5c814745c&t=10aa7927-e7fc-52ea-935a-8bead9c9068b
> fix(infrastructure): add horizon links in test env

- appeals/api/src/server/config/config.js
- appeals/api/src/server/config/schema.js
- appeals/api/src/server/utils/horizon-gateway.js
> fix(api): add timeout and better logging to Horizon Gateway

- infrastructure/data-horizon.tf
- infrastructure/networking-secondary.tf
- infrastructure/networking.tf
https://pins-ds.atlassian.net/browse/DEV-267
> fix(infrastructure): fix vnet peering to horizon, reference the correct remote vnet

- appeals/api/src/server/endpoints/addresses/__tests__/addresses.test.js
- appeals/api/src/server/endpoints/addresses/addresses.controller.js
- appeals/api/src/server/endpoints/appeal-timetables/appeal-timetables.controller.js
- appeals/api/src/server/endpoints/appeals/appeals.controller.js
- appeals/api/src/server/endpoints/documents/documents.controller.js
- appeals/api/src/server/endpoints/site-visits/site-visits.controller.js
- appeals/web/src/server/appeals/appeal-details/address/address.controller.js
- appeals/web/src/server/appeals/appeal-details/application-decision-date/application-decision-date.controller.js
- appeals/web/src/server/appeals/appeal-details/change-lpa-reference/change-lpa-reference.controller.js
- appeals/web/src/server/appeals/appeal-details/costs/__tests__/costs.test.js
- appeals/web/src/server/appeals/appeal-details/inspector-access/inspector-access.controller.js
- appeals/web/src/server/appeals/appeal-details/internal-correspondence/__tests__/internal-correspondence.test.js
- appeals/web/src/server/appeals/appeal-details/neighbouring-sites/neighbouring-sites.controller.js
- appeals/web/src/server/appeals/appeal-details/other-appeals/other-appeals.controller.js
- appeals/web/src/server/appeals/appeal-details/safety-risks/safety-risks.controller.js
- appeals/web/src/server/appeals/appeal-details/service-user/service-user.controller.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.controller.js
- appeals/web/src/server/lib/__tests__/libraries.test.js
- appeals/web/src/server/lib/url-utilities.js
[A2-582](https://pins-ds.atlassian.net/browse/A2-582)
[A2-456]: https://pins-ds.atlassian.net/browse/A2-456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[A2-582]: https://pins-ds.atlassian.net/browse/A2-582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(appeals): address security logs

- azure-pipelines-ci.yml
- infrastructure/pipelines/terraform-ci-commit.yaml
Only run either code pipelines or infra pipelines based on paths in merge queue
> ci: run correct infra/code pipelines in merge queue

- azure-pipelines-ci.yml
- infrastructure/pipelines/terraform-ci-commit.yaml
This reverts commit a470868c4601a087acb55a40748d5aeff5ad8ee0.
Infra-only changes got stuck in the merge queue as the PR check was skipped. Have to run all checks.
> Revert "ci: run correct infra/code pipelines in merge queue"

- infrastructure/data-horizon.tf
> fix(infrastructure): horizon data block needs horizon provider

- appeals/api/src/server/common/validators/boolean-with-conditional-string-parameters.js
- appeals/api/src/server/common/validators/string-parameter.js
- appeals/api/src/server/endpoints/addresses/addresses.validators.js
- appeals/api/src/server/endpoints/appeals/appeals.validators.js
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.validators.js
- appeals/api/src/server/endpoints/change-appeal-type/change-appeal-type.validators.js
- appeals/api/src/server/endpoints/constants.js
- appeals/api/src/server/endpoints/documents/documents.validators.js
- appeals/api/src/server/endpoints/link-appeals/link-appeals.validators.js
- appeals/api/src/server/endpoints/neighbouring-sites/neighbouring-sites.validators.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.router.js
- appeals/web/src/server/appeals/appeal-details/development-description/__tests__/__snapshots__/development-description.test.js.snap
- appeals/web/src/server/appeals/appeal-details/development-description/__tests__/development-description.test.js
- appeals/web/src/server/appeals/appeal-details/development-description/development-description.controller.js
- appeals/web/src/server/appeals/appeal-details/development-description/development-description.mapper.js
- appeals/web/src/server/appeals/appeal-details/development-description/development-description.router.js
- appeals/web/src/server/appeals/appeal-details/development-description/development-description.service.js
- appeals/web/src/server/appeals/appeal-details/development-description/development-description.validators.js
- appeals/web/src/server/lib/mappers/appellantCase.mapper.js
https://pins-ds.atlassian.net/browse/A2-298
> feat(appeals): add change page for development description

- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.controller.js
- Updated manage document pages headings to match copy deck
[A2-311 'Manage' screens for the three new rows/folders for HAS LPAQ](https://pins-ds.atlassian.net.mcas.ms/browse/A2-311)
> feat(web): manage new rows upload headings

- appeals/web/src/server/appeals/appeal-details/withdrawal/withdrawal.controller.js
submit in 'Europe/London' timezone
> fix(web): bugfix/withdrawal-submit-date-in-british-time

- appeals/api/src/database/seed/seed-training.js
Deletes all records when running `db:seed` for the TRAINING environment.
> feat(api): seed training deletes all records

- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.controller.js
- Updated headings on upload, details and manage for 'Who Notified' row
[A2-317](https://pins-ds.atlassian.net.mcas.ms/browse/A2-317)
[A2-317]: https://pins-ds.atlassian.net/browse/A2-317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web): headings updated on who notified on lpaq

- appeals/api/src/database/seed/data-samples.js
- appeals/api/src/server/common/validators/enum-parameter.js
- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.controller.js
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.validators.js
- appeals/api/src/server/repositories/appeal.repository.js
- appeals/api/src/server/repositories/appellant-case.repository.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.mapper.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.router.js
- appeals/web/src/server/appeals/appeal-details/owners-known/__tests__/__snapshots__/owners-known.test.js.snap
- appeals/web/src/server/appeals/appeal-details/owners-known/__tests__/owners-known.test.js
- appeals/web/src/server/appeals/appeal-details/owners-known/owners-known.controller.js
- appeals/web/src/server/appeals/appeal-details/owners-known/owners-known.mapper.js
- appeals/web/src/server/appeals/appeal-details/owners-known/owners-known.router.js
- appeals/web/src/server/appeals/appeal-details/owners-known/owners-known.service.js
- appeals/web/src/server/lib/mappers/appellantCase.mapper.js
- appeals/web/testing/app/fixtures/referencedata.js
change page for appellant case owners known
A2-283
> feat(appeals): change page for appellant case owners known

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/application-submission-date/__tests__/__snapshots__/application-submission-date.test.js.snap
- appeals/web/src/server/appeals/appeal-details/application-submission-date/__tests__/application-submission-date.test.js
- appeals/web/src/server/appeals/appeal-details/application-submission-date/application-submission-date.controller.js
- appeals/web/src/server/appeals/appeal-details/application-submission-date/application-submission-date.mapper.js
- appeals/web/src/server/lib/mappers/appellantCase.mapper.js
https://pins-ds.atlassian.net/browse/A2-536
> feat(web): feature/A2-536-change-application-date-to-application-submmitted

- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/audit-trails/audit-trails.formatter.js
- appeals/web/src/server/appeals/appeal-details/audit/audit.service.js
Links document uploads in the costs folders.
TODO additional stages / document types, when data-model v1.8.0 is available.
[A2-392](https://pins-ds.atlassian.net/browse/A2-392)
[A2-392]: https://pins-ds.atlassian.net/browse/A2-392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(appeals): linking costs docs in audit

- appeals/web/src/server/lib/mappers/appeal.mapper.js
hide agent change link when no agent present in appeal
> fix(web): hide agent change link when no agent present in appeal

- appeals/web/src/server/appeals/appeal-details/application-submission-date/__tests__/__snapshots__/application-submission-date.test.js.snap
- appeals/web/src/server/appeals/appeal-details/application-submission-date/__tests__/application-submission-date.test.js
- appeals/web/src/server/appeals/appeal-details/application-submission-date/application-submission-date.router.js
- appeals/web/src/server/appeals/appeal-details/application-submission-date/application-submission-date.validators.js
https://pins-ds.atlassian.net/browse/A2-536
> feat(web): feature/A2-536-application-submitted-date-validators

- appeals/web/src/server/appeals/appeal-details/service-user/__tests__/__snapshots__/service-user.test.js.snap
- appeals/web/src/server/appeals/appeal-details/service-user/__tests__/service-user.test.js
- appeals/web/src/server/appeals/appeal-details/service-user/service-user.validators.js
fix validation error message on service user change page phone number field
A2-623
> fix(web): fix validation error message on service user change page phone number field

- appeals/e2e/cypress/support/e2e.js
Includes a single missing file required for Cypress Grep to work (to enable running of sub-set of tests for smoke vs regression testing)
> Cypress Grep (Run sub-set of tests) - Missing file

- appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
https://pins-ds.atlassian.net/browse/A2-539
> fix(web): bugfix/A2-539-withdrawal-wrong-link-in-the-inset

- appeals/api/src/server/endpoints/appeals/appeals.formatter.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.controller.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
https://pins-ds.atlassian.net/browse/A2-386
> fix(web): bugfix/A2-386-missing-inset-for-closed-appeals

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.controller.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.controller.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.controller.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js
- appeals/web/src/server/lib/documents.js
fix late entry tag missing from upload and document details pages
A2-381
> fix(web): fix late entry tag missing from upload and document details pages

- appeals/api/src/server/endpoints/constants.js
- appeals/api/src/server/utils/notify-client.js
Adds additional logging for Notify errors
> chore(api): additional logging for Notify

- appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js
fix manage document page history activity entries for system user
A2-404
> fix(web): fix manage document page history activity entries for system user

- appeals/api/src/server/endpoints/integrations/__tests__/integrations.test.js
- appeals/api/src/server/endpoints/integrations/integrations.controller.js
- appeals/api/src/server/endpoints/integrations/integrations.mappers.js
- appeals/api/src/server/endpoints/integrations/integrations.mappers/appeal-type.mapper.js
- appeals/api/src/server/endpoints/integrations/integrations.middleware.js
- appeals/api/src/server/endpoints/integrations/integrations.routes.js
Ensures only appeal types 'D' (Householder) are imported through the integrations.
> fix(api): validate appeal type and reject non HAS

- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.router.js
- appeals/web/src/server/appeals/appeal-details/application-decision-date/application-decision-date.service.js
- appeals/web/src/server/appeals/appeal-details/application-outcome/__tests__/__snapshots__/application-outcome.test.js.snap
- appeals/web/src/server/appeals/appeal-details/application-outcome/__tests__/application-outcome.test.js
- appeals/web/src/server/appeals/appeal-details/application-outcome/application-outcome.controller.js
- appeals/web/src/server/appeals/appeal-details/application-outcome/application-outcome.mapper.js
- appeals/web/src/server/appeals/appeal-details/application-outcome/application-outcome.router.js
- appeals/web/src/server/appeals/appeal-details/application-outcome/application-outcome.service.js
- appeals/web/src/server/appeals/appeal-details/application-outcome/application-outcome.validators.js
- appeals/web/src/server/lib/mappers/appellantCase.mapper.js
https://pins-ds.atlassian.net/browse/A2-296
> feat(appeals): add application outcome change page

- appeals/api/src/server/endpoints/integrations/integrations.mappers.js
- appeals/api/src/server/endpoints/integrations/integrations.mappers/casedata.mapper.js
Split decision wasn't respecting the schema, failing to broadcast.
[ASI-136](https://pins-ds.atlassian.net/browse/ASI-136)
[ASI-136]: https://pins-ds.atlassian.net/browse/ASI-136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(api): correct mapping of appeal decision

- appeals/api/src/server/endpoints/integrations/integrations.broadcasters/service-users.js
- appeals/api/src/server/endpoints/integrations/integrations.mappers/service-user.mapper.js
ODW requirement to change the values broadcasted for service users:
- id (start range 200,000,000)
- sourceSuid (start range 200,000,000)
N/A
> fix(api): service user ID broadcast to start at 200,000,000

- appeals/web/src/server/appeals/appeal-details/extra-conditions/__tests__/__snapshots__/extra-conditions.test.js.snap
- appeals/web/src/server/appeals/appeal-details/extra-conditions/__tests__/extra-conditions.test.js
- appeals/web/src/server/appeals/appeal-details/extra-conditions/extra-conditions.controller.js
- appeals/web/src/server/appeals/appeal-details/extra-conditions/extra-conditions.mapper.js
- appeals/web/src/server/appeals/appeal-details/extra-conditions/extra-conditions.router.js
- appeals/web/src/server/appeals/appeal-details/extra-conditions/extra-conditions.service.js
- appeals/web/src/server/appeals/appeal-details/extra-conditions/extra-conditions.validator.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.router.js
- appeals/web/src/server/lib/mappers/lpaQuestionnaire.mapper.js
add change page for extra conditions
A2-289
> feat(web): add change page for extra conditions

- appeals/web/src/server/appeals/appeal-details/appeal-costs-application/__tests__/__snapshots__/appeal-costs-application.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appeal-costs-application/__tests__/appeal-costs-application.test.js
- appeals/web/src/server/appeals/appeal-details/appeal-costs-application/appeal-costs-application.controller.js
- appeals/web/src/server/appeals/appeal-details/appeal-costs-application/appeal-costs-application.mapper.js
- appeals/web/src/server/appeals/appeal-details/appeal-costs-application/appeal-costs-application.router.js
- appeals/web/src/server/appeals/appeal-details/appeal-costs-application/appeal-costs-application.service.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.router.js
- appeals/web/src/server/lib/mappers/appellantCase.mapper.js
[A2-299](https://pins-ds.atlassian.net/browse/A2-299)
[A2-299]: https://pins-ds.atlassian.net/browse/A2-299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(api): a2-299 change page for appeal costs applied for

- azure-pipelines-deploy-appeals.yml
- infrastructure/app-web-2.tf
- infrastructure/front-door-web.tf
https://pins-ds.atlassian.net/browse/DEV-247
Temporary second web app in test while deployment issues are investigated.
> fix(tooling): add second web app in test temporarily

- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.controller.js
- appeals/api/src/server/openapi-types.ts
- appeals/api/src/server/openapi.json
- appeals/api/src/server/repositories/lpa-questionnaire.repository.js
- appeals/api/src/server/swagger.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.router.js
- appeals/web/src/server/appeals/appeal-details/notification-methods/__tests__/__snapshots__/notification-methods.test.js.snap
- appeals/web/src/server/appeals/appeal-details/notification-methods/__tests__/notification-methods.test.js
- appeals/web/src/server/appeals/appeal-details/notification-methods/notification-methods.controller.js
- appeals/web/src/server/appeals/appeal-details/notification-methods/notification-methods.mapper.js
- appeals/web/src/server/appeals/appeal-details/notification-methods/notification-methods.router.js
- appeals/web/src/server/appeals/appeal-details/notification-methods/notification-methods.service.js
- appeals/web/src/server/lib/mappers/lpaQuestionnaire.mapper.js
- appeals/web/testing/app/fixtures/referencedata.js
add change page for lpa notification methods
A2-286
> feat(appeals): change page for lpa notification methods

- package.json
Reduce concurrency as the tests are failing in the pipeline
n/a
> fix(appeals): reduce concurrency to stop test crash

- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.router.js
- appeals/web/src/server/appeals/appeal-details/lpa-changed-description/__tests__/__snapshots__/lpa-changed-description.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-changed-description/__tests__/lpa-changed-description.test.js
- appeals/web/src/server/appeals/appeal-details/lpa-changed-description/lpa-changed-description.controller.js
- appeals/web/src/server/appeals/appeal-details/lpa-changed-description/lpa-changed-description.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-changed-description/lpa-changed-description.router.js
- appeals/web/src/server/appeals/appeal-details/lpa-changed-description/lpa-changed-description.service.js
- appeals/web/src/server/appeals/appeal-details/lpa-changed-description/lpa-changed-description.validator.js
- appeals/web/src/server/lib/mappers/appellantCase.mapper.js
https://pins-ds.atlassian.net/browse/A2-297
> add changed description change page

- appeals/api/src/server/endpoints/integrations/__tests__/integrations.test.js
- appeals/api/src/server/endpoints/lpa-questionnaires/__tests__/lpa-questionnaires.test.js
- appeals/api/src/server/state/state-machines/fpa.js
S78 state machine, adding unhappy paths
> feat(api): type S78 state machine

- appeals/web/src/server/appeals/appeal-details/costs/__tests__/__snapshots__/costs.test.js.snap
- appeals/web/src/server/appeals/appeal-details/costs/costs.controller.js
update to render file upload component in multiple files configuration for all costs document flows
A2-383
> fix(web): update all costs document upload pages to multiple file upload

- appeals/api/src/server/endpoints/appeals/appeals.controller.js
- appeals/web/package.json
- azure-pipelines-build.yml
- package.json
Increase memory allocation on unit tests
> chore(appeals): unit test memory settings 

- appeals/web/src/client/components/file-uploader/_html.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/costs/__tests__/__snapshots__/costs.test.js.snap
- appeals/web/src/server/appeals/appeal-details/internal-correspondence/__tests__/__snapshots__/internal-correspondence.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.controller.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js
a11y improvements to manage folder and manage document pages
A2-406
> fix(web): a11y improvements to manage folder and manage document pages

- docs/api.md
add process notes to readme re. adding a document folder. Preview: https://github.com/Planning-Inspectorate/appeals-back-office/blob/docs/A2-750/docs/api.md
A2-750
> docs(api): add process notes to readme re. adding a document folder

- appeals/api/src/database/seed/LPAs/dev.js
- appeals/api/src/database/seed/LPAs/training.js
Adds the Q9998 LPA on the training environment.
> feat(appeals): adds an additional training LPA

- appeals/api/src/server/config/config.js
- infrastructure/app-api.tf
- infrastructure/app-web-2.tf
- infrastructure/app-web.tf
- infrastructure/environments/dev.tfvars
- infrastructure/environments/prod.tfvars
- infrastructure/environments/test.tfvars
- infrastructure/environments/training.tfvars
- infrastructure/variables.tf
Configuration for feature flags in terraform
> feat(tooling): feature flag infrastructure

- appeals/api/src/database/seed/data-test.js
> fix(api): db seed always created S78 cases

- appeals/api/src/database/seed/LPAs/training.js
Correct settings of LPA code and email for `System Test Borough Council 2`
> fix(api): settings for the training LPAs

- appeals/web/src/server/appeals/appeal-details/neighbouring-sites/__tests__/neighbouring-sites.test.js
- appeals/web/src/server/appeals/appeal-details/neighbouring-sites/neighbouring-sites.controller.js
- appeals/web/src/server/appeals/appeal-details/neighbouring-sites/neighbouring-sites.mapper.js
- appeals/web/src/server/appeals/appeal.constants.js
- appeals/web/src/server/lib/mappers/notification-banners.mapper.js
> fix(web): bugfix/A2-400-fix-neighbouring-sites-removal-redirects

- appeals/api/package.json
- appeals/api/src/database/seed/data-static.js
- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.controller.js
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.formatter.js
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.validators.js
- appeals/api/src/server/endpoints/integrations/integrations.mappers/questionnaire.mapper.js
- appeals/api/src/server/openapi-types.ts
- appeals/api/src/server/openapi.json
- appeals/api/src/server/swagger.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/lpa-changed-description/__tests__/__snapshots__/lpa-changed-description.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/lpa-changed-description/__tests__/lpa-changed-description.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/lpa-changed-description/lpa-changed-description.mapper.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/lpa-changed-description/lpa-changed-description.service.js
- appeals/web/src/server/lib/mappers/appellantCase.mapper.js
- package-lock.json
- package.json
- Aligns schema to 1.8.3
- Fixes ASI-151
[ASI-151](https://pins-ds.atlassian.net/browse/ASI-151)
[ASI-151]: https://pins-ds.atlassian.net/browse/ASI-151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(api): schemas 1.8.3 and ASI-151

- appeals/web/src/server/appeals/appeal-details/costs/__tests__/costs.test.js
- appeals/web/src/server/appeals/appeal-details/costs/costs.controller.js
[A2-581](https://pins-ds.atlassian.net/browse/A2-581)
[A2-581]: https://pins-ds.atlassian.net/browse/A2-581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web): A2-581 costs application documents

- appeals/api/src/server/endpoints/documents/documents.controller.js
- appeals/api/src/server/endpoints/documents/documents.mapper.js
Uploading document was not storing the correct documentURI.
[ASI-149](https://pins-ds.atlassian.net/browse/ASI-149)
[ASI-149]: https://pins-ds.atlassian.net/browse/ASI-149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(api): documentURI missing container

- appeals/api/package.json
- appeals/e2e/package.json
- package-lock.json
[A2-768](https://pins-ds.atlassian.net/browse/A2-768)
[A2-456]: https://pins-ds.atlassian.net/browse/A2-456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[A2-582]: https://pins-ds.atlassian.net/browse/A2-582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(appeals): A2-768 address security logs 

- appeals/api/src/database/migrations/20240813132358_add_s78_questionnaire_fields/migration.sql
- appeals/api/src/database/schema.prisma
> feat(appeals): add s78 questionnaire fields to prisma schema

- appeals/web/src/server/appeals/appeal-details/appellant-case/appeal-costs-application/appeal-costs-application.controller.js
- appeals/web/src/server/appeals/appeal-details/green-belt/green-belt.controller.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.controller.js
[A2-768](https://pins-ds.atlassian.net/browse/A2-768)
> fix(appeals): A2-768 address security logs

- appeals/api/setup-tests.js
- appeals/api/src/database/migrations/20240815143728_add_representations/migration.sql
- appeals/api/src/database/schema.d.ts
- appeals/api/src/database/schema.prisma
- appeals/api/src/database/seed/data-test.js
- appeals/api/src/database/seed/seed-clear.js
- appeals/api/src/server/endpoints/appeals.routes.js
- appeals/api/src/server/endpoints/business-days/business-days.routes.js
- appeals/api/src/server/endpoints/constants.js
- appeals/api/src/server/endpoints/representations/__tests__/representations.test.js
- appeals/api/src/server/endpoints/representations/representations.controller.js
- appeals/api/src/server/endpoints/representations/representations.formatter.js
- appeals/api/src/server/endpoints/representations/representations.routes.js
- appeals/api/src/server/endpoints/representations/representations.service.js
- appeals/api/src/server/endpoints/representations/representations.validators.js
- appeals/api/src/server/openapi-types.ts
- appeals/api/src/server/openapi.json
- appeals/api/src/server/repositories/appeal-lists.repository.js
- appeals/api/src/server/repositories/representation.repository.js
- appeals/api/src/server/repositories/service-customer.repository.js
- appeals/api/src/server/swagger.js
- appeals/api/src/server/tests/representations/mocks.js
- packages/appeals/constants/common.js
Initial work on S78 API requirements for statements and comments:
- DB tables
- Seed to inject some mock data
- API endpoints
[A2-747](https://pins-ds.atlassian.net/browse/A2-747)
[A2-747]: https://pins-ds.atlassian.net/browse/A2-747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(api): initial back-end for representations

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js
Only render appellant case and LPAQ review controls if appeal is in appropriate status
A2-151
> Only render appellant case and LPAQ review controls if appeal is in appropriate status

- appeals/api/src/server/endpoints/constants.js
- appeals/api/src/server/endpoints/representations/__tests__/representations.test.js
- appeals/api/src/server/endpoints/representations/representations.routes.js
Removed redundant validation from rep routes
Improved validation messages
> feat(api): improve validation pipeline for representation routes

- appeals/api/src/database/seed/data-samples.js
- appeals/api/src/database/seed/data-test.js
- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.controller.js
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.formatter.js
- appeals/api/src/server/openapi-types.ts
- appeals/api/src/server/openapi.json
- appeals/api/src/server/swagger.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/agricultural-holding/__tests__/__snapshots__/agricultural-holding.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/agricultural-holding/__tests__/agricultural-holding.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/agricultural-holding/agricultural-holding.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/agricultural-holding/agricultural-holding.mapper.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/agricultural-holding/agricultural-holding.router.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/agricultural-holding/agricultural-holding.service.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.router.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/planning-obligation/__tests__/__snapshots__/planning-obligation.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/planning-obligation/planning-obligation.mapper.js
- appeals/web/src/server/lib/mappers/appellant-case/appeal-type-fpa.mapper.js
- appeals/web/src/server/lib/mappers/appellant-case/appeal-type-has.mapper.js
- appeals/web/src/server/lib/mappers/appellantCase.mapper.js
- appeals/web/testing/app/fixtures/referencedata.js
add agricultural holding rows to s78 appellant case
A2-264
> feat(appeals): add agricultural holding rows to s78 appellant case

- appeals/web/src/server/appeals/appeal-documents/appeal-documents.controller.js
[A2-768](https://pins-ds.atlassian.net/browse/A2-768)
> fix(appeals): A2-768  review and address security warnings redirect debug

- appeals/api/src/server/endpoints/integrations/integrations.broadcasters/appeal.js
- appeals/api/src/server/endpoints/integrations/integrations.mappers.js
3 fields were not broadcasted correctly as the relevant DB tables were not included in the query....
> fix(api): broadcast 3 fields which were failing

- appeals/web/src/server/appeals/appeal-users/users-service.js
https://pins-ds.atlassian.net/browse/A2-832
> fix(web): remove page limit for azureAd user fetch

- appeals/web/src/server/appeals/appeal-documents/appeal-documents.controller.js
- appeals/web/src/server/lib/__tests__/libraries.test.js
- appeals/web/src/server/lib/url-utilities.js
[A2-768](https://pins-ds.atlassian.net/browse/A2-768)
> fix(appeals): A2-768  review and address security warnings redirect fix& remove debug

- appeals/api/src/server/endpoints/integrations/integrations.mappers/address.mapper.js
Fix incorrect mapping for neighbouring sites
> fix(api): map neighbouring sites correctly

- appeals/e2e/cypress/e2e/back-office-appeals/nationalListSearch.spec.js
- appeals/e2e/cypress/e2e/back-office-appeals/reviewAppellantCase.spec.js
- appeals/e2e/cypress/e2e/back-office-appeals/reviewLpaq.spec.js
- appeals/e2e/cypress/e2e/back-office-appeals/scheduleSiteVisit.spec.js
- appeals/e2e/cypress/e2e/back-office-appeals/startCase.spec.js
- appeals/e2e/cypress/fixtures/appealsApiRequests.js
- appeals/e2e/cypress/page_objects/caseDetailsPage.js
Updated review appellant and review lpaq tests to adhere to this ticket https://pins-ds.atlassian.net/browse/A2-151. Added smoke tags onto tests needed for smoke test suite.
> test(appeals): added to the e2e smoke tests

- appeals/api/src/server/utils/appeal-reference.js
- appeals/web/src/server/app/app.router.js
- packages/appeals/constants/common.js
Adds a short url route that redirects to appeal details: `/case/:caseReference`
[A2-831](https://pins-ds.atlassian.net/browse/A2-831)
[A2-831]: https://pins-ds.atlassian.net/browse/A2-831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(appeals): short url to appeal details

- appeals/api/src/server/endpoints/integrations/integrations.mappers/document.mapper.js
Additional improvements for doc names
Ignores document ID sent from FO
> fix(api): additional fixes for doc names

- appeals/api/src/server/endpoints/integrations/integrations.service.js
Removes an extra database call to check document UUIDs. We are no longer trying to preserve the UUIDs the FO stores documents with, so this is no longer necessary.
> fix(api): remove redundant check on doc UUID

- appeals/web/src/server/appeals/appeal-details/appellant-case/appeal-costs-application/__tests__/appeal-costs-application.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appeal-costs-application/appeal-costs-application.controller.js
[A2-856](https://pins-ds.atlassian.net/browse/A2-856)
[A2-856]: https://pins-ds.atlassian.net/browse/A2-856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web): A2-856 back link and notification banner for applied for award of appeal costs

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.controller.js
- appeals/web/src/server/appeals/appeal-details/costs/__tests__/costs.test.js
- appeals/web/src/server/appeals/appeal-details/costs/costs.controller.js
- appeals/web/src/server/appeals/appeal-details/internal-correspondence/__tests__/internal-correspondence.test.js
- appeals/web/src/server/appeals/appeal-details/internal-correspondence/internal-correspondence.controller.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.controller.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.controller.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js
add change links to shared document upload check your answers pages
A2-850
> fix(web): add change links to shared document upload check your answers pages

- appeals/web/src/server/appeals/appeal-details/appellant-case/lpa-changed-description/__tests__/lpa-changed-description.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/lpa-changed-description/lpa-changed-description.controller.js
[A2-799](https://pins-ds.atlassian.net/browse/A2-799)
[A2-799]: https://pins-ds.atlassian.net/browse/A2-799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web): A2-799 back hyper link on lpa changed description change page 

- appeals/web/src/client/components/file-uploader/_client-actions.js
https://pins-ds.atlassian.net/browse/A2-825
> fix(web): bugfix/A2-825-fix-2-file-uploads

- appeals/web/src/client/components/show-more/show-more.js
[A2-863](https://pins-ds.atlassian.net/browse/A2-863)
[A2-863]: https://pins-ds.atlassian.net/browse/A2-863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(appeals): A2-863 review and address security logs

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.controller.js
- appeals/web/src/server/lib/mappers/notification-banners.mapper.js
add document updated notification banner whenever a new version of a document is uploaded
A2-732
> fix(web): add document updated notification banner whenever a new version of a document is uploaded

- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-incomplete/outcome-incomplete.controller.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/outcome-incomplete/outcome-incomplete.controller.js
populate updated due date from session on appellant case and lpaq incomplete flows
A2-407
> fix(web): populate updated due date from session on appellant case and lpaq incomplete flows

- appeals/web/src/server/appeals/appeal-details/start-case/start-case.mapper.js
restrict start case page content to 2/3 width
A2-773
> fix(web): restrict start case page content to 2/3 width

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/lib/mappers/appeal.mapper.js
only render issue decision action link when appeal is in appropriate status
A2-394
> fix(web): only render issue decision action link when appeal is in appropriate status

- appeals/web/src/server/appeals/appeal-details/neighbouring-sites/__tests__/__snapshots__/neighbouring-sites.test.js.snap
- appeals/web/src/server/appeals/appeal-details/neighbouring-sites/neighbouring-sites.mapper.js
right align actions column on manage neighbouring sites page
A2-824
> fix(web): right align actions column on manage neighbouring sites page

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/lib/display-page-formatter.js
- appeals/web/src/server/lib/mappers/appellantCase.mapper.js
- appeals/web/src/server/lib/mappers/lpaQuestionnaire.mapper.js
add utility to format summary list rows for document folders
A2-857
> refactor(web): add utility to format summary list rows for document folders

- package-lock.json
[A2-898](https://pins-ds.atlassian.net/browse/A2-898)
[A2-898]: https://pins-ds.atlassian.net/browse/A2-898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(appeals): A2-898 review and address security logs

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/lib/mappers/appeal.mapper.js
https://pins-ds.atlassian.net/browse/A2-808
> fix(web): bugfix/A2-808-remove-change-links-for-not-received-lpaq

- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
> fix(web): bugfix/A2-808-fix-unit-test

- appeals/web/src/server/appeals/appeal-documents/appeal-documents.controller.js
https://pins-ds.atlassian.net/browse/A2-390
> fix(web): bugfix/A2-390-remove-document-uploaded-generic-banner

- infrastructure/environments/prod.tfvars
> feat(web): enable service bus broadcast

- appeals/api/src/database/seed/LPAs/prod.js
> feat(web): add barnet to lpa seed

- appeals/web/package.json
add params to test script in package.json to force hanging failed tests to exit
A2-809
> refactor(web): add params to test script in package.json to force hanging failed tests to exit

- appeals/api/src/database/prisma.batch-delete.js
- appeals/api/src/database/seed/seed-clear.js
Added a batchDelete function for the documentVersion table, to delete records in smaller chunks.
[A2-898]: https://pins-ds.atlassian.net/browse/A2-898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(appeals): fix seed pipeline

- appeals/api/src/server/endpoints/documents/documents.controller.js
https://pins-ds.atlassian.net/browse/A2-941
> fix(appeals): add broadcast to updateDocuments

- azure-pipelines-deploy-appeals.yml
Function deployment isn't work from a tag.
Related changes:
https://github.com/Planning-Inspectorate/back-office/pull/2640
https://github.com/Planning-Inspectorate/applications-service/pull/1307
> fix(tooling): fix function deploy artifact download

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.controller.js
- appeals/web/src/server/appeals/appeal-details/costs/__tests__/__snapshots__/costs.test.js.snap
- appeals/web/src/server/appeals/appeal-details/costs/__tests__/costs.test.js
- appeals/web/src/server/appeals/appeal-details/costs/costs.controller.js
- appeals/web/src/server/appeals/appeal-details/costs/costs.mapper.js
- appeals/web/src/server/appeals/appeal-details/internal-correspondence/__tests__/__snapshots__/internal-correspondence.test.js.snap
- appeals/web/src/server/appeals/appeal-details/internal-correspondence/__tests__/internal-correspondence.test.js
- appeals/web/src/server/appeals/appeal-details/internal-correspondence/internal-correspondence.controller.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/affected-listed-buildings/__tests__/affected-listed-buildings.test.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.controller.js
- appeals/web/src/server/appeals/appeal-documents/__tests__/__snapshots__/appeal-documents.test.js.snap
- appeals/web/src/server/appeals/appeal-documents/__tests__/appeal-documents.test.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js
disable multi file upload in preparation for pilot release, to allow use of the standard check your answers page pattern, and to give us time to address issues with the current multi-file upload implementation
A2-922
> feat(web): disable multi file upload

- appeals/api/src/database/migrations/20240905073536_add_appellant_procedure_fields/migration.sql
- appeals/api/src/database/schema.d.ts
- appeals/api/src/database/schema.prisma
- appeals/api/src/database/seed/data-samples.js
- appeals/api/src/server/common/validators/number-range-parameter.js
- appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
- appeals/api/src/server/endpoints/appeals/appeals.formatter.js
- appeals/api/src/server/endpoints/appellant-cases/__tests__/appellant-cases.test.js
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.controller.js
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.formatter.js
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.validators.js
- appeals/api/src/server/endpoints/constants.js
- appeals/api/src/server/endpoints/integrations/integrations.mappers/appellant-case.mapper.js
- appeals/api/src/server/openapi-types.ts
- appeals/api/src/server/openapi.json
- appeals/api/src/server/swagger.js
- appeals/api/src/server/tests/appeals/mocks.js
[A2-860](https://pins-ds.atlassian.net/browse/A2-860)
[A2-860]: https://pins-ds.atlassian.net/browse/A2-860?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(api): A2-860 new question - preferred procedure

- appeals/api/src/database/migrations/20240906160156_add_is_affecting_neighbouring_sites_to_lpaq/migration.sql
- appeals/api/src/database/schema.prisma
- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/appeals/appeals.formatter.js
- appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.controller.js
- appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.formatter.js
- appeals/api/src/server/openapi-types.ts
- appeals/api/src/server/openapi.json
- appeals/api/src/server/repositories/lpa-questionnaire.repository.js
- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/neighbouring-sites/__tests__/__snapshots__/neighbouring-sites.test.js.snap
- appeals/web/src/server/appeals/appeal-details/neighbouring-sites/neighbouring-sites.mapper.js
- appeals/web/src/server/lib/mappers/appeal.mapper.js
add isAffectingNeighbouringSites to lpaq and fix change page
A2-954
> fix(appeals): add isAffectingNeighbouringSites to lpaq and fix change page

- appeals/e2e/cypress/e2e/back-office-appeals/issueDecision.spec.js
- appeals/e2e/cypress/page_objects/caseDetailsPage.js
- appeals/e2e/cypress/support/happyPathHelper.js
Added initial work for first issue decision test - 'allowed decision' - this is still wip - date work has not been done yet.
(https://pins-ds.atlassian.net/browse/A2-885)
> test(appeals): added to issue desicion e2e tests

- appeals/e2e/cypress/e2e/back-office-appeals/issueDecision.spec.js
- appeals/e2e/cypress/page_objects/dateTimeSection.js
Rewrite of the datetime page page to be simpiler to use and extend
> feat: refactor e2e datetime page object

- appeals/api/src/database/seed/seed-clear-test-data.js
Removes case data from test LPAs - adds additional reference tables that were missed.
> fix(api): delete test data from test LPAs

- infrastructure/document-storage.tf
> feat(): add custom document rbac

- appeals/web/src/client/components/file-uploader/_client-actions.js
- appeals/web/src/client/components/file-uploader/_html.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/costs/__tests__/__snapshots__/costs.test.js.snap
- appeals/web/src/server/appeals/appeal-details/internal-correspondence/__tests__/__snapshots__/internal-correspondence.test.js.snap
- appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/__snapshots__/issue-decision.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/withdrawal/__tests__/__snapshots__/withdrawal.test.js.snap
- appeals/web/src/server/appeals/appeal-documents/__tests__/__snapshots__/appeal-documents.test.js.snap
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.controller.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js
- appeals/web/src/server/views/app/components/file-uploader.component.njk
- appeals/web/src/server/views/appeals/documents/document-upload.njk
https://pins-ds.atlassian.net/browse/A2-887
This PR checks the list of filenames in the `currentFolder` and displays an error if the user attempts to upload a file with a name that already exists in that list.
- [] I have made corresponding changes to the documentation
> feat(web): feature/A2-887-no-duplicate-filenames-to-be-uploaded

- appeals/web/src/client/components/file-uploader/_client-actions.js
> fix(web): bugfix/A2-887-fix-when-no-folder

- appeals/web/src/client/components/file-uploader/_client-actions.js
- appeals/web/src/server/app/app.router.js
- appeals/web/src/server/app/components/file-downloader.component.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/costs/__tests__/__snapshots__/costs.test.js.snap
- appeals/web/src/server/appeals/appeal-details/costs/__tests__/costs.test.js
- appeals/web/src/server/appeals/appeal-details/costs/costs.mapper.js
- appeals/web/src/server/appeals/appeal-details/internal-correspondence/__tests__/__snapshots__/internal-correspondence.test.js.snap
- appeals/web/src/server/appeals/appeal-details/internal-correspondence/__tests__/internal-correspondence.test.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/__snapshots__/issue-decision.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
- appeals/web/src/server/appeals/appeal-details/withdrawal/__tests__/__snapshots__/withdrawal.test.js.snap
- appeals/web/src/server/appeals/appeal-documents/__tests__/__snapshots__/appeal-documents.test.js.snap
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.controller.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js
- appeals/web/src/server/views/app/components/file-uploader.component.njk
- appeals/web/src/styles/7-components/file-upload.scss
fixes to single file upload pilot implementation, based on design review feedback
A2-922
> feat(appeals): fixes to single file upload pilot implementation

- appeals/e2e/cypress/e2e/back-office-appeals/linkAppeals.spec.js
- appeals/e2e/cypress/page_objects/caseDetailsPage.js
Initial e2e test for linking an unlinked appeal to an unlinked appeal
(https://pins-ds.atlassian.net/browse/A2-1033)
> test(appeals): initial  e2e tests for linking an appeal

- appeals/e2e/cypress/page_objects/caseDetailsPage.js
> test(appeals): updated tests for uploading file in issue decision

- appeals/e2e/cypress/e2e/back-office-appeals/changeAppealType.spec.js
- appeals/e2e/cypress/page_objects/caseDetailsPage.js
- appeals/e2e/cypress/page_objects/dateTimeSection.js
> test(appeals): added tests for changing appeal type

- appeals/web/src/server/appeals/appeal-details/appellant-case/address/address.mapper.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/agricultural-holding/agricultural-holding.mapper.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appeal-costs-application/appeal-costs-application.mapper.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/application-decision-date/application-decision-date.mapper.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/lpa-changed-description/lpa-changed-description.mapper.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/ownership-certificate/ownership-certificate.mapper.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/planning-obligation/planning-obligation.mapper.js
- appeals/web/src/server/appeals/appeal-details/green-belt/__tests__/__snapshots__/green-belt.test.js.snap
- appeals/web/src/server/appeals/appeal-details/green-belt/green-belt.mapper.js
- appeals/web/src/server/appeals/appeal-details/inspector-access/inspector-access.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/affected-listed-buildings/affected-listed-buildings.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/correct-appeal-type/correct-appeal-type.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/extra-conditions/extra-conditions.mapper.js
- appeals/web/src/server/appeals/appeal-details/neighbouring-sites/__tests__/__snapshots__/neighbouring-sites.test.js.snap
- appeals/web/src/server/appeals/appeal-details/neighbouring-sites/neighbouring-sites.mapper.js
- appeals/web/src/server/appeals/appeal-details/safety-risks/safety-risks.mapper.js
- appeals/web/src/server/lib/mappers/global-mapper-formatter.js
- appeals/web/src/server/lib/page-components/address.js
- appeals/web/src/server/lib/page-components/radio.js
- appeals/web/src/server/lib/page-components/radio.test.js
Reduce duplicate code by adding utility functions for certain page types.
Tickets:
https://pins-ds.atlassian.net/browse/A2-1097
https://pins-ds.atlassian.net/browse/A2-1098
> refactor(web): extract input page utilities

- appeals/e2e/cypress/e2e/back-office-appeals/issueDecision.spec.js
- appeals/e2e/cypress/page_objects/caseDetailsPage.js
https://pins-ds.atlassian.net/browse/A2-1114
> test(appeals): e2e test for uploading a document on the appellant case

- infrastructure/document-storage.tf
- Removes provider from custom blob role data block
- Adds scope for the data block
> fix(tooling): custom blob role

- appeals/api/package.json
- appeals/web/package.json
- package-lock.json
- packages/express/package.json
[A2-1152](https://pins-ds.atlassian.net/browse/A2-1152)
[A2-1152]: https://pins-ds.atlassian.net/browse/A2-1152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(appeals): A2-1152 address security logs

- appeals/e2e/cypress/e2e/back-office-appeals/manageDocsAppellantCase.spec.js
- appeals/e2e/cypress/page_objects/caseDetailsPage.js
- appeals/e2e/cypress/support/happyPathHelper.js
e2e test for uploading an updated version of a doc on the appellant case
> test(appeals): e2e test for uploading an updated version of a doc

- azure-pipelines-deploy-appeals.yml
Updating common pipeline tag in deploy and release pipelines as these pipelines refers to azure_web_app_deploy.yml
Change: Docker credentials are removed from 'azure_web_app_deploy.yml'
Ticket number: DEV-284
Ticket link: https://pins-ds.atlassian.net/browse/DEV-284
Parent ticket link: https://pins-ds.atlassian.net/browse/DEV-273
> fix(tooling): updating common pipeline tag to 3.18.1

- appeals/e2e/cypress/e2e/back-office-appeals/addCostDecisionRedacted.spec.js
- appeals/e2e/cypress/page_objects/basePage.js
- appeals/e2e/cypress/page_objects/caseDetailsPage.js
Added a test for adding a cost decision which is redacted
A2-1164 https://pins-ds.atlassian.net/browse/A2-1164
- [X ] Other (please explain in the description section above)
- [X ] I have performed a self-review of my own code
- [X ] I have double checked this work does not include any hardcoded secrets or passwords
- [X ] I have made corresponding changes to the documentation
- [X ] I have referenced the ticket number above
- [X ] I have provided a description of the ticket
> test: add test for adding redacted cost decision

- appeals/api/src/database/seed/data-test.js
- appeals/api/src/server/endpoints/representations/representations.controller.js
- appeals/api/src/server/endpoints/representations/representations.service.js
- appeals/api/src/server/repositories/representation.repository.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.controller.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.router.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/__tests__/__snapshots__/interested-party-comments.test.js.snap
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/__tests__/interested-party-comments.test.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/interested-party-comments.controller.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/interested-party-comments.mapper.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/interested-party-comments.router.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/interested-party-comments.service.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/interested-party-comments.types.d.ts
- appeals/web/src/server/lib/mappers/appeal.mapper.js
- appeals/web/src/server/views/appeals/appeal/interested-party-comments.njk
- appeals/web/testing/app/fixtures/referencedata.js
IP Comments page
- tabs with awaiting review, valid and invalid comments
- pagination built in, but not applied. Page size hardcoded at 1000
Related
- comments test data added for S78 appeals
- IP comments row for appeals details built, but not applied. Will be handled in a separate ticket. Needs S78 feature flagging
[A2-594](https://pins-ds.atlassian.net/browse/A2-594)
[A2-456]: https://pins-ds.atlassian.net/browse/A2-456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[A2-585]: https://pins-ds.atlassian.net/browse/A2-585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[A2-594]: https://pins-ds.atlassian.net/browse/A2-594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViL …
> feat(web): A2-594 layout of interested party comments page

- appeals/api/src/database/seed/data-test.js
Adding more S78 appeals to test data
- 2 new appeals in LPAQ status
- 1 more appeal in Validation status
[A2-594 Layout of 'Interested party comments' page](https://pins-ds.atlassian.net/browse/A2-594)
> feat(api): adding more s78 appeals to test data

- appeals/api/src/server/endpoints/appellant-cases/__tests__/appellant-cases.test.js
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.validators.js
[A2-1171](https://pins-ds.atlassian.net/browse/A2-1171)
[A2-1171]: https://pins-ds.atlassian.net/browse/A2-1171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web): A2-1171 API - Preferred Procedure - Validation updates

- appeals/api/src/server/common/validators/string-parameter.js
- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.validators.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.router.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/procedure-preference/__tests__/__snapshots__/procedure-preference.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/procedure-preference/__tests__/procedure-preference.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/procedure-preference/procedure-preference.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/procedure-preference/procedure-preference.mapper.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/procedure-preference/procedure-preference.router.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/procedure-preference/procedure-preference.service.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/procedure-preference/procedure-preference.validators.js
- appeals/web/src/server/lib/mappers/appellant-case/appeal-type-fpa.mapper.js
- appeals/web/src/server/lib/mappers/appellantCase.mapper.js
add appellant case rows for preferred procedure:
- appellantProcedurePreference
- appellantProcedurePreferenceDetails
- appellantProcedurePreferenceDuration
- inquiryHowManyWitnesses
A2-259
> feat(web): add appellant case rows for preferred procedure

- appeals/api/src/server/endpoints/representations/representations.formatter.js
- appeals/api/src/server/openapi-types.ts
- appeals/api/src/server/openapi.json
- appeals/api/src/server/repositories/representation.repository.js
- appeals/api/src/server/tests/representations/mocks.js
- appeals/api/src/server/utils/__tests__/format-name.test.js
- appeals/api/src/server/utils/format-name.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/__tests__/__snapshots__/interested-party-comments.test.js.snap
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/interested-party-comments.controller.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/interested-party-comments.mapper.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/interested-party-comments.middleware.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/interested-party-comments.router.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/interested-party-comments.service.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/interested-party-comments.types.d.ts
- appeals/web/src/server/appeals/appeals.types.d.ts
Set up Interested Party Comment View page. Includes changes to the API to return ServiceUser information with Representations.
* refactor(web): change controller's 404 path to use a guard statement
* feat(api): return representationType as a field from the API
feat(api): return represented ServiceUser in response for Representation
feat(api): return address for represented ServiceUser in Representation
test(api): add unit tests for the new formatName function
feat(web): change Review link to direct to appropriate URL
feat(web): create a route viewing comments and render display-page
feat(web): create a mapper function to render the view IP comment page
chore(web): update test snapshots
* feat(web): change back link to direct back to IP landing page
* feat(api): include document relations …
> Interested Party Comments View page

- appeals/api/src/server/endpoints/integrations/__tests__/document-type-mapping.test.js
- appeals/api/src/server/endpoints/integrations/integrations.mappers/document-folder.mapper.js
- appeals/api/src/server/endpoints/integrations/integrations.mappers/site-visit.mapper.js
- appeals/api/src/server/endpoints/integrations/integrations.service.js
- appeals/api/src/server/repositories/integrations.repository.js
Fixes a couple of regressions following dates refactoring (site visit broadcast) and additional LPAQ documents (plans/drawing defined in both appellant case and lpaq)
> fix(api): integration site visit regression

- appeals/e2e/cypress/e2e/back-office-appeals/issueDecision.spec.js
> test(appeals): updated the uploadDoc function in  issue decision spec

- appeals/web/src/client/components/file-uploader/_server-actions.js
fix issue with file upload delete function not working on dev
A2-918
> fix(web): fix issue with file upload delete function not working on dev

- infrastructure/provider.tf
> chore(appeals): upgrading-tf-to-v-1.9.6

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/procedure-preference/__tests__/__snapshots__/procedure-preference.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/procedure-preference/__tests__/procedure-preference.test.js
- appeals/web/src/server/lib/mappers/appellantCase.mapper.js
change preferred procedure row label to procedure preference
A2-259
> fix(web): change preferred procedure row label to procedure preference

- appeals/api/src/server/common/validators/date-parameter.js
- appeals/api/src/server/endpoints/appeal-decision/__tests__/appeal-decision.test.js
- appeals/api/src/server/endpoints/appeal-timetables/__tests__/appeal-timetables.test.js
- appeals/api/src/server/endpoints/appeal-timetables/appeal-timetables.service.js
- appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
- appeals/api/src/server/endpoints/business-days/__tests__/business-days.test.js
- appeals/api/src/server/endpoints/integrations/integrations.broadcasters/documents.js
- appeals/api/src/server/utils/business-days.js
- appeals/e2e/cypress/page_objects/caseDetailsPage.js
- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
- appeals/web/src/server/appeals/appeal-details/appeal-timetables/appeal-timetables.controller.js
- appeals/web/src/server/lib/__tests__/libraries.test.js
- appeals/web/src/server/lib/dates.js
- appeals/web/src/server/lib/validators/date-input.validator.js
Fixes a date issue with the appeal decision
Fixes e2e tests
> fix(appeals): decision and e2e

- appeals/api/package.json
- appeals/web/package.json
- azure-pipelines-ci.yml
- package.json
- packages/express/package.json
- packages/platform/package.json
- turbo.json
Don't run coverage and open handle detection by default for tests. Still run coverage on the CI pipeline.
> chore(tooling): setup separate test scripts for coverage

- appeals/web/src/client/components/file-uploader/_client-actions.js
Fixes an issue with the newly-refactored file upload component which allows a user to add multiple files even when the component is configured in single-file only mode.
A2-1253
> fix(web): fix issue with file upload component allowing multiple files in single-file mode

- infrastructure/app-web-2.tf
- infrastructure/app-web.tf
Aligned read-only group as `APPEALS_READERS_GROUP_ID` setting
> fix(appeals): mapping of read-only group

- appeals/web/src/server/lib/mappers/appeal/submappers/ip-comments-due-date.mapper.js
- appeals/web/src/server/lib/mappers/appeal/submappers/lpa-statement-due-date.mapper.js
> feat(web): feature/A2-902-copy-update

- appeals/web/environment/config.d.ts
- appeals/web/environment/config.js
- appeals/web/environment/schema.js
- appeals/web/src/server/app/app.express.js
Ensure static assets have a non-zero max-age applied. To be improved in the future with immutable assets and cache-busting techniques.
> chore(web): add cache control max-age

- appeals/api/src/server/endpoints/change-appeal-type/__tests__/change-appeal-type.test.js
- appeals/api/src/server/endpoints/change-appeal-type/change-appeal-type.service.js
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.controller.js
Another date issue - double validation was setting an incorrect date
[A2-1267](https://pins-ds.atlassian.net/browse/A2-1267)
[A2-1267]: https://pins-ds.atlassian.net/browse/A2-1267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(appeals): change appeal type

- appeals/web/src/server/appeals/appeal-details/appellant-case/application-outcome/__tests__/__snapshots__/application-outcome.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/application-outcome/application-outcome.mapper.js
- appeals/web/src/server/lib/mappers/appellantCase.mapper.js
Changed 'Granted' to 'Granted with conditions'
[A2-163](https://pins-ds.atlassian.net.mcas.ms/browse/A2-163)
[A2-163]: https://pins-ds.atlassian.net/browse/A2-163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web): content update to application outcome

- appeals/web/src/server/app/app.router.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.controller.js
- appeals/web/src/server/appeals/appeal-details/costs/costs.controller.js
- appeals/web/src/server/appeals/appeal-details/internal-correspondence/internal-correspondence.controller.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.controller.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.controller.js
- appeals/web/src/server/appeals/appeal-details/withdrawal/__tests__/__snapshots__/withdrawal.test.js.snap
- appeals/web/src/server/appeals/appeal-details/withdrawal/withdrawal.controller.js
- appeals/web/src/server/appeals/appeal-details/withdrawal/withdrawal.mapper.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.controller.js
refactor shared document functions to use destructured object parameters
A2-949
> refactor(web): refactor shared document functions to use destructured object parameters

- appeals/web/package.json
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/__tests__/__snapshots__/interested-party-comments.test.js.snap
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/__tests__/interested-party-comments.test.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/interested-party-comments.controller.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/interested-party-comments.mapper.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/interested-party-comments.router.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/interested-party-comments.validators.js
- appeals/web/testing/app/fixtures/referencedata.js
- packages/appeals/constants/common.js
Added Review comment UI.
[A2-940](https://pins-ds.atlassian.net/browse/A2-940)
[A2-940]: https://pins-ds.atlassian.net/browse/A2-940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(web): A2-940 Review comment page for an IP comment uploaded manually to the BO

- appeals/web/src/server/appeals/appeal-details/appellant-case/procedure-preference/__tests__/procedure-preference.test.js
- appeals/web/src/server/lib/mappers/appellantCase.mapper.js
fix for appellant expected length of procedure showing null days when value is null
A2-259
> fix(web): fix for appellant expected length of procedure showing null days when value is null

- appeals/api/src/server/endpoints/case-notes/case-notes.routes.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
Fixes a conflict that reverted inspector permission fix
Removes redundant route on case note API
> fix(web): revert permission on appeal detail mapper

- azure-pipelines-deploy-appeals.yml
> chore(tooling): make prod depend on training

- docs/basic-setup.md
Updates basic setup documentation related to the creation of SQL docker image.
Latest images require a different configuration, as the old one may fail on startup on Docker > 4.33
> docs(appeals): updated docs on SQL docker image

- appeals/api/src/database/migrations/20241014115538_add_representation_site_visit_request/migration.sql
- appeals/api/src/database/schema.prisma
- appeals/api/src/database/seed/data-samples.js
- appeals/api/src/server/endpoints/representations/representations.formatter.js
- appeals/api/src/server/openapi-types.ts
- appeals/api/src/server/openapi.json
- appeals/api/src/server/tests/representations/mocks.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/__tests__/__snapshots__/interested-party-comments.test.js.snap
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/__tests__/interested-party-comments.test.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/interested-party-comments.mapper.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/interested-party-comments.types.d.ts
- appeals/web/testing/app/fixtures/referencedata.js
[A2-907](https://pins-ds.atlassian.net/browse/A2-907)
[A2-907]: https://pins-ds.atlassian.net/browse/A2-907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(web): A2-907 interested party comment page for an invalid comment submitted via the fo

- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/appellant-cases/__tests__/appellant-cases.test.js
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.controller.js
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.service.js
- appeals/api/src/server/endpoints/lpa-questionnaires/__tests__/lpa-questionnaires.test.js
- appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.service.js
Adds handling of newly introduced variables for Notify calls
> fix(api): introduce `lpa_reference` where needed

- appeals/web/src/server/appeals/appeal-details/interested-party-comments/__tests__/__snapshots__/interested-party-comments.test.js.snap
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/__tests__/interested-party-comments.test.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/interested-party-comments.controller.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/interested-party-comments.mapper.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/interested-party-comments.service.js
- appeals/web/src/server/appeals/appeal.constants.js
- appeals/web/src/server/lib/mappers/notification-banners.mapper.js
Ticket: https://pins-ds.atlassian.net/browse/A2-67
https://github.com/user-attachments/assets/79f6173b-7e83-41da-a2a1-036f13374802
> feat(web): mark ip comments as valid

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap
- appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.mapper.js
- appeals/web/testing/app/fixtures/referencedata.js
A2-1304
site visit fixes displaying 0 correctly
> fix(web): bugfix/A2-1304-site-visit-fix-displaying-0-correctly

- appeals/api/src/database/migrations/20241018110551_add_representation_source/migration.sql
- appeals/api/src/database/schema.prisma
- appeals/api/src/database/seed/data-test.js
> feat(api): add source to representations

- appeals/api/src/server/endpoints/appeal-decision/appeal-decision.validator.js
https://pins-ds.atlassian.net/browse/A2-1265
> fix(api): bugfix/A2-1265-no-biz-date-validator

- infrastructure/front-door-web.tf
https://pins-ds.atlassian.net/browse/DEV-289
> feat(infrastructure): add ip-block WAF rule

- infrastructure/front-door-web.tf
> chore(infrastructure): update rate limit in line with guidance

- appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-ip-comment/add-ip-comment.controller.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-ip-comment/add-ip-comment.router.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-ip-comment/add-ip-comment.service.js
* feat(web): create a post handler for file upload step of add IP comment
refactor: return whole folder from getAttachmentsFolder
Will need to test in dev.
[A2-604](https://pins-ds.atlassian.net/browse/A2-604)
[A2-604]: https://pins-ds.atlassian.net/browse/A2-604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(web): create a post handler for file upload step of add IP comment

- appeals/web/src/server/appeals/appeal-details/interested-party-comments/interested-party-comments.mapper.js
Change IP comments back link to lead to personal-list page.
This was flagged up as not matching the ACs during test.
[A2-588](https://pins-ds.atlassian.net/browse/A2-588)
[A2-588]: https://pins-ds.atlassian.net/browse/A2-588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web): change IP comments back link to lead to personal-list page

- appeals/web/src/server/appeals/appeal-details/accordions/s78.js
> fix(web): move ip comments up in appeal docs

- appeals/web/src/server/appeals/appeal-details/accordions/index.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
- appeals/web/src/server/appeals/appeal-details/case-notes/case-notes.mapper.js
- appeals/web/src/server/appeals/appeal-details/case-summary/case-summary.mapper.js
- appeals/web/src/server/appeals/appeal-details/status-tags/status-tags.mapper.js
> refactor(web): clean up appeal detail mappers

- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js
Fixing display of additional S78 rows
> fix(web): display of S78 uploads LPAQ

- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.controller.js
- appeals/web/src/server/lib/mappers/lpa-questionnaire/submappers/map-eia-environmental-statement.js
Fixes the copy for doc upload and folder view (EIA Environmental statement)
> fix(web): copy for EIA docs

- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.controller.js
Fixes and align upload copy on EIA folders
> fix(web): copy for EIA uploads

- appeals/api/package.json
- package-lock.json
- package.json
Upgrades data-model version to 1.9.2, which has additional HAS document types sent from LPAQ.
> feat(appeals): upgrade data-model to v1.9.2

- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/constants.js
- appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.controller.js
- appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.formatter.js
- appeals/api/src/server/repositories/lpa-questionnaire.repository.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/is-infrastructure-levy-formally-adopted/__tests__/__snapshots__/is-infrastructure-levy-formally-adopted.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/is-infrastructure-levy-formally-adopted/__tests__/is-infrastructure-levy-formally-adopted.test.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/is-infrastructure-levy-formally-adopted/is-infrastructure-levy-formally-adopted.controller.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/is-infrastructure-levy-formally-adopted/is-infrastructure-levy-formally-adopted.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/is-infrastructure-levy-formally-adopted/is-infrastructure-levy-formally-adopted.router.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/is-infrastructure-levy-formally-adopted/is-infrastructure-levy-formally-adopted.service.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.router.js
- appeals/web/src/server/lib/mappers/lpa-questionnaire/s78.js
- appeals/web/src/server/lib/mappers/lpa-questionnaire/submappers/map-is-infrastructure-levy-formally-adopted.js
add boolean row and change page for isInfrastructureLevyFormallyAdopted
A2-1150
> feat(appeals): add boolean row and change page for isInfrastructureLevyFormallyAdopted

- appeals/api/src/database/seed/seed-clear-test-data.js
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.controller.js
When trying to run a pipeline that deletes test cases, the pipeline failed since the introduction of case notes.
Quick fix to delete case notes as well as part of the script.
Also fixed a regression on uploading decision letter (defaults to no redaction required).
> fix(appeals): adding notes to clear test data, small regression on decision

- appeals/api/src/database/seed/seed-clear.js
> fix(api): delete rep text and selections in seed

- appeals/web/src/server/lib/mappers/appeal/submappers/ip-comments-due-date.mapper.js
Small issue with an incorrect route...
> fix(web): ip-comments deadline update link

- appeals/web/src/server/appeals/appeal-details/appellant-case/appeal-costs-application/__tests__/__snapshots__/appeal-costs-application.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/lpa-changed-description/__tests__/__snapshots__/lpa-changed-description.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/affects-scheduled-monument/__tests__/__snapshots__/affects-scheduled-monument.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/affects-scheduled-monument/affects-scheduled-monument.controller.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/affects-scheduled-monument/affects-scheduled-monument.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/has-protected-species/has-protected-species.controller.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/has-protected-species/has-protected-species.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/is-aonb-national-landscape/__tests__/__snapshots__/is-aonb-national-landscape.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/is-aonb-national-landscape/is-aonb-national-landscape.controller.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/is-aonb-national-landscape/is-aonb-national-landscape.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/is-gypsy-or-traveller-site/is-gypsy-or-traveller-site.controller.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/is-gypsy-or-traveller-site/is-gypsy-or-traveller-site.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/is-infrastructure-levy-formally-adopted/is-infrastructure-levy-formally-adopted.controller.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/is-infrastructure-levy-formally-adopted/is-infrastructure-levy-formally-adopted.mapper.js
- appeals/web/src/server/lib/mappers/appeal/submappers/appellant-final-comment-due-date.mapper.js
- appeals/web/src/server/lib/mappers/appeal/submappers/appellant-statement-due-date.mapper.js
- appeals/web/src/server/lib/mappers/appeal/submappers/ip-comments-due-date.mapper.js
- appeals/web/src/server/lib/mappers/appeal/submappers/issue-determination-date.mapper.js
- appeals/web/src/server/lib/mappers/appeal/submappers/lpa-questionnaire-due-date.mapper.js
- appeals/web/src/server/lib/mappers/appeal/submappers/lpa-statement-due-date.mapper.js
- appeals/web/src/server/lib/mappers/appeal/submappers/s106-obligation-due-date.mapper.js
- appeals/web/src/server/lib/mappers/components/radio.js
Fix binding of correct `bool` in `components/radio`. Used by submappers for appellant case and lpaq.
[A2-1460](https://pins-ds.atlassian.net/browse/A2-1460)
[A2-1460]: https://pins-ds.atlassian.net/browse/A2-1460?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web): binding of components/radio - A2-1460

- appeals/api/src/database/seed/data-test.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/view-and-review/__tests__/__snapshots__/view-and-review.test.js.snap
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/view-and-review/view-and-review.controller.js
- appeals/web/src/server/lib/mappers/notification-banners.mapper.js
- appeals/web/src/server/lib/mappers/page-components/interested-party-comments/view-and-review/common.js
fix(web): improve ip comment seed, fix reject and redact flows
> fix(web): improve ip comment seed, fix reject and redact flows

- appeals/web/src/server/lib/dates.js
- appeals/web/src/server/lib/mappers/appeal/submappers/appellant-final-comment-due-date.mapper.js
- appeals/web/src/server/lib/mappers/appeal/submappers/appellant-statement-due-date.mapper.js
- appeals/web/src/server/lib/mappers/appeal/submappers/complete-date.mapper.js
- appeals/web/src/server/lib/mappers/appeal/submappers/ip-comments-due-date.mapper.js
- appeals/web/src/server/lib/mappers/appeal/submappers/issue-determination-date.mapper.js
- appeals/web/src/server/lib/mappers/appeal/submappers/lpa-final-comment-due-date.mapper.js
- appeals/web/src/server/lib/mappers/appeal/submappers/lpa-questionnaire-due-date.mapper.js
- appeals/web/src/server/lib/mappers/appeal/submappers/lpa-statement-due-date.mapper.js
- appeals/web/src/server/lib/mappers/appeal/submappers/s106-obligation-due-date.mapper.js
- appeals/web/src/server/lib/mappers/appeal/submappers/started-at.mapper.js
- appeals/web/src/server/lib/mappers/appeal/submappers/valid-at.mapper.js
- packages/appeals/constants/documents.js
Fixes the validation of PPTX files
Adds an overrideable default for no input in date function
Align usage of some date mappers
> fix(appeals): pptx upload

- appeals/api/src/database/seed/data-samples.js
- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.controller.js
- appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.formatter.js
- appeals/api/src/server/repositories/lpa-questionnaire.repository.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/infrastructure-levy-adopted-date/__tests__/__snapshots__/infrastructure-levy-adopted-date.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/infrastructure-levy-adopted-date/__tests__/infrastructure-levy-adopted-date.test.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/infrastructure-levy-adopted-date/infrastructure-levy-adopted-date.controller.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/infrastructure-levy-adopted-date/infrastructure-levy-adopted-date.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/infrastructure-levy-adopted-date/infrastructure-levy-adopted-date.router.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/infrastructure-levy-adopted-date/infrastructure-levy-adopted-date.service.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/infrastructure-levy-adopted-date/infrastructure-levy-adopted-date.validator.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/infrastructure-levy-expected-date/__tests__/__snapshots__/infrastructure-levy-expected-date.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/infrastructure-levy-expected-date/__tests__/infrastructure-levy-expected-date.test.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/infrastructure-levy-expected-date/infrastructure-levy-expected-date.controller.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/infrastructure-levy-expected-date/infrastructure-levy-expected-date.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/infrastructure-levy-expected-date/infrastructure-levy-expected-date.router.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/infrastructure-levy-expected-date/infrastructure-levy-expected-date.service.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/infrastructure-levy-expected-date/infrastructure-levy-expected-date.validator.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.router.js
- appeals/web/src/server/lib/mappers/components/instructions/date.js
- appeals/web/src/server/lib/mappers/components/instructions/index.js
- appeals/web/src/server/lib/mappers/components/page-components/date.js
- appeals/web/src/server/lib/mappers/components/page-components/index.js
- appeals/web/src/server/lib/mappers/lpa-questionnaire/s78.js
- appeals/web/src/server/lib/mappers/lpa-questionnaire/submappers/map-infrastructure-levy-adopted-date.js
- appeals/web/src/server/lib/mappers/lpa-questionnaire/submappers/map-infrastructure-levy-expected-date.js
add rows to s78 appellant case for infrastructure levy adopted date and expected date
A2-1286
> feat(appeals): add rows to s78 appellant case for infrastructure levy adopted date and expected date

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appeal-details.router.js
- appeals/web/src/server/appeals/appeal-details/internal-correspondence/internal-correspondence.router.js
- appeals/web/src/server/lib/mappers/appeal/submappers/cross-team-correspondence.mapper.js
- appeals/web/src/server/lib/mappers/appeal/submappers/inspector-correspondence.mapper.js
- appeals/web/src/server/lib/mappers/appeal/submappers/started-at.mapper.js
- appeals/web/src/server/lib/mappers/appeal/submappers/valid-at.mapper.js
- Aligns the behaviour of valid and start items in timetable
- Allows inspectors to manage and add internal correspondence
> fix(web): aligning behaviour of valid and start in timetables

- appeals/api/src/server/endpoints/documents/documents.controller.js
> fix(api): doc rename broadcast failure

- appeals/web/src/server/appeals/appeal-details/interested-party-comments/redact/redact.controller.js
- appeals/web/src/server/lib/mappers/components/page-components/notification-banners.mapper.js
> refactor(web): correct redirect

- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/is-gypsy-or-traveller-site/is-gypsy-or-traveller-site.controller.js
Boolean not binding set value
[A2-1460](https://pins-ds.atlassian.net/browse/A2-1460)
[A2-1460]: https://pins-ds.atlassian.net/browse/A2-1460?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web): binding of bool (gypsy-traveller a2-1460)

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.mapper.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-incomplete/outcome-incomplete.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/outcome-valid/outcome-valid.controller.js
- appeals/web/src/server/lib/dates.js
- Prefills the date set when a case is valid to the received date
- Prefills the date set when a case is incomplete to a future date based on the original LPA decision date and the appeal type
[A2-161](https://pins-ds.atlassian.net/browse/A2-161)
[A2-1148](https://pins-ds.atlassian.net/browse/A2-1148)
[A2-161]: https://pins-ds.atlassian.net/browse/A2-161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[A2-1148]: https://pins-ds.atlassian.net/browse/A2-1148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(appeals): prefilled dates on case validation

- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/documents/__tests__/documents.test.js
- appeals/api/src/server/endpoints/documents/documents.controller.js
- appeals/api/src/server/endpoints/integrations/integrations.broadcasters/appeal.js
- appeals/api/src/server/endpoints/integrations/integrations.broadcasters/documents.js
- appeals/api/src/server/endpoints/integrations/integrations.broadcasters/event.js
- appeals/api/src/server/endpoints/integrations/integrations.broadcasters/service-users.js
- appeals/api/src/server/repositories/document.repository.js
Broadcast a document update when AV scan completes
[A2-1585](https://pins-ds.atlassian.net/browse/A2-1585)
[A2-1585]: https://pins-ds.atlassian.net/browse/A2-1585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(appeals): broadcast AV check A2-1585

- infrastructure/environments/dev.tfvars
- infrastructure/environments/prod.tfvars
- infrastructure/environments/test.tfvars
- infrastructure/environments/training.tfvars
- infrastructure/front-door-web.tf
- infrastructure/variables.tf
Adds an infra configuration for rate limiting on the WAF. Set as 1500/5...
> feat(appeals): infra config for WAF rate limiting

- appeals/e2e/cypress/fixtures/appealsApiRequests.js
- appeals/e2e/cypress/support/apiPaths.js
- appeals/e2e/cypress/support/appealsApiClient.js
- adds correct documents to the api requests, depending on environment
- modifies 1st line of address for cases created with automation with `e2e Test Address`
> test(test/e2e): improved submissions to create cases

- appeals/api/src/server/endpoints/appeal-decision/appeal-decision.validator.js
- appeals/api/src/server/openapi-types.ts
- appeals/api/src/server/openapi.json
- appeals/api/src/server/swagger.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/view-and-review/__tests__/__snapshots__/view-and-review.test.js.snap
- appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/issue-decision.test.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.router.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.validators.js
https://pins-ds.atlassian.net/browse/A2-1265
Issue decision date must be a business day
> fix(web): bugfix/A2-1265-issue-decision-date-must-be-business-day

- appeals/api/Dockerfile
- appeals/api/src/server/build-app.js
- appeals/api/src/server/config/config.js
- appeals/api/src/server/config/schema.js
- appeals/web/Dockerfile
- appeals/web/environment/base-config.js
- appeals/web/environment/config.d.ts
- appeals/web/environment/schema.js
- appeals/web/src/server/app/app.controller.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/view-and-review/__tests__/__snapshots__/view-and-review.test.js.snap
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/view-and-review/__tests__/view-and-review.test.js
- azure-pipelines-build.yml
- azure-pipelines-deploy-appeals.yml
- packages/scripts/verify_commit_hash.sh
Verifies that docker images are correctly deployed, by verifying the commit hash of the released build.
Screenshot of the deployment task in appeals API:
Screenshot of the deployment task in appeals Web:
> chore(tooling): verify deployment hash

- appeals/web/src/server/appeals/appeal-details/costs/__tests__/__snapshots__/costs.test.js.snap
- appeals/web/src/server/appeals/appeal-details/costs/costs.controller.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/view-and-review/__tests__/view-and-review.test.js
- appeals/web/src/server/appeals/appeal-details/internal-correspondence/__tests__/__snapshots__/internal-correspondence.test.js.snap
- appeals/web/src/server/appeals/appeal-details/internal-correspondence/internal-correspondence.controller.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.controller.js
update file upload flows to allow multiple files where appropriate
A2-1325
> feat(web): update file upload flows to allow multiple files where appropriate

- appeals/api/src/server/endpoints/business-days/__tests__/business-days.test.js
- appeals/api/src/server/endpoints/business-days/business-days.controller.js
- appeals/api/src/server/endpoints/business-days/business-days.routes.js
- appeals/api/src/server/openapi-types.ts
- appeals/api/src/server/openapi.json
- appeals/api/src/server/swagger.js
- appeals/api/src/server/utils/business-days.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/view-and-review/__tests__/view-and-review.test.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/view-and-review/page-components/reject.mapper.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/view-and-review/view-and-review.controller.js
- appeals/web/src/server/lib/dates.js
* feat(api): create API endpoint for adding business days to date
* feat(web): call the new add-business-days endpoint from the web app
* test(api): add unit tests for add-business-days endpoint
Tested locally and added unit tests.
> Add business days

- infrastructure/data.tf
- infrastructure/environments/dev.tfvars
- infrastructure/environments/prod.tfvars
- infrastructure/environments/test.tfvars
- infrastructure/environments/training.tfvars
- infrastructure/front-door-docs.tf
- infrastructure/front-door-web.tf
- infrastructure/provider.tf
- infrastructure/variables.tf
> test(tooling): adding frontdoor tooling to dev and test

- appeals/web/src/server/appeals/appeal-details/interested-party-comments/redact/__tests__/__snapshots__/redact.test.js.snap
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/redact/confirm.mapper.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/redact/redact.controller.js
- appeals/web/src/server/lib/mappers/components/page-components/notification-banners.mapper.js
Updating the text and redirect functionality of redacting a valid comment
https://pins-ds.atlassian.net/browse/A2-1364
> feat(web): updating valid comment redaction cta functionality

- appeals/web/package.json
- appeals/web/src/server/app/app.router.js
- appeals/web/src/server/app/components/file-downloader.component.js
- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
- appeals/web/src/server/appeals/appeal-documents/appeal.documents.service.js
- appeals/web/src/server/lib/mappers/components/instructions/text.js
- appeals/web/src/server/lib/mappers/data/appeal/has.js
- appeals/web/src/server/lib/mappers/data/appeal/submappers/case-files-download.mapper.js
- appeals/web/src/server/lib/mappers/types.js
- package-lock.json
Adds a bulk download button on the appeal detail page. This will trigger a zip file download containing all appeal documents, except internal correspondence.
[A2-1167](https://pins-ds.atlassian.net/browse/A2-1167)
[A2-1167]: https://pins-ds.atlassian.net/browse/A2-1167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(appeals): bulk download A2-1167

- infrastructure/app-api.tf
- infrastructure/app-web.tf
Permissions on slots from infra-modules 1.30
> fix(appeals): use infra-modules 1.30

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/appeal-details/case-notes/case-notes.controller.js
- appeals/web/src/server/appeals/appeal-details/case-notes/case-notes.formatter.js
- appeals/web/src/server/appeals/appeal-details/case-notes/case-notes.mapper.js
- appeals/web/src/server/views/appeals/components/case-notes.njk
- Replace basic textarea on case notes with character count textarea.
- Using session to store comment if validation fails.
- Test added for 300 characters max
[A2-1583 BO: Apply character count to Case Notes textarea](https://pins-ds.atlassian.net.mcas.ms/browse/A2-1583)
> Case notes character count

- appeals/api/src/database/seed/LPAs/prod.js
Additional LPAs for production release:
- Richmond
- Havering
- Greenwich
- Bromley
[A2-823](https://pins-ds.atlassian.net/browse/A2-823)
[A2-823]: https://pins-ds.atlassian.net/browse/A2-823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(api): adds 4 additional LPAs on prod

- appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-document/router.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-ip-comment/__tests__/add-ip-comment.test.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-ip-comment/add-ip-comment.router.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-ip-comment/add-ip-comment.validators.js
> fix(web): Fix add comment date submitted validation

- appeals/api/src/server/endpoints/invalid-appeal-decision/__tests__/invalid-appeal-decision.test.js
- appeals/api/src/server/repositories/representation.repository.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-ip-comment/__tests__/add-ip-comment.test.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-ip-comment/add-ip-comment.controller.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-ip-comment/add-ip-comment.mapper.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-ip-comment/add-ip-comment.router.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-ip-comment/add-ip-comment.service.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/interested-party-comments.types.d.ts
Fixes and improvements to the add ip comment flow
[A2-1586](https://pins-ds.atlassian.net/browse/A2-1586)
[A2-1586]: https://pins-ds.atlassian.net/browse/A2-1586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(api): A2-1586 Add IP Address - New Address not displaying on add comment page

- appeals/web/src/server/appeals/appeal-details/interested-party-comments/view-and-review/reject/reject.controller.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/view-and-review/reject/reject.validators.js
* fix(web): prevent throw when errors are present but not [''] property
[A2-1670](https://pins-ds.atlassian.net/browse/A2-1670)
[A2-1670]: https://pins-ds.atlassian.net/browse/A2-1670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web): prevent throw when errors are present but not [''] property

- appeals/api/src/database/seed/data-samples.js
- appeals/api/src/database/seed/data-test.js
- appeals/api/src/database/seed/data-utilities.js
- appeals/api/src/server/common/validators/number-parameter.js
- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.controller.js
- appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.formatter.js
- appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.validators.js
- appeals/api/src/server/repositories/lpa-questionnaire.repository.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/procedure-preference/__tests__/procedure-preference.test.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.router.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/procedure-preference/__tests__/__snapshots__/procedure-preference.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/procedure-preference/__tests__/procedure-preference.test.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/procedure-preference/procedure-preference.controller.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/procedure-preference/procedure-preference.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/procedure-preference/procedure-preference.router.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/procedure-preference/procedure-preference.service.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/procedure-preference/procedure-preference.validators.js
- appeals/web/src/server/lib/mappers/components/page-components/index.js
- appeals/web/src/server/lib/mappers/components/page-components/input.js
- appeals/web/src/server/lib/mappers/components/page-components/textarea.js
- appeals/web/src/server/lib/mappers/data/lpa-questionnaire/s78.js
- appeals/web/src/server/lib/mappers/data/lpa-questionnaire/submappers/map-procedure-preference-details.js
- appeals/web/src/server/lib/mappers/data/lpa-questionnaire/submappers/map-procedure-preference-duration.js
- appeals/web/src/server/lib/mappers/data/lpa-questionnaire/submappers/map-procedure-preference.js
- Add procedure preference rows for s78 lpaq
- Add supporting improvements to seeding code
- Refactor appellant case procedure preference feature code and unit tests to reflect improvements made in equivalent LPAQ code
A2-1588
> feat(appeals): add procedure preference rows for s78 lpaq, supporting improvements to seeding code

- appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-document/controller/check-your-answers.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-document/router.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/common/redaction-status.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/view-and-review/page-components/review.mapper.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/view-and-review/view-and-review.controller.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/view-and-review/view-and-review.middleware.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/view-and-review/view-and-review.router.js
- appeals/web/src/server/appeals/appeal.constants.js
- appeals/web/src/server/lib/mappers/components/page-components/check-your-answers.js
- appeals/web/src/server/lib/mappers/components/page-components/notification-banners.mapper.js
> feat(web): a2-1315 Add doc to IP comment cya page

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/views/appeals/components/case-notes.njk
> fix(web): a2-1404 make case notes 2/3

- appeals/api/src/server/endpoints/constants.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/view-and-review/page-components/reject.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/affected-listed-buildings/affected-listed-buildings.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/has-community-infrastructure-levy/__tests__/__snapshots__/has-community-infrastructure-levy.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/has-community-infrastructure-levy/__tests__/has-community-infrastructure-levy.test.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/has-community-infrastructure-levy/has-community-infrastructure-levy.router.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/has-community-infrastructure-levy/has-community-infrastructure-levy.validator.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/is-infrastructure-levy-formally-adopted/__tests__/__snapshots__/is-infrastructure-levy-formally-adopted.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/is-infrastructure-levy-formally-adopted/__tests__/is-infrastructure-levy-formally-adopted.test.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/is-infrastructure-levy-formally-adopted/is-infrastructure-levy-formally-adopted.router.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/is-infrastructure-levy-formally-adopted/is-infrastructure-levy-formally-adopted.validator.js
- appeals/web/src/server/lib/mappers/components/page-components/radio.js
- appeals/web/src/server/lib/mappers/components/page-components/radio.test.js
fix validation and case history entries for s78 lpa infrastructure levy rows
A2-1336
> fix(appeals): fix validation and case history entries for s78 lpa infrastructure levy rows

- appeals/e2e/cypress/e2e/back-office-appeals/changeStartDate.spec.js
- appeals/e2e/cypress/e2e/back-office-appeals/relatedAppeals.spec.js
- appeals/e2e/cypress/fixtures/appealsApiRequests.js
- appeals/e2e/cypress/page_objects/caseDetailsPage.js
- appeals/e2e/cypress/page_objects/dateTimeSection.js
Added e2e tests for 'relating'  an unrelated appeal to an unrelated appeal and an unrelated appeal to a related appeal
> test(appeals): added e2e tests for 2 related appeals scenarios

- appeals/web/src/server/appeals/appeal-details/interested-party-comments/__tests__/__snapshots__/interested-party-comments.test.js.snap
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/interested-party-comments.mapper.js
> fix(web): a2-1692 add more width to ip columns

- appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-document/router.js
> fix(web): fix cya post 404

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/lib/mappers/data/appellant-case/submappers/application-decision-date.js
- appeals/web/src/server/lib/mappers/data/appellant-case/submappers/application-decision.js
- appeals/web/src/server/lib/mappers/data/appellant-case/submappers/decision-letter.js
- appeals/web/src/server/lib/mappers/data/appellant-case/submappers/supporting-documents.js
https://pins-ds.atlassian.net/browse/A2-1186
> feat(web): feature/A2-1186-copy-update

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.mapper.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/page-components/fpa.mapper.js
- appeals/web/src/server/lib/mappers/data/appellant-case/submappers/ownership-certificate.js
https://pins-ds.atlassian.net/browse/A2-1187
> feat(web): feature/A2-1187-s78-row-reorder

- appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-ip-comment/__tests__/__snapshots__/add-ip-comment.test.js.snap
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-ip-comment/add-ip-comment.controller.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-ip-comment/add-ip-comment.mapper.js
> fix(web): add comment cya page tweaks

- appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-document/controller/check-your-answers.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-document/controller/index.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-ip-comment/__tests__/__snapshots__/add-ip-comment.test.js.snap
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/common/date-submitted.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/view-and-review/__tests__/view-and-review.test.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/view-and-review/view-and-review.middleware.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/view-and-review/view-and-review.router.js
- appeals/web/src/server/lib/mappers/components/page-components/date.js
- appeals/web/testing/app/fixtures/referencedata.js
> fix(web): a2-626 fix back buttons and date hint

- appeals/web/src/server/lib/mappers/components/page-components/notification-banners.mapper.js
> fix(web): display success banner on add comment a2-1698

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.mapper.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/page-components/s78.mapper.js
- appeals/web/src/server/lib/mappers/data/appellant-case/submappers/new-plans-drawings.js
- appeals/web/src/server/lib/mappers/data/appellant-case/submappers/other-new-documents.js
> feat(web): row reshuffle

- appeals/web/src/server/lib/mappers/components/page-components/notification-banners.mapper.js
fix(web): change 'Comment invalid' to 'Comment rejected' in banner
[A2-1184](https://pins-ds.atlassian.net/browse/A2-1184)
[A2-1184]: https://pins-ds.atlassian.net/browse/A2-1184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web): change 'Comment invalid' to 'Comment rejected' in banner

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.mapper.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/application-decision-date/__tests__/__snapshots__/application-decision-date.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/application-decision-date/__tests__/application-decision-date.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/application-decision-date/application-decision-date.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/application-decision-date/application-decision-date.mapper.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/application-decision-date/application-decision-date.router.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/application-outcome/__tests__/__snapshots__/application-outcome.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/application-outcome/__tests__/application-outcome.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/application-outcome/application-outcome.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/application-outcome/application-outcome.mapper.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/application-outcome/application-outcome.validators.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/procedure-preference/__tests__/__snapshots__/procedure-preference.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/procedure-preference/procedure-preference.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/procedure-preference/procedure-preference.mapper.js
- appeals/web/src/server/lib/mappers/components/page-components/radio.js
fix copy in appellant case application details rows and change pages
A2-1186
> fix(web): fix copy in appellant case application details rows and change pages

- appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-document/controller/check-your-answers.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-ip-comment/add-ip-comment.controller.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/common/redaction-status.js
> fix(web): set redaction status

- appeals/api/src/database/seed/data-static.js
Updating copy order and alignment for rejection reasons
https://pins-ds.atlassian.net/browse/A2-1614?atlOrigin=eyJpIjoiOTcyZjBmMWRjMGM5NDJhMWIyYjU2MDQzZDQwNmJlZjIiLCJwIjoiaiJ9
> fix(web): updating copy order and text for rejection reasons

- appeals/web/src/server/lib/mappers/components/page-components/notification-banners.mapper.js
> fix(web): fix ip comment doc added banner text

- appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-ip-comment/__tests__/__snapshots__/add-ip-comment.test.js.snap
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-ip-comment/add-ip-comment.controller.js
> fix(web): fix add ip comment change links

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
> fix(web): bugfix/fix-broken-web-tests

- appeals/web/src/styles/7-components/app-header.scss
WEB:
- Header Logo
- Updated app-header.scss to prevent navigation overlaying the logo in a mobile device or when page zoomed in.
TESTING:
[A2-1531 Implement new royal crest across all pages (BO)](https://pins-ds.atlassian.net/browse/A2-1531)
> fix(appeals): nav header should be responsive (a2-1532)

- appeals/api/src/database/seed/data-test.js
Makes dates in seed appeals more varied...
Adds reviewed comments
> feat(api): mixing up the seed

- appeals/web/src/server/appeals/appeal-details/appellant-case/procedure-preference/__tests__/__snapshots__/procedure-preference.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/procedure-preference/__tests__/procedure-preference.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/procedure-preference/procedure-preference.validators.js
https://pins-ds.atlassian.net/browse/A2-1293
> fix(web): bugfix/A2-1293-missing-validators

- appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-ip-comment/__tests__/__snapshots__/add-ip-comment.test.js.snap
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-ip-comment/add-ip-comment.controller.js
> fix(web): s

- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/__tests__/interested-party-comments.test.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-ip-comment/__tests__/add-ip-comment.test.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-ip-comment/add-ip-comment.service.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/interested-party-comments.service.js
Small fix for a bug introduced in previous PR for A2-1772
> fix(web): correct type=comments to type=comment in call to reps API

- appeals/web/src/server/appeals/appeal-details/interested-party-comments/view-and-review/__tests__/__snapshots__/view-and-review.test.js.snap
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/view-and-review/__tests__/view-and-review.test.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/view-and-review/view-and-review.controller.js
[A2-1317](https://pins-ds.atlassian.net/browse/A2-1317)
[A2-1317]: https://pins-ds.atlassian.net/browse/A2-1317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web): A2-1317 ip comments copy changes

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/lib/display-page-formatter.js
Global rollout of updated copy for empty document folder rows
A2-1255
> feat(web): global rollout of updated copy for empty document folder rows

- appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-ip-comment/__tests__/add-ip-comment.test.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-ip-comment/add-ip-comment.service.js
Erroneously changed this with the other GET API calls earlier.
> fix(web): revert change to rep POST API call

- appeals/e2e/cypress/page_objects/caseDetailsPage.js
https://pins-ds.atlassian.net/browse/A2-1640
- [ x ] Other (please explain in the description section above)
- [ x ] I have performed a self-review of my own code
- [ x ] I have double checked this work does not include any hardcoded secrets or passwords
- [ x ] I have referenced the ticket number above
> test: fix broken remove file upload test

- appeals/api/src/server/config/config.js
- appeals/api/src/server/config/schema.js
- appeals/api/src/server/endpoints/representations/__tests__/representations.test.js
- appeals/api/src/server/endpoints/representations/representations.service.js
- infrastructure/app-api.tf
- infrastructure/environments/dev.tfvars
- infrastructure/environments/prod.tfvars
- infrastructure/environments/test.tfvars
- infrastructure/environments/training.tfvars
Created new templates in test and production Notify, updated the logic to use them, and synced changes with Terraform. Added unit tests to validate template selection, data handling, and uncovered scenarios.
[A2-1751](https://pins-ds.atlassian.net/browse/A2-1751)
[A2-1751]: https://pins-ds.atlassian.net/browse/A2-1751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(api): A2-1751 Notify Comms - rejected comment - reasons and deadline date not displaying correctly 

- appeals/web/src/server/appeals/appeal-details/interested-party-comments/view-and-review/page-components/common.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/eia-development-description/__tests__/__snapshots__/eia-development-description.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/eia-development-description/eia-development-description.mapper.js
- appeals/web/src/server/lib/mappers/data/lpa-questionnaire/submappers/map-eia-development-description.js
> fix(web): correct eia display text

- appeals/web/src/server/appeals/appeal-details/interested-party-comments/redact/__tests__/__snapshots__/redact.test.js.snap
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/redact/components/redact-input.js
- appeals/web/src/server/lib/mappers/components/page-components/textarea.js
> feat(web): a2-1785 lock down ip comment redact textarea

- appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
- appeals/api/src/server/endpoints/appeals/appeals.service.js
API:
- Fixed issue with item count
- Fixed unit test
TESTING:
- API unit tests pass
[A2-1753 Additions to the Filtering on All cases - BO](https://pins-ds.atlassian.net/browse/A2-1753)
> fix(appeals): fix all cases pagination (a2-1753)

- docs/blob-emulator.md
> fix(web): bugfix/fix-typo-in-readme-instructions

- appeals/api/src/server/endpoints/appeals/appeals.controller.js
API:
- Fixed statuses format
TESTING:
- API unit tests pass
[A2-1828 Problem with Appeals assigned to me - BO](https://pins-ds.atlassian.net/browse/A2-1828)
> fix(appeals): fix problem with appeals assigned to me (a2-1828)

- appeals/api/Dockerfile
- appeals/web/Dockerfile
> fix(api): specify alpine version

- appeals/e2e/cypress/e2e/back-office-appeals/changeSiteVisit.spec.js
- appeals/e2e/cypress/e2e/back-office-appeals/scheduleSiteVisit.spec.js
- appeals/e2e/cypress/page_objects/caseDetailsPage.js
e2e tests for changing the site visit from within the case timetable and site section
> Test/e2e change site visit 

- appeals/web/src/client/components/file-uploader/_client-actions.js
https://pins-ds.atlassian.net/browse/A2-1703
> fix(web): bugfix/A2-1703-bug-when-removing-and-reselecting-same-file

- appeals/api/src/server/endpoints/representations/representations.controller.js
- appeals/api/src/server/endpoints/representations/representations.routes.js
- appeals/api/src/server/endpoints/representations/representations.service.js
- appeals/api/src/server/repositories/representation.repository.js
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.controller.js
- appeals/web/src/server/appeals/appeal-details/representations/representations.service.js
> feat(api): create rep count endpoint

- appeals/web/src/server/appeals/appeal-details/neighbouring-sites/__tests__/__snapshots__/neighbouring-sites.test.js.snap
- appeals/web/src/server/appeals/appeal-details/service-user/__tests__/__snapshots__/service-user.test.js.snap
- appeals/web/src/server/lib/error-handlers/__tests__/error-handlers.test.js
- appeals/web/src/server/lib/error-handlers/change-screen-error-handlers.js
https://pins-ds.atlassian.net/browse/A2-1685
> fix(web): a2-1685 resolving missed copy updates

- appeals/api/src/server/endpoints/representations/__tests__/representations.test.js
- appeals/api/src/server/endpoints/representations/representations.validators.js
[A2-1777](https://pins-ds.atlassian.net/browse/A2-1777)
[A2-1777]: https://pins-ds.atlassian.net/browse/A2-1777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(api): A2-1777 IP Comment Add 504 Timeout Error

- appeals/api/src/database/seed/seed-clear.js
> fix(api): seed clear order

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js
- appeals/web/src/server/views/app/components/file-uploader.component.njk
https://pins-ds.atlassian.net/browse/A2-1666
> feat(web): feature/A2-1666-copy-update-and-remove-unnecessary-checkbox

- appeals/api/src/server/openapi-types.ts
- appeals/api/src/server/openapi.json
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/appeal-details/accordions/has.js
- appeals/web/src/server/appeals/appeal-details/accordions/index.js
- appeals/web/src/server/appeals/appeal-details/accordions/s78.js
- appeals/web/src/server/appeals/appeal-details/accordions/utils/map-status-dependent-notifications.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.controller.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
- appeals/web/src/server/lib/mappers/components/page-components/notification-banners.mapper.js
add notification banner entry point for appellant and lpa final comments
A2-1727
> feat(appeals): add notification banner entry point for appellant and lpa final comments

- appeals/api/src/database/seed/data-test.js
- appeals/api/src/database/seed/seed-clear.js
> fix(api): seed order and more tx

- appeals/api/src/database/seed/data-test.js
- appeals/api/src/server/endpoints/appeals/appeals.formatter.js
- appeals/api/src/server/endpoints/representations/representations.controller.js
- appeals/api/src/server/endpoints/representations/representations.routes.js
- appeals/api/src/server/endpoints/representations/representations.service.js
- appeals/api/src/server/openapi.json
- appeals/web/src/server/appeals/appeal-details/accordions/s78.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.router.js
- appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/lpa-statement.router.js
- appeals/web/src/server/appeals/appeal-details/representations/representations.middleware.js
- appeals/web/src/server/appeals/appeal-details/representations/representations.router.js
- appeals/web/src/server/appeals/appeal-details/representations/representations.service.js
- appeals/web/src/server/appeals/appeals.types.d.ts
- appeals/web/src/server/lib/mappers/data/appeal/s78.js
- appeals/web/src/server/lib/mappers/data/appeal/submappers/lpa-statement.mapper.js
- packages/appeals/constants/common.js
> feat(web): statement docs entrypoint

- appeals/api/src/database/seed/data-test.js
- appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
- appeals/api/src/server/endpoints/appeals/appeals.formatter.js
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/appeal-details/accordions/s78.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.types.d.ts
- appeals/web/src/server/lib/mappers/data/appeal/s78.js
- appeals/web/src/server/lib/mappers/data/appeal/submappers/appellant-final-comments.mapper.js
- appeals/web/src/server/lib/mappers/data/appeal/submappers/lpa-final-comments.mapper.js
add documentation summary entry point for appellant and lpa final comments
A2-1723
> feat(appeals): add documentation summary entry point for appellant and lpa final comments

- appeals/web/src/server/appeals/appeal-details/interested-party-comments/view-and-review/view-and-review.controller.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/view-and-review/view-and-review.router.js
- appeals/web/src/server/appeals/appeal-details/representations/common/validators.js
- appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/incomplete/incomplete.controller.js
- appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/incomplete/incomplete.router.js
- appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/lpa-statement.controller.js
- appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/lpa-statement.mapper.js
- appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/lpa-statement.router.js
- packages/appeals/constants/common.js
https://github.com/user-attachments/assets/575016fc-b289-46dd-b23e-51906fbc54fc
> feat(web): mark statement as incomplete

- appeals/api/src/server/repositories/folder.repository.js
update ordering of documents in folders to oldest first
A2-859
> feat(api): update ordering of documents in folders to oldest first

- appeals/web/src/client/components/file-uploader/__tests__/file-uploader.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/costs/__tests__/__snapshots__/costs.test.js.snap
- appeals/web/src/server/appeals/appeal-details/costs/__tests__/costs.test.js
- appeals/web/src/server/appeals/appeal-details/internal-correspondence/__tests__/__snapshots__/internal-correspondence.test.js.snap
- appeals/web/src/server/appeals/appeal-details/internal-correspondence/__tests__/internal-correspondence.test.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/__snapshots__/issue-decision.test.js.snap
- appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/issue-decision.test.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
- appeals/web/src/server/appeals/appeal-details/withdrawal/__tests__/__snapshots__/withdrawal.test.js.snap
- appeals/web/src/server/appeals/appeal-details/withdrawal/__tests__/withdrawal.test.js
- appeals/web/src/server/appeals/appeal-documents/__tests__/__snapshots__/appeal-documents.test.js.snap
- appeals/web/src/server/appeals/appeal-documents/__tests__/appeal-documents.test.js
- appeals/web/src/server/views/app/components/file-uploader.component.njk
- appeals/web/src/styles/7-components/file-upload.scss
file upload component copy updates
A2-1666
> fix(web): file upload component copy updates

- appeals/web/src/server/appeals/personal-list/__tests__/__snapshots__/personal-list.test.js.snap
- appeals/web/src/server/appeals/personal-list/__tests__/personal-list.test.js
- appeals/web/src/server/appeals/personal-list/personal-list.mapper.js
add a11y text to personal list action links
A2-1769
> fix(web): add a11y text to personal list action links

- infrastructure/.tflint.hcl
- infrastructure/provider.tf
> chore(tooling): upgrading-terraform

- appeals/api/src/database/seed/data-test.js
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/appeal-details/accordions/utils/map-status-dependent-notifications.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.router.js
- appeals/web/src/server/appeals/appeal-details/final-comments/final-comments.middleware.js
- appeals/web/src/server/appeals/appeal-details/final-comments/final-comments.router.js
- appeals/web/src/server/appeals/appeal-details/final-comments/final-comments.service.js
- appeals/web/src/server/appeals/appeal-details/final-comments/view-and-review/__tests__/__snapshots__/view-and-review.test.js.snap
- appeals/web/src/server/appeals/appeal-details/final-comments/view-and-review/__tests__/view-and-review.test.js
- appeals/web/src/server/appeals/appeal-details/final-comments/view-and-review/page-components/common.js
- appeals/web/src/server/appeals/appeal-details/final-comments/view-and-review/page-components/review.mapper.js
- appeals/web/src/server/appeals/appeal-details/final-comments/view-and-review/view-and-review.controller.js
- appeals/web/src/server/appeals/appeal-details/final-comments/view-and-review/view-and-review.mapper.js
- appeals/web/src/server/appeals/appeal-details/final-comments/view-and-review/view-and-review.router.js
- appeals/web/src/server/appeals/appeal-details/final-comments/view-and-review/view-and-review.service.js
- appeals/web/src/server/appeals/appeal-details/final-comments/view-and-review/view-and-review.validators.js
- appeals/web/src/server/appeals/personal-list/personal-list.mapper.js
- appeals/web/src/server/lib/mappers/data/appeal/submappers/appellant-final-comment-due-date.mapper.js
- appeals/web/src/server/lib/mappers/data/appeal/submappers/appellant-final-comments.mapper.js
- appeals/web/src/server/lib/mappers/data/appeal/submappers/lpa-final-comment-due-date.mapper.js
- appeals/web/src/server/lib/mappers/data/appeal/submappers/lpa-final-comments.mapper.js
- appeals/web/testing/app/fixtures/referencedata.js
https://pins-ds.atlassian.net/browse/A2-1729
> feat(web): feature/A2-1729-final-comments-review-page

- appeals/api/src/server/endpoints/lpa-questionnaires/__tests__/lpa-questionnaires.test.js
- fix bank holiday LPA Questionnaire due date to one in future
> ptest(api): fix bank holiday LPA Questionnaire due date to one in future

- appeals/web/src/server/appeals/appeal-details/appeal-details.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.mapper.js
> fix(web): update manage doc page title

- appeals/web/src/server/lib/mappers/components/page-components/__tests__/notification-banners.mapper.test.js
- appeals/web/src/server/lib/mappers/components/page-components/notification-banners.mapper.js
[A2-1922](https://pins-ds.atlassian.net/browse/A2-1922)
[A2-1922]: https://pins-ds.atlassian.net/browse/A2-1922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web): A2-1922 Success banner should read "Comment redacted and accepted"

- appeals/web/src/server/appeals/appeal-details/representations/common/validators.js
- appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/lpa-statement.mapper.js
> fix(web): update copy

- appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-ip-comment/__tests__/__snapshots__/add-ip-comment.test.js.snap
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-ip-comment/add-ip-comment.controller.js
[A2-2008](https://pins-ds.atlassian.net/browse/A2-2008)
[A2-2004]: https://pins-ds.atlassian.net/browse/A2-2004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[A2-2008]: https://pins-ds.atlassian.net/browse/A2-2008?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web): A2-2008 IP Comment CYA Page Address Provided Change link

- appeals/api/src/database/schema.d.ts
- appeals/api/src/server/endpoints/link-appeals/__tests__/link-appeal.test.js
- appeals/api/src/server/endpoints/link-appeals/link-appeals.service.js
- appeals/api/src/server/mappers/api/shared/map-appeal-relationships.js
- appeals/api/src/server/repositories/appeal.repository.js
- appeals/api/src/server/tests/appeals/mocks.js
Fixes the mapping of appeal type for linked and related appeals
N/A
> fix(api): mapping of linked appeal types

- appeals/api/src/server/tests/integrations/mocks.js
Should remove conflicts caused by regenerating GUIDs in swagger.
N/A
> fix(api): makes guid in mocks static

- appeals/api/src/server/endpoints/appeal-decision/appeal-decision.controller.js
- appeals/api/src/server/mappers/api/shared/map-appeal-decision.js
- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/issue-decision.test.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.mapper.js
- appeals/web/src/server/appeals/appeal-details/status-tags/status-tags.mapper.js
- appeals/web/src/server/lib/mappers/data/appeal/submappers/appeal-decision.mapper.js
- appeals/web/src/server/lib/mappers/data/appeal/submappers/decision.mapper.js
Pre-release fix
split decision / invalid decision flows
> fix(appeals): split and invalid decision flow fixes

- appeals/api/src/server/mappers/api/shared/map-folders-documents.js
Fix prod issue (hopefully)!
[Ticket]()
> fix(api): null-redaction-status-on-import

- appeals/web/src/server/appeals/appeal-details/linked-appeals/__tests__/__snapshots__/linked-appeals.test.js.snap
- appeals/web/src/server/appeals/appeal-details/linked-appeals/linked-appeals.mapper.js
WEB:
- Added the right aligned class where missing
TESTING:
- WEB updated snapshots and checked all other tests pass
[A2-2084 Linked and related appeals: Action links should be aligned to the right](https://pins-ds.atlassian.net/browse/A2-2084)
> feat(appeals): linked appeal action links should be aligned to the right (a2-2084)

- appeals/api/src/database/seed/LPAs/dev.js
- appeals/api/src/database/seed/LPAs/prod.js
Adds another test LPA (Q1111) to the production LPA list.
[Ticket]()
> feat(api): lpa list adding Q1111 to prod

- infrastructure/function-casedata-import.tf
- infrastructure/service-bus.tf
- infrastructure/terraform.tfvars
- infrastructure/variables.tf
Adds representation topic and subscriptions to the service bus
[Ticket](https://pins-ds.atlassian.net/browse/A2-2133)
> feat(appeals): adds service bus topic and subs for reps

- appeals/e2e/cypress/page_objects/dateTimeSection.js
Refactor to reduce the amount of duplicate code in the `dateTimeSection.js` page object
I've re-run all the e2e tests and they're passing
> appeals(test/e2e): refactor time selectors

- appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-document/add-document.router.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/add-document/controller/check-your-answers.js
Small bug fixes to ip comments add documentation flow
[A2-2134](https://pins-ds.atlassian.net/browse/A2-2134)
[A2-2134]: https://pins-ds.atlassian.net/browse/A2-2134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web): A2-2134 IP Comments > Add documentation > 500 Internal Server error

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/lib/mappers/components/page-components/__tests__/notification-banners.mapper.test.js
- appeals/web/src/server/lib/mappers/components/page-components/notification-banners.mapper.js
change awaiting transfer notification banner type to important
https://pins-ds.atlassian.net/browse/A2-1348
> fix(web): change awaiting transfer notification banner type to important

- appeals/web/src/server/appeals/appeal-details/appellant-case/address/address.mapper.js
- appeals/web/src/server/appeals/appeal-details/final-comments/reject/reject.controller.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/interested-party-comments.mapper.js
- appeals/web/src/server/appeals/appeal-details/interested-party-comments/view-and-review/reject/reject.controller.js
- appeals/web/src/server/appeals/appeal-details/neighbouring-sites/neighbouring-sites.mapper.js
- appeals/web/src/server/appeals/appeal-details/representations/common/render-select-rejection-reasons.js
- appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/incomplete/incomplete.controller.js
- appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/lpa-statement.controller.js
- appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/lpa-statement.mapper.js
- appeals/web/src/server/appeals/appeal-details/representations/representations.service.js
- appeals/web/src/server/appeals/appeals.types.d.ts
- appeals/web/src/server/lib/mappers/components/page-components/address.js
- appeals/web/src/server/lib/mappers/components/page-components/check-your-answers.js
- appeals/web/src/server/lib/nunjucks-template-builders/page-component-rendering.js
- Adds a few new fields to LPA Statement CYA page
- Fixes some change link issues
- Fixes a bug in the pre render code which blatted existing pre-rendered HTML
[Ticket](https://pins-ds.atlassian.net/browse/A2-1742)
> fix(web): expand lpa statement cya page capabilities

- appeals/api/src/server/repositories/representation.repository.js
Small bug fixes to consistency between getRepresentations and getById in the repository.
[A2-1731](https://pins-ds.atlassian.net/browse/A2-1731)
[A2-1731]: https://pins-ds.atlassian.net/browse/A2-1731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(api): consistency between getRepresentations and getById

- appeals/api/src/server/endpoints/appeal-details/appeal-details.controller.js
- appeals/api/src/server/endpoints/appeal-details/appeal-details.service.js
- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/repositories/appeal.repository.js
- appeals/web/src/server/appeals/appeal-details/service-user/__tests__/__snapshots__/service-user.test.js.snap
- appeals/web/src/server/appeals/appeal-details/service-user/__tests__/service-user.test.js
- appeals/web/src/server/appeals/appeal-details/service-user/service-user.controller.js
- appeals/web/src/server/appeals/appeal-details/service-user/service-user.router.js
- appeals/web/src/server/appeals/appeal-details/service-user/service-user.service.js
- appeals/web/src/server/lib/mappers/data/appeal/submappers/agent.mapper.js
WEB:
- Added "Add" link to Agent row when the agent has not been added
- Added new /appeals-service/appeal-details/{appealId}/service-user/{action}/ route where action can be "add" or "change"
- Added assign service user service
API:
- Add agent to appeal update payload
TESTING:
- WEB unit tests added
[A2-612 Adding an agent](https://pins-ds.atlassian.net/browse/A2-612)
> feat(appeals): adding an agent (a2-612)

- appeals/web/src/server/appeals/personal-list/personal-list.mapper.js
Add entry point for sharing IP comments and statement to the personal list page.
[A2-1734](https://pins-ds.atlassian.net.mcas.ms/browse/A2-1734)
[A2-1734]: https://pins-ds.atlassian.net/browse/A2-1734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(web): add a link to share statement and comments from personal page

- appeals/web/src/server/appeals/appeal-details/service-user/__tests__/__snapshots__/service-user.test.js.snap
- appeals/web/src/server/appeals/appeal-details/service-user/__tests__/service-user.test.js
- appeals/web/src/server/appeals/appeal-details/service-user/service-user.controller.js
- appeals/web/src/server/appeals/appeal-details/service-user/service-user.middleware.js
- appeals/web/src/server/appeals/appeal-details/service-user/service-user.router.js
Fix a 500 error in the previous PR for this ticket
WEB:
- Allow the user type of agent to not be in the appeals data when the action is add
- Moved the validation of the action param into middleware as suggested when merging the previous PR
TESTING:
- WEB unit tests changed to prevent add test to run for appellant user type
[A2-612 Adding an agent](https://pins-ds.atlassian.net/browse/A2-612)
> fix(appeals): fix add an agent (a2-612)

- appeals/web/src/server/appeals/appeal-details/accordions/utils/map-status-dependent-notifications.js
- appeals/web/src/server/lib/mappers/components/page-components/notification-banners.mapper.js
* feat(web): add notification banner to share comments and LPA statement
[A2-1745](https://pins-ds.atlassian.net/browse/A2-1745)
[A2-1745]: https://pins-ds.atlassian.net/browse/A2-1745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(web): add notification banner to share comments and LPA statement

- appeals/api/setup-tests.js
- appeals/api/src/server/endpoints/constants.js
- appeals/api/src/server/endpoints/service-user/__tests__/service-user.test.js
- appeals/api/src/server/endpoints/service-user/service-user.controller.js
- appeals/api/src/server/endpoints/service-user/service-user.routes.js
- appeals/api/src/server/endpoints/service-user/service-user.validators.js
- appeals/api/src/server/openapi-types.ts
- appeals/api/src/server/openapi.json
- appeals/api/src/server/repositories/appeal.repository.js
- appeals/api/src/server/swagger.js
- appeals/web/src/server/appeals/appeal-details/service-user/__tests__/__snapshots__/service-user.test.js.snap
- appeals/web/src/server/appeals/appeal-details/service-user/__tests__/service-user.test.js
- appeals/web/src/server/appeals/appeal-details/service-user/service-user.controller.js
- appeals/web/src/server/appeals/appeal-details/service-user/service-user.mapper.js
- appeals/web/src/server/appeals/appeal-details/service-user/service-user.router.js
- appeals/web/src/server/appeals/appeal-details/service-user/service-user.service.js
- appeals/web/src/server/views/patterns/change-page.pattern.njk
WEB:
- Add "Remove agent" link to bottom of "Update agent details" page
- Create new "Remove agent" page including controllers, services, routes and a success banner
API:
- Added endpoint to remove a service user 
- Updated Swagger
TESTING:
- WEB unit tests added for agent deletion
- API unit tests added for agent deletion
[A2-2108 Remove an agent](https://pins-ds.atlassian.net/browse/A2-2108)
> feat(appeals): remove an agent (a2-2108)

- appeals/api/src/server/repositories/neighbouring-sites.repository.js
* fix(api): only delete neighbouring site if record exists
[A2-766](https://pins-ds.atlassian.net/browse/A2-766)
[A2-766]: https://pins-ds.atlassian.net/browse/A2-766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(api): only delete neighbouring site if record exists

- appeals/web/src/server/appeals/appeal-details/final-comments/add-document/add-document.router.js
- appeals/web/src/server/appeals/appeal-details/final-comments/controller/check-your-answers.js
- appeals/web/src/server/appeals/appeal-details/final-comments/controller/date-submitted.js
- appeals/web/src/server/appeals/appeal-details/final-comments/controller/index.js
- appeals/web/src/server/appeals/appeal-details/final-comments/controller/redaction-status.js
- appeals/web/src/server/appeals/appeal-details/final-comments/final-comments.middleware.js
- appeals/web/src/server/appeals/appeal-details/final-comments/final-comments.router.js
- appeals/web/src/server/appeals/appeal-details/final-comments/final-comments.service.js
- appeals/web/src/server/appeals/appeal-details/final-comments/manage-documents/manage-documents.controller.js
- appeals/web/src/server/appeals/appeal-details/final-comments/manage-documents/manage-documents.router.js
- appeals/web/src/server/appeals/appeal-details/final-comments/view-and-review/__tests__/__snapshots__/view-and-review.test.js.snap
- appeals/web/src/server/appeals/appeal-details/final-comments/view-and-review/__tests__/view-and-review.test.js
- appeals/web/src/server/appeals/appeal-details/final-comments/view-and-review/page-components/common.js
- appeals/web/src/server/appeals/appeal-details/final-comments/view-and-review/view-and-review.mapper.js
- appeals/web/src/server/appeals/appeal-details/representations/representations.service.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.controller.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js
- appeals/web/src/server/appeals/appeal.constants.js
- appeals/web/src/server/lib/mappers/components/page-components/notification-banners.mapper.js
- appeals/web/testing/app/fixtures/referencedata.js
Implement add and manage supporting documents in final comments flow. 
[A2-1731](https://pins-ds.atlassian.net/browse/A2-1731)
[A2-1731]: https://pins-ds.atlassian.net/browse/A2-1731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(web): A2-1731 Add and manage files

- appeals/web/src/server/appeals/appeal-details/representations/representations.mapper.js
https://pins-ds.atlassian.net/browse/A2-2149
[Ticket]()
> fix(web): bugfix/A2-2149-fix-add-another-text-not-populating

- appeals/e2e/cypress/e2e/back-office-appeals/addCostDecisionRedacted.spec.js
- appeals/e2e/cypress/page_objects/caseDetailsPage.js
This pr adds the final p3 tests for cost decision. 
The tests are
-change the redaction status of a cost decision
- Upload new version and change the filename
The tickets are listed below
https://pins-ds.atlassian.net/browse/A2-1986
https://pins-ds.atlassian.net/browse/A2-1987
[Ticket]()
> test: add final p3 tests for cost decision

- appeals/api/src/server/config/config.js
- appeals/api/src/server/config/schema.js
- appeals/api/src/server/endpoints/lpa-questionnaires/__tests__/lpa-questionnaires.test.js
- appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.service.js
Note, this requires the new environment variable: GOV_NOTIFY_LPAQ_COMPLETE_APPELLANT_ID
API:
- Added notify call
TESTING:
- API unit tests updated
- Confirmed in Notify portal
[A2-1027 Notify: LPAQ Published](https://pins-ds.atlassian.net/browse/A2-1027)
> feat(appeals): notify lpaq published (a2-1027)

- appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/incomplete/incomplete.controller.js
- appeals/web/src/server/lib/mappers/components/page-components/check-your-answers.js
- Adds a missing piece of text to the LPA statement incomplete CYA page
- Adds before and after options to pass extra page components to CYA page renderer
[Ticket](https://pins-ds.atlassian.net/browse/A2-1742)
> fix(web): add missing paragraph to LPA statement incomplete CYA

- infrastructure/app-api.tf
- infrastructure/environments/dev.tfvars
- infrastructure/environments/test.tfvars
…## Describe your changes
This adds the new environment variable: GOV_NOTIFY_LPAQ_COMPLETE_APPELLANT_ID for DEV and TEST in Terraform
[A2-1027 Notify: LPAQ Published](https://pins-ds.atlassian.net/browse/A2-1027)
> feat(appeals): notify lpaq for appellant - template id for dev and test (a2-1027)

- appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/incomplete/incomplete.controller.js
Updating the casing of the resubmit statement field on the check your answers page  
https://pins-ds.atlassian.net/jira/software/c/projects/A2/boards/246?atlOrigin=eyJpIjoiODE5MWU2OTE0YzUyNDBkOGIyMGI3MTJiMjY1MzM4ODIiLCJwIjoiaiJ9&selectedIssue=A2-1743&sprints=855
> fix(web): casing fix on the incomplete check your answers page

- appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.service.js
chore(api): log real error when LPAQ notify call fails
[A2-2210](https://pins-ds.atlassian.net/browse/A2-2210)
[A2-2210]: https://pins-ds.atlassian.net/browse/A2-2210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(api): log real error when LPAQ notify call fails

- appeals/functions/document-processing/update-completed-events/function.json
fix(functions): correct NCRONTAB expression for update-completed-events
[A2-1211](https://pins-ds.atlassian.net/browse/A2-1121)
[A2-1211]: https://pins-ds.atlassian.net/browse/A2-1211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(functions): correct NCRONTAB expression for update-completed-events

- appeals/functions/document-processing/update-completed-events/function.json
chore(functions): give the timer trigger a name
> chore(functions): give the timer trigger a name

- infrastructure/environments/prod.tfvars
- infrastructure/environments/training.tfvars
- Added notify template IDs for Prod and Training
[A2-1141 Notify: Final comment rejected (all main parties)](https://pins-ds.atlassian.net/browse/A2-1141)
> feat(appeals): add prod and training template-ids (a2-1141)

- appeals/api/src/server/endpoints/representations/__tests__/representations.test.js
- appeals/api/src/server/endpoints/representations/notify/get-service.js
- appeals/api/src/server/endpoints/representations/notify/index.js
- appeals/api/src/server/endpoints/representations/notify/service-map.js
- appeals/api/src/server/endpoints/representations/notify/services/index.js
- appeals/api/src/server/endpoints/representations/notify/services/utils.js
- appeals/api/src/server/endpoints/representations/representations.controller.js
- appeals/api/src/server/endpoints/representations/representations.service.js
- Adds a function to send emails when rep status changes
- Adds a list to connect rep status, rep type and a function to send specific emails. This should make extension trivial
[Ticket](https://pins-ds.atlassian.net/browse/A2-1773)
> feat(api): add code to send notifies for different reps

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/appeal-details/accordions/utils/map-status-dependent-notifications.js
- appeals/web/src/server/lib/mappers/components/page-components/notification-banners.mapper.js
WEB:
- Add the banner when the status is EVENT
TESTING:
- Add unit test for the banner
- All other WEB unit tests pass
[A2-2145 Set up site visit - Important banner entry point](https://pins-ds.atlassian.net/browse/A2-2145)
> feat(appeals): set up site visit banner (a2-2145)

- appeals/api/src/database/migrations/20241029135111_s78_timetable_updates/migration.sql
- appeals/api/src/database/migrations/20250203151300_consolidate_s78_timetable/migration.sql
> fix(api): timetable data structure

- appeals/api/src/server/config/config.js
- appeals/api/src/server/config/schema.js
- appeals/api/src/server/endpoints/representations/notify/service-map.js
- appeals/api/src/server/endpoints/representations/notify/services/index.js
- infrastructure/app-api.tf
- infrastructure/environments/dev.tfvars
- infrastructure/environments/prod.tfvars
- infrastructure/environments/test.tfvars
- infrastructure/environments/training.tfvars
Sends notify email when LPA statement is marked as incomplete
[Ticket](https://pins-ds.atlassian.net/browse/A2-1042)
> feat(api): send notify on lpa statement incomplete

- appeals/api/package.json
- appeals/api/src/server/mappers/integration/commands/questionnaire.mapper.js
- package-lock.json
- package.json
Updates data model to 1.9.13 (small command fixes)
> fix(api): import of designated sites custom - upgrade data model 1.9.13

- appeals/api/package.json
- package-lock.json
- package.json
Another data model update to latest
[Ticket]()
> feat(appeals): data model v1.9.4

- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/constants.js
- appeals/api/src/server/repositories/lpa-questionnaire.repository.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/designated-sites/__tests__/__snapshots__/designated-sites.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/designated-sites/__tests__/designated-sites.test.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/designated-sites/designated-sites.controller.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/designated-sites/designated-sites.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/designated-sites/designated-sites.router.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/designated-sites/designated-sites.service.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/designated-sites/designated-sites.validator.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.router.js
- appeals/web/src/server/lib/mappers/components/instructions/index.js
- appeals/web/src/server/lib/mappers/components/instructions/list.js
- appeals/web/src/server/lib/mappers/components/page-components/checkbox.js
- appeals/web/src/server/lib/mappers/components/page-components/index.js
- appeals/web/src/server/lib/mappers/data/lpa-questionnaire/s78.js
- appeals/web/src/server/lib/mappers/data/lpa-questionnaire/submappers/map-designated-sites.js
- appeals/web/src/server/lib/nunjucks-template-builders/gds-components-properties-jsdoc.js
- appeals/web/testing/app/fixtures/referencedata.js
- add new row to s78 LPA Questionnaire page (designated sites, in section 1. Constraints, designations and other issues)
- add change page and associated functionality for the row
https://pins-ds.atlassian.net/browse/A2-1466
> s78 LPAQ new row and change page: designated sites

- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.controller.js
* for 'environmental services' question page, change pattern to use correct width style for this type of page
* update snapshot to reflect change
[A2-2054](https://pins-ds.atlassian.net/browse/A2-2054)
[A2-2054]: https://pins-ds.atlassian.net/browse/A2-2054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web): a2-2054 change width of environmental services page

- infrastructure/app-api.tf
dev-310
turning public access on for dev
[Ticket]()
> chore(infrastructure): turning-public-access-to-enabled

- infrastructure/app-web.tf
Access between endpoints over deployment
> chore(appeals): app web public access over pe

- appeals/web/src/server/appeals/appeal-details/appeal-details.router.js
- appeals/web/src/server/appeals/appeal-details/progress-case/from-final-comments/__tests__/from-final-comments.test.js
- appeals/web/src/server/appeals/appeal-details/progress-case/from-final-comments/from-final-comments.controller.js
- appeals/web/src/server/appeals/appeal-details/progress-case/from-final-comments/from-final-comments.mapper.js
- appeals/web/src/server/appeals/appeal-details/progress-case/from-final-comments/from-final-comments.router.js
- appeals/web/src/server/appeals/appeal-details/progress-case/progress-case.router.js
Progress case from final comments (share final comments, if any)
https://pins-ds.atlassian.net/browse/A2-89
> feat(web): feature/A2-89-share-final-comments-part-1

- appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/lpa-statement.mapper.js
- Connects the view LPA statement screen to the redact statement journey
[Ticket](https://pins-ds.atlassian.net/browse/A2-1735)
> feat(web): redact accepted lpa statement

- appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/__tests__/interested-party-comments.test.js
- appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/interested-party-comments.mapper.js
Fixed back link url and added test coverage.
[A2-1731](https://pins-ds.atlassian.net/browse/A2-1731)
[A2-1731]: https://pins-ds.atlassian.net/browse/A2-1731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web): A2-1731 clicking 'back" from Review IP comments navigates to assigned to me

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/appeal-details/accordions/utils/map-status-dependent-notifications.js
- appeals/web/src/server/lib/mappers/components/page-components/notification-banners.mapper.js
https://pins-ds.atlassian.net/browse/A2-1747
> feat(web): feature/A2-1747-share-fc-important-banner

- infrastructure/.terraform.lock.hcl
- infrastructure/provider.tf
Updating azurerm to latest version 3.18.0
[Ticket](https://pins-ds.atlassian.net/browse/DEV-353)
> chore(tooling): upgarding azurerm

- infrastructure/document-storage.tf
> chore(tooling): adding malware scanning resource block

- appeals/web/src/server/appeals/appeal-details/final-comments/view-and-review/__tests__/__snapshots__/view-and-review.test.js.snap
- appeals/web/src/server/appeals/appeal-details/final-comments/view-and-review/page-components/common.js
fix show more functionality not working on view final comments screen
https://pins-ds.atlassian.net/browse/A2-2393
> fix(web): fix show more functionality not working on view final comments screen

- infrastructure/document-storage.tf
> fix(tooling): creating terraform import resource for malware scanning

- appeals/web/src/server/appeals/personal-list/__tests__/personal-list.test.js
- appeals/web/src/server/appeals/personal-list/personal-list.mapper.js
https://pins-ds.atlassian.net/browse/A2-1746
> feat(web): feature/A2-1746-share-fc-personal-list

- appeals/api/src/server/state/list-states.js
- appeals/api/src/server/state/transition-state.js
Fixes null procedure types in state machine.
[Ticket]()
> fix(api): handling null procedure types, defaults to written

- appeals/web/src/server/lib/display-page-formatter.js
- appeals/web/src/server/lib/mappers/data/appeal/submappers/ip-comments.mapper.js
https://pins-ds.atlassian.net/browse/A2-2407
> fix(web): bugfix/A2-2407-ip-comments-incorrect-status

- appeals/api/src/server/endpoints/constants.js
- appeals/api/src/server/endpoints/representations/representations.controller.js
- appeals/web/src/server/appeals/appeal-details/final-comments/reject/__tests__/__snapshots__/reject-final-comments.test.js.snap
- appeals/web/src/server/appeals/appeal-details/final-comments/reject/__tests__/reject-final-comments.test.js
- appeals/web/src/server/appeals/appeal-details/final-comments/reject/reject.mapper.js
- appeals/web/src/server/appeals/appeal-details/final-comments/reject/reject.router.js
- appeals/web/src/server/appeals/appeal-details/final-comments/reject/reject.validators.js
Make corrections to final comment copy
[Ticket](https://pins-ds.atlassian.net/browse/A2-2283)
> fix(web): update final comment copy

- infrastructure/environments/prod.tfvars
- infrastructure/environments/training.tfvars
INFRA:
- Add template IDs for Appellant and LPA 
[Ticket: A2-1043](https://pins-ds.atlassian.net.mcas.ms/browse/A2-1043)
> fix(appeals): notify share comments and statements - prod templates (a2-1043)

- appeals/web/src/server/appeals/appeal-details/final-comments/view-and-review/__tests__/__snapshots__/view-and-review.test.js.snap
- appeals/web/src/server/appeals/appeal-details/final-comments/view-and-review/__tests__/view-and-review.test.js
- appeals/web/src/server/appeals/appeal-details/representations/document-attachments/manage-documents.controller.js
- appeals/web/src/server/appeals/appeal-details/representations/document-attachments/manage-documents.router.js
Add generic attachments code for managing Add & Remove version flow in LPA Statements & Final Comments
[A2-1731](https://pins-ds.atlassian.net/browse/A2-1731)
[A2-1765](https://pins-ds.atlassian.net/browse/A2-1765)
[A2-1731]: https://pins-ds.atlassian.net/browse/A2-1731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[A2-1765]: https://pins-ds.atlassian.net/browse/A2-1765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web): A2-1731/A2-1765 Manage attachment Add & Remove version flow LPA Statements & Final Comments

- appeals/api/src/server/config/config.js
- appeals/api/src/server/endpoints/representations/notify/index.js
- appeals/api/src/server/endpoints/representations/notify/services/index.js
- appeals/api/src/server/endpoints/representations/notify/services/utils.js
- appeals/api/src/server/endpoints/representations/representations.controller.js
- appeals/api/src/server/repositories/representation.repository.js
- appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/incomplete/incomplete.controller.js
- appeals/web/src/server/appeals/appeal-details/representations/representations.service.js
- Adds some missing data from statement submission
- Corrects names of notify vars
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-1042)
> fix(web): correct notify vars

- appeals/web/src/server/appeals/appeal-details/accordions/s78.js
Add site visit row to timetable accordion list on s78 appeal case details page.
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-1707)
> feat(web): a2-1707 add site visit to s78 timetable accordion

- appeals/api/src/server/endpoints/test-utils/test-utils.controller.js
- appeals/api/src/server/endpoints/test-utils/test-utils.routes.js
- appeals/api/src/server/openapi.json
- appeals/e2e/cypress/e2e/back-office-appeals/progressS78ToFinalComments.spec.js
- appeals/e2e/cypress/fixtures/appealsApiRequests.js
- appeals/e2e/cypress/page_objects/caseDetailsPage.js
- appeals/e2e/cypress/support/appealsApiClient.js
- appeals/e2e/cypress/support/commands.js
- appeals/e2e/cypress/support/happyPathHelper.js
Add `e2e` Cypress test to take a S78 appeal from inception to `FINAL COMMENTS`
[Ticket](https://pins-ds.atlassian.net/browse/A2-2432)
> feat(test/e2e): journey S78 inception to final comments

- appeals/api/src/server/endpoints/constants.js
- appeals/api/src/server/endpoints/integrations/integrations.controller.js
- appeals/api/src/server/mappers/integration/commands/representation.mapper.js
- appeals/web/src/server/appeals/appeal-details/audit/audit.service.js
- appeals/web/src/server/views/appeals/components/status-tag.njk
Fixes audit log by specifying the type of representation received and making the status tags nice.
> fix(appeals): reps auditing entries

- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/lpa-questionnaire.controller.js
Fix the incomplete LPAQ questionaire redirect so that reasons can be entered
> fix(appeals): fix incomplete lpaq review redirect

- appeals/web/src/server/appeals/appeal-details/final-comments/view-and-review/__tests__/__snapshots__/view-and-review.test.js.snap
- appeals/web/src/server/appeals/appeal-details/final-comments/view-and-review/__tests__/view-and-review.test.js
- appeals/web/src/server/appeals/appeal-details/representations/document-attachments/manage-documents.controller.js
Refactor URL constructor in postDeleteDocumentPage and update tests.
[A2-2445](https://pins-ds.atlassian.net/browse/A2-2445)
[A2-2445]: https://pins-ds.atlassian.net/browse/A2-2445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web): A2-2445 LPA Statement > Supporting documents > Delete document functionality producing 404 error

- appeals/web/src/server/appeals/appeal-details/representations/representations.mapper.js
https://pins-ds.atlassian.net/browse/A2-2377
> fix(web): bugfix/A2-2377-final-comments-fix-width

- appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.mapper.js
- appeals/web/src/server/lib/mappers/components/page-components/notification-banners.mapper.js
- Corrected misspelled definition of BannerTypeAndChange
- Corrected misspelled banner object
https://pins-ds.atlassian.net/jira/software/c/projects/A2/boards/246?selectedIssue=A2-2076
> fix(web): renamed banner and definition

- appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
- appeals/api/src/server/endpoints/appeals/appeals.formatter.js
- appeals/api/src/server/repositories/appeal-lists.repository.js
Added due date to formatter and list appeal repository. Added test.
https://pins-ds.atlassian.net/jira/software/c/projects/A2/boards/246?selectedIssue=A2-2420
> feat(api): added site visit due date

- appeals/api/src/server/endpoints/integrations/__tests__/representation-mapping.test.js
- appeals/api/src/server/endpoints/integrations/integrations.broadcasters/representation.js
- appeals/api/src/server/mappers/integration/commands/representation.mapper.js
- appeals/api/src/server/mappers/integration/map-representation-entity.js
Fixes the mapping of the representation `source` field.
> fix(api): representation mapping

- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.service.js
* fix(api): fall back to agent email address if no appellant is present
[A2-2493](https://pins-ds.atlassian.net/browse/A2-2493)
[A2-2493]: https://pins-ds.atlassian.net/browse/A2-2493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(api): fall back to agent email address if no appellant is present

- .github/dependabot.yml
Enable dependabot package updates, weekly
> chore(tooling): enable dependabot version updates

- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.service.js
- appeals/api/src/server/endpoints/lpa-questionnaires/lpa-questionnaires.service.js
Mismatch of Service bus event type when broadcasting some documents
> fix(api): event update type case mismatch

- appeals/api/src/database/schema.d.ts
- appeals/api/src/server/endpoints/documents/documents.formatter.js
- appeals/api/src/server/endpoints/documents/documents.mapper.js
- appeals/api/src/server/endpoints/representations/__tests__/representations.test.js
- appeals/api/src/server/endpoints/representations/representations.formatter.js
- appeals/api/src/server/openapi-types.ts
- appeals/web/src/server/appeals/appeal-details/final-comments/view-and-review/__tests__/view-and-review.test.js
- appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/interested-party-comments.router.js
- appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/view-and-review/__tests__/__snapshots__/view-and-review.test.js.snap
- appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/view-and-review/__tests__/view-and-review.test.js
- appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/__tests__/lpa-statement.test.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.middleware.js
- appeals/web/src/server/appeals/appeal-documents/appeal.documents.service.js
- appeals/web/testing/app/fixtures/referencedata.js
Added GUID to stored filenames, removed GUID for display, filtered manage documents by representation.
[A2-2377](https://pins-ds.atlassian.net/browse/A2-2377)
[A2-2377]: https://pins-ds.atlassian.net/browse/A2-2377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(api): A2-2377 API > IP Comments > Adding the same document to multiple comments causes a 504 error

- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/lib/mappers/data/appeal/submappers/appellant-final-comments.mapper.js
- appeals/web/src/server/lib/mappers/data/appeal/submappers/lpa-final-comments.mapper.js
- appeals/web/src/server/lib/representation-utilities.js
Logic error causing the 'View' link to appear even when there's no LPA statement present.
[A2-2430](https://pins-ds.atlassian.net/browse/A2-2430)
[A2-2430]: https://pins-ds.atlassian.net/browse/A2-2430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web): logic error in mapRepresentationDocumentSummaryActionLink

- appeals/api/src/database/prisma.batch-delete.js
- appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
- appeals/api/src/server/endpoints/appeals/appeals.formatter.js
- appeals/api/src/server/endpoints/appeals/appeals.service.js
- appeals/api/src/server/repositories/appeal-lists.repository.js
- appeals/api/src/server/utils/format-documentation-status.js
- package.json
Corrects appeal formatter types in the API
[Ticket](https://pins-ds.atlassian.net/browse/A2-1362)
> fix(api): fix appeal formatting types

- appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
- appeals/api/src/server/endpoints/appeals/appeals.controller.js
- appeals/api/src/server/endpoints/appeals/appeals.routes.js
- appeals/api/src/server/endpoints/appeals/appeals.service.js
- appeals/api/src/server/openapi.json
- appeals/api/src/server/repositories/appeal-lists.repository.js
Added appealTypeId as a filter to the GET appeals endpoint and updated tests to support it.
[A2-2492](https://pins-ds.atlassian.net/browse/A2-2492)
[A2-2492]: https://pins-ds.atlassian.net/browse/A2-2492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(api): A2-2492 Add appeal type to list of filters in the all cases list 

- appeals/web/src/server/appeals/appeal-details/environmental-assessment/__tests__/__snapshots__/environmental-assessment.test.js.snap
- appeals/web/src/server/appeals/appeal-details/environmental-assessment/__tests__/environmental-assessment.test.js
- appeals/web/src/server/appeals/appeal-details/environmental-assessment/environmental-assessment.controller.js
- appeals/web/src/server/appeals/appeal-details/environmental-assessment/environmental-assessment.router.js
- Removed redundant endpoints
- Added additional unit tests
- Web snapshots added/updated
- All web unit tests pass
[Ticket: Increase unit test coverage for environmental assessment uploads (A2-2554)](https://pins-ds.atlassian.net.mcas.ms/browse/A2-2554)
> chore(appeals): increase unit test coverage for environmental assessment uploads (a2-2554)

- appeals/api/src/server/endpoints/case-notes/__tests__/case-notes.test.js
- appeals/api/src/server/endpoints/representations/notify/services/index.js
- appeals/api/src/server/endpoints/representations/notify/services/utils.js
- appeals/api/src/server/endpoints/representations/representations.formatter.js
- appeals/api/src/server/endpoints/representations/representations.service.js
- appeals/api/src/server/repositories/representation.repository.js
- appeals/api/src/server/repositories/service-user.repository.js
Fixes rep types in the API
[Ticket](https://pins-ds.atlassian.net/browse/A2-1362)
> fix(api): fix representation api types

- appeals/api/package.json
- appeals/web/package.json
- azure-pipelines-api-test.yml
- azure-pipelines-build.yml
- azure-pipelines-ci.yml
- azure-pipelines-db-clear-test-data.yml
- azure-pipelines-db-seed-appeals.yml
- azure-pipelines-deploy-appeals.yml
- azure-pipelines-regenerate-api-key.yml
- packages/add-auth-headers-for-backend/package.json
- packages/appeals/package.json
- packages/blob-storage-client/package.json
- packages/event-client/package.json
- packages/express/package.json
- packages/key-vault-secrets-client/package.json
- packages/platform/package.json
- packages/redis/package.json
Upgrades the node version to `>=22.0.0 <= 22.14.0`
> chore(appeals): upgrade to node 22

- package-lock.json
- package.json
- packages/applications/package.json
- packages/scripts/package.json
Some packages missed when updating to run node 22
> fix(appeals): dependencies node upgrade

- appeals/api/Dockerfile
- appeals/api/src/server/endpoints/appeal-details/appeal-details.service.js
- appeals/api/src/server/endpoints/appeals/appeals.service.js
- appeals/api/src/server/repositories/appeal.repository.js
- appeals/api/src/server/utils/has-value-or-null.js
- appeals/web/Dockerfile
- Upgrade node version of Docker images to 22
- Small refactoring of duplicated code
> chore(appeals): docker node versions

- appeals/web/src/server/appeals/appeal-details/representations/final-comments/accept/__tests__/__snapshots__/accept-final-comments.test.js.snap
- appeals/web/src/server/appeals/appeal-details/representations/final-comments/accept/__tests__/accept-final-comments.test.js
- appeals/web/src/server/appeals/appeal-details/representations/final-comments/accept/components/summary-list.js
- appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/lpa-statement.controller.js
- appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/lpa-statement.mapper.js
- appeals/web/src/server/lib/mappers/types.js
- appeals/web/src/server/views/app/includes/change-page-content.pattern.njk
- appeals/web/src/server/views/patterns/change-page-full-width.pattern.njk
- appeals/web/src/server/views/patterns/change-page.pattern.njk
- appeals/web/src/server/views/patterns/display-page.pattern.njk
Change:
Created condition which instruct IP comments view to use two-thirds content size and inserts style value into html attributes.
Ticket:
https://pins-ds.atlassian.net/browse/A2-2392
> fix(appeals) full text width on review lpa statements view (a2-2392)

- appeals/api/notifications-node-client.d.ts
- appeals/api/package.json
- appeals/api/src/server/endpoints/appeals/appeals.formatter.js
- appeals/api/src/server/endpoints/case-notes/case-notes.formatter.js
- appeals/api/src/server/endpoints/case-notes/case-notes.service.js
- appeals/api/src/server/endpoints/documents/documents.validators.js
- appeals/api/src/server/endpoints/listed-buildings/__tests__/listed-buildings.test.js
- appeals/api/src/server/endpoints/neighbouring-sites/__tests__/neighbouring-sites.test.js
- appeals/api/src/server/endpoints/service-user/service-user.controller.js
- appeals/api/src/server/endpoints/site-visits/site-visits.service.js
- appeals/api/src/server/repositories/appeal-timetable.repository.js
- package-lock.json
- package.json
Fixes the last of the type errors and turns API type checking back on 🥳 
[Ticket](https://pins-ds.atlassian.net/browse/A2-1362)
> fix(api): re-enable api typechecking

- appeals/web/Dockerfile
Mismatch of docker node version in WEB.
> fix(web): docker node version

- package-lock.json
- package.json
> fix(web): missing prettier deps

- appeals/api/src/server/endpoints/appeal-types/__tests__/appeal-types.test.js
- appeals/api/src/server/endpoints/appeal-types/appeal-types.routes.js
- appeals/api/src/server/endpoints/appeals.routes.js
- appeals/api/src/server/openapi.json
- appeals/api/src/server/tests/shared/mocks.js
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/__tests__/__snapshots__/change-appeal-type.test.js.snap
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.mapper.js
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.service.js
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.types.d.ts
- appeals/web/src/server/appeals/appeals.types.d.ts
- appeals/web/src/server/appeals/national-list/__tests__/__snapshots__/national-list.test.js.snap
- appeals/web/src/server/appeals/national-list/__tests__/national-list.test.js
- appeals/web/src/server/appeals/national-list/national-list.controller.js
- appeals/web/src/server/appeals/national-list/national-list.mapper.js
- appeals/web/src/server/appeals/national-list/national-list.service.js
- appeals/web/testing/app/fixtures/referencedata.js
Added a dropdown filter to the Search all cases page, also added the /appeals/appeal-types API endpoint to support the UI. 
[A2-2568](https://pins-ds.atlassian.net/browse/A2-2568)
[A2-2568]: https://pins-ds.atlassian.net/browse/A2-2568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(appeals): A2-2568 Add appeal type to list of filters in the all cases list

- appeals/api/src/database/migrations/20250313155735_inquiry_how_many_witnesses/migration.sql
- appeals/api/src/database/schema.prisma
- appeals/api/src/server/mappers/integration/commands/appellant-case.mapper.js
- appeals/api/src/server/mappers/integration/s78/map-appellant-case.js
Missing field, reported by @brpins
> fix(api): store inquiryHowManyWitnesses field in appellant case

- appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/redact/redact.controller.js
- appeals/web/src/server/lib/mappers/components/page-components/__tests__/notification-banners.mapper.test.js
- appeals/web/src/server/lib/mappers/components/page-components/notification-banners.mapper.js
Updated redirection URL to ensure case officers are taken to the IP landing page after redacting or accepting IP comments. Confirmed that the banner displays correctly following these actions.
[A2-2083](https://pins-ds.atlassian.net/browse/A2-2083)
[A2-2083]: https://pins-ds.atlassian.net/browse/A2-2083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web): A2-2083 IP Comments > Redact and accept comment > Navigate case officer to IP Landing Page

- appeals/api/src/server/endpoints/representations/representations.controller.js
* retain 'published' status if user updating a representation which is already published
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-2661)
> fix(api): a2-2661 allow updates for published representations

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/lib/mappers/data/appeal/submappers/allocation-details.mapper.js
https://pins-ds.atlassian.net/browse/A2-2666
> feat(web): bugfix/A2-2666-copy-update

- appeals/e2e/cypress/e2e/back-office-appeals/s78ChangeTimetable.spec.js
- appeals/e2e/cypress/page_objects/caseDetailsPage.js
- appeals/e2e/cypress/support/appealsApiClient.js
- appeals/e2e/cypress/support/commands.js
Fix S78 test - add allocation if page exists.
Refactor timetable changes tests
Add test to cover business day error message for the timetable
[Ticket](https://pins-ds.atlassian.net/browse/A2-2755)
> test(appeals): fix e2e test for S78

- infrastructure/environments/prod.tfvars
Enables S78 written flag in production
> feat(appeals): enable S78 written on PROD

- appeals/web/src/server/appeals/appeal-details/representations/document-attachments/add-document.controller.js
- appeals/web/src/server/appeals/appeal-details/representations/document-attachments/manage-documents.controller.js
- appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/valid/valid.mapper.js
https://pins-ds.atlassian.net/browse/A2-2712
Fix LPA statements CYA broken links
> fix(web): bugfix/A2-2712-fix-LPA-statement-broken-CYA-links

- appeals/web/src/client/components/show-more/show-more.js
Small clientside JS fix to resolve show more not working correctly for lists
https://pins-ds.atlassian.net/browse/A2-2719
> fix(web): fix show more not working correctly for lists

- appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/__tests__/lpa-statement.test.js
- appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/allocation/allocation.mapper.js
- appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/redact/redact.mapper.js
- appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/valid/valid.controller.js
- appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/valid/valid.mapper.js
This PR fixes logic for forced allocation answers on CYA page of lpa statement review journey
https://pins-ds.atlassian.net/browse/A2-2712
https://pins-ds.atlassian.net/browse/A2-2713
> fix(web): bugfix/A2-2713-lpa-stmt-cya-allocation-specialisms

- appeals/web/src/server/appeals/appeal-details/representations/document-attachments/manage-documents.controller.js
> fix(web): fix logic to determine if IP comments

- appeals/web/src/styles/7-components/status-tag.scss
Fix box sizing on tags after 5.9.0 update
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-1710)
> fix(web): update tag box sizing after govukfe update

- appeals/api/src/server/endpoints/representations/representations.controller.js
- package-lock.json
- packages/appeals/constants/support.js
- Changed displayed text to "appellanbt/lpa final comment accpeted"
- Changed other final comments text to uniform sentence  
- Added IF condition for accepted comment status to determine correct text for case history update
https://pins-ds.atlassian.net/browse/A2-2687
> fix(appeals): correcting final comment text displayed in case history (a2-2687)

- azure-pipelines-ci.yml
Small fix detecting github queue branches
> fix(appeals): merge branches no cov

- appeals/web/src/server/appeals/appeal-details/start-case/start-case.controller.js
- appeals/web/src/server/appeals/appeal-details/start-case/start-case.router.js
Quick fix to allow s78 cases to be started despite POST functionality for the select procedure type not being in place yet
https://pins-ds.atlassian.net/browse/A2-2954
> fix(web): quick fix for inability to start s78 cases due to select procedure page

- appeals/api/jest.config.js
- appeals/api/package.json
- appeals/pdf-service-api/jest.config.js
- appeals/pdf-service-api/package.json
- appeals/web/jest.config.js
- appeals/web/package.json
- packages/express/package.json
- packages/platform/package.json
Uses worker limits to reduce memory usage
https://jestjs.io/docs/configuration#workeridlememorylimit-numberstring
> fix: use worker limits and log heap

- appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/incomplete/incomplete.controller.js
https://pins-ds.atlassian.net/browse/A2-2746
> fix(web): bugfix/A2-2746-incorrect-attachment-view

- appeals/api/src/server/notify/emulate-notify.js
> chore(appeals): delete temp email files on restart

- appeals/web/src/server/appeals/appeal-details/accordions/has.js
- appeals/web/src/server/appeals/appeal-details/accordions/s78.js
* fix(web): remove check for if startedAt is in the past
> fix(web): remove check for if startedAt is in the past

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/lib/mappers/data/appeal/submappers/__tests__/lpa-questionnaire-due-date.mapper.test.js
- appeals/web/src/server/lib/mappers/data/appeal/submappers/lpa-questionnaire-due-date.mapper.js
https://pins-ds.atlassian.net/browse/A2-2499
> fix(web): bugfix/A2-2499-lpaq-timetable-change-link

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/costs/__tests__/__snapshots__/costs.test.js.snap
- appeals/web/src/server/appeals/appeal-details/environmental-assessment/__tests__/__snapshots__/environmental-assessment.test.js.snap
- appeals/web/src/server/appeals/appeal-details/internal-correspondence/__tests__/__snapshots__/internal-correspondence.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/representations/final-comments/view-and-review/__tests__/__snapshots__/view-and-review.test.js.snap
- appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/view-and-review/__tests__/__snapshots__/view-and-review.test.js.snap
- appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/__tests__/__snapshots__/lpa-statement.test.js.snap
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js
* replaces CURRENT VERSION with Current version on the tag the document version history - snapshots updated accordingly
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-3031)
> fix(web): a2-3031 change case for current version tag

- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/correct-appeal-type/__tests__/__snapshots__/correct-appeal-type.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/correct-appeal-type/__tests__/correct-appeal-type.test.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/correct-appeal-type/correct-appeal-type.mapper.js
- appeals/web/src/server/lib/mappers/data/lpa-questionnaire/submappers/map-is-correct-appeal-type.js
* WEB: ensure appeal type is in lower case in LPAQ section
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-2965)
> fix(web): a2-2965 remove capitalisation of appeal type on lpaq

- appeals/web/src/server/appeals/appeal-details/representations/final-comments/accept/components/summary-list.js
- appeals/web/src/server/appeals/appeal-details/representations/final-comments/redact/__tests__/redact-final-comments.test.js
- appeals/web/src/server/appeals/appeal-details/representations/final-comments/redact/components/summary-list.js
- appeals/web/src/server/appeals/appeal-details/representations/final-comments/reject/__tests__/reject-final-comments.test.js
- appeals/web/src/server/appeals/appeal-details/representations/final-comments/reject/reject.mapper.js
- appeals/web/src/server/appeals/appeal-details/representations/final-comments/view-and-review/__tests__/__snapshots__/view-and-review.test.js.snap
- appeals/web/src/server/appeals/appeal-details/representations/final-comments/view-and-review/page-components/common.js
- appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/view-and-review/__tests__/__snapshots__/view-and-review.test.js.snap
- appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/view-and-review/page-components/__tests__/__snapshots__/common.test.js.snap
- appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/view-and-review/page-components/common.js
- appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/__tests__/__snapshots__/lpa-statement.test.js.snap
- appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/incomplete/incomplete.controller.js
- appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/lpa-statement.mapper.js
- appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/valid/valid.mapper.js
[2603] :https://pins-ds.atlassian.net/browse/A2-2603?linkSource=email
> fix(web): amending supporting documents section to say No documents instead of Not provided

- appeals/web/src/server/appeals/appeal-details/appeal-details.router.js
- appeals/web/src/server/appeals/appeal-details/hearing/hearing.router.js
- appeals/web/src/server/appeals/appeal-details/hearing/setup/__tests__/__snapshots__/set-up-hearing.test.js.snap
- appeals/web/src/server/appeals/appeal-details/hearing/setup/__tests__/set-up-hearing.test.js
- appeals/web/src/server/appeals/appeal-details/hearing/setup/set-up-hearing.controller.js
- appeals/web/src/server/appeals/appeal-details/hearing/setup/set-up-hearing.mapper.js
- appeals/web/src/server/appeals/appeal-details/hearing/setup/set-up-hearing.router.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/community-infrastructure-levy/infrastructure-levy-adopted-date/__tests__/__snapshots__/infrastructure-levy-adopted-date.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/community-infrastructure-levy/infrastructure-levy-expected-date/__tests__/__snapshots__/infrastructure-levy-expected-date.test.js.snap
- appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/add-ip-comment/__tests__/__snapshots__/add-ip-comment.test.js.snap
- appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/add-ip-comment/__tests__/add-ip-comment.test.js
- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap
- appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.mapper.js
- appeals/web/src/server/lib/mappers/components/page-components/date.js
- appeals/web/src/server/lib/mappers/components/page-components/time.js
- appeals/web/src/server/lib/nunjucks-template-builders/gds-components-properties-jsdoc.js
- appeals/web/src/server/lib/validators/time-input.validator.js
- appeals/web/src/server/views/app/components/time-input.njk
Add first page of set up hearing user journey
[A2-2711](https://pins-ds.atlassian.net.mcas.ms/browse/A2-2711?McasTsid=20596&McasCtx=4)
[A2-2711]: https://pins-ds.atlassian.net/browse/A2-2711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(web): add first page of set up hearing user journey

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/accordions/common/case-costs.js
- appeals/web/src/server/lib/mappers/data/appeal/has.js
- appeals/web/src/server/lib/mappers/data/appeal/submappers/costs-appellant-correspondence.mapper.js
- appeals/web/src/server/lib/mappers/data/appeal/submappers/costs-appellant-withdrawal.mapper.js
- appeals/web/src/server/lib/mappers/data/appeal/submappers/costs-lpa-application.mapper.js
- appeals/web/src/server/lib/mappers/data/appeal/submappers/costs-lpa-correspondence.mapper.js
- appeals/web/src/server/lib/mappers/data/appeal/submappers/costs-lpa-withdrawal.mapper.js
Looks like these were mistakenly deleted in a previous ticket.
- Updated snap shots
[Rows in Costs section of Case Details not showing (A2-3129)](https://pins-ds.atlassian.net/browse/A2-3129)
> fix(appeals): restore rows in costs section (a2-3129)

- docs/notifications-and-triggers.md
- docs/notifications.md
The remaining templates to be migrated will have their documentation added in another ticket/pr
[Comms: what actions trigger GovNotify emails and how (A2-2302)](https://pins-ds.atlassian.net/browse/A2-2302)
> feat(appeals): update notify triggers documentation (a2-2302)

- appeals/web/src/server/appeals/appeal-details/hearing/add-estimates/__tests__/__snapshots__/add-estimates.test.js.snap
- appeals/web/src/server/appeals/appeal-details/hearing/add-estimates/__tests__/add-estimates.test.js
- appeals/web/src/server/appeals/appeal-details/hearing/add-estimates/add-estimates.controller.js
- appeals/web/src/server/appeals/appeal-details/hearing/add-estimates/add-estimates.mapper.js
- appeals/web/src/server/appeals/appeal-details/hearing/add-estimates/add-estimates.router.js
- appeals/web/src/server/appeals/appeal-details/hearing/add-estimates/add-estimates.validators.js
- appeals/web/src/server/appeals/appeal-details/hearing/hearing.router.js
First page of add hearing estimates user journey
[A2-2749](https://pins-ds.atlassian.net.mcas.ms/browse/A2-2749?McasTsid=20596&McasCtx=4)
[A2-2749]: https://pins-ds.atlassian.net/browse/A2-2749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(web): add hearing estimates page

- appeals/api/setup-tests.js
- appeals/api/src/database/migrations/20250407145316_add_appeal_notifications/migration.sql
- appeals/api/src/database/schema.d.ts
- appeals/api/src/database/schema.prisma
- appeals/api/src/server/endpoints/appeals.routes.js
- appeals/api/src/server/endpoints/notifications/notification.controller.js
- appeals/api/src/server/endpoints/notifications/notifications.routes.js
- appeals/api/src/server/mappers/api/definitions/index.js
- appeals/api/src/server/mappers/api/definitions/notification.js
- appeals/api/src/server/notify/__tests__/notify-send.test.js
- appeals/api/src/server/notify/notify-send.js
- appeals/api/src/server/openapi-types.ts
- appeals/api/src/server/openapi.json
- appeals/api/src/server/repositories/appeal-notification.repository.js
- packages/appeals/constants/support.js
Notification logger and api endpoint to retrieve emails sent from the system.
It will start collecting data on the new notification internal templates.
[Ticket](https://pins-ds.atlassian.net/browse/A2-2741)
> feat(api): notifications logger

- appeals/web/src/server/appeals/national-list/national-list.mapper.js
- Adding missing error page summary for national cases searching
[Ticket](https://pins-ds.atlassian.net/browse/A2-2398)
> A2-2938(fix-web): adding error page summary for searching all cases national list

- appeals/web/src/server/appeals/appeal-details/linked-appeals/__tests__/__snapshots__/linked-appeals.test.js.snap
- appeals/web/src/server/appeals/appeal-details/linked-appeals/add/add.controller.js
- appeals/web/src/server/appeals/appeal-details/linked-appeals/add/add.mapper.js
* fix(web): use inline error for linked appeal reference field
test: update test snapshots to include inline error
[A2-3166](https://pins-ds.atlassian.net/browse/A2-3166)
[A2-3166]: https://pins-ds.atlassian.net/browse/A2-3166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web): use inline error for linked appeal reference field

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/lib/mappers/data/appeal/submappers/local-planning-authority.mapper.js
- appeals/web/src/server/lib/mappers/data/appeal/submappers/lpa-contact-details.mapper.js
- appeals/web/src/server/lib/mappers/data/appellant-case/submappers/local-planning-authority.js
* disable change links for LPA pending further work on functionality
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-2605)
> chore(web): a2-2605 disable change lpa link

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/lib/mappers/utils/__tests__/format-case-officer-details-for-case-summary.test.js
- appeals/web/src/server/lib/mappers/utils/format-case-officer-details-for-case-summary.js
* modify data-cy tag to assist e2e testing
*
> feat(web): a2-2983 modify data-cy tag for case officer CTA

- appeals/e2e/cypress/e2e/back-office-appeals/appellantCase.spec.js
- appeals/e2e/cypress/e2e/back-office-appeals/caseHistory.spec.js
- appeals/e2e/cypress/e2e/back-office-appeals/changeSiteVisit.spec.js
- appeals/e2e/cypress/e2e/back-office-appeals/changeStartDate.spec.js
- appeals/e2e/cypress/e2e/back-office-appeals/nationalListSearch.spec.js
- appeals/e2e/cypress/e2e/back-office-appeals/s78ChangeTimetable.spec.js
- appeals/e2e/cypress/e2e/back-office-appeals/s78LpaStatement.spec.js
- appeals/e2e/cypress/e2e/back-office-appeals/scheduleSiteVisit.spec.js
- appeals/e2e/cypress/e2e/back-office-appeals/updateLpaqDueDate.spec.js
- appeals/e2e/cypress/page_objects/basePage.js
- appeals/e2e/cypress/page_objects/caseDetailsPage.js
This PR contains e2e tests to;
- add new tests for CO updating LPA application reference 
- fix failing tests
- refactor test code
[Ticket](https://pins-ds.atlassian.net/browse/A2-2606)
> test(appeals): add test for the LPA application and fix failing tests

- appeals/e2e/cypress/e2e/back-office-appeals/assignUserToCase.spec.js
- appeals/e2e/cypress/page_objects/basePage.js
- appeals/e2e/cypress/page_objects/caseDetailsPage.js
This PR is for cypress test to check for the service header.
[Ticket](https://pins-ds.atlassian.net/browse/A2-3043)
> test(appeals): add test for service header

- appeals/api/src/server/notify/notify-send.js
Notify Templates are now loaded asynchronously
All unit tests still pass.
Sending notify email still works.
> feat(appeals): notify read templates asynchronously

- appeals/e2e/cypress/e2e/back-office-appeals/hearing.spec.js
- appeals/e2e/cypress/e2e/back-office-appeals/s78ChangeTimetable.spec.js
- appeals/e2e/cypress/page_objects/caseDetailsPage.js
This PR is for cypress test to add and update hearing estimates.
[Ticket](https://pins-ds.atlassian.net/browse/A2-2825)
> test(appeals): update estimates for e2e tests

- appeals/e2e/cypress/e2e/back-office-appeals/hearing.spec.js
- appeals/e2e/cypress/page_objects/caseDetailsPage.js
Amend hearings and check the number of days.
[Ticket](https://pins-ds.atlassian.net/browse/A2-3039)
> test(appeals): amend hearings from case overview

- appeals/api/src/database/seed/data-test.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/issue-decision.test.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.controller.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.mapper.js
- appeals/web/src/server/lib/error-handlers/__tests__/error-handlers.test.js
- appeals/web/src/server/lib/error-handlers/change-screen-error-handlers.js
Displays error message inline for decision screen
[Ticket](https://pins-ds.atlassian.net/browse/A2-3191)
> fix(web): a2-3191 display error message inline

- appeals/web/src/server/appeals/appeal-documents/appeal-documents.validators.js
- Added space to regex
ticket: https://pins-ds.atlassian.net/browse/A2-3169
> fix(web): allowing spaces in document file names

- appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/__snapshots__/issue-decision.test.js.snap
- appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/issue-decision.test.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.controller.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.mapper.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.router.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.types.d.ts
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.validators.js
- Implemented /issue-decision/appellant-costs-decision page
- Validation of above page
- Added a new row to the check your decision page for above
- Handle the back url correctly from change link.
[Issuing decision flow - Part 3 - Appellant costs decision (A2-3111)](https://pins-ds.atlassian.net/browse/A2-3111)
> fix(appeals): issue appellant costs decision (a2-3111)

- appeals/api/src/server/endpoints/appellant-cases/__tests__/appellant-cases.test.js
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.constants.js
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.controller.js
- packages/appeals/constants/support.js
Fixed case history to display updated development type.
[A2-2241](https://pins-ds.atlassian.net/browse/A2-2241)
[A2-2241]: https://pins-ds.atlassian.net/browse/A2-2241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web): A2-2241 corrected case history entry for development type updates

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.router.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/address/__tests__/__snapshots__/address.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/address/__tests__/address.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/address/address.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/address/address.mapper.js
- appeals/web/src/server/appeals/appeal-details/case-notes/case-notes.formatter.js
- appeals/web/src/server/lib/mappers/components/page-components/notification-banners.mapper.js
- appeals/web/src/server/lib/mappers/data/appeal/submappers/site-address.mapper.js
- add dynamic back link and case details specific route to change site address flow
https://pins-ds.atlassian.net/browse/A2-3164
> fix(web): change site address back link and redirect issues

- appeals/api/src/database/seed/seed-clear-test-data.js
Fixes the `clear test data` script, which was failing as unable to delete notifications from test cases.
Error details: https://dev.azure.com/planninginspectorate/appeals-back-office/_build/results?buildId=114206&view=logs&j=0a1d8c75-6a3d-5944-5d56-564de451fe0b
> fix(api): clear test data not deleting notifications

- appeals/web/src/client/components/file-uploader/_client-actions.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/__snapshots__/issue-decision.test.js.snap
- appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/issue-decision.test.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.controller.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.mapper.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.router.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.types.d.ts
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.validators.js
- appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/add-ip-comment/add-ip-comment.mapper.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.controller.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.mapper.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.types.d.ts
- appeals/web/src/server/views/appeals/documents/document-upload.njk
- Updated /issue-decision/appellant-costs-decision page and correct "cost" with "costs" where required
- Amended the Appellant costs decision page so that it redirects to the new Appellant costs decision letter upload page when "Yes" has been selected
- Added /issue-decision/appellant-costs-decision-letter-upload page
- Updated pre headers to include a suffix of - issue decision
- Added a new row to the check your decision page for above
- Handle the back url correctly from change link
- Fixed upload button so that it does not change the text when dropping files in the dropzone
[Issuing decision flow - Part 4 - 'Appellant costs decision …
> feat(appeals): issue appellant costs decision letter upload (a2-3133)

- appeals/web/src/server/lib/mappers/utils/__tests__/is-lpaq-received.test.js
- appeals/web/src/server/lib/mappers/utils/is-lpaq-received.js
* update logic to check if an LPAQ has been received or not
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-2605)
> fix(web): a2-2605 fix lpaq received logic

- appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/__snapshots__/issue-decision.test.js.snap
- appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/issue-decision.test.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.controller.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.mapper.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.router.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.types.d.ts
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.validators.js
- Implemented /issue-decision/lpa-costs-decision page
- Validation of above page
- Added a new row to the check your decision page for above
- Handle the back url correctly from change link.
[Issuing decision flow - Part 5 - LPA costs decision (A2-3151)](https://pins-ds.atlassian.net/browse/A2-3151)
> fix(appeals): issue lpa costs decision (a2-3151)

- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.controller.js
Clear file cache when document type changes
[Ticket A2-3153](https://pins-ds.atlassian.net.mcas.ms/browse/A2-3153)
> fix(appeals): issue lpa decision clear file cache (a2-3153)

- appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/__snapshots__/issue-decision.test.js.snap
- appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/issue-decision.test.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.controller.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.mapper.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.router.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.validators.js
- appeals/web/testing/app/fixtures/referencedata.js
- Removed unnecessary code for previous invalid page and decision date pages
- Incorporate redirection logic as described within the ticket using defined constants
[Appellant and LPA Costs Decision Screen Logic (A2-3158)](https://pins-ds.atlassian.net/browse/A2-3158)
> feat(appeals): issue lpa and appellant decision screen logic (a2-3158)

- appeals/web/src/server/appeals/appeal-details/appellant-case/address/__tests__/__snapshots__/address.test.js.snap
- appeals/web/src/server/appeals/appeal-details/hearing/setup/__tests__/__snapshots__/set-up-hearing.test.js.snap
- appeals/web/src/server/appeals/appeal-details/neighbouring-sites/__tests__/__snapshots__/neighbouring-sites.test.js.snap
- appeals/web/src/server/appeals/appeal-details/neighbouring-sites/__tests__/neighbouring-sites.test.js
- appeals/web/src/server/lib/error-handlers/__tests__/error-handlers.test.js
- appeals/web/src/server/lib/error-handlers/change-screen-error-handlers.js
- appeals/web/src/server/lib/mappers/components/page-components/address.js
- appeals/web/src/server/lib/validators/address.validator.js
- appeals/web/testing/app/shared-examples/address-form.js
* update content and handling for address validation error messages
* update tests/snapshots
[Ticket](https://pins-ds.atlassian.net/browse/A2-3195)
> feat(web): a2-3194 update address validation error messages and handling

- infrastructure/service-bus.tf
- infrastructure/terraform.tfvars
- infrastructure/variables.tf
Adds the new service bus topic 'appeal_event_estimate'.
> chore(appeals): appeal event estimate sb topic

- appeals/api/src/server/endpoints/case-notes/__tests__/case-notes.test.js
- appeals/api/src/server/endpoints/case-notes/case-notes.validators.js
- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/appeal-details/appeals-details.validator.js
- appeals/web/src/server/appeals/appeal-details/case-notes/case-notes.mapper.js
- appeals/web/src/server/appeals/appeal.constants.js
- appeals/web/src/server/lib/nunjucks-template-builders/gds-components-properties-jsdoc.js
- appeals/web/src/server/views/appeals/components/case-notes.njk
- increases character limit on case note text to 500
- updates to unit tests
https://pins-ds.atlassian.net/browse/A2-3316
> fix(appeals): increase case note character limit to 500

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/change-appeal-details/local-planning-authority/__tests__/__snapshots__/local-planning-authority.test.js.snap
- appeals/web/src/server/appeals/appeal-details/change-appeal-details/local-planning-authority/local-planning-authority.controller.js
- appeals/web/src/server/appeals/appeal-details/change-appeal-details/local-planning-authority/local-planning-authority.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
* enable inline error message on change LPA radio page
* update test snapshots
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-3195)
> fix(web): a2-3195 bugfix add inline error message on change LPA page

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/change-appeal-details/local-planning-authority/__tests__/__snapshots__/local-planning-authority.test.js.snap
- appeals/web/src/server/appeals/appeal-details/change-appeal-details/local-planning-authority/local-planning-authority.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
* update id prefix so error message behaviour is as expected
[Ticket](https://pins-ds.atlassian.net/browse/A2-3195)
> fix(web): a2-3195 bugfix update change LPA id prefix

- appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/add-ip-comment/add-ip-comment.router.js
- appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/add-ip-comment/add-ip-comment.validators.js
- appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/common/validators.js
- appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/edit-ip-comment/edit-ip-comment.router.js
add validation to County field when editing IP comment address
[A2-1288](https://pins-ds.atlassian.net.mcas.ms/browse/A2-1288)
[A2-1288]: https://pins-ds.atlassian.net/browse/A2-1288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web): add validation to County field when editing IP comment address

- docs/feature-flags.md
Add instructions for creating feature flags
> docs(appeals): add instructions for creating feature flags

- appeals/api/src/server/endpoints/invalid-appeal-decision/__tests__/invalid-appeal-decision.test.js
- appeals/api/src/server/endpoints/invalid-appeal-decision/invalid-appeal-decision.service.js
[A2-3354](https://pins-ds.atlassian.net/browse/A2-3354)
[A2-3354]: https://pins-ds.atlassian.net/browse/A2-3354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(api): routing a single invalid reason to the decision email

- appeals/web/src/server/appeals/appeal-details/representations/final-comments/view-and-review/__tests__/__snapshots__/view-and-review.test.js.snap
- appeals/web/src/server/appeals/appeal-details/representations/final-comments/view-and-review/page-components/common.js
fixed redact link to the LPA and Appellant final comments
[A2-2694](https://pins-ds.atlassian.net/browse/A2-2694)
[A2-2694]: https://pins-ds.atlassian.net/browse/A2-2694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web): added redact link to appellant and LPA final comments

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/national-list/__tests__/__snapshots__/national-list.test.js.snap
- appeals/web/src/server/appeals/personal-list/__tests__/__snapshots__/personal-list.test.js.snap
- appeals/web/src/server/lib/appeal-status.js
- appeals/web/src/server/lib/nunjucks-filters/status-tag.js
- appeals/web/src/server/views/appeals/components/status-tag.njk
- global updates to status tag colours
https://pins-ds.atlassian.net/browse/A2-1057
> feat(appeals): global updates to status tag colours

- appeals/web/src/server/appeals/appeal-details/hearing/setup/__tests__/__snapshots__/change-hearing.test.js.snap
- appeals/web/src/server/appeals/appeal-details/hearing/setup/__tests__/__snapshots__/set-up-hearing.test.js.snap
- appeals/web/src/server/appeals/appeal-details/hearing/setup/set-up-hearing.mapper.js
- add data-cy tags and accessibility labels to change links on hearing CYA page
[A2-3023](https://pins-ds.atlassian.net/browse/A2-3023)
[A2-3023]: https://pins-ds.atlassian.net/browse/A2-3023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web): add data-cy tags to change links on hearing CYA page

- appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/lpa-statement.controller.js
- appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/valid/valid.controller.js
- appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/valid/valid.mapper.js
- appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/valid/valid.router.js
- fixes allocation level and specialisms selected options persisting between appeals in review LPA statement journey
https://pins-ds.atlassian.net/browse/A2-3403
> fix(web): scope lpa statement review session data to appeal id

- appeals/web/src/server/appeals/appeal-details/hearing/setup/__tests__/__snapshots__/cancel-hearing.test.js.snap
- appeals/web/src/server/appeals/appeal-details/hearing/setup/__tests__/cancel-hearing.test.js
- appeals/web/src/server/appeals/appeal-details/hearing/setup/cancel-hearing.mapper.js
- appeals/web/src/server/views/app/includes/check-and-confirm-page-content.pattern.njk
- Reinstate keep hearing link on cancel hearing page
[A2-2927](https://pins-ds.atlassian.net/browse/A2-2927)
[A2-2927]: https://pins-ds.atlassian.net/browse/A2-2927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web): reinstate keep hearing link on cancel hearing page

- appeals/web/src/server/appeals/national-list/__tests__/__snapshots__/national-list.test.js.snap
- appeals/web/src/server/appeals/national-list/national-list.mapper.js
- appeals/web/src/styles/5-elements/_elements.page.scss
- appeals/web/src/styles/7-components/_table.scss
Add custom CSS to resolve layout issues with all cases table at smaller screen sizes
https://pins-ds.atlassian.net/browse/A2-3288
> fix(web): fix layout issues with all cases table at small screen sizes

- appeals/web/src/server/appeals/appeal-details/representations/final-comments/accept/__tests__/__snapshots__/accept-final-comments.test.js.snap
- appeals/web/src/server/appeals/appeal-details/representations/final-comments/accept/components/summary-list.js
- appeals/web/src/server/appeals/appeal-details/representations/final-comments/redact/components/summary-list.js
- appeals/web/src/server/appeals/appeal-details/representations/final-comments/reject/reject.mapper.js
- appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/view-and-review/__tests__/__snapshots__/view-and-review.test.js.snap
- appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/view-and-review/page-components/reject.mapper.js
- appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/view-and-review/reject/reject.controller.js
- appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/incomplete/incomplete.controller.js
Add manage and add supporting document (attachment) links to ip comment and final comment cya pages (these were previously missing)
https://pins-ds.atlassian.net/browse/A2-3415
> fix(web): add manage and add supporting doc links to ip comment and final comment cya pages

- appeals/web/src/server/appeals/appeal-details/issue-decision-old/issue-decision.mapper.js
Add show more component to the invalid reasons text on the issue invalid decision CYA page (old flow)
https://pins-ds.atlassian.net/browse/A2-3353
> fix(web): add show more to issue decision invalid reasons text on CYA page

- appeals/web/src/server/appeals/national-list/__tests__/__snapshots__/national-list.test.js.snap
- appeals/web/src/server/appeals/national-list/national-list.mapper.js
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-3370)
> feat(web): removing link from planning application reference in national list

- appeals/api/src/server/endpoints/appeal-timetables/__tests__/appeal-timetables.test.js
- appeals/api/src/server/endpoints/appeal-timetables/appeal-timetables.service.js
- appeals/api/src/server/endpoints/hearings/__tests__/hearing.test.js
- appeals/api/src/server/endpoints/hearings/hearing.controller.js
- packages/appeals/constants/support.js
- Add hearing events to case history
[A2-3128](https://pins-ds.atlassian.net/browse/A2-3128)
[A2-3128]: https://pins-ds.atlassian.net/browse/A2-3128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(api): add audit trail for hearings

- appeals/web/src/server/appeals/appeal-details/representations/final-comments/accept/__tests__/__snapshots__/accept-final-comments.test.js.snap
- appeals/web/src/server/appeals/appeal-details/representations/final-comments/accept/components/summary-list.js
- appeals/web/src/server/appeals/appeal-details/representations/final-comments/redact/__tests__/redact-final-comments.test.js
- appeals/web/src/server/appeals/appeal-details/representations/final-comments/redact/components/summary-list.js
- appeals/web/src/server/appeals/appeal-details/representations/final-comments/reject/__tests__/reject-final-comments.test.js
- appeals/web/src/server/appeals/appeal-details/representations/final-comments/reject/reject.mapper.js
“change” button on review decision CYA accept view (back button goes back to personal list) 
“change” button on “review decision” row – CYA redact view (back button goes to personal list)
“change” button on “review decision” row – CYA reject view (back button goes to personal list)
“change” button on “reject reasons” row – CYA reject view (back button goes to review comment)
[A2-3054](https://pins-ds.atlassian.net/browse/A2-3054)
[A2-3054]: https://pins-ds.atlassian.net/browse/A2-3054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(web): added backlinks to urls based on requirements

- infrastructure/.terraform.lock.hcl
- infrastructure/provider.tf
https://pins-ds.atlassian.net/browse/DEV-470
> chore(infrastructure): upgrade azurerm to 4.32.0

- infrastructure/app-api.tf
- infrastructure/app-web.tf
- infrastructure/function-casedata-import.tf
- infrastructure/function-doc-processing.tf
- infrastructure/function-refdata-import.tf
- infrastructure/function-scheduled-jobs.tf
- infrastructure/provider.tf
https://pins-ds.atlassian.net/browse/DEV-467
> chore(infrastructure): support terraform 1.12

- appeals/api/src/server/endpoints/hearings/__tests__/hearing.test.js
- appeals/api/src/server/endpoints/hearings/hearing.controller.js
Fixed bug were not all address was displaying for hearing audit trail
[A2-3128](https://pins-ds.atlassian.net/browse/A2-3128)
[A2-3128]: https://pins-ds.atlassian.net/browse/A2-3128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fixed bug were not all address was displaying for hearing audit trail

- appeals/web/src/server/lib/mappers/data/appeal/submappers/lpa-final-comments.mapper.js
- removed console.log
https://pins-ds.atlassian.net/browse/A2-3236
> a2-3236/removed-console-log

- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/affected-listed-buildings/affected-listed-buildings.controller.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/affected-listed-buildings/affected-listed-buildings.mapper.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/changed-listed-buildings/__tests__/__snapshots__/changed-listed-buildings.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/changed-listed-buildings/__tests__/changed-listed-buildings.test.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/changed-listed-buildings/changed-listed-buildings.mapper.js
- appeals/web/testing/app/fixtures/referencedata.js
Updating copy to reflect the design given in A2-3495
[Ticket](https://pins-ds.atlassian.net/browse/A2-3495)
> feat(web): update copy for affected and changed listed building

- appeals/web/src/server/appeals/appeal-details/appeal-details.router.js
- appeals/web/src/server/appeals/appeal-details/inquiry/inquiry.router.js
- appeals/web/src/server/appeals/appeal-details/inquiry/setup/__tests__/__snapshots__/set-up-inquiry.test.js.snap
- appeals/web/src/server/appeals/appeal-details/inquiry/setup/__tests__/set-up-inquiry.test.js
- appeals/web/src/server/appeals/appeal-details/inquiry/setup/inquiry.service.js
- appeals/web/src/server/appeals/appeal-details/inquiry/setup/set-up-inquiry-validators.js
- appeals/web/src/server/appeals/appeal-details/inquiry/setup/set-up-inquiry.controller.js
- appeals/web/src/server/appeals/appeal-details/inquiry/setup/set-up-inquiry.mapper.js
- appeals/web/src/server/appeals/appeal-details/inquiry/setup/set-up-inquiry.router.js
- appeals/web/src/server/appeals/appeal-details/start-case/start-case.controller.js
added inquiry date page with setup directory
[A2-3259](https://pins-ds.atlassian.net/browse/A2-3259)
[A2-3259]: https://pins-ds.atlassian.net/browse/A2-3259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(appeals): added inquiry date page with setup directory

- appeals/api/src/server/endpoints/appeal-details/__tests__/appeals-details.test.js
- appeals/api/src/server/mappers/api/shared/map-completed-state-list.js
Small fix to logic for adding states to completed List
[Ticket]()
> fix(web): fixing bug for mapcompletedStateList

- appeals/web/environment/config.js
- infrastructure/app-api.tf
- infrastructure/app-web.tf
- infrastructure/environments/dev.tfvars
- infrastructure/environments/prod.tfvars
- infrastructure/environments/test.tfvars
- infrastructure/environments/training.tfvars
- infrastructure/variables.tf
Add the CAS feature flag to terraform.
> feat(appeals): add feature flag for CAS

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/lib/mappers/data/appellant-case/submappers/inspector-access.js
- appeals/web/src/server/lib/mappers/data/appellant-case/submappers/other-tenants-of-agricultural-holding.js
changed text from no answered to no
[A2-3485](https://pins-ds.atlassian.net/browse/A2-3485)
[A2-3485]: https://pins-ds.atlassian.net/browse/A2-3485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(appeals): changed text from no answered to no

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/appeal-details/status-tags/status-tags.mapper.js
- Correct the view issue link
- Update tests and snapshots for above
- [(A2-3173)Issuing decision flow - Part 9 - Viewing the decision details](https://pins-ds.atlassian.net/browse/A2-3173)
> fix(appeals): viewing the decision details (a2-3173)

- appeals/api/src/server/endpoints/documents/documents.controller.js
- appeals/web/src/server/appeals/appeal-details/audit/audit.mapper.js
- packages/appeals/constants/support.js
FIxed audit trail for document uploads
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-2610)
> fix(api): fixing audit trail for document and document versions

- appeals/web/src/server/appeals/appeal-details/assign-user/__tests__/assign-user.test.js
- appeals/web/src/server/appeals/appeal-details/assign-user/assign-user.controller.js
- Addressing a bug where state wasn't transitioning
[Ticket]()
> fix(web): changing variable to id rather than assigneeId to address bug

- appeals/web/src/server/lib/mappers/data/appeal/submappers/__tests__/environmental-assessment.mapper.test.js
- appeals/web/src/server/lib/mappers/data/appeal/submappers/environmental-assessment.mapper.js
Added width to table column to keep width of environmental services doc row
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-3417)
> fix(web): updating cell sizing to keep links on the same line

- appeals/web/src/server/appeals/appeal-details/appeal-decision/__tests__/__snapshots__/appeal-decision.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appeal-decision/__tests__/appeal-decision.test.js
- appeals/web/src/server/appeals/appeal-details/appeal-decision/appeal-decision.mapper.js
- appeals/web/src/server/appeals/appeal-details/status-tags/status-tags.mapper.js
- Presenting the re-issue date on the status-mapper for decision letters
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-3448)
> Feat(A2-3448): adding reissue date on inset text

- appeals/web/src/server/appeals/appeal-details/timetable/__tests__/__snapshots__/timetable.test.js.snap
- appeals/web/src/server/appeals/appeal-details/timetable/__tests__/timetable.test.js
- appeals/web/src/server/appeals/appeal-details/timetable/timetable.controller.js
- appeals/web/src/server/appeals/appeal-details/timetable/timetable.mapper.js
- appeals/web/src/server/appeals/appeal-details/timetable/timetable.validators.js
- appeals/web/src/server/lib/dates.js
- appeals/web/src/server/lib/string-utilities.js
- appeals/web/src/server/lib/validators/date-input.validator.js
- Adding logic to replay error fields to the user rather than resetting them
- Adding new validator to check whether due dates are after some other specified dates
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-3094)
> feat(A2-3094): Timetable due date validation bugs

- appeals/api/src/server/endpoints/integrations/integrations.middleware.js
Removed feature flag check as it doesn't add anything at this stage
Added s20 to the allowed list
https://pins-ds.atlassian.net/browse/A2-3762
> fix:(api): a2-3762 allow reps on s20 appeal

- appeals/api/src/server/endpoints/appeal-timetables/__tests__/appeal-timetables.test.js
- appeals/api/src/server/endpoints/appeal-timetables/appeal-timetables.service.js
- Saving timetable due dates case history updates as bullet point list
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-3726)
> feat(A2-3726): Saving case history timetable changes as a bullet point list

- appeals/web/src/server/appeals/appeal-details/hearing/setup/__tests__/change-hearing.test.js
- appeals/web/src/server/appeals/appeal-details/hearing/setup/__tests__/set-up-hearing.test.js
- appeals/web/src/server/appeals/appeal-details/inquiry/setup/__tests__/set-up-inquiry.test.js
- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap
- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/site-visit.test.js
- appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.controller.js
- appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.mapper.js
- appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.validators.js
- appeals/web/src/server/lib/mappers/components/page-components/notification-banners.mapper.js
- appeals/web/src/server/lib/mappers/components/page-components/time.js
- appeals/web/src/server/lib/validators/time-input.validator.js
- appeals/web/src/server/views/app/components/time-input.njk
- Updated error messages for time fields
- Updated Success banners for fit visit scheduling and updating
- Added inline errors for the time component
- Manual tested the new error messages within the browser
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-3203)
> feat(web): updating error messages for site visit page (A2-3203)

- appeals/e2e/cypress/e2e/back-office-appeals/hearing.spec.js
- appeals/e2e/cypress/e2e/back-office-appeals/progressS78ToDecision.spec.js
- appeals/e2e/cypress/page_objects/caseDetailsPage.js
- appeals/e2e/cypress/support/appealsApiClient.js
- appeals/e2e/cypress/support/commands.js
This PR contains cypress test to:
- site section is removed for hearing cases
- verify site section is present for written cases
- fix function to update cases
[Ticket](https://pins-ds.atlassian.net/browse/A2-3778)
> remove site section for hearing cases

- appeals/api/src/server/endpoints/appeal-timetables/__tests__/appeal-timetables.test.js
- appeals/api/src/server/endpoints/appellant-cases/__tests__/__snapshots__/appellant-cases.test.js.snap
- appeals/api/src/server/endpoints/appellant-cases/__tests__/appellant-cases.test.js
- appeals/api/src/server/tests/appeals/mocks.js
Adds missed appellant notify test cases
[Ticket A2-3575](https://pins-ds.atlassian.net.mcas.ms/browse/A2-3575)
> test(api): a2-3575 s20 appellant notify p1

- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/page-components/cas.mapper.js
Adding linked appeals in the CAS appellant case to match the change made to HAS (https://github.com/Planning-Inspectorate/appeals-back-office/pull/1579)
[Ticket](https://pins-ds.atlassian.net/browse/A2-3263)
> fix(web): show linked appeals in CAS appellant case (A2-3263)

- appeals/web/src/client/components/file-uploader/_client-actions.js
- appeals/web/src/client/components/file-uploader/_html.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/issue-decision.test.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.validators.js
- Updated error messages for the issue decision flow
- Manual testing within browser 
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-3654)
> feat(web): issue decision error messages and success banners (A2-3654)

- appeals/api/src/server/endpoints/representations/__tests__/representations.test.js
- appeals/api/src/server/endpoints/representations/representations.service.js
- appeals/api/src/server/notify/templates/__tests__/appeal-valid-start-case-s78-appellant.test.js
- appeals/api/src/server/notify/templates/__tests__/appeal-valid-start-case-s78-lpa.test.js
- appeals/api/src/server/notify/templates/__tests__/notify-hearing-set-up.test.js
- appeals/api/src/server/notify/templates/__tests__/notify-hearing-updated.test.js
- appeals/api/src/server/notify/templates/appeal-valid-start-case-s78-appellant.content.md
- appeals/api/src/server/notify/templates/appeal-valid-start-case-s78-lpa.content.md
- appeals/api/src/server/notify/templates/appeal-valid-start-case-s78-lpa.subject.md
- appeals/api/src/server/notify/templates/hearing-set-up.content.md
- appeals/api/src/server/notify/templates/hearing-updated.content.md
Fixed various issues with email notifications for hearing cases that were flagged up by testing.
[A2-3068](https://pins-ds.atlassian.net/browse/A2-3068)
[A2-3068]: https://pins-ds.atlassian.net/browse/A2-3068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(api): hearing comms amendments

- appeals/web/src/server/appeals/appeal-details/inquiry/setup/__tests__/__snapshots__/set-up-inquiry.test.js.snap
- appeals/web/src/server/appeals/appeal-details/inquiry/setup/set-up-inquiry.controller.js
- appeals/web/src/server/appeals/appeal-details/inquiry/setup/set-up-inquiry.mapper.js
- Added session values to mapper
https://pins-ds.atlassian.net/browse/A2-3498?atlOrigin=eyJpIjoiNTI3YmM5Yzk2MGFlNDBiZWFlOGIwMjU4Njg2N2I1ZmUiLCJwIjoiaiJ9
> feat(web): adding session values to page map (a2-3498)

- appeals/web/src/server/appeals/appeal-details/timetable/__tests__/__snapshots__/timetable.test.js.snap
- appeals/web/src/server/appeals/appeal-details/timetable/__tests__/timetable.test.js
- appeals/web/src/server/appeals/appeal-details/timetable/timetable.mapper.js
- appeals/web/src/server/lib/dates.js
- Added function to show more applicable hint dates depending on todays date 
- Using function in timetable due dates page
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-3727)
> feat(A2-3727): adding function to show more relevant hint dates

- appeals/api/src/server/endpoints/appeal-timetables/__tests__/appeal-timetables.test.js
- appeals/api/src/server/endpoints/appeal-timetables/appeal-timetables.controller.js
- appeals/api/src/server/endpoints/representations/__tests__/representations.test.js
- appeals/api/src/server/endpoints/representations/representations.service.js
- appeals/api/src/server/notify/templates/__tests__/notify-received-statement-and-ip-comments-appellant.test.js
- appeals/api/src/server/notify/templates/__tests__/notify-received-statement-and-ip-comments-lpa.test.js
- appeals/api/src/server/notify/templates/received-statement-and-ip-comments-appellant.subject.md
- appeals/api/src/server/notify/templates/received-statement-and-ip-comments-lpa.subject.md
> fix(api): more amendments to hearing comms

- appeals/e2e/cypress/e2e/back-office-appeals/hearing.spec.js
- appeals/e2e/cypress/fixtures/appealsApiRequests.js
- appeals/e2e/cypress/page_objects/caseDetails/hearingSectionPage.js
- appeals/e2e/cypress/page_objects/caseDetailsPage.js
- appeals/e2e/cypress/support/appealsApiClient.js
- appeals/e2e/cypress/support/commands.js
- appeals/e2e/cypress/support/happyPathHelper.js
This PR contains cypress test to:
- verify hearing comms, part 1
- refactor codes and fix failing tests
[Ticket](https://pins-ds.atlassian.net/browse/A2-3068)
> test(appeals): verify hearing comms

- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
- appeals/api/src/server/endpoints/appeals/appeals.formatter.js
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/personal-list/personal-list.mapper.js
- appeals/web/src/server/lib/mappers/utils/__tests__/required-actions.test.js
- appeals/web/src/server/lib/mappers/utils/map-status-dependent-notifications.js
- appeals/web/src/server/lib/mappers/utils/required-actions.js
- appeals/web/testing/app/fixtures/referencedata.js
Added personal list information for hearing when hearing address is not setup
[A2-3806](https://pins-ds.atlassian.net/browse/A2-3806)
[A2-3806]: https://pins-ds.atlassian.net/browse/A2-3806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(appeals): personal list information for hearing

- appeals/web/src/server/appeals/appeal-details/representations/final-comments/accept/__tests__/__snapshots__/accept-final-comments.test.js.snap
- appeals/web/src/server/appeals/appeal-details/representations/final-comments/accept/components/summary-list.js
- appeals/web/src/server/appeals/appeal-details/representations/final-comments/redact/components/summary-list.js
Fixed routing issues with final comments
[A2-3825](https://pins-ds.atlassian.net/browse/A2-3825)
[A2-3825]: https://pins-ds.atlassian.net/browse/A2-3825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(appeals): fixed issues with backlinks on final comments

- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/__snapshots__/site-visit.test.js.snap
- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/site-visit.test.js
- appeals/web/src/server/appeals/appeal-details/site-visit/site-visit.mapper.js
- appeals/web/src/server/lib/mappers/components/page-components/notification-banners.mapper.js
- appeals/web/src/server/lib/validators/time-input.validator.js
- appeals/web/src/server/views/app/components/time-input.njk
- Corrected success banner to say site visit updated
- Updated time input fields to text so that the correct error messages can be displayed
- Updated snapshots 
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-3203)
> feat(web): update site visit banner and time error messages(A2-3203)

- appeals/web/src/server/appeals/appeal-details/representations/final-comments/accept/__tests__/__snapshots__/accept-final-comments.test.js.snap
- appeals/web/src/server/appeals/appeal-details/representations/final-comments/accept/components/summary-list.js
Updated backlink 
[A2-3871](https://pins-ds.atlassian.net/browse/A2-3871)
[A2-3871]: https://pins-ds.atlassian.net/browse/A2-3871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(appeals): updated change backurl link for final comments

- docs/notifications.md
Quick chore PR to update notify documentation to indicate the templates are a nunjucks/markdown hybrid
> feat(appeals): add defaults and comments to help with code review (a2-3753)

- appeals/api/src/server/endpoints/representations/__tests__/representations.test.js
- appeals/api/src/server/endpoints/representations/representations.controller.js
- appeals/api/src/server/endpoints/representations/representations.service.js
Fix notify trigger logic for statements/ip comments
[A2-3844](https://pins-ds.atlassian.net/browse/A2-3844)
[A2-3844]: https://pins-ds.atlassian.net/browse/A2-3844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(api): A2-3844 fix notify trigger logic for statements/ip comments

- appeals/api/src/server/endpoints/representations/__tests__/representations.test.js
- appeals/api/src/server/endpoints/representations/representations.service.js
- appeals/api/src/server/notify/templates/__tests__/notify-received-statement-and-ip-comments-lpa.test.js
- appeals/api/src/server/notify/templates/received-statement-and-ip-comments-lpa.content.md
Fix notify trigger logic when no statements/ip comments
[A2-3844](https://pins-ds.atlassian.net/browse/A2-3844)
[A2-3844]: https://pins-ds.atlassian.net/browse/A2-3844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(api): A2-3844 fix notify trigger logic when no statements/ip comments

- infrastructure/environments/prod.tfvars
Increase the database capacity in production from an S0 -> S3. This is as a result of production issues.
> fix(appeals): increased db size to S3

- appeals/web/src/server/appeals/appeal-details/status-tags/status-tags.mapper.js
- appeals/web/src/server/appeals/personal-list/personal-list.mapper.js
- appeals/web/src/server/lib/mappers/data/appeal/submappers/started-at.mapper.js
- appeals/web/src/server/lib/mappers/utils/map-status-dependent-notifications.js
[Ticket: a2-3475](https://pins-ds.atlassian.net.mcas.ms/browse/A2-3475)
> fix(appeals): make sure linked appeals is behind the feature flag (a2-3475)

- appeals/e2e/cypress/e2e/back-office-appeals/hearing.spec.js
Fix hearing e2e tests
Audit log message has changed
> fix(test/e2e): fix hearing e2e tests

- azure-pipelines-build.yml
- azure-pipelines-deploy-appeals.yml
Changed the build and deploy pipelines to run the PDF generator.
> feat(appeals): create deployment pipelines for PDF generator (a2 3751)

- appeals/e2e/cypress/e2e/back-office-appeals/hearing.spec.js
- appeals/e2e/cypress/page_objects/caseDetails/hearingSectionPage.js
Fix hearing test pipeline failure (datetime-related)
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-3927)
> test(appeals): fix datetime test failure for hearing

- appeals/e2e/cypress/e2e/back-office-appeals/changeContact.spec.js
- appeals/e2e/cypress/fixtures/appealsApiRequests.js
- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/service-user/__tests__/__snapshots__/service-user.test.js.snap
- appeals/web/src/server/appeals/appeal-details/service-user/__tests__/service-user.test.js
- appeals/web/src/server/appeals/appeal-details/service-user/service-user.controller.js
- appeals/web/src/server/appeals/appeal-details/service-user/service-user.mapper.js
- appeals/web/src/server/appeals/appeal-details/service-user/service-user.validators.js
- appeals/web/src/server/lib/validators/email-input.validator.js
- appeals/web/src/server/lib/validators/text-input-validator.js
- packages/appeals/constants/index.d.ts
- packages/appeals/utils/string-token-replacement.js
- Updated error and banner messages for changing the contact details page
- Updated snapshots 
- Updated e2e tests
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-3676)
> feat(web): appellant and agent details - Error Messages (A2-3676)

- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.mapper.js
- Swapping the view decision rows
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-3292)
> feat(A2-3292): Swapping the view decision rows

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/issue-decision.test.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.controller.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.mapper.js
- appeals/web/src/server/appeals/appeal-details/status-tags/status-tags.mapper.js
- appeals/web/testing/app/fixtures/referencedata.js
- fixed the view decision and appeal details screen
- Added missing unit tests
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-3295)
> feat(web): showing correct text on view decision and appeal-details screens (A2-3295)

- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
- appeals/web/src/server/appeals/appeal-documents/appeal-documents.validators.js
- Small updated to bring the page inline with new copy text
- Updated unit test
- tested within browser
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-3697)
> feat(web): appellant cost withdrawl error messages and banners (A2-3697)

- appeals/e2e/cypress/e2e/back-office-appeals/changeContact.spec.js
- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/service-user/service-user.controller.js
- appeals/web/src/server/lib/validators/text-input-validator.js
- Updated success banners for agent and appellant contact details updates
- Added error handling for invalid characters for first name and last name
- updated unit tests and snapshots
-  updated e2e tests
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-3676)
> feat(web): updating contact details success banners (A2-3676)

- appeals/web/src/server/appeals/appeal-details/accordions/common/case-overview.js
- appeals/web/src/server/lib/mappers/data/appeal/submappers/__tests__/case-procedure.mapper.test.js
- appeals/web/src/server/lib/mappers/data/appeal/submappers/case-procedure.mapper.js
added change link to procedure type on case detail
[A2-3919](https://pins-ds.atlassian.net/browse/A2-3919)
[A2-3919]: https://pins-ds.atlassian.net/browse/A2-3919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(appeals): added change link to procedure type on case detail

- appeals/api/src/server/endpoints/linkable-appeals/__tests__/linkable-appeal.test.js
- appeals/api/src/server/endpoints/linkable-appeals/linkable-appeal.controller.js
- appeals/api/src/server/endpoints/linkable-appeals/linkable-appeal.service.js
- Applying fixes from last release to main
https://github.com/Planning-Inspectorate/appeals-back-office/commit/ac6d8bbbb70bfb3c007e6cb499f7e0728b5ab321
https://github.com/Planning-Inspectorate/appeals-back-office/commit/e56b614d3fc003c55c70cf16ea3c943f00ad7038
[Ticket]()
> fix(api): applying api linked appeals fixes from release to main

- appeals/web/src/styles/7-components/_autocomplete.scss
- CSS update to add background color for odd options in autocomplete component (same as FO). 
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-3832)
> feat(A2-3832): css update to add background color for autocomplete

- appeals/web/src/server/appeals/appeal-details/accordions/common/case-overview.js
visially removed additional line when case not started
[A2-3919](https://pins-ds.atlassian.net/browse/A2-3919)
[A2-3919]: https://pins-ds.atlassian.net/browse/A2-3919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(appeals): visually removed additional line when case not started

- appeals/e2e/cypress/e2e/back-office-appeals/linkAppeals.spec.js
- appeals/e2e/cypress/page_objects/caseDetailsPage.js
[Ticket: a2-3630](https://pins-ds.atlassian.net/browse/A2-3630)
> feat(test/e2e): fix linked appeal test

- appeals/web/src/server/appeals/appeal-details/assign-user/__tests__/__snapshots__/assign-user.test.js.snap
- appeals/web/src/server/appeals/appeal-details/assign-user/__tests__/assign-user.test.js
- appeals/web/src/server/appeals/appeal-details/assign-user/assign-user.mapper.js
- appeals/web/src/server/appeals/appeal-details/assign-user/assign-user.validator.js
- Updated page title and error messages
- Updated unit tests and snapshots
- Manual testing within browser
- Check e2e assignUserToCase was not broken
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-3843)
> feat(web): updating assign user title and error messages (A2-3843)

- appeals/api/src/server/state/__tests__/state-machine.test.js
- appeals/api/src/server/state/create-state-machine.js
- appeals/api/src/server/state/transition-state.js
- updated state machine so that if case is progressed after final comments are rejected or approved and the site visit has elapsed the case will progress to issue decision
- Updated test 
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-3695)
> fix(api): state transition from final comments to issue decision

- appeals/api/src/database/seed/LPAs/prod.js
- Removing Sedgemoor (as previously done for release)
- Removing south somerset
[A2-4058](https://pins-ds.atlassian.net/browse/A2-4058) 
[A2-4058]: https://pins-ds.atlassian.net/browse/A2-4058?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Feat(A2-4058/A2-4059): removing south somerset

- appeals/api/src/server/mappers/__tests__/mapper-factory.test.js
- appeals/api/src/server/mappers/integration/commands/questionnaire.mapper.js
- appeals/api/src/server/mappers/integration/s20/map-lpa-questionnaire.js
- appeals/api/src/server/tests/appeals/s20.js
Maps consultHistoricEngland prop on data model in and out of back office
[Ticket](https://pins-ds.atlassian.net/browse/A2-4111)
> fix(api): map consultHistoricEngland to and from data model (a2-4111)

- appeals/api/src/server/endpoints/business-days/__tests__/business-days.test.js
- appeals/e2e/cypress/e2e/back-office-appeals/inquiry.spec.js
This PR contains test to verify order of sections for inquiry.
[Ticket](https://pins-ds.atlassian.net/browse/A2-3659)
> test(appeals): verify order of sections for inquiry

- appeals/api/src/server/state/__tests__/state-machine.test.js
- appeals/api/src/server/state/create-state-machine.js
- Added state transitions to invalid for required states
- Added unit test for these transitions
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-4010)
> feat(api): updating state machine to allow transition to invalid (A2-4010)

- azure-pipelines-purge-container-registry.yml
Adding pdf service to container registry purge
Fixes failing pipeline
> fix(tooling): include pdf service in container registry purge

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.mapper.js
- removed addition view decision date row
- Added new unit test and snapshot for the page
- Manually tested in browser
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-3295)
> feat(web): fix decision issue date in view decision page (A2-3295)

- appeals/e2e/cypress/e2e/back-office-appeals/issueDecision.spec.js
- appeals/e2e/cypress/support/happyPathHelper.js
* Refactored Issue Decision e2e tests to use `happyPathHelper` method. Removes a large chunk of code inside the test case
* Changed existing `happyPathHelper` methods to use new `fileUploader` functionality
* Removed `dateTimeSection.enterValidDate(dueDate)` in `reviewAppellantCase(caseRef)` - was unnecessary as the date on this page is already pre-filled. Minor time saving.
[A2-4201](https://pins-ds.atlassian.net/browse/A2-4201)
[A2-4201]: https://pins-ds.atlassian.net/browse/A2-4201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Refactor Issue Decision e2e

- appeals/api/src/database/seed/data-static.js
- appeals/api/src/database/seed/data-test.js
added seed data for proof of evidence
[A2-4182](https://pins-ds.atlassian.net/browse/A2-4182)
[A2-4182]: https://pins-ds.atlassian.net/browse/A2-4182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(appeals): added seed data for proof of evidence

- appeals/web/src/server/appeals/appeal-details/hearing/setup/set-up-hearing.controller.js
- appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/__tests__/__snapshots__/interested-party-comments.test.js.snap
- appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/add-ip-comment/__tests__/__snapshots__/add-ip-comment.test.js.snap
- appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/add-ip-comment/__tests__/add-ip-comment.test.js
- appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/add-ip-comment/add-ip-comment.controller.js
- appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/add-ip-comment/add-ip-comment.mapper.js
- appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/common/date-submitted.js
- appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/common/redaction-status.js
- appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/edit-ip-comment/__tests__/__snapshots__/edit-ip-comment.test.js.snap
- appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/edit-ip-comment/edit-ip-comment.controller.js
- appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/interested-party-comments.controller.js
- appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/interested-party-comments.mapper.js
- appeals/web/src/server/lib/edit-utilities.js
- appeals/web/src/server/lib/middleware/save-back-url.js
Now the user is taken back to the CYA page. Similar to #1651.
[A2-3053](https://pins-ds.atlassian.net/browse/A2-3053)
[A2-3053]: https://pins-ds.atlassian.net/browse/A2-3053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(web): improve back links when editing from add IP comment CYA page

- appeals/web/src/server/appeals/appeal-details/invalid-appeal/invalid-appeal.mapper.js
- Back button fix for invalid appeals page
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-3841)
> Feat(A2-3841): back button fix invalid appeals page

- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/lib/mappers/data/lpa-questionnaire/submappers/map-is-infrastructure-levy-formally-adopted.js
Minor change to amend default from blank to 'Not applicable'
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-4106)
> fix(web): amend infrastructure levy formally adopted default display

- appeals/api/src/server/notify/templates/__tests__/appeal-valid-start-case-lpa.test.js
- appeals/api/src/server/notify/templates/appeal-valid-start-case-lpa.content.md
- start case notify content update
[Ticket](https://pins-ds.atlassian.net/browse/A2-4078)
> feat(A2-4078): updating start case notify content

- appeals/api/src/database/migrations/20250828140806_adds_cas_adverts_appellant_case_fields/migration.sql
- appeals/api/src/database/schema.prisma
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.controller.js
- appeals/api/src/server/mappers/api/definitions/appellant-case.js
- appeals/api/src/server/openapi-types.ts
- appeals/api/src/server/openapi.json
Api work to enable additional rows required for cas adverts appeals
[Ticket](https://pins-ds.atlassian.net/browse/A2-3858)
> feat(api): a2-3858 cas adverts appeal form

- appeals/web/src/server/appeals/appeal-details/appeal-timetables/__tests__/appeal-timetables.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/appellant-case.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/application-submission-date/__tests__/__snapshots__/application-submission-date.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/application-submission-date/__tests__/application-submission-date.test.js
- appeals/web/src/server/appeals/appeal-details/change-appeal-type-old/__tests__/__snapshots__/change-appeal-type.test.js.snap
- appeals/web/src/server/appeals/appeal-details/change-appeal-type-old/__tests__/change-appeal-type.test.js
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/__tests__/__snapshots__/change-appeal-type.test.js.snap
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/__tests__/change-appeal-type.test.js
- appeals/web/src/server/appeals/appeal-details/inquiry/setup/__tests__/set-up-inquiry.test.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/__snapshots__/lpa-questionnaire.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/__tests__/lpa-questionnaire.test.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/community-infrastructure-levy/infrastructure-levy-adopted-date/__tests__/__snapshots__/infrastructure-levy-adopted-date.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/community-infrastructure-levy/infrastructure-levy-adopted-date/__tests__/infrastructure-levy-adopted-date.test.js
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/community-infrastructure-levy/infrastructure-levy-expected-date/__tests__/__snapshots__/infrastructure-levy-expected-date.test.js.snap
- appeals/web/src/server/appeals/appeal-details/lpa-questionnaire/community-infrastructure-levy/infrastructure-levy-expected-date/__tests__/infrastructure-levy-expected-date.test.js
- appeals/web/src/server/appeals/appeal-details/representations/interested-party-comments/add-ip-comment/__tests__/add-ip-comment.test.js
- appeals/web/src/server/appeals/appeal-details/site-visit/__tests__/site-visit.test.js
- appeals/web/src/server/lib/constants.js
- appeals/web/src/server/lib/validators/date-input.validator.js
- used trim() to remove trailing spaces before validation
- converted valid month name inputs into month number string
- reverted to users original date input on any error
- updated unit tests to cover various month inputs
[A2-4035](https://pins-ds.atlassian.net/browse/A2-4035)
[A2-4035]: https://pins-ds.atlassian.net/browse/A2-4035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(web): refactor date validation functions

- appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/issue-decision.test.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.controller.js
- Make sure code and tests use constants for the values to determine the selected decision valid or invalid
- Fix unit tests 
- Make sure all unit tests pass
- Tested in browser
[A2-3075](https://pins-ds.atlassian.net/browse/A2-3075)
[A2-3075]: https://pins-ds.atlassian.net/browse/A2-3075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(appeals): invalid issue decision redirection error (a2-3075)

- appeals/api/src/database/seed/LPAs/prod.js
Already applied this to prod, just merging it into main
[A2-4093](https://pins-ds.atlassian.net/browse/A2-4093)
[A2-4093]: https://pins-ds.atlassian.net/browse/A2-4093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(api): remove Lambeth and Hillingdon LPAs from cohort 3

- appeals/api/src/server/mappers/integration/__tests__/mappers.test.js
- appeals/api/src/server/mappers/integration/shared/s20s78/map-case-dates.js
Broadcast `statementOfCommonGroundDueDate` and `planningObligationDueDate` to service bus.
[A2-3921](https://pins-ds.atlassian.net/browse/A2-3921)
[A2-3921]: https://pins-ds.atlassian.net/browse/A2-3921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(api): broadcast statementOfCommonGroundDueDate and planningObligationDueDate

- appeals/api/src/server/endpoints/appeals/__tests__/appeals.test.js
- appeals/api/src/server/repositories/appeal-lists.repository.js
- appeals/api/src/server/utils/feature-flags-appeal-types.js
Fixed issue with filtering all appeals based off the procedure type
[A2-4145](https://pins-ds.atlassian.net/browse/A2-4145)
[A2-4145]: https://pins-ds.atlassian.net/browse/A2-4145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(appeals): fixed issue with filtering

- appeals/e2e/cypress/e2e/back-office-appeals/linkAppeals.spec.js
- appeals/e2e/cypress/support/happyPathHelper.js
* Added happyPathHelper method for adding a linked appeal to a case
* Opening 'Overview' accordion will now be handled outside of this method by a separate method for greater flexibility
* Refactored existing linked appeals tests to use new method
[a2-4306](https://pins-ds.atlassian.net/browse/A2-4306)
> a2-4306 add linked appeal happypathhelper

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/appeal-details/hearing/setup/set-up-hearing.controller.js
- appeals/web/src/server/lib/mappers/components/page-components/notification-banners.mapper.js
fixed issue with hearing banners
[A2-4204](https://pins-ds.atlassian.net/browse/A2-4204)
[A2-4204]: https://pins-ds.atlassian.net/browse/A2-4204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(appeals): fixed issue with hearing banners

- appeals/web/src/server/appeals/appeal-details/change-appeal-type/__tests__/__snapshots__/change-appeal-type.test.js.snap
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/__tests__/change-appeal-type.test.js
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.mapper.js
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.validators.js
Content update for resubmit appeal page
[Ticket](https://pins-ds.atlassian.net/browse/A2-4283)
> fix(web): update content for resubmit appeal page

- appeals/web/package.json
- appeals/web/src/server/appeals/appeal-details/update-case-team/__tests__/__snapshots__/update-case-team.test.js.snap
- appeals/web/src/server/appeals/appeal-details/update-case-team/__tests__/update-case-team.test.js
- appeals/web/src/server/appeals/appeal-details/update-case-team/update-case-team.controller.js
- appeals/web/src/server/appeals/appeal-details/update-case-team/update-case-team.mapper.js
- appeals/web/src/server/appeals/appeal-details/update-case-team/update-case-team.validators.js
- appeals/web/src/styles/7-components/_autocomplete.scss
- package-lock.json
- Replaced radio component with accessble-autocomplete component
- bumping version of acccessible-autocomplete dependency to pull in correct coloring and shading (matches FO)
- Removing the unassign team option since no longer needed
- Updating the error message for when no team is selected
- Unit test updates to match updated content
- Tested in browser
[Ticket](https://pins-ds.atlassian.net.mcas.ms/browse/A2-4263)
> feat(A2-4263): Adding autocomplete feature to case team page and ui updates

- appeals/api/src/database/seed/LPAs/prod.js
update email address for telford and wrekin council 
[Ticket](https://pins-ds.atlassian.net/browse/A2-4252)
> feat(api): update email address for telford and wrekin council (A2-4252)

- appeals/api/src/database/seed/LPAs/prod.js
update email address isle of wight Council
[Ticket](https://pins-ds.atlassian.net/browse/A2-4357)
> feat(api): update email address Isle of Wight Council

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/appeals/appeal-details/__tests__/appeal-details.test.js
- appeals/web/src/server/appeals/appeal-details/accordions/common/case-contacts.js
- appeals/web/src/server/appeals/appeal-details/accordions/common/case-costs.js
- appeals/web/src/server/appeals/appeal-details/accordions/common/case-documentation.js
- appeals/web/src/server/appeals/appeal-details/accordions/common/case-management.js
- appeals/web/src/server/appeals/appeal-details/accordions/common/case-overview.js
- appeals/web/src/server/appeals/appeal-details/accordions/common/case-team.js
- appeals/web/src/server/appeals/appeal-details/accordions/common/site-details.js
- appeals/web/src/server/appeals/appeal-details/accordions/has.js
- appeals/web/src/server/appeals/appeal-details/accordions/index.js
- appeals/web/src/server/appeals/appeal-details/accordions/s78.js
- appeals/web/src/server/appeals/appeal-details/accordions/s78/case-hearing.js
- appeals/web/src/server/appeals/appeal-details/accordions/s78/case-inquiry.js
- appeals/web/src/server/appeals/appeal-details/accordions/utils/index.js
- appeals/web/src/server/appeals/appeal-details/accordions/utils/remove-accordion-components-actions.js
- appeals/web/src/server/appeals/appeal-details/appeal-details-page-sections/utils/index.js
- appeals/web/src/server/appeals/appeal-details/appeal-details.mapper.js
This reverts commit 982b3fed7cf8ad123a869c71e6ba915a2bf733e5.
Reverting removing the case details accordion
[Ticket](https://pins-ds.atlassian.net/browse/A2-2107
> Revert "feat(web): remove case details accordion (A2-2107)"

- appeals/web/src/server/appeals/appeal-details/start-case/hearing/__tests__/__snapshots__/start-case-hearing.test.js.snap
- appeals/web/src/server/appeals/appeal-details/start-case/hearing/__tests__/start-case-hearing.test.js
- appeals/web/src/server/appeals/appeal-details/start-case/hearing/hearing.controller.js
- appeals/web/src/server/appeals/appeal-details/start-case/hearing/hearing.mapper.js
- appeals/web/src/server/appeals/appeal-details/start-case/hearing/hearing.router.js
- appeals/web/src/server/appeals/appeal-details/start-case/hearing/hearing.validators.js
Date question page for new start case flow for hearing cases. The user selects yes or no to whether they know the date of the hearing, and is redirected accordingly.
[A2-4317](https://pins-ds.atlassian.net/browse/A2-4317)
[A2-4317]: https://pins-ds.atlassian.net/browse/A2-4317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(web): date known question page for new hearing flow

- appeals/api/src/server/utils/blob-copy.js
- When not emulating blob storage, use the topic "appeal-document-to-move" to send an event to move the blobs between appeals
[A2-4173 - BO - What happens to cost files/'Costs' accordion on child appeals when linking (relates to all appeal types)](https://pins-ds.atlassian.net/browse/A2-4173)
> fix(appeals): use an event to move blobs between appeals (a2-4173)

- appeals/e2e/cypress/e2e/back-office-appeals/caseHistory.spec.js
- appeals/e2e/cypress/e2e/back-office-appeals/changeAppealProcedureType.spec.js
- appeals/e2e/cypress/e2e/back-office-appeals/changeAppealType.spec.js
- appeals/e2e/cypress/e2e/back-office-appeals/inquiry.spec.js
- appeals/e2e/cypress/e2e/back-office-appeals/linkAppeals.spec.js
- appeals/e2e/cypress/page_objects/caseDetailsPage.js
More fixes for e2e tests after accordion removal.
Also fixes to caseHistory and changeAppealType.
[A2-2107](https://pins-ds.atlassian.net/browse/A2-2107)
[A2-2107]: https://pins-ds.atlassian.net/browse/A2-2107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test(appeals): accordion e2e fix

- appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.controller.js
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.mapper.js
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.router.js
Small text changes to mark appeal as invalid screen on change appeal type flow
[Ticket](https://pins-ds.atlassian.net/browse/A2-4322)
> fix(appeals): mark appeal invalid page text changes

- appeals/api/src/server/endpoints/appeals.d.ts
- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.service.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/advertisement-in-position/__tests__/__snapshots__/advertisement-in-position.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/advertisement-in-position/__tests__/advertisement-in-position.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/advertisement-in-position/advertisement-in-position.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/advertisement-in-position/advertisement-in-position.mapper.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/advertisement-in-position/advertisement-in-position.router.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/advertisement-in-position/advertisement-in-position.service.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.router.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/page-components/cas-advert.mapper.js
- appeals/web/src/server/lib/mappers/data/appellant-case/cas-advert.js
- appeals/web/src/server/lib/mappers/data/appellant-case/submappers/advertisement-in-position.js
- packages/appeals/constants/support.js
- Adding the advertisement in position row
- Appeal updated banner 
- Adding the message for the case history to audit trail
- Adding the new variables to appeals.d.ts
[Ticket](https://pins-ds.atlassian.net/browse/A2-3452)
> feat(web): a2-3452 advertisement in position row

- appeals/api/src/server/endpoints/appellant-cases/appellant-cases.service.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/__tests__/__snapshots__/appellant-case.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/appellant-case.router.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/landowner-permission/__tests__/__snapshots__/landowner-permission.test.js.snap
- appeals/web/src/server/appeals/appeal-details/appellant-case/landowner-permission/__tests__/landowner-permission.test.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/landowner-permission/landowner-permission.controller.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/landowner-permission/landowner-permission.mapper.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/landowner-permission/landowner-permission.router.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/landowner-permission/landowner-permission.service.js
- appeals/web/src/server/appeals/appeal-details/appellant-case/page-components/cas-advert.mapper.js
- appeals/web/src/server/lib/mappers/data/appellant-case/cas-advert.js
- appeals/web/src/server/lib/mappers/data/appellant-case/submappers/landowner-permission.js
- packages/appeals/constants/support.js
- Adding the landowner permission row
- Appeal updated banner
- Adding the message for the case history to audit trail
[Ticket](https://pins-ds.atlassian.net/browse/A2-3453)
> feat(web): a2-3453_landowner_permission_row

- infrastructure/provider.tf
- Bumping terraform version max version restriction since terraform has been updated
[Ticket]()
> chore(infrastructure): upgrade terraform version

- appeals/web/src/server/appeals/appeal-details/change-appeal-type/__tests__/change-appeal-type.test.js
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.controller.js
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.mapper.js
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.router.js
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.service.js
New screen for change appeal type flow - check details and update
[Ticket](https://pins-ds.atlassian.net/browse/A2-3646)
> feat(appeals): change appeal check details and update screen

- appeals/api/src/server/endpoints/hearings/__tests__/hearing.test.js
- appeals/api/src/server/repositories/appeal-status.repository.js
- appeals/api/src/server/state/transition-state.js
The rollback state was not scoped to a particular appeal which caused many appealStatus deletions to occur after some SQL queries had been applied
[Ticket]()
> HotFix: Release rollback state causing deletions

- appeals/api/src/database/seed/teams/dev.js
Update seed data setup for testing
[Ticket](https://pins-ds.atlassian.net/browse/A2-3719)
> feat(api): update team assignments for dev/test seed

- appeals/e2e/cypress/e2e/back-office-appeals/changeAppealProcedureType.spec.js
Skip failing test caused by the post-MVP hearing flow changes.
[Ticket](N/A)
> fix(test/e2e): skip procedure type test

- infrastructure/environments/prod.tfvars
- infrastructure/environments/training.tfvars
Set the feature flags for auto assign so the functionality is available in training and prod
> fix(appeals): set auto assign feature flags to true for all environments

- appeals/web/src/server/appeals/personal-list/__tests__/__snapshots__/personal-list.test.js.snap
- appeals/web/src/server/appeals/personal-list/__tests__/personal-list.test.js
- appeals/web/src/server/appeals/personal-list/personal-list.mapper.js
Updating action link text for personal list
[Ticket](https://pins-ds.atlassian.net/browse/A2-4525)
> fix(web): personal list awaiting transfer action link text

- appeals/api/src/server/endpoints/change-appeal-type/__tests__/change-appeal-type.test.js
- appeals/api/src/server/endpoints/change-appeal-type/change-appeal-type.service.js
Notify for change appeal type - invalid appeal flow
[Ticket](https://pins-ds.atlassian.net/browse/A2-3691)
> feat(api): notify for change appeal type invalid route

- appeals/web/src/server/appeals/appeal-details/__tests__/__snapshots__/appeal-details.test.js.snap
- appeals/web/src/server/lib/mappers/data/appeal/submappers/team.mapper.js
1. update logic to display the correct link text  
2. update unit tests and snapshots
3. manual testing
[Ticket](https://pins-ds.atlassian.net/browse/A2-4549)
> fix(web): fix auto assign issues (A2-4232)

- appeals/web/src/server/appeals/appeal-details/appeal-details-page-sections/common/case-documentation.js
- appeals/web/src/server/appeals/appeal-details/appeal-details-page-sections/common/case-management.js
- appeals/web/src/server/appeals/appeal-details/appeal-details-page-sections/utils/remove-appeal-details-sections-components-actions.js
- appeals/web/src/server/lib/mappers/types.js
Enabling Documentation and Case Management links for appeals in Awaiting Transfer
[Ticket](https://pins-ds.atlassian.net/browse/A2-3232)
> fix(appeals): show select case management links on awaiting transfer

- appeals/api/src/database/seed/LPAs/prod.js
[Ticket](https://pins-ds.atlassian.net/browse/A2-4570)
> fix(api): a2-4570 update email for north hertfordshire

- appeals/api/src/server/repositories/appeal-status.repository.js
- appeals/api/src/server/state/transition-state.js
See the original PR against main for reference here: [fix(appeals): missed hot fix changes for appeals status rollback bug (a2-4499)](https://github.com/Planning-Inspectorate/appeals-back-office/pull/2164)
- Add changes that were made in the hot fix and that are currently live that were missed in the previous PR to fix this in main
- Make sure all unit tests pass
- [A2-4499 - Restore hearing state roll-back functionality](https://pins-ds.atlassian.net/browse/A2-4499)
- [A2-4586 - Patch the Release with a fix for known issue](https://pins-ds.atlassian.net.mcas.ms/browse/A2-4586)
> fix(appeals): missed changes for appeals status rollback bug (a2-4499) - for release

- appeals/e2e/cypress/e2e/back-office-appeals/manageDocsSupporting.spec.js
One of the upload document tests is currently failing as was in status of waiting for virus scan 
Have added a wait (reload) which seems to work - though may need to look at more elegant solution? 
*{Is no ticket - fix}*
> test(test/e2e): updating document upload test

- appeals/web/src/server/appeals/appeal-details/representations/lpa-statement/incomplete/incomplete.mapper.js
Content update
[Ticket](https://pins-ds.atlassian.net/browse/A2-4388)
> feat(web): update lpa statement resubmission page content

- appeals/functions/casedata-import/host.json
- appeals/functions/document-processing/host.json
- appeals/functions/refdata-import/host.json
- appeals/functions/scheduled-jobs/host.json
upgrade the function bundle
https://pins-ds.atlassian.net/browse/DEV-555
> chore(functions): align function settings in host.json

- appeals/web/src/server/appeals/appeal-details/change-appeal-type/__tests__/__snapshots__/change-appeal-type.test.js.snap
- appeals/web/src/server/appeals/appeal-details/change-appeal-type/change-appeal-type.mapper.js
Preheading content fixes for change appeal flow to make consistent with the other screens
[Ticket](https://pins-ds.atlassian.net/browse/A2-4632)
> feat(web): change appeal screens preheading content

- appeals/web/src/server/lib/mappers/__tests__/mappers.test.js
- appeals/web/src/server/lib/mappers/data/appeal/submappers/appellant-proof-of-evidence-and-witness.mapper.js
- appeals/web/src/server/lib/mappers/data/appeal/submappers/lpa-proof-of-evidence-and-witness.mapper.js
- appeals/web/src/server/lib/mappers/utils/__tests__/map-status-dependent-notifications.test.js
- appeals/web/src/server/lib/mappers/utils/required-actions.js
- appeals/web/src/server/lib/representation-utilities.js
- appeals/web/testing/app/fixtures/referencedata.js
Inquiry - Case details page for POE as Incomplete
[A2-4528](https://pins-ds.atlassian.net/browse/A2-4528)
[A2-4529](https://pins-ds.atlassian.net/browse/A2-4529)
[A2-4528]: https://pins-ds.atlassian.net/browse/A2-4528?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[A2-4529]: https://pins-ds.atlassian.net/browse/A2-4529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(appeals): added poe incomplete information on the case detail page

- infrastructure/service-bus.tf
Private endpoint not checking test/staging correctly leading to deletion in test env 
This doesn't fully resolve 4654
https://pins-ds.atlassian.net/browse/A2-4654
> fix(infrastructure): handle shared private endpoint correctly

- appeals/api/src/server/endpoints/change-appeal-type/__tests__/change-appeal-type.test.js
- appeals/api/src/server/endpoints/change-appeal-type/change-appeal-type.controller.js
- appeals/api/src/server/endpoints/change-appeal-type/change-appeal-type.service.js
- appeals/api/src/server/endpoints/change-appeal-type/change-appeal-type.util.js
- appeals/api/src/server/tests/appeals/mocks.js
Formatting of appeal types used in change appeal type, mark invalid flow, notify.
[Ticket](https://pins-ds.atlassian.net/browse/A2-4631)
> feat(api): invalid appeals notify appeal types formatting

- appeals/web/src/server/appeals/appeal-details/issue-decision/__tests__/issue-decision.test.js
- appeals/web/src/server/appeals/appeal-details/issue-decision/issue-decision.validators.js
Fixing validate invalid reason middleware for issuing decision and relevant test
[Ticket](https://pins-ds.atlassian.net/browse/A2-4265)
> fix(web): validate invalid reason middleware fix and test

- appeals/api/src/database/seed/LPAs/prod.js
a2-4686 update cambridge city council email
[Ticket - a2-4686](https://pins-ds.atlassian.net/browse/A2-4686)
> fix(appeals): a2-4686 update cambridge city council email
